# 《The Inn》简体中文翻译 · options

translate simplified_chinese strings:

    old "The Inn (Chapter 2)"
    new "The Inn（第二章）"

    old "The Inn is the fruit of countless hours of work and headscratching.\n\nIf you enjoy my work, please consider supporting it on {a=https://www.patreon.com/theinn/}Patreon{/a} or {a=https://subscribestar.adult/the-inn/}SubscribeStar{/a}!\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}All music in this game is licensed under Creative Commons and were created by the awesome people at:{/size}\n\n{a=https://www.incompetech.com/}{image=gui/logos/incompetech.webp}{/a}\n\nAND\n\n{a=https://www.bensound.com/}{image=gui/logos/bensound.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}Icons used in various parts of this game were made by:{/size}\n\nGregor Cresnar, Nikita Golubev, Pixel Buddha, Freepik, Dave Gandy and Elias Bikbulatov\n\nFind more about them at:\n\n{a=https://www.flaticon.com/}{image=gui/logos/flaticon.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}"
    new "《The Inn》凝聚了无数小时的心血与挠头。\n\n如果你喜欢我的作品，欢迎在 {a=https://www.patreon.com/theinn/}Patreon{/a} 或 {a=https://subscribestar.adult/the-inn/}SubscribeStar{/a} 上支持我！\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}本游戏中的所有音乐均采用 Creative Commons 授权，由以下站点的朋友们创作：{/size}\n\n{a=https://www.incompetech.com/}{image=gui/logos/incompetech.webp}{/a}\n\n以及\n\n{a=https://www.bensound.com/}{image=gui/logos/bensound.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}本游戏各处使用的图标由以下作者制作：{/size}\n\nGregor Cresnar、Nikita Golubev、Pixel Buddha、Freepik、Dave Gandy 与 Elias Bikbulatov\n\n了解更多请访问：\n\n{a=https://www.flaticon.com/}{image=gui/logos/flaticon.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}"

    old "The Inn is the fruit of countless hours of work and headscratching.\n\nIf you enjoy my work, please consider supporting it on {a=https://www.patreon.com/theinn/}Patreon{/a} or {a=https://subscribestar.adult/the-inn/}SubscribeStar{/a}!\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}Music in this game is licensed under Creative Commons and were created by the awesome people at:{/size}\n\n{a=https://www.incompetech.com/}{image=gui/logos/incompetech.webp}{/a}\n\nAND\n\n{a=https://www.bensound.com/}{image=gui/logos/bensound.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}Icons used in various parts of this game were made by:{/size}\n\nGregor Cresnar, Nikita Golubev, Pixel Buddha, Freepik, Dave Gandy and Elias Bikbulatov\n\nFind more about them at:\n\n{a=https://www.flaticon.com/}{image=gui/logos/flaticon.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}The songs used in the WWD Minigame are part of the Club Fantastic Packs for Stepmania{/size}\n\nFind more about it at:\n\n{a=https://www.clubfantastic.com/}{image=gui/logos/club_fantastic.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}"
    new "《The Inn》凝聚了无数小时的心血与挠头。\n\n如果你喜欢我的作品，欢迎在 {a=https://www.patreon.com/theinn/}Patreon{/a} 或 {a=https://subscribestar.adult/the-inn/}SubscribeStar{/a} 上支持我！\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}本游戏中的所有音乐均采用 Creative Commons 授权，由以下站点的朋友们创作：{/size}\n\n{a=https://www.incompetech.com/}{image=gui/logos/incompetech.webp}{/a}\n\n以及\n\n{a=https://www.bensound.com/}{image=gui/logos/bensound.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}本游戏各处使用的图标由以下作者制作：{/size}\n\nGregor Cresnar、Nikita Golubev、Pixel Buddha、Freepik、Dave Gandy 与 Elias Bikbulatov\n\n了解更多请访问：\n\n{a=https://www.flaticon.com/}{image=gui/logos/flaticon.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}\n\n{size=32}WWD 小游戏中使用的曲目来自 Stepmania 的 Club Fantastic 曲包{/size}\n\n了解更多请访问：\n\n{a=https://www.clubfantastic.com/}{image=gui/logos/club_fantastic.webp}{/a}\n\n{image=gui/logos/linebreaker.webp}"
