# -*- coding: utf-8 -*-
# Generated by tools/generate.py - do not edit by hand.
# Sinful Summer (Chapter 3.6) - Simplified Chinese localisation.

translate schinese story41_Erik_Lyna_Helga_335332d4:
    n "他怀念两人曾拥有那份单纯的亲密，怀念那个最大的烦恼只是从妈妈的罐子里偷吃一块饼干的时光。"

translate schinese story41_Erik_Lyna_Helga_65c4017e:
    n "此刻他被困住了；夹在对母亲的担忧、对莱娜那份不健康的欲望，以及那场乱伦幽会令人战栗的刺激之间。"

translate schinese story42_Erik_Lyna_Helga_5d5da9e2:
    n "这个家庭曾经温暖舒适的关系，已变成一场危险的赌博；他们连怎么玩都不知道，更别说赢。"

translate schinese story42_Erik_Lyna_Helga_2ec32d9c:
    centered "然后，那个夜晚来临了。"

translate schinese story42_Erik_Lyna_Helga_6948470b:
    centered "{font=font_narration}{size=+10}{cps=25}七月初——赫尔加到达三周后……"

translate schinese story42_Erik_Lyna_Helga_7666070b:
    e "快点，姐……为什么选这里？"

translate schinese story42_Erik_Lyna_Helga_1c9951c6:
    l "因为我想啊？"

translate schinese story42_Erik_Lyna_Helga_84df95b7:
    e "可是妈她——"

translate schinese story42_Erik_Lyna_Helga_82894426:
    l "我知道！我就是想在这里做，就在她卧室外面。"

translate schinese story42_Erik_Lyna_Helga_50d17661:
    e "可万一她——"

translate schinese story42_Erik_Lyna_Helga_a5604d78:
    l "她不会。浴室在里面。"

translate schinese story42_Erik_Lyna_Helga_f9ed804d:
    e "那万一她想……呃……吃夜宵呢？"

translate schinese story42_Erik_Lyna_Helga_07ba81bc:
    l "就她那顿丰盛大餐之后？哈！"

translate schinese story42_Erik_Lyna_Helga_2c952779:
    e "那万一——"

translate schinese story42_Erik_Lyna_Helga_bab99c00:
    l "老哥，冷静！很晚了，妈在睡觉呢。"

translate schinese story42_Erik_Lyna_Helga_11f1cf45:
    e "可是……我们——"

translate schinese story42_Erik_Lyna_Helga_e709c3d5:
    l "我们只要非常非常安静，对吧？"

translate schinese story42_Erik_Lyna_Helga_57159681:
    l "也不许哼唧，变态先生。嘿嘿~"

translate schinese story42_Erik_Lyna_Helga_55cc37fe:
    e "不！这次我不听你的！"

translate schinese story42_Erik_Lyna_Helga_122f4372:
    e "忘了我们说过的了？我也有发言权。"

translate schinese story42_Erik_Lyna_Helga_663fc40c:
    e "所以我们去外面，或者……找个更安全的地方，行吗。"

translate schinese story42_Erik_Lyna_Helga_7bee84aa:
    l "啧。行吧！你真是无聊透了，我发誓……"

translate schinese story42_Erik_Lyna_Helga_23204e75:
    l "等、等一下哥，你听到那个声音了吗？"

translate schinese story42_Erik_Lyna_Helga_43c42ab4:
    e "嗯？什么声音？"

translate schinese story42_Erik_Lyna_Helga_b970c9ae:
    l "从客厅传来的，过来。"

translate schinese story42_Erik_Lyna_Helga_7477f9ed:
    l "好吓人，你先走！"

translate schinese story42_Erik_Lyna_Helga_43465fb8:
    e "什么？只是天黑了，莱娜。"

translate schinese story42_Erik_Lyna_Helga_17f5cf93:
    l "就、就……快去！开个灯什么的……"

translate schinese story42_Erik_Lyna_Helga_8f9ad8a2:
    l "搞什——"

translate schinese story42_Erik_Lyna_Helga_bf4016f8:
    h "该死的破瓶子！*嗝*{size=-5}别滚了……"

translate schinese story42_Erik_Lyna_Helga_390567cd:
    e "妈！你怎么躺在地上？受伤了吗？！"

translate schinese story42_Erik_Lyna_Helga_23b201fe:
    l "天啊！你是不是……喝酒了？！"

translate schinese story42_Erik_Lyna_Helga_2085803b:
    h "{size=+5}哦！嘿、孩子们！" with vpunch

translate schinese story42_Erik_Lyna_Helga_72d65990:
    h "*嗝* 这么晚了你们怎么还没睡？"

translate schinese story42_Erik_Lyna_Helga_9fef4908:
    l "这话该我们问你才对！"

translate schinese story42_Erik_Lyna_Helga_23f2be97:
    h "*抽泣* 你们是来陪妈妈的，对吧？"

translate schinese story42_Erik_Lyna_Helga_925b06b8:
    e "妈，你没事吧？你在……哭？！"

translate schinese story42_Erik_Lyna_Helga_323b73ff:
    l "{size=-5}我有种不好的预感……"

translate schinese story42_Erik_Lyna_Helga_43613eff:
    h "那个，我……*嗝*{size=-5}我只是……"

translate schinese story42_Erik_Lyna_Helga_ccddae69:
    e "妈，我觉得我们得谈谈。我们不能一直装作一切都正常。"

translate schinese story42_Erik_Lyna_Helga_a0b2bd81:
    h "不、不，我的宝贝们……{size=-5}我……"

translate schinese story42_Erik_Lyna_Helga_95b6fb1b:
    l "妈妈求你了！埃里克说得对。"

translate schinese story42_Erik_Lyna_Helga_19975090:
    l "我们在这里。告诉我们出什么事了。"

translate schinese story42_Erik_Lyna_Helga_3300d5fa:
    hm "{size=-5}他在……看着我，评判我！他知道我对他做的那些可怕的事吗？！"

translate schinese story42_Erik_Lyna_Helga_6d3d0633:
    e "妈？你脑子里在想什么？我们需要知道。"

translate schinese story42_Erik_Lyna_Helga_249e8720:
    l "对！跟我们说吧，求你了。"

translate schinese story42_Erik_Lyna_Helga_12bce986:
    h "{size=+10}该死，该死……该死！"

translate schinese story42_Erik_Lyna_Helga_c21afb7d:
    e "嘿、嘿，没事的！我们在这里陪你。"

translate schinese story42_Erik_Lyna_Helga_1086a009:
    l "对妈，冷静点……"

translate schinese story42_Erik_Lyna_Helga_0857e68f:
    e "别管那个了，我们一起坐下来坐好，好吗？"

translate schinese story42_Erik_Lyna_Helga_62d9161e:
    h "*抽泣*{size=-5}好、好……"

translate schinese story42_Erik_Lyna_Helga_5948988c:
    e "妈？求你说点什么！"

translate schinese story42_Erik_Lyna_Helga_084a4ebb:
    l "你最近一直很疏远我们……"

translate schinese story42_Erik_Lyna_Helga_bff93612:
    l "尤其是我们一起洗澡那天之后。是我害的吗？"

translate schinese story42_Erik_Lyna_Helga_50ae25f1:
    e "你们俩……什么？"

translate schinese story42_Erik_Lyna_Helga_82c408a8:
    h "不……宝贝。*嗝*不是你的错。"

translate schinese story42_Erik_Lyna_Helga_cb5744b2:
    h "是我。我一直在被一些事情折磨。一些……{size=-5}回忆。"

translate schinese story42_Erik_Lyna_Helga_e29cabc6:
    e "回忆？不好的那种？"

translate schinese story42_Erik_Lyna_Helga_ab3959ce:
    h "关于你们爸爸、我们的婚姻，还有……*抽泣*我做错的事。"

translate schinese story42_Erik_Lyna_Helga_3f2ee55d:
    e "妈，你不必把所有事都怪在自己头上。"

translate schinese story42_Erik_Lyna_Helga_3432abbd:
    h "我知道，宝贝。{size=-5}但事情没那么简单。"

translate schinese story42_Erik_Lyna_Helga_5d1d9f6b:
    h "我……我也犯过错。我无法挽回的错误。"

translate schinese story42_Erik_Lyna_Helga_724d801f:
    e "不管是什么，你都可以告诉我们。我们在这里听。"

translate schinese story42_Erik_Lyna_Helga_ce37dde3:
    l "对，妈。我们爱你！这一点永远不会变。"

translate schinese story42_Erik_Lyna_Helga_a3342b33:
    h "*叹气* 有些事你们不知道……"

translate schinese story42_Erik_Lyna_Helga_dfbc7a57:
    h "关于你们爸爸和我的事。还有关于……{size=-5}我们家的事。"

translate schinese story42_Erik_Lyna_Helga_97742b49:
    e "不管是什么，我们一起面对，好吗？"

translate schinese story42_Erik_Lyna_Helga_7d55f055:
    l "对，一起！再也不藏秘密了~"

translate schinese story42_Erik_Lyna_Helga_2f92a2f0:
    e "嗯？妈你要去哪儿？"

translate schinese story42_Erik_Lyna_Helga_09f9c8bd:
    h "*嗝* 我接下来要说的事……还得再喝点酒……"

translate schinese story42_Erik_Lyna_Helga_0fca4e62:
    e "等等，你不该——"

translate schinese story42_Erik_Lyna_Helga_6b1d8af2:
    l "哥，这次就让她喝吧！她需要。"

translate schinese story42_Erik_Lyna_Helga_c9ee022c:
    e "好吧……但我不喜欢看到妈这样。"

translate schinese story42_Erik_Lyna_Helga_2a4ba20f:
    e "好了，我觉得你现在够舒服了，对吧？"

translate schinese story42_Erik_Lyna_Helga_3c40bb89:
    h "好了，孩子们。是……*嗝*时候了。你们有权知道真相。"

translate schinese story42_Erik_Lyna_Helga_4765765a:
    h "这话没有容易的说法，所以我就直说了。"

translate schinese story42_Erik_Lyna_Helga_573e9c4c:
    h "你爸、爸爸……*抽泣*{size=-5}约翰……{/size}并不是你以为的那种人。"

translate schinese story42_Erik_Lyna_Helga_a48eaab6:
    h "而我们离婚的真正原因是……{size=-5}他出轨了。"

translate schinese story42_Erik_Lyna_Helga_63a5ce4c:
    l "{size=+10}什么？！天啊！" with hpunch

translate schinese story42_Erik_Lyna_Helga_dd4b541c:
    e "{size=+5}爸、爸做了什么？！{/size}哦不……"

translate schinese story42_Erik_Lyna_Helga_57ebb5f4:
    l "妈，你认真的吗？！这只是个玩笑吧？"

translate schinese story42_Erik_Lyna_Helga_72b104da:
    h "{size=-5}我……{size=-10}没有……"

translate schinese story42_Erik_Lyna_Helga_6a76fb32:
    l "{size=+10}怎么会？！{/size} {size=+5}这他妈不公平！"

translate schinese story42_Erik_Lyna_Helga_6c528c55:
    l "{size=+5}他怎么能这样对你？对我们……我们？！"

translate schinese story42_Erik_Lyna_Helga_e4d82e79:
    e "妈，你为什么不告诉我们……？"

translate schinese story42_Erik_Lyna_Helga_5eddec61:
    h "我以为如果……*抽泣*如果你们不知道真相，会好过一点。"

translate schinese story42_Erik_Lyna_Helga_91eee7d9:
    h "{size=-5}我也不想伤害你们……"

translate schinese story42_Erik_Lyna_Helga_de24a52d:
    h "可我……*嗝*我大错特错了！{size=-5}对不起……"

translate schinese story42_Erik_Lyna_Helga_d8a2d8f8:
    h "{size=-5}秘密这东西，会把一切都染上毒。"

translate schinese story42_Erik_Lyna_Helga_f3aeaecb:
    e "是谁，妈？是我们认识的人？！"

translate schinese story42_Erik_Lyna_Helga_e3654f3f:
    h "不，不是……是他公司里一个年轻同事。"

translate schinese story42_Erik_Lyna_Helga_5110bcaa:
    h "啧。是谁已经不重要了……"

translate schinese story42_Erik_Lyna_Helga_5801044f:
    h "重要的是，你们爸爸毁了这个家！"

translate schinese story42_Erik_Lyna_Helga_e9bed6c4:
    h "而且他……*抽泣*{size=-5}他背叛了我的信任。"

translate schinese story42_Erik_Lyna_Helga_f717d289:
    l "可为什么？他为什么要那样？！"

translate schinese story42_Erik_Lyna_Helga_666ea92a:
    h "我他妈也不知道……*抽泣*"

translate schinese story42_Erik_Lyna_Helga_77734678:
    h "人会犯错。会犯下可怕又伤人的错！"

translate schinese story42_Erik_Lyna_Helga_60a3d015:
    h "有时候，那些错误会带来连锁的后果……"

translate schinese story42_Erik_Lyna_Helga_ab6190a6:
    e "{size=-5}这么长时间，我们一直以为只是因为他们不再相爱了……"

translate schinese story42_Erik_Lyna_Helga_ca98cc9a:
    l "{size=-5}结果严重得多！他怎么能这样对妈？"

translate schinese story42_Erik_Lyna_Helga_66d2e262:
    h "对不起！对不起我一直瞒着你们……"

translate schinese story42_Erik_Lyna_Helga_91892e33:
    h "我以为我是在保护你们，其实只是让我们所有人都伤得更重……"

translate schinese story42_Erik_Lyna_Helga_c8b2109e:
    e "这不是你的错！你只是想把对我们最好的事做到最好。"

translate schinese story42_Erik_Lyna_Helga_f3ef4b52:
    l "可你自己呢，妈？什么才是对你最好的？"

translate schinese story42_Erik_Lyna_Helga_7a86ad91:
    h "我……*抽泣* 我只是想让这个家不散。"

translate schinese story42_Erik_Lyna_Helga_3ae86c6e:
    h "但有时候，无论多努力，事情就是会崩掉。"

translate schinese story42_Erik_Lyna_Helga_17c7444a:
    h "而我们家族有一些……{size=-5}本不该发生的事。"

translate schinese story42_Erik_Lyna_Helga_dc0c04b5:
    l "{size=-5}嘘！她在说什么啊哥？太离谱了！"

translate schinese story42_Erik_Lyna_Helga_968b69ef:
    e "{size=-5}不知道，但我觉得我们只是碰到了冰山一角。"

translate schinese story42_Erik_Lyna_Helga_bc746dd2:
    l "{size=-5}我记得她前两天跟我提过我们姨妈……"

translate schinese story42_Erik_Lyna_Helga_9143144e:
    e "{size=-5}什么？你是说……安娜？那位我们从没见过面的姨妈？我以为她再也不想见我们了。"

translate schinese story42_Erik_Lyna_Helga_066667a4:
    h "*抽泣* 对不起……{size=-5}*抽泣*真的对不起……"

translate schinese story42_Erik_Lyna_Helga_f7cdda7c:
    e "嘿，别怪自己！没事的。我们在这里。"

translate schinese story42_Erik_Lyna_Helga_cc13e6ae:
    l "对妈，我们还是爱你！一切都会好起来的。"

translate schinese story42_Erik_Lyna_Helga_0619d9ca:
    h "对不起……{size=-5}为了所有的一切。"

translate schinese story42_Erik_Lyna_Helga_21e91913:
    h "为了一直保守秘密，为了你需要我的时候我不在……"

translate schinese story42_Erik_Lyna_Helga_88cd9e7d:
    e "没事的妈。我们都会犯错，你也会。"

translate schinese story42_Erik_Lyna_Helga_514cd386:
    l "对！我们明白这对你来说一定也很难。我们真的明白。"

translate schinese story42_Erik_Lyna_Helga_18be638e:
    h "天哪……{size=-5}我的宝贝们。"

translate schinese story42_Erik_Lyna_Helga_2606a0fc:
    h "*抽泣* 你们是我这辈子遇到的最好的事。"

translate schinese story42_Erik_Lyna_Helga_d8815b73:
    h "{size=-5}没有你们两个，我可不知道该怎么办……"

translate schinese story42_Erik_Lyna_Helga_d207f0e2:
    e "这个你永远都不用担心，妈。"

translate schinese story42_Erik_Lyna_Helga_2bfac5b2:
    l "对，我们永远在这里陪你。"

translate schinese story42_Erik_Lyna_Helga_79f2129b:
    h "你们知道吗，你们小时候我常这样抱着你们俩。"

translate schinese story42_Erik_Lyna_Helga_ad5535c9:
    h "你们那么可爱、那么小、那么纯真。我真希望能回到那些日子……"

translate schinese story42_Erik_Lyna_Helga_f52a03f1:
    h "{size=-5}在一切变得这么复杂之前。"

translate schinese story42_Erik_Lyna_Helga_02c5d84f:
    e "我们还可以有那样的时刻，妈。"

translate schinese story42_Erik_Lyna_Helga_3dc71be3:
    l "对，我们还可以像一家人那样在一起。"

translate schinese story42_Erik_Lyna_Helga_ac4e6f40:
    h "可我……亏待了你们俩！我太沉浸在自己的工作和自己的挣扎里，忘了陪在你们身边。"

translate schinese story42_Erik_Lyna_Helga_82f61ac0:
    h "对不起孩子们。你们本该有个更好的童年……"

translate schinese story42_Erik_Lyna_Helga_b3f96b16:
    e "没事的妈，我们理解。而且我们原谅你，对吧，姐？"

translate schinese story42_Erik_Lyna_Helga_084c8a1d:
    l "呃，那、那个……"

translate schinese story42_Erik_Lyna_Helga_4dd559fe:
    l "我、我们原谅你，对！"

translate schinese story42_Erik_Lyna_Helga_41e06354:
    l "妈，你给了我们生命！我们怎么可能恨你？"

translate schinese story42_Erik_Lyna_Helga_13fa3fdb:
    e "我们想把失去的时间补回来……我们想陪在你身边。"

translate schinese story42_Erik_Lyna_Helga_d902a492:
    l "而且我们得互相支持！因为说到底，我们只有彼此。"

translate schinese story42_Erik_Lyna_Helga_a17c284c:
    h "谢谢你们！*抽泣*{size=-5}真的谢谢……"

translate schinese story42_Erik_Lyna_Helga_736deac4:
    h "你们不知道这些话对我有多重要！"

translate schinese story42_Erik_Lyna_Helga_c61496e4:
    h "{size=-5}过来孩子们，躺到我腿上……"

translate schinese story42_Erik_Lyna_Helga_6163db5e:
    h "{cps=25}我可爱的小宝贝们……"

translate schinese story42_Erik_Lyna_Helga_484325fc:
    h "你们和我把你们带到这世上那天一样美。"

translate schinese story42_Erik_Lyna_Helga_5acb256b:
    h "我……*嗝*我给你们看过怀孕时的照片吗？"

translate schinese story42_Erik_Lyna_Helga_978afbb5:
    h "我的肚子超级大！{size=-5}你们真该看看……"

translate schinese story42_Erik_Lyna_Helga_8911a8c2:
    l "哈哈哈！妈你说话怪怪的！"

translate schinese story42_Erik_Lyna_Helga_ed9bd3d4:
    e "改天一定要给我们看……"

translate schinese story42_Erik_Lyna_Helga_dfb7bd87:
    h "然后……*嗝*生下你们之后……"

translate schinese story42_Erik_Lyna_Helga_894cf2a1:
    h "我会这样把你们俩抱着，一边一个……"

translate schinese story42_Erik_Lyna_Helga_2bbff065:
    h "然后同时给你们两个喂奶。"

translate schinese story42_Erik_Lyna_Helga_db553717:
    h "我的胸部又大又饱满，涨满了奶水……{size=-5}好让你长得壮实……"

translate schinese story42_Erik_Lyna_Helga_6518f942:
    l "{size=+5}妈——！信息量太大了！"

translate schinese story42_Erik_Lyna_Helga_44461f76:
    l "你喝了多少杯酒？！嘿嘿嘿~"

translate schinese story42_Erik_Lyna_Helga_ddc55fdf:
    h "*嗝* 可这是事实，宝、宝贝……"

translate schinese story42_Erik_Lyna_Helga_8dfca9c4:
    e "我同意，妈。你有点太怀旧了！"

translate schinese story42_Erik_Lyna_Helga_f8ca6795:
    h "我怎么可能不怀旧？！你们是我最完美的双胞胎……"

translate schinese story42_Erik_Lyna_Helga_f0e57c94:
    h "我还是不敢相信已经快二十年了！"

translate schinese story42_Erik_Lyna_Helga_b8e3e463:
    h "你们已经长成很不错的一对了，嗯？"

translate schinese story42_Erik_Lyna_Helga_26d63fd5:
    hm "{cps=25}我的大……{w=0.35}美丽的……{w=0.35}孩子们。"

translate schinese story42_Erik_Lyna_Helga_e81eb644:
    l "妈，你喜欢我穿的衣服吗？嘻嘻！"

translate schinese story42_Erik_Lyna_Helga_abf5e7ed:
    h "我……*嗝*我刚注意到，是的……"

translate schinese story42_Erik_Lyna_Helga_dba8331a:
    h "你很好看，宝贝……*嗝*"

translate schinese story42_Erik_Lyna_Helga_97d3b59c:
    h "{cps=25}就是……{w=0.35}{size=-5}该死……{w=0.35}{size=-10}好可爱。"

translate schinese story42_Erik_Lyna_Helga_ce335cfe:
    l "嘿……妈妈？我能问你件事吗？"

translate schinese story42_Erik_Lyna_Helga_e4aa7158:
    h "嗯？当然……{size=-10}宝、宝贝。"

translate schinese story42_Erik_Lyna_Helga_97e18a3f:
    l "埃里克跟我说，你最近很喜欢跟他一起睡……"

translate schinese story42_Erik_Lyna_Helga_5b3f9e22:
    e "{size=-5}嘘！你在说什么？现在不是说这个的时候。"

translate schinese story42_Erik_Lyna_Helga_7b79ff99:
    l "是真的吗，妈？"

translate schinese story42_Erik_Lyna_Helga_eac54251:
    e "*叹气* 莉妮……"

translate schinese story42_Erik_Lyna_Helga_ab53d887:
    h "哎呀，宝贝，你真傻！*嗝*"

translate schinese story42_Erik_Lyna_Helga_d4977ff8:
    h "不过是的，我最近很享受跟你哥哥一起睡……{size=-5}有时候。"

translate schinese story42_Erik_Lyna_Helga_89bde367:
    h "{size=-5}他好暖和……好让人安心……"

translate schinese story42_Erik_Lyna_Helga_a560d645:
    l "太好了！听我说，我有个很棒的主意……"

translate schinese story42_Erik_Lyna_Helga_6753d98e:
    l "今晚要不要跟我们一起睡，嗯？"

translate schinese story42_Erik_Lyna_Helga_668975f2:
    l "我们可以抱在一起、聊聊天……就这样待在一块。"

translate schinese story42_Erik_Lyna_Helga_118b0f51:
    h "听起来真的很棒！{size=-5}只要能离你们两个近一点……"

translate schinese story42_Erik_Lyna_Helga_b6890eaa:
    h "{size=-5}可、可是我不想打扰你们……"

translate schinese story42_Erik_Lyna_Helga_8789c0ef:
    l "不会打扰的，妈。我们也想这样！对吧，哥？"

translate schinese story42_Erik_Lyna_Helga_6020cc0d:
    e "我……呃……对！我们想，妈。"

translate schinese story42_Erik_Lyna_Helga_f7ecbd2d:
    h "好好好！我也很想今晚跟你们一起睡。"

translate schinese story42_Erik_Lyna_Helga_cdac4e02:
    l "说不定还能让埃里克再给你来一次那种超棒的按摩！"

translate schinese story42_Erik_Lyna_Helga_2d8b5e7f:
    l "妈，你好像真的很喜欢那种按摩呢？"

translate schinese story42_Erik_Lyna_Helga_b3813933:
    h "哎呀，你太了解我了！那个我确实很享受，还有……{size=-10}你的也是。"

translate schinese story42_Erik_Lyna_Helga_2b8e8545:
    e "{size=-5}莉妮！你确定吗？我们不该这样逼她。"

translate schinese story42_Erik_Lyna_Helga_a980f795:
    l "{size=-5}可她需要这个！她需要我们，哥。"

translate schinese story42_Erik_Lyna_Helga_9106d743:
    h "好了孩子们，那我们去睡吧。"

translate schinese story42_Erik_Lyna_Helga_d880eb95:
    l "其实……我觉得今晚你只跟埃里克睡比较好。"

translate schinese story42_Erik_Lyna_Helga_791fe67c:
    l "他房间可舒服了，而且还能让他单独给你免费按摩。"

translate schinese story42_Erik_Lyna_Helga_a1eb418b:
    l "因为我可不想打扰，或者让他紧张……"

translate schinese story42_Erik_Lyna_Helga_f40ee28c:
    h "哦……*嗝*小南瓜！总是想着你哥哥……"

translate schinese story42_Erik_Lyna_Helga_5e18dff8:
    e "{size=-5}嗯？姐？可你刚还说——"

translate schinese story42_Erik_Lyna_Helga_b1065217:
    l "{size=-5}嘘！相信我就好。我有个主意……"

translate schinese story42_Erik_Lyna_Helga_9d09f6a4:
    h "你确定吗……宝贝？会不会觉得被排除在外？*嗝*"

translate schinese story42_Erik_Lyna_Helga_ba932a2d:
    l "不会的，妈妈。没关系！真的！"

translate schinese story42_Erik_Lyna_Helga_c9342b76:
    l "你们需要我的话，我就在自己房间待着。"

translate schinese story42_Erik_Lyna_Helga_916a1159:
    h "好吧宝贝，如果那是……你、你想的……"

translate schinese story42_Erik_Lyna_Helga_9ace7ee1:
    l "你一定要好好照顾她，好吗？"

translate schinese story42_Erik_Lyna_Helga_1a7aab69:
    l "你可得给妈来一生中最棒的一次按摩！"

translate schinese story42_Erik_Lyna_Helga_a67aceca:
    hm "天哪！她都已经说得像在期待一样了……"

translate schinese story42_Erik_Lyna_Helga_c450afe0:
    h "不过你哥哥同意这样吗？"

translate schinese story42_Erik_Lyna_Helga_88fbb8db:
    e "同、同意，妈。我……{size=-5}我不介意。"

translate schinese story42_Erik_Lyna_Helga_01370a16:
    h "好、太好了！你妹妹说得对。"

translate schinese story42_Erik_Lyna_Helga_aef784e5:
    h "*嗝* 我后背一直疼得要命，说真的……{size=-5}我……"

translate schinese story42_Erik_Lyna_Helga_73350344:
    h "{size=-5}我真的很需要那双神奇的手再帮我一次。"

translate schinese story42_Erik_Lyna_Helga_90d31e40:
    e "只要能让你好受一点，我很乐意……"

translate schinese story42_Erik_Lyna_Helga_4dc7a091:
    l "{size=+5}耶~！这才是我大哥！"

translate schinese story42_Erik_Lyna_Helga_76e7f833:
    l "你留在这儿等我们几分钟，好吗？"

translate schinese story42_Erik_Lyna_Helga_0aa31aef:
    l "我们会把一切都准备好，迎接我们美丽的妈妈！"

translate schinese story42_Erik_Lyna_Helga_edfb3a47:
    l "跟我来，哥。我们得谈谈。"

translate schinese hscene24_Erik_Lyna_Helga_d9fd7b32:
    l "我有个计划，好吗？别担心。"

translate schinese hscene24_Erik_Lyna_Helga_7896fe83:
    e "我不知道你这次又在搞什么鬼，但我真希望你知道自己在干什么……"

translate schinese hscene24_Erik_Lyna_Helga_3b474e41:
    l "你以为我瞎了吗，埃里克？你心里清楚你想干什么。"

translate schinese hscene24_Erik_Lyna_Helga_8f9ec231:
    l "那天涂防晒霜的「按摩」时你可积极了……"

translate schinese hscene24_Erik_Lyna_Helga_db0c88fa:
    e "什么？那……什么都不是！"

translate schinese hscene24_Erik_Lyna_Helga_b23b1300:
    l "得了吧老哥，过去几周我看你偷看她无数次了。"

translate schinese hscene24_Erik_Lyna_Helga_642726c4:
    l "她现在连内衣都不穿了。你也注意到了吧？嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_e98440f6:
    e "你到底什么问题，莱娜？！真是不可理喻！"

translate schinese hscene24_Erik_Lyna_Helga_041e7849:
    e "我们刚跟妈妈进行了一番掏心窝子的对话，然后……"

translate schinese hscene24_Erik_Lyna_Helga_cd4532c7:
    e "你现在就在想{size=-5}色色的事{/size}了？！真的假的？！"

translate schinese hscene24_Erik_Lyna_Helga_89593853:
    l "嗯？老哥！你认真的吗？"

translate schinese hscene24_Erik_Lyna_Helga_d8168271:
    l "在撞见她醉成那样之前，我们本来就差点要去背着她干超级变态的事了。"

translate schinese hscene24_Erik_Lyna_Helga_aa7855d4:
    e "唉！{size=-5}我知道……{size=-10}我知道……"

translate schinese hscene24_Erik_Lyna_Helga_c6ea3913:
    l "再说了，你只是给她按摩，别的什么都不做。"

translate schinese hscene24_Erik_Lyna_Helga_e6c75fe0:
    l "就当是为了妈妈，拜托啦~？"

translate schinese hscene24_Erik_Lyna_Helga_3b469d3a:
    l "你刚也听到了。她那么寂寞、那么难过，一点都不奇怪！"

translate schinese hscene24_Erik_Lyna_Helga_a3d43a4b:
    l "我不想再看到她那样哭了，你呢？"

translate schinese hscene24_Erik_Lyna_Helga_79c71122:
    e "当然不想……"

translate schinese hscene24_Erik_Lyna_Helga_c998175f:
    l "那就去做吧，好吗？你会让妈妈非常开心的！"

translate schinese hscene24_Erik_Lyna_Helga_dc8a73bf:
    e "呃……我是说，你说得有点道理……"

translate schinese hscene24_Erik_Lyna_Helga_d45bc77e:
    l "对！所以……？"

translate schinese hscene24_Erik_Lyna_Helga_73755858:
    e "好吧！但我不是因为你的命令或什么奇怪计划才做的……"

translate schinese hscene24_Erik_Lyna_Helga_7b067a6a:
    e "我这么做只是因为我觉得这会对我们的母亲有帮助！"

translate schinese hscene24_Erik_Lyna_Helga_327e7db5:
    l "好！这才是该有的态度，老哥！"

translate schinese hscene24_Erik_Lyna_Helga_e6a75c4d:
    l "现在我们去把你的房间弄得更豪华一点……"

translate schinese hscene24_Erik_Lyna_Helga_caabe058:
    hm "嗯。他们在搞什么？"

translate schinese hscene24_Erik_Lyna_Helga_03a6109a:
    hm "算了，管他们呢……"

translate schinese hscene24_Erik_Lyna_Helga_3e77a5cd:
    hm "靠，他们连那瓶该死的酒都拿走了！"

translate schinese hscene24_Erik_Lyna_Helga_5ab8310d:
    hm "我想再喝点。我想忘掉……"

translate schinese hscene24_Erik_Lyna_Helga_a9ce40bc:
    h "还有这条该死的内裤……呃！*打嗝*好痒！"

translate schinese hscene24_Erik_Lyna_Helga_2433f7d8:
    h "去你的！" with hpunch

translate schinese hscene24_Erik_Lyna_Helga_0a10f3e5:
    h "呃……我头晕得厉害……"

translate schinese hscene24_Erik_Lyna_Helga_35aa72fe:
    h "{cps=30}{size=-5}*抽泣*{w=0.35}我只是想再次感觉被爱……"

translate schinese hscene24_Erik_Lyna_Helga_31bb7a4c:
    h "{cps=30}{size=-5}感觉还有人想要我，{w=0.35}{size=-10}作为一个女人……"

translate schinese hscene24_Erik_Lyna_Helga_6db6ca74:
    centered "{font=font_narration}{cps=20}{color=#f1d377}( 这要求过分吗？ )"

translate schinese hscene24_Erik_Lyna_Helga_4e544c8e:
    l "好吧，这比预想的久了一点……"

translate schinese hscene24_Erik_Lyna_Helga_0c118631:
    e "至少她看起来比刚才放松了。"

translate schinese hscene24_Erik_Lyna_Helga_aadd0fcf:
    e "我从没见过妈妈哭得那么厉害……"

translate schinese hscene24_Erik_Lyna_Helga_427b339a:
    l "我替她很难过。他们在一起那么多年……"

translate schinese hscene24_Erik_Lyna_Helga_63f7e015:
    e "我知道，莱娜……但她得向前走，像我们一样。"

translate schinese hscene24_Erik_Lyna_Helga_2529a2b7:
    e "我们改不了她的过去，但我们仍可以陪在她身边。"

translate schinese hscene24_Erik_Lyna_Helga_a4fdf736:
    l "对。来吧老哥，我们去扶她。"

translate schinese hscene24_Erik_Lyna_Helga_a7667445:
    h "{size=+5}嗨——！{/size}我的宝贝们……{size=-5}嗨……"

translate schinese hscene24_Erik_Lyna_Helga_46e2f926:
    l "抱歉！我们花久了点。"

translate schinese hscene24_Erik_Lyna_Helga_5cf66c34:
    h "我以为……{size=-5}你们把我忘了。"

translate schinese hscene24_Erik_Lyna_Helga_dc8928a4:
    e "怎么会妈妈！来，小心脚下。"

translate schinese hscene24_Erik_Lyna_Helga_8c3e8752:
    l "你扶着她了，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_59a5b597:
    e "对！呃……晚安，妹妹。"

translate schinese hscene24_Erik_Lyna_Helga_7f39f41c:
    l "拜拜！{size=-15}玩得开心……"

translate schinese hscene24_Erik_Lyna_Helga_ae055791:
    lm "现在轮到你了，冠军！"

translate schinese hscene24_Erik_Lyna_Helga_983bc42c:
    em "可怜的妈妈，她看起来……碎了。"

translate schinese hscene24_Erik_Lyna_Helga_d90355f6:
    em "她这一面很少见。看她受苦太让人难受了。"

translate schinese hscene24_Erik_Lyna_Helga_0b2f199c:
    em "但现在她需要我，比任何时候都需要。"

translate schinese hscene24_Erik_Lyna_Helga_a61f84c7:
    em "虽然我不想跟妹妹承认……"

translate schinese hscene24_Erik_Lyna_Helga_a4ec1e11:
    em "我有点想再摸妈妈，像那天在海滩那样……"

translate schinese hscene24_Erik_Lyna_Helga_aa0a9bfb:
    em "操。我脑子坏了。"

translate schinese hscene24_Erik_Lyna_Helga_e512a8b3:
    em "我们俩都是。"

translate schinese hscene24_Erik_Lyna_Helga_9fc427b4:
    lm "对不起妈妈。你这么脆弱的时候还做这种事，感觉太卑鄙了……"

translate schinese hscene24_Erik_Lyna_Helga_3d5ed834:
    lm "{cps=25}但这个夜晚变得那么……{w=0.35}更……{w=0.35}有趣了。"

translate schinese hscene24_Erik_Lyna_Helga_4346b49e:
    lm "嗯？什么……？"

translate schinese hscene24_Erik_Lyna_Helga_10ed64a9:
    e "我觉得有点过头了，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_ea89d6d3:
    h "{size=+5}哇！你开玩笑吗？！这也太漂亮了！"

translate schinese hscene24_Erik_Lyna_Helga_256b1779:
    e "确实挺温馨的……"

translate schinese hscene24_Erik_Lyna_Helga_71efbca1:
    e "莱娜帮我为今晚加了点装饰。"

translate schinese hscene24_Erik_Lyna_Helga_e300579f:
    h "我确实看得出来……"

translate schinese hscene24_Erik_Lyna_Helga_117d6f3f:
    hm "啊，在那儿！那个小坏蛋知道我要什么。"

translate schinese hscene24_Erik_Lyna_Helga_e96818fd:
    hm "而且等等，那是……？那只猫是……{size=-5}天啊。"

translate schinese hscene24_Erik_Lyna_Helga_a3298827:
    h "你知道吗儿子，我一直很喜欢你的房间。"

translate schinese hscene24_Erik_Lyna_Helga_702ad776:
    h "不管我们搬过多少次家，它们总是那么……*打嗝*那么像你！"

translate schinese hscene24_Erik_Lyna_Helga_3a8b405c:
    h "{size=-5}安静、有条理、让人安心……"

translate schinese hscene24_Erik_Lyna_Helga_ff73b505:
    e "谢谢妈妈。我很高兴你喜欢。"

translate schinese hscene24_Erik_Lyna_Helga_87552f3f:
    h "不过少了点东西。"

translate schinese hscene24_Erik_Lyna_Helga_21c12c7e:
    e "嗯？真的吗？"

translate schinese hscene24_Erik_Lyna_Helga_56736cea:
    h "对！在我们北欧的老家，你还留着我在你两岁生日时送的那只旧泰迪熊。还记得吗？"

translate schinese hscene24_Erik_Lyna_Helga_6580e5b9:
    h "我喜欢你这么多年还把它带在身边。真是太可爱了！"

translate schinese hscene24_Erik_Lyna_Helga_57c36094:
    e "是、是的，可我去年不可能把它带去国外上学。"

translate schinese hscene24_Erik_Lyna_Helga_8dc64cff:
    e "我室友会觉得我超级奇怪……"

translate schinese hscene24_Erik_Lyna_Helga_5e623210:
    h "是啊，哈哈！我完全理解。"

translate schinese hscene24_Erik_Lyna_Helga_a1ec3b99:
    h "但你不奇怪，宝贝。这只能证明你这么爱我……"

translate schinese hscene24_Erik_Lyna_Helga_fc67fc1d:
    h "即使你已经高过我腰部了，你还是每晚都抱着那只毛绒玩具睡觉。"

translate schinese hscene24_Erik_Lyna_Helga_192b1c54:
    h "你说是它让你有安全感，让你感到：「和妈妈非常亲近」。"

translate schinese hscene24_Erik_Lyna_Helga_0141b00e:
    e "是的，我记得。他和莱娜总是扶着我……"

translate schinese hscene24_Erik_Lyna_Helga_201fb71d:
    e "{size=-5}因为你和爸爸那么忙……{size=-10}总是不在家……"

translate schinese hscene24_Erik_Lyna_Helga_69d5a9a8:
    h "而现在我有自己的大泰迪熊可以抱了！嘿嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_196c89c4:
    h "哦不，宝贝……"

translate schinese hscene24_Erik_Lyna_Helga_4d81c13f:
    h "我非常非常抱歉！你和你妹妹那时候一定很寂寞。"

translate schinese hscene24_Erik_Lyna_Helga_c40d954e:
    h "我们太多次不尽父母该尽的责任了……"

translate schinese hscene24_Erik_Lyna_Helga_97190f8e:
    e "妈妈请别担心。你现在在这里，这才是最重要的。"

translate schinese hscene24_Erik_Lyna_Helga_ab3ead1d:
    h "{cps=25}{size=-5}天啊，{w=0.35}我的孩子……"

translate schinese hscene24_Erik_Lyna_Helga_f80f68b6:
    e "你不想呃……做那件事吗？"

translate schinese hscene24_Erik_Lyna_Helga_26d2d6e9:
    h "好、好的，当然！等一下……"

translate schinese hscene24_Erik_Lyna_Helga_9f42bd67:
    e "真的吗妈妈？！你还要继续喝吗？"

translate schinese hscene24_Erik_Lyna_Helga_269bf6d0:
    h "别担心我，宝贝……就让我放纵一次吧。"

translate schinese hscene24_Erik_Lyna_Helga_d0d6870b:
    e "{size=-5}啧。我早该把酒藏起来的……"

translate schinese hscene24_Erik_Lyna_Helga_71a16a20:
    h "我知道我不该喝这么多，但感觉太爽了。"

translate schinese hscene24_Erik_Lyna_Helga_a719406f:
    h "它能让那种……疼痛变得麻木。"

translate schinese hscene24_Erik_Lyna_Helga_f6bbadf6:
    e "也行。但求你别养成习惯！"

translate schinese hscene24_Erik_Lyna_Helga_1e19274a:
    e "你不能只是用酒精浇灭忧愁，然后假装这样能修复过去……"

translate schinese hscene24_Erik_Lyna_Helga_e72ce132:
    e "因为你还有我们，好吗？永远别忘了。"

translate schinese hscene24_Erik_Lyna_Helga_6370fb3b:
    h "嗯哼……"

translate schinese hscene24_Erik_Lyna_Helga_9ddef043:
    hm "他一直是个这么贴心的孩子。这么体贴，这么有爱……"

translate schinese hscene24_Erik_Lyna_Helga_d41b418d:
    hm "不管发生什么都只想给我最好的……"

translate schinese hscene24_Erik_Lyna_Helga_1e3d2606:
    h "*打嗝*你知道吗，我的儿子？"

translate schinese hscene24_Erik_Lyna_Helga_93d2cc1a:
    h "我觉得我现在可以享受那次美妙的按摩了……"

translate schinese hscene24_Erik_Lyna_Helga_fbbf73dc:
    l "{size=+20}你们好啊！"

translate schinese hscene24_Erik_Lyna_Helga_1330c5ea:
    e "{size=+5}天啊莱娜！进别人房间要敲门，懂吗？？！"

translate schinese hscene24_Erik_Lyna_Helga_7ce45f43:
    l "哎呀~"

translate schinese hscene24_Erik_Lyna_Helga_0d701297:
    h "{size=+5}噢噢！我的宝贝！{/size}*打嗝*你改主意了？！"

translate schinese hscene24_Erik_Lyna_Helga_b63d196b:
    l "没有，哈哈！我只是忘了给埃里克一样重要的东西。"

translate schinese hscene24_Erik_Lyna_Helga_d6325a55:
    l "{size=-5}给，装满按摩油的。"

translate schinese hscene24_Erik_Lyna_Helga_46a1c18f:
    e "{size=-5}嗯？你到底计划这计划多久了？！"

translate schinese hscene24_Erik_Lyna_Helga_e81f2237:
    l "{size=-5}什么意思？我只是在家里找到这个的~"

translate schinese hscene24_Erik_Lyna_Helga_0468f099:
    e "{size=-5}是啊，才怪……"

translate schinese hscene24_Erik_Lyna_Helga_328ea221:
    l "{size=-5}还有听着，老哥……"

translate schinese hscene24_Erik_Lyna_Helga_fa2dd488:
    l "{size=-5}这之后你可能会从我这儿得到一份非常特别的礼物……"

translate schinese hscene24_Erik_Lyna_Helga_c995eac7:
    e "{size=-5}*吞咽*那另一条毛、毛巾是干嘛的？"

translate schinese hscene24_Erik_Lyna_Helga_d62823fe:
    l "{size=-5}我们都知道妈妈那件浴袍里面没穿内衣。"

translate schinese hscene24_Erik_Lyna_Helga_6c672608:
    l "你们玩得开心！我这次真的走了！"

translate schinese hscene24_Erik_Lyna_Helga_ed8e787c:
    l "{size=-5}该死，这天气……{/size}今晚真暖和，对吧？？！"

translate schinese hscene24_Erik_Lyna_Helga_09ed01cd:
    em "唉，这个女孩……"

translate schinese hscene24_Erik_Lyna_Helga_c4aaf2dc:
    h "不错！那些东西会派上……*打嗝*用场的！"

translate schinese hscene24_Erik_Lyna_Helga_e32f6de5:
    e "妈妈，你确定吗？如果你不舒服我们可以不——"

translate schinese hscene24_Erik_Lyna_Helga_2822d8a7:
    h "是的，宝贝。{size=-5}我真的很想做……"

translate schinese hscene24_Erik_Lyna_Helga_45272f0a:
    hm "我不该这么急切地想再次感受他的手，可是……"

translate schinese hscene24_Erik_Lyna_Helga_b6c9cd27:
    hm "我需要这个。我需要……他。"

translate schinese hscene24_Erik_Lyna_Helga_20595e77:
    em "该死，冷静点埃里克！"

translate schinese hscene24_Erik_Lyna_Helga_6453e9c9:
    h "宝贝，你可能已经注意到了……这件浴袍里面我没穿内衣。"

translate schinese hscene24_Erik_Lyna_Helga_09892fb5:
    e "没关系妈、妈妈！莱娜给了我另一条毛巾专门应付这个。"

translate schinese hscene24_Erik_Lyna_Helga_1b51d9cc:
    h "是啊。你妹妹真体贴……"

translate schinese hscene24_Erik_Lyna_Helga_64ee6eea:
    h "我好像没怎么把「货」瞒过你们这些孩子，是吧？"

translate schinese hscene24_Erik_Lyna_Helga_9b475a49:
    h "希望你们能原谅……*打嗝*{size=-5}我没穿内衣。"

translate schinese hscene24_Erik_Lyna_Helga_520a4433:
    e "别、别担心妈妈，我懂……今晚挺暖和的。"

translate schinese hscene24_Erik_Lyna_Helga_35685afd:
    h "那就别在意我了！*打嗝*"

translate schinese hscene24_Erik_Lyna_Helga_9f5348ca:
    em "哦不不不……她该不会是指{size=+5}所有{/size}内衣都脱了吧？！"

translate schinese hscene24_Erik_Lyna_Helga_e7e6d0e6:
    em "妈妈全裸了！我从没见过这么美的东西……"

translate schinese hscene24_Erik_Lyna_Helga_ffdadeb1:
    h "天哪天哪！嘿嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_465cd8f5:
    h "我忘了下面也什么都没穿。我真傻！"

translate schinese hscene24_Erik_Lyna_Helga_ff02596e:
    em "该死，她要转过来吗？！我得赶紧行动！"

translate schinese hscene24_Erik_Lyna_Helga_b33e909e:
    e "给……那、那条毛巾。"

translate schinese hscene24_Erik_Lyna_Helga_f79c8529:
    h "哦？别担心，儿子。这没什么你没见过的……"

translate schinese hscene24_Erik_Lyna_Helga_c388a5cb:
    h "喂！你不用闭眼！我说了没关系……"

translate schinese hscene24_Erik_Lyna_Helga_34c97d1e:
    e "请你先遮一下自己。"

translate schinese hscene24_Erik_Lyna_Helga_1526e9e4:
    h "好吧。我准备好了，宝贝。"

translate schinese hscene24_Erik_Lyna_Helga_8f45a0b8:
    h "看？都遮好了。"

translate schinese hscene24_Erik_Lyna_Helga_d207f634:
    em "这太疯狂了！但我……我现在不能反悔了。"

translate schinese hscene24_Erik_Lyna_Helga_7860c3fa:
    h "那么，我们刚才说到哪了？过来点……"

translate schinese hscene24_Erik_Lyna_Helga_017bec53:
    em "天啊，那根本什么都没遮住……"

translate schinese hscene24_Erik_Lyna_Helga_a544e406:
    h "宝贝？别害羞，来给你老妈咪按摩……"

translate schinese hscene24_Erik_Lyna_Helga_13c8deee:
    h "*打嗝*而且你大概应、应该也把衬衫脱了吧，嗯？"

translate schinese hscene24_Erik_Lyna_Helga_c34bf8b7:
    e "呃……我——"

translate schinese hscene24_Erik_Lyna_Helga_76833851:
    h "还是你更想让你可怜的老妈去洗那些难看的污渍？"

translate schinese hscene24_Erik_Lyna_Helga_b55757a5:
    h "噢噢！你变结实了，儿子！"

translate schinese hscene24_Erik_Lyna_Helga_95eafbd2:
    e "谢谢……能重新规律锻炼感觉真好。"

translate schinese hscene24_Erik_Lyna_Helga_d7fa2af7:
    h "怎么样？妈妈在等着呢，我英俊的儿子……"

translate schinese hscene24_Erik_Lyna_Helga_eb76f337:
    em "加油，埃里克！你能做到。妈妈需要你……"

translate schinese hscene24_Erik_Lyna_Helga_26cb879f:
    h "嗯……对，就是这样，儿子。"

translate schinese hscene24_Erik_Lyna_Helga_dcf4bc37:
    hm "他的触碰如此抚慰。我已经能感觉到紧绷在消融……"

translate schinese hscene24_Erik_Lyna_Helga_00f6e964:
    lm "{size=+5}哇！我到底错过了什么？！"

translate schinese hscene24_Erik_Lyna_Helga_10b73782:
    lm "我就知道她抵抗不了！但等等，她……全裸了？！"

translate schinese hscene24_Erik_Lyna_Helga_5dd54e6f:
    lm "这些就是她的内衣？所以她刚才当着我们的面在客厅里脱了！多变态的妈妈……"

translate schinese hscene24_Erik_Lyna_Helga_647fdd31:
    lm "*嗅*{size=+10}操！这太刺激了！" with vpunch

translate schinese hscene24_Erik_Lyna_Helga_cde5955b:
    h "哦宝贝，我能习惯这个。"

translate schinese hscene24_Erik_Lyna_Helga_7605ca14:
    em "这太疯狂了！但她好像挺享受……？"

translate schinese hscene24_Erik_Lyna_Helga_5702891f:
    h "啊……你有双神奇的手，儿子。这正是我需要的。"

translate schinese hscene24_Erik_Lyna_Helga_cf8bb3f0:
    e "我……我很高、高兴你享受，妈妈。"

translate schinese hscene24_Erik_Lyna_Helga_b8b89e6d:
    lm "就是这样，老哥……"

translate schinese hscene24_Erik_Lyna_Helga_d9f606e1:
    lm "这是我们母亲需要的。是我们所有人都需要的。"

translate schinese hscene24_Erik_Lyna_Helga_894e8e99:
    lm "这只是个开始，大哥哥……{size=-5}妈妈……"

translate schinese hscene24_Erik_Lyna_Helga_ae3399bf:
    h "*打嗝*希望你后面没有……什么{i}想法{/i}。"

translate schinese hscene24_Erik_Lyna_Helga_15d5746c:
    h "我可不想让你不舒服，宝贝。"

translate schinese hscene24_Erik_Lyna_Helga_2610b8dc:
    e "妈、妈妈，你在说什么？"

translate schinese hscene24_Erik_Lyna_Helga_2586c7d1:
    h "我是说，我上半身光着，只裹着一条小毛巾什么的……"

translate schinese hscene24_Erik_Lyna_Helga_9a56f6df:
    h "希望你不会，你懂的……"

translate schinese hscene24_Erik_Lyna_Helga_ed31bbd7:
    h "{size=-5}太兴奋了。"

translate schinese hscene24_Erik_Lyna_Helga_4422895b:
    e "{size=+5}妈妈！你认真的吗？！" with vpunch

translate schinese hscene24_Erik_Lyna_Helga_79380fec:
    e "我只是给、给你按摩！{size=-5}就只是……{size=-10}这样。"

translate schinese hscene24_Erik_Lyna_Helga_9b8a990e:
    h "天啊！你这么容易害羞！真是可爱。"

translate schinese hscene24_Erik_Lyna_Helga_62b5467c:
    e "妈妈，别这样……"

translate schinese hscene24_Erik_Lyna_Helga_8011f47f:
    h "哈哈！宝贝，我只是逗你！"

translate schinese hscene24_Erik_Lyna_Helga_58d5a8fe:
    h "我知道你会是个乖孩子的，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_400240de:
    e "嗯哼……"

translate schinese hscene24_Erik_Lyna_Helga_9679f76a:
    lm "{size=+10}这他妈太色了！"

translate schinese hscene24_Erik_Lyna_Helga_e43df78c:
    lm "{size=+5}我移不开眼！我控制不住想要她们两个……"

translate schinese hscene24_Erik_Lyna_Helga_5d27c5c9:
    centered "{font=font_narration}{cps=20}{color=#69d9fe}( 我的双胞胎哥哥……{w=0.5}我亲生的妈妈…… )"

translate schinese hscene24_Erik_Lyna_Helga_70d77ae4:
    h "告诉我，我的儿子……"

translate schinese hscene24_Erik_Lyna_Helga_87b1dc85:
    h "你以前见过女人的身体吗？*打嗝*{size=-5}我是说，认真地看。"

translate schinese hscene24_Erik_Lyna_Helga_0d35af17:
    e "妈妈，我……我觉得现在不是谈这个的时间和场合。"

translate schinese hscene24_Erik_Lyna_Helga_2c8cade8:
    h "嗯，我只是在想也许你可以……{size=-10}也按摩一下前面。"

translate schinese hscene24_Erik_Lyna_Helga_a792bb3d:
    e "嗯？什么……？我不——"

translate schinese hscene24_Erik_Lyna_Helga_66a8d812:
    h "哦，拜托，小甜心。别扫兴。"

translate schinese hscene24_Erik_Lyna_Helga_9e339c76:
    e "可妈、妈妈，你——"

translate schinese hscene24_Erik_Lyna_Helga_98270180:
    h "裸体。对！这只是人生自然而然的一部分……"

translate schinese hscene24_Erik_Lyna_Helga_6fb141b8:
    e "你到底在……暗示什么？！"

translate schinese hscene24_Erik_Lyna_Helga_b1940957:
    e "你醉了妈妈！你不知道自己在说什么！"

translate schinese hscene24_Erik_Lyna_Helga_ed6eef93:
    h "喂！*打嗝*别……呃……担心。"

translate schinese hscene24_Erik_Lyna_Helga_3a290a57:
    h "你妈咪喝点酒还是撑得住的！嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_c43c4794:
    h "再说了，我只是让你揉揉我的肚子，仅此而已……"

translate schinese hscene24_Erik_Lyna_Helga_4221f3ab:
    e "我不知道……"

translate schinese hscene24_Erik_Lyna_Helga_3adde7d3:
    h "为什么这么犹豫？求你了，会很舒服的。"

translate schinese hscene24_Erik_Lyna_Helga_eb29bd80:
    h "你以前见过我穿比基尼，对吧？差不了多少。"

translate schinese hscene24_Erik_Lyna_Helga_3b6198e9:
    h "还记得吗……我们那天早上的意外？"

translate schinese hscene24_Erik_Lyna_Helga_f0c3d37d:
    e "我、我记得，可我们只有一条多余的毛巾……"

translate schinese hscene24_Erik_Lyna_Helga_620adac9:
    h "哦……？*打嗝*我完全忘了！"

translate schinese hscene24_Erik_Lyna_Helga_e4458258:
    hm "可恶，我知道他说得对，可是……"

translate schinese hscene24_Erik_Lyna_Helga_a3b01973:
    hm "今晚我好像一点都不在乎了。和儿子在一起我只觉得那么安心。"

translate schinese hscene24_Erik_Lyna_Helga_59e428fc:
    e "{size=-5}看来我得去再拿一条……？"

translate schinese hscene24_Erik_Lyna_Helga_d4539c10:
    h "{cps=30}别去。{w=0.35}你只要选遮住哪一部分，{w=0.35}对吧？"

translate schinese hscene24_Erik_Lyna_Helga_34a2d2ab:
    h "{cps=30}上面还是下面，{w=0.15}宝贝。{w=0.5}你选。"

translate schinese hscene24_Erik_Lyna_Helga_f5187e57:
    em "哇！我都认不出来了。这真的是我妈妈吗？！"

translate schinese hscene24_Erik_Lyna_Helga_598e6411:
    em "我们一向很亲近，可有了酒……她彻底疯了！"

translate schinese hscene24_Erik_Lyna_Helga_f42ca172:
    e "等、等等！不应该……"

translate schinese hscene24_Erik_Lyna_Helga_532669c4:
    e "你光着身子，而我是你儿子。这不对。"

translate schinese hscene24_Erik_Lyna_Helga_0f96f7f8:
    h "哦，小宝贝儿子……总是这么正派，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_b0984e88:
    h "你知道吗，有时候走出自己的舒适区是好事。"

translate schinese hscene24_Erik_Lyna_Helga_0ab2c118:
    h "而且我们确实是家人，但是……"

translate schinese hscene24_Erik_Lyna_Helga_27035f7f:
    h "你当时让我看到你能控制住{i}它{/i}，在我处理你伤口的时候。"

translate schinese hscene24_Erik_Lyna_Helga_0a90183e:
    h "所以我真不介意你多看一点不该看的，儿子……"

translate schinese hscene24_Erik_Lyna_Helga_0afb3a19:
    em "搞什么鬼？！她怎么能说得这么随便？！"

translate schinese hscene24_Erik_Lyna_Helga_a45c9dd3:
    em "而且她又在说我的勃起！"

translate schinese hscene24_Erik_Lyna_Helga_5fd9cc47:
    em "这太不对了，可是莱娜……她答应过我，如果我——"

translate schinese hscene24_Erik_Lyna_Helga_82f89b9d:
    h "你不想也好好按摩一下前面吗？"

translate schinese hscene24_Erik_Lyna_Helga_ebd4d63a:
    h "我知道你真的很喜欢我的……*打嗝*{size=-5}我紧实的肌肉……"

translate schinese hscene24_Erik_Lyna_Helga_33b1951b:
    e "好、好吧妈妈……我做。但只是因为看起来你真的很想要！"

translate schinese hscene24_Erik_Lyna_Helga_e6771e17:
    e "我们用毛巾遮住你的……{size=-5}你懂的。"

translate schinese hscene24_Erik_Lyna_Helga_76ec2e29:
    h "嗯……？"

translate schinese hscene24_Erik_Lyna_Helga_725cb357:
    e "你的私密部位，妈妈！"

translate schinese hscene24_Erik_Lyna_Helga_8510d749:
    h "哦，对哦！嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_83ddb42e:
    em "她一口就喝完了，哇……"

translate schinese hscene24_Erik_Lyna_Helga_928abf03:
    e "我……我给你留点空间。"

translate schinese hscene24_Erik_Lyna_Helga_55c3084a:
    h "宝贝？你在干什么……？"

translate schinese hscene24_Erik_Lyna_Helga_e4b171b0:
    e "{size=-5}你、你准备好了吗？"

translate schinese hscene24_Erik_Lyna_Helga_b3cfcc03:
    h "好了！别担心，我用手挡着奶子呢。"

translate schinese hscene24_Erik_Lyna_Helga_948e5d40:
    e "{size=+5}妈妈！真的假的？！"

translate schinese hscene24_Erik_Lyna_Helga_321a7e3e:
    h "怎么？你更想让我给你看？哈哈！"

translate schinese hscene24_Erik_Lyna_Helga_71f351c8:
    h "来吧，我害羞的小儿子……我在等。"

translate schinese hscene24_Erik_Lyna_Helga_a30714f9:
    em "哦不不……不！她真的做了？！"

translate schinese hscene24_Erik_Lyna_Helga_ba53b9a2:
    h "看？*打嗝*没什么大不了的！"

translate schinese hscene24_Erik_Lyna_Helga_38d76c5d:
    em "加油埃里克，呼吸！别让她看到你硬了，现在不行……"

translate schinese hscene24_Erik_Lyna_Helga_c40a4857:
    e "妈妈这不对……呃……"

translate schinese hscene24_Erik_Lyna_Helga_e9e2aae2:
    h "天啊，你害羞起来真是该死地可爱！"

translate schinese hscene24_Erik_Lyna_Helga_94563ac6:
    h "不过说真的，没关系。"

translate schinese hscene24_Erik_Lyna_Helga_ad0a8625:
    e "呃……{size=-5}呃……"

translate schinese hscene24_Erik_Lyna_Helga_67c08635:
    h "只是我，你妈妈。你可以转过来了。"

translate schinese hscene24_Erik_Lyna_Helga_da88ba21:
    e "你至少能闭一下眼睛吗？"

translate schinese hscene24_Erik_Lyna_Helga_0014b40c:
    h "当然，如果那能让你自在一点。"

translate schinese hscene24_Erik_Lyna_Helga_8181ec73:
    h "我全心全意信任你。{size=-5}我知道你会守规矩……"

translate schinese hscene24_Erik_Lyna_Helga_ea39c045:
    em "她那话到底是什么意思？！"

translate schinese hscene24_Erik_Lyna_Helga_cbf586a6:
    em "这完全疯了，可我现在不能停下了，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_d7ac749d:
    em "我必须看完。我必须帮妈妈。"

translate schinese hscene24_Erik_Lyna_Helga_f5385522:
    n "男孩脑子里不停找借口，想不通母亲怎么能在他面前穿得这么少还那么自在。"

translate schinese hscene24_Erik_Lyna_Helga_8f29f7a1:
    n "一定是酒精，他告诉自己。他看不出别的理由。"

translate schinese hscene24_Erik_Lyna_Helga_7c41b28c:
    h "来吧宝贝，我还在等……"

translate schinese hscene24_Erik_Lyna_Helga_c73e82ef:
    h "啊啊，对……{size=-5}这才是我的儿子……"

translate schinese hscene24_Erik_Lyna_Helga_50840dc9:
    n "他的触碰有力却温柔。可他的目光却不断飘向她几乎遮不住的胸部。"

translate schinese hscene24_Erik_Lyna_Helga_c1789c70:
    n "每当他抚过她光洁的肌肤，那女人就会本能地把胸部压得更紧。"

translate schinese hscene24_Erik_Lyna_Helga_afbaac97:
    n "而她并不是唯一的一个……"

translate schinese hscene24_Erik_Lyna_Helga_e12a8911:
    hm "我不能相信我居然让他这么做！天啊……"

translate schinese hscene24_Erik_Lyna_Helga_857a4a22:
    hm "等等，那是……？"

translate schinese hscene24_Erik_Lyna_Helga_a0cdc38f:
    hm "当然了！多尴尬……我都不知道我在期待什么。"

translate schinese hscene24_Erik_Lyna_Helga_88e2465d:
    hm "你儿子现在是年轻男人了，赫尔加。他有需求的！"

translate schinese hscene24_Erik_Lyna_Helga_c0f2f182:
    hm "我真是个糟糕、糟糕的母亲！这样在他面前暴露自己……"

translate schinese hscene24_Erik_Lyna_Helga_dc4a0df5:
    hm "我不该怂恿他跟我这么亲密……"

translate schinese hscene24_Erik_Lyna_Helga_2c9b2402:
    hm "可那为什么……？！为什么我这么想让他看我？"

translate schinese hscene24_Erik_Lyna_Helga_6a16cfcc:
    hm "承认这个太可耻了，可我想再次感受{i}那{/i}一晚。"

translate schinese hscene24_Erik_Lyna_Helga_353804fb:
    hm "我当初就不该做那件事。那太错误、太愚蠢、太不可想象……可我亲生的儿子却让我感觉如此……"

translate schinese hscene24_Erik_Lyna_Helga_d07c3657:
    centered "{font=font_narration}{size=+15}{cps=20}{color=#f1d377}（活着）{w=0.8}{nw}"

translate schinese hscene24_Erik_Lyna_Helga_7eaa6dc8:
    em "{size=+5}搞什么鬼？！她为什么突然那样？！" with hpunch

translate schinese hscene24_Erik_Lyna_Helga_7f1d0b5a:
    em "{size=+10}我全都看见了！我妈妈的……"

translate schinese hscene24_Erik_Lyna_Helga_6fa67e8f:
    h "宝贝……？你怎么停了？"

translate schinese hscene24_Erik_Lyna_Helga_7471d0f9:
    e "可、可是妈妈！你的……呃……露出来了！"

translate schinese hscene24_Erik_Lyna_Helga_7e4e4fef:
    h "你是说我的胸？抱歉，我胳膊有点酸了……"

translate schinese hscene24_Erik_Lyna_Helga_809a0ab1:
    h "但我不介意，宝贝。*打嗝*不过就是一对胸部而已，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_cc425dc2:
    em "是啊！要不是它们这么大……这么完美……而且偏偏长在我该死的妈妈身上！"

translate schinese hscene24_Erik_Lyna_Helga_e5982b4e:
    h "只是……*打嗝*你让我感觉那么放松。"

translate schinese hscene24_Erik_Lyna_Helga_323b6616:
    e "那很、太好了，可是呃……我——"

translate schinese hscene24_Erik_Lyna_Helga_57e1dc8c:
    h "埃里克？！别告诉我你要把活干一半就跑掉！"

translate schinese hscene24_Erik_Lyna_Helga_6102018f:
    e "什么？不不不，绝不会！但你真的完全确定吗？"

translate schinese hscene24_Erik_Lyna_Helga_4c00fc77:
    h "宝贝，看着我。没关系。"

translate schinese hscene24_Erik_Lyna_Helga_48ee8e0c:
    h "我们是母子，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_46e3b2a3:
    h "我们不该在彼此面前感到尴尬，好吗？"

translate schinese hscene24_Erik_Lyna_Helga_6c86102a:
    em "我不能相信她就这样让我继续下去……"

translate schinese hscene24_Erik_Lyna_Helga_444e0e95:
    em "可我在骗自己吗？我想看看这会走到哪一步。"

translate schinese hscene24_Erik_Lyna_Helga_190ad7d3:
    h "求你为我做吧？没什么能让我更开心的了……"

translate schinese hscene24_Erik_Lyna_Helga_51ac6f95:
    e "{size=-5}好、好的妈……"

translate schinese hscene24_Erik_Lyna_Helga_1af32cff:
    h "很好！继续吧，我的儿子……{size=-5}把你开始的做完。"

translate schinese hscene24_Erik_Lyna_Helga_a432d488:
    h "{size=+5}唔嗯！{/size}就是这样……"

translate schinese hscene24_Erik_Lyna_Helga_ee704262:
    h "你喜欢妈咪的腹肌吗？"

translate schinese hscene24_Erik_Lyna_Helga_a1b47ea2:
    e "{size=-5}喜欢，你他妈太健美了……"

translate schinese hscene24_Erik_Lyna_Helga_ed7c98d8:
    hm "这感觉真好。{size=+5}太好了！"

translate schinese hscene24_Erik_Lyna_Helga_408ffd7c:
    hm "我不该这么喜欢这个……可他也很享受，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_b5210667:
    hm "天啊，我为什么停不下来盯着我儿子的凸起？！他硬成这样！"

translate schinese hscene24_Erik_Lyna_Helga_da04cf0f:
    lm "哇！妈妈就这样让他做了？！"

translate schinese hscene24_Erik_Lyna_Helga_fa820dd3:
    lm "更棒的是……我那个害羞的小变态玩得这么投入！"

translate schinese hscene24_Erik_Lyna_Helga_f6026b8a:
    lm "这比那些愚蠢的假色情片好上一百万倍……"

translate schinese hscene24_Erik_Lyna_Helga_0d2d98c5:
    lm "甚至完美过头了，因为这是真的……"

translate schinese hscene24_Erik_Lyna_Helga_87ab055f:
    centered "{font=font_narration}{size=+15}{cps=20}{color=#69d9fe}（真正的乱伦！）{w=1.0}{nw}"

translate schinese hscene24_Erik_Lyna_Helga_026edd49:
    lm "操！光这个念头就差点让我射了！"

translate schinese hscene24_Erik_Lyna_Helga_44be9298:
    lm "只要再摸一下，我敢说我能射出一条河……"

translate schinese hscene24_Erik_Lyna_Helga_1f5a4e74:
    h "继续，儿子，把那油抹满我{size=-5}性感{/size}的肚子……"

translate schinese hscene24_Erik_Lyna_Helga_590fc91f:
    e "妈妈？！你在说什么？"

translate schinese hscene24_Erik_Lyna_Helga_6aca856b:
    h "对、对不起宝贝！*打嗝*{size=-5}只是酒在说话……"

translate schinese hscene24_Erik_Lyna_Helga_02816049:
    h "能再往上一点吗？"

translate schinese hscene24_Erik_Lyna_Helga_16b06569:
    em "操，我……没法拒绝她。"

translate schinese hscene24_Erik_Lyna_Helga_e6429590:
    h "嗯哼！好宝贝！感觉真舒服……"

translate schinese hscene24_Erik_Lyna_Helga_850434f4:
    em "如果我……？"

translate schinese hscene24_Erik_Lyna_Helga_c3394db2:
    hm "天哪天哪！他刚才是不是……？！我的孩子什么时候变得这么大胆了？！"

translate schinese hscene24_Erik_Lyna_Helga_6a27ae94:
    hm "{size=+5}我受不了了！"

translate schinese hscene24_Erik_Lyna_Helga_658bdce9:
    hm "我需要释放。我需要感觉……点什么。任何东西！"

translate schinese hscene24_Erik_Lyna_Helga_7a331ffb:
    hm "我都像很正常一样跟女儿一起洗澡了，让他摸我又怎样？"

translate schinese hscene24_Erik_Lyna_Helga_79d9995f:
    hm "对，去他的！我醉得已经不在乎了……反正我什么都不会记得。"

translate schinese hscene24_Erik_Lyna_Helga_1ab52a72:
    e "对不起，我的手只是……{size=-5}呃……{size=-10}滑了一下。"

translate schinese hscene24_Erik_Lyna_Helga_d2506ea9:
    h "宝贝，告诉我一件事……*打嗝*"

translate schinese hscene24_Erik_Lyna_Helga_8271cfbd:
    h "你以前摸过像这样的女人吗？"

translate schinese hscene24_Erik_Lyna_Helga_7cf18560:
    e "什么……？"

translate schinese hscene24_Erik_Lyna_Helga_a00d8c32:
    h "回答我就行。求你说实话。"

translate schinese hscene24_Erik_Lyna_Helga_2e46d02f:
    em "对不起妈妈，可你永远不能知道莱娜的事……"

translate schinese hscene24_Erik_Lyna_Helga_83402c53:
    e "没、没有。"

translate schinese hscene24_Erik_Lyna_Helga_6d04347f:
    h "我明白了，那很好。"

translate schinese hscene24_Erik_Lyna_Helga_b7305f03:
    h "话说，你想不想……*打嗝*{size=-5}碰碰我别的地方？"

translate schinese hscene24_Erik_Lyna_Helga_0d48bc95:
    e "妈妈？！你在——我……我不知道该说什么。"

translate schinese hscene24_Erik_Lyna_Helga_5d152a8a:
    e "那不是非常不合适吗？"

translate schinese hscene24_Erik_Lyna_Helga_3f288518:
    h "会吗？如果是我在问的话……"

translate schinese hscene24_Erik_Lyna_Helga_7fd4fbc3:
    e "嗯，你真的……想吗？{size=-5}我觉得我们不该。"

translate schinese hscene24_Erik_Lyna_Helga_804e609f:
    h "啊，宝贝。你真纯洁。"

translate schinese hscene24_Erik_Lyna_Helga_f3f62edf:
    h "我说过了……我知道过去几周你一直盯着看。"

translate schinese hscene24_Erik_Lyna_Helga_eae902c0:
    h "看？*打嗝*我可记不得我儿子这么大胆！嘿嘿嘿~"

translate schinese hscene24_Erik_Lyna_Helga_4f8a741a:
    h "你就那么喜欢我的奶子吗？所以才那么执着？"

translate schinese hscene24_Erik_Lyna_Helga_c54f0395:
    em "{size=+5}我不能相信妈妈会问我这种问题！"

translate schinese hscene24_Erik_Lyna_Helga_59ab1d95:
    h "我们是家人。应该什么都能聊，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_ce38aa32:
    h "再说了，我只是……好奇。我想知道你怎么想。"

translate schinese hscene24_Erik_Lyna_Helga_81294f0f:
    em "够了。我受够了假装！她基本就是在求我了……"

translate schinese hscene24_Erik_Lyna_Helga_476c0613:
    e "{size=-5}我喜欢。{size=-10}它们很美。"

translate schinese hscene24_Erik_Lyna_Helga_c74a84e2:
    h "什么？你能再说一遍吗？我有点……*打嗝*{size=-5}微醺。"

translate schinese hscene24_Erik_Lyna_Helga_c1e616cf:
    e "你的、你的奶子，妈妈！它们又大又美！" with hpunch

translate schinese hscene24_Erik_Lyna_Helga_33098169:
    hm "天哪天哪！他居然夸了我的胸部！"

translate schinese hscene24_Erik_Lyna_Helga_f0103f32:
    hm "我亲生的儿子，我甜蜜的小王子……"

translate schinese hscene24_Erik_Lyna_Helga_45ac2748:
    h "谢谢你，宝贝。"

translate schinese hscene24_Erik_Lyna_Helga_65ebb292:
    h "你知道妈妈喜欢你说实话……"

translate schinese hscene24_Erik_Lyna_Helga_9e09d54e:
    h "{size=-5}{cps=20}你觉得我是熟女吗，{w=0.35}儿子？"

translate schinese hscene24_Erik_Lyna_Helga_c810c942:
    e "啥？！你知道那是什么意思吗？！"

translate schinese hscene24_Erik_Lyna_Helga_024ea3be:
    h "呃……知道！当然知道！*打嗝*"

translate schinese hscene24_Erik_Lyna_Helga_c18beece:
    h "你妹妹告诉我说是年轻觉得有吸引力的老女人，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_d3063ae1:
    em "看在上帝份上，莱娜……"

translate schinese hscene24_Erik_Lyna_Helga_5dfbc7fb:
    e "对，大概……是那个意思。"

translate schinese hscene24_Erik_Lyna_Helga_d137db65:
    h "那我是吗？"

translate schinese hscene24_Erik_Lyna_Helga_4e10dd46:
    e "妈妈，求你了……"

translate schinese hscene24_Erik_Lyna_Helga_fbbb5723:
    h "对不起，对不起！我知道我不该问这个，也不该在你面前裸着……"

translate schinese hscene24_Erik_Lyna_Helga_8a54e45e:
    h "可你一直都是这么棒的儿子，你知道的吧？"

translate schinese hscene24_Erik_Lyna_Helga_9052d5c6:
    h "而且在你的怀里我觉得那么安全、那么舒适……"

translate schinese hscene24_Erik_Lyna_Helga_77f089f2:
    e "*叹气*你是……{size=-5}很有吸引力的，是的。"

translate schinese hscene24_Erik_Lyna_Helga_1ff50e87:
    h "嗯，我明白了。{cps=20}那就告诉我，{size=-5}{w=0.35}小甜心……"

translate schinese hscene24_Erik_Lyna_Helga_b5c6f611:
    h "{cps=30}你想摸摸{i}它们{/i}吗？{w=0.5}摸一摸……{w=0.35}一对胸部？"

translate schinese hscene24_Erik_Lyna_Helga_1de6a30e:
    em "{size=+5}我勒个去！我是在做梦吗？！"

translate schinese hscene24_Erik_Lyna_Helga_38ed4998:
    em "我不能相信自己居然在考虑这个。她那么脆弱、那么缺爱……"

translate schinese hscene24_Erik_Lyna_Helga_72f9cc8f:
    em "但我不能否认我也很好奇。"

translate schinese hscene24_Erik_Lyna_Helga_e429ca81:
    h "求你了，就……*打嗝*摸一小会儿，好吗？"

translate schinese hscene24_Erik_Lyna_Helga_2e441a34:
    h "我不会告诉任何人。这会是我们的秘密。"

translate schinese hscene24_Erik_Lyna_Helga_056a3f75:
    e "可是妈妈，那……太疯狂了。"

translate schinese hscene24_Erik_Lyna_Helga_e654ddcf:
    h "我知道，宝贝。我知道！可是求你……我需要感受你的触碰。"

translate schinese hscene24_Erik_Lyna_Helga_1879d971:
    h "{size=-5}我需要知道这世上还有一个男人在乎我。"

translate schinese hscene24_Erik_Lyna_Helga_88d07d20:
    em "天啊……她在说什么？！"

translate schinese hscene24_Erik_Lyna_Helga_f6baffae:
    em "操。对不起妈妈。我知道你现在醉得厉害，脑子也不清醒……"

translate schinese hscene24_Erik_Lyna_Helga_82f9dff2:
    em "可我他妈欲火焚身！而且莱娜今天没「帮」我……"

translate schinese hscene24_Erik_Lyna_Helga_6cb8f80d:
    em "所以求你原谅我接下来要做的事。"

translate schinese hscene24_Erik_Lyna_Helga_2e88b654:
    e "{cps=20}{size=-5}好吧妈……{w=0.5}我会摸它们。"

translate schinese hscene24_Erik_Lyna_Helga_07c202e9:
    h "{cps=20}{size=-5}很好，{w=0.35}我的小王子。{w=0.5}很好……"

translate schinese hscene24_Erik_Lyna_Helga_20d15e83:
    h "{cps=25}我准备好给你了……{w=0.35}小宝贝儿子。"

translate schinese hscene24_Erik_Lyna_Helga_a6f797ac:
    h "{cps=15}{size=-5}来摸妈妈……"

translate schinese hscene24_Erik_Lyna_Helga_25fd8408:
    hm "天啊，他连犹豫都没有！那是他的手……{size=-5}我儿子的手。"

translate schinese hscene24_Erik_Lyna_Helga_7d41daaf:
    em "哇！这到底是什么感觉？！她的皮肤又软又暖……"

translate schinese hscene24_Erik_Lyna_Helga_3b328c77:
    em "它们比我妹妹的大多了……"

translate schinese hscene24_Erik_Lyna_Helga_cf8c7dc0:
    n "怀着几乎原始的渴望，埃里克急忙抓住另一边的乳房。"

translate schinese hscene24_Erik_Lyna_Helga_5342eb3e:
    h "你、你喜欢吗？你喜欢我的……{size=-5}奶子吗？"

translate schinese hscene24_Erik_Lyna_Helga_87a8a0d8:
    e "{size=-5}喜欢……"

translate schinese hscene24_Erik_Lyna_Helga_deb877f3:
    n "男孩一边往它们上涂油，一边下流地揉捏，被醉酒母亲甜美迷人的话语不断推着向前。"

translate schinese hscene24_Erik_Lyna_Helga_34ae6070:
    n "他想尽情沉浸在这份前所未有的礼物中，把这神圣的感觉永远刻进记忆。"

translate schinese hscene24_Erik_Lyna_Helga_8eb76695:
    h "呃……它们软吗，宝贝？手感好吗？"

translate schinese hscene24_Erik_Lyna_Helga_67fec784:
    e "是的，妈。它们……{size=-5}非常软。"

translate schinese hscene24_Erik_Lyna_Helga_c052b74b:
    h "哦，宝贝，我真幸运能有你这样有爱的儿子。"

translate schinese hscene24_Erik_Lyna_Helga_6625f935:
    e "谢谢妈妈。我看得出你很享受……"

translate schinese hscene24_Erik_Lyna_Helga_83ec5cbb:
    h "嗯，感觉……{size=-5}棒极了……"

translate schinese hscene24_Erik_Lyna_Helga_9b411923:
    hm "而且我讨厌这样！我讨厌自己这么喜欢……"

translate schinese hscene24_Erik_Lyna_Helga_450cee65:
    hm "可这次他是清醒的，对吧？而且他同意了。我不是在再利用他，因为……"

translate schinese hscene24_Erik_Lyna_Helga_baebea26:
    centered "{font=font_narration}{cps=25}{color=#f1d377}( 我亲生的儿子同意摸我裸露的胸部。 )"

translate schinese hscene24_Erik_Lyna_Helga_b9b9efdf:
    h "{size=+5}呃……！"

translate schinese hscene24_Erik_Lyna_Helga_f3fc689f:
    em "该死！我不能相信她这么享受。"

translate schinese hscene24_Erik_Lyna_Helga_dbd8e0bd:
    lm "我的天！怎么他妈升级得这么快？！"

translate schinese hscene24_Erik_Lyna_Helga_5f61533f:
    lm "我本来只想偷看个火辣的后背按摩，可这比我最疯狂的梦还过分……"

translate schinese hscene24_Erik_Lyna_Helga_7fa000b6:
    lm "我哥哥真的在摸妈妈的奶子，而她……还由着他！"

translate schinese hscene24_Erik_Lyna_Helga_ccdc2a1d:
    lm "操，我真希望我也在里面。"

translate schinese hscene24_Erik_Lyna_Helga_e7eb04fc:
    hm "我们不该这样……可感觉太他妈爽了！"

translate schinese hscene24_Erik_Lyna_Helga_f02b8102:
    hm "{size=+5}我这是怎么了？！我控制不住想要更多！"

translate schinese hscene24_Erik_Lyna_Helga_9dc523e5:
    h "儿子……别停！{size=-5}你的触碰太舒服了……"

translate schinese hscene24_Erik_Lyna_Helga_a860d259:
    h "{cps=25}{size=-10}就像你天生就是干这个的。"

translate schinese hscene24_Erik_Lyna_Helga_7c2ed996:
    lm "这太他妈离谱了，但太色了！"

translate schinese hscene24_Erik_Lyna_Helga_5bf88055:
    l "{size=-5}操、操、操……！"

translate schinese hscene24_Erik_Lyna_Helga_ce206f1a:
    lm "就是这样老哥，继续捏妈妈那对又大又肥的奶子！"

translate schinese hscene24_Erik_Lyna_Helga_3036f8ab:
    h "{size=+5}求你了小宝贝儿子，再用力点！"

translate schinese hscene24_Erik_Lyna_Helga_5a4c32ea:
    h "{size=+15}啊啊啊啊！{/size}操……"

translate schinese hscene24_Erik_Lyna_Helga_a0e13059:
    em "该死！她叫得这么大声！我们在干什么？！"

translate schinese hscene24_Erik_Lyna_Helga_d9dd4349:
    e "够了……妈妈。我们不能继续这样了。"

translate schinese hscene24_Erik_Lyna_Helga_14f7eb9b:
    h "哼！什么？拜托……"

translate schinese hscene24_Erik_Lyna_Helga_9910a2c6:
    h "哦？！我好像看出你的{i}问题{/i}了……"

translate schinese hscene24_Erik_Lyna_Helga_3f9fb3a1:
    h "我把注意力全抢走了，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_98d75973:
    em "该死！她正盯着看呢！"

translate schinese hscene24_Erik_Lyna_Helga_b930c5d9:
    hm "天啊，都快塞不进去了……"

translate schinese hscene24_Erik_Lyna_Helga_152de2e8:
    e "妈、妈妈，这不是你想的那样……我——"

translate schinese hscene24_Erik_Lyna_Helga_c1304201:
    h "你是这么乖的{i}小{/i}家伙，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_920e46a6:
    h "你总是知道怎么让我感觉好……"

translate schinese hscene24_Erik_Lyna_Helga_e205ab25:
    h "{cps=20}那也许……"

translate schinese hscene24_Erik_Lyna_Helga_2d10b4dd:
    h "{cps=25}妈妈也该让你感觉好起来，{w=0.35}对吧？"

translate schinese hscene24_Erik_Lyna_Helga_889924d4:
    h "这是因为我吗？因为我们正在做的事……？"

translate schinese hscene24_Erik_Lyna_Helga_3ccc8089:
    h "你下面绷得好紧，小宝贝儿子……"

translate schinese hscene24_Erik_Lyna_Helga_c318ac64:
    h "你该不会一直在骗我吧？"

translate schinese hscene24_Erik_Lyna_Helga_8b6918df:
    h "问题不在你那位女老师身上，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_64929480:
    e "{size=+5}妈妈！求、求你了，别再这样疯下去！"

translate schinese hscene24_Erik_Lyna_Helga_93fff96a:
    e "你喝太多了酒！就……冷静点。"

translate schinese hscene24_Erik_Lyna_Helga_8a20fef9:
    h "天啊，我……*打嗝*{size=-5}我不是故意那样的……"

translate schinese hscene24_Erik_Lyna_Helga_0a8bdfc8:
    h "对不起宝贝！我不知道自己今晚怎么了……"

translate schinese hscene24_Erik_Lyna_Helga_4cd47578:
    e "妈妈，我……我不知道该说什么。这一切太混乱了。"

translate schinese hscene24_Erik_Lyna_Helga_d2d8ba71:
    e "*叹气*你醉得很厉害。现在连脑子都不清楚了。"

translate schinese hscene24_Erik_Lyna_Helga_296d8841:
    e "我觉得自己趁你这个状态占你便宜！"

translate schinese hscene24_Erik_Lyna_Helga_f35f2aa3:
    e "你明白的，对吧？我不能再这样了……"

translate schinese hscene24_Erik_Lyna_Helga_e163a0dc:
    h "啊，我这个傻儿子！{size=-5}总是想着别人……"

translate schinese hscene24_Erik_Lyna_Helga_2d974f46:
    h "别担心，因为……*打嗝*我其实超喜欢这样！"

translate schinese hscene24_Erik_Lyna_Helga_4d114650:
    e "那只是酒在说话，你看不出来吗？！"

translate schinese hscene24_Erik_Lyna_Helga_1da0a31e:
    e "再说了，你仍然是我妈妈！"

translate schinese hscene24_Erik_Lyna_Helga_8f60aca9:
    e "我不该跟你做这些事……"

translate schinese hscene24_Erik_Lyna_Helga_5862c6c5:
    em "因为那样会阻止我跟莱娜，对吧？"

translate schinese hscene24_Erik_Lyna_Helga_afa29951:
    h "是我太老了吗？*打嗝*是这样吗……"

translate schinese hscene24_Erik_Lyna_Helga_86af78ea:
    h "我变得松垮、起了皱纹……{size=-5}我讨厌这样。"

translate schinese hscene24_Erik_Lyna_Helga_be6841d2:
    h "所以他才……*抽泣*才离开我的吗，埃里克？"

translate schinese hscene24_Erik_Lyna_Helga_6a8d5073:
    h "{size=+5}所以你爸爸才毁了我们该死的婚姻？！" with hpunch

translate schinese hscene24_Erik_Lyna_Helga_9641d4b3:
    em "该死，可怜的妈妈……我不能就这样离开她。"

translate schinese hscene24_Erik_Lyna_Helga_a347276d:
    em "我都不知道我们是怎么走到这一步的，但她至少需要一些安慰。"

translate schinese hscene24_Erik_Lyna_Helga_7cab1595:
    h "{size=+10}那个该死的混蛋！"

translate schinese hscene24_Erik_Lyna_Helga_3324a506:
    e "妈妈，我非常抱歉他那样伤你……"

translate schinese hscene24_Erik_Lyna_Helga_c84bf2f7:
    h "{size=+5}他怎么能那样对我？！对我们？！"

translate schinese hscene24_Erik_Lyna_Helga_05330d8b:
    h "你爸爸以前可喜欢这对胸部了！难道我还不够好吗？！"

translate schinese hscene24_Erik_Lyna_Helga_96d1ec22:
    h "{size=+5}他干脆去操一个年轻的小婊子了！"

translate schinese hscene24_Erik_Lyna_Helga_97a5f0ed:
    e "冷静点，求你了……"

translate schinese hscene24_Erik_Lyna_Helga_642016a3:
    hm "我到底在干什么？！我不该把过去对约翰的爱投射到我们天真的儿子身上。"

translate schinese hscene24_Erik_Lyna_Helga_0313fe79:
    hm "可我太寂寞了。我需要再次感觉被爱，需要被一个不会让我心碎的人渴望。"

translate schinese hscene24_Erik_Lyna_Helga_d43873d1:
    e "喂、喂……看着我。没事的。"

translate schinese hscene24_Erik_Lyna_Helga_2dd27e3f:
    e "你不老，妈妈。你是这么美的女人。"

translate schinese hscene24_Erik_Lyna_Helga_1d2335e3:
    e "你身上的每一部分，好吗？包括……{size=-5}你的身体。"

translate schinese hscene24_Erik_Lyna_Helga_22f7eab2:
    e "而且是爸爸离开你才犯了大错！所以请永远别为此责怪自己。"

translate schinese hscene24_Erik_Lyna_Helga_e189c54f:
    h "谢谢你！*抽泣*太谢谢你了……我甜蜜的儿子。"

translate schinese hscene24_Erik_Lyna_Helga_156fe50e:
    h "你对这个世界来说太善良了。你总是知道该说什么。"

translate schinese hscene24_Erik_Lyna_Helga_889681df:
    h "而我……我很抱歉摸了你下面。我不该未经你允许就那样做。"

translate schinese hscene24_Erik_Lyna_Helga_bb7936c2:
    e "没关系……你只是吓了我一下。"

translate schinese hscene24_Erik_Lyna_Helga_aa5a38ab:
    hm "{size=-5}天啊，我真希望我能就——"

translate schinese hscene24_Erik_Lyna_Helga_e834257c:
    h "不过你知道吗，宝贝……如果你愿意，你还可以继续摸我。"

translate schinese hscene24_Erik_Lyna_Helga_54897e05:
    h "而且事实上，还有比我的奶子更好的东西。"

translate schinese hscene24_Erik_Lyna_Helga_572b983f:
    h "*打嗝*你想看吗，儿子？"

translate schinese hscene24_Erik_Lyna_Helga_5ca514b4:
    e "什么意思，妈、妈妈？"

translate schinese hscene24_Erik_Lyna_Helga_94e653e7:
    h "{size=-5}{cps=25}那是一个非常特别的地方，{w=0.35}你懂的。"

translate schinese hscene24_Erik_Lyna_Helga_90c46585:
    h "{size=-5}{cps=25}那是……{size=-10}{cps=20}{w=0.5}只有女人能给男人看的东西。"

translate schinese hscene24_Erik_Lyna_Helga_bdedad16:
    em "操，我为什么就是停不下她？！"

translate schinese hscene24_Erik_Lyna_Helga_1b51cb14:
    em "可实际上……我到底想停下她吗？"

translate schinese hscene24_Erik_Lyna_Helga_4ad8b9f9:
    h "来……*打嗝*{size=-5}还是我给你看比较好……*打嗝*"

translate schinese hscene24_Erik_Lyna_Helga_ef477af6:
    em "别告诉我她——"

translate schinese hscene24_Erik_Lyna_Helga_43a174fb:
    h "*打嗝*呃……"

translate schinese hscene24_Erik_Lyna_Helga_f2bfd76c:
    lm "{size=+5}天哪天哪！她把一切都给他看了！"

translate schinese hscene24_Erik_Lyna_Helga_6f21b475:
    l "唔嗯哼！{size=-5}妈妈……埃里克——"

translate schinese hscene24_Erik_Lyna_Helga_8cb0fa89:
    l "我……我要——"

translate schinese hscene25_Erik_Lyna_Helga_af1781aa:
    e "妈妈……？"

translate schinese hscene25_Erik_Lyna_Helga_e9348dd9:
    e "喂！你没事吧？！"

translate schinese hscene25_Erik_Lyna_Helga_296de099:
    em "她还在呼吸，这就好……"

translate schinese hscene25_Erik_Lyna_Helga_fb42ee3e:
    em "所以她只是昏过去了？！真的假的？！"

translate schinese hscene25_Erik_Lyna_Helga_dbd60192:
    em "好吧，妈妈最后还是把整瓶都喝光了……"

translate schinese hscene25_Erik_Lyna_Helga_a85e0b77:
    em "该死！我早该阻止她的！"

translate schinese hscene25_Erik_Lyna_Helga_7eb179ad:
    em "我现在该怎么办？！"

translate schinese hscene25_Erik_Lyna_Helga_2dd60efd:
    em "我好像移不开眼……{size=-5}她的身材太他妈完美了。"

translate schinese hscene25_Erik_Lyna_Helga_dff80480:
    lm "刚才太他妈爽了！我射得好厉害……"

translate schinese hscene25_Erik_Lyna_Helga_ffa6f90d:
    lm "嗯？怎么回事？他们一动不动……"

translate schinese hscene25_Erik_Lyna_Helga_a574cd2d:
    lm "看他，那条内裤都要炸开了！"

translate schinese hscene25_Erik_Lyna_Helga_ce44a04e:
    lm "他就只是……盯着看？而妈妈彻底昏了？！这简直疯了……"

translate schinese hscene25_Erik_Lyna_Helga_4a97af00:
    lm "管他的！我受不了了！我要进去跟他们在一起。"

translate schinese hscene25_Erik_Lyna_Helga_1f0415e0:
    em "该死、该死！我该怎么办……？"

translate schinese hscene25_Erik_Lyna_Helga_a93eab97:
    l "你可真会哄女人……"

translate schinese hscene25_Erik_Lyna_Helga_7fe6eae3:
    e "妹、妹妹？！你怎么会在这里？"

translate schinese hscene25_Erik_Lyna_Helga_eeb8d60d:
    l "你怎么想，笨蛋？"

translate schinese hscene25_Erik_Lyna_Helga_b3691ce7:
    l "看看窗外。"

translate schinese hscene25_Erik_Lyna_Helga_03869a61:
    e "嗯？你到底干了什么？"

translate schinese hscene25_Erik_Lyna_Helga_c7cfcd65:
    e "该死……别告诉我我们——"

translate schinese hscene25_Erik_Lyna_Helga_a4f24c3d:
    l "没错！我在偷看你。"

translate schinese hscene25_Erik_Lyna_Helga_74661bd9:
    e "{size=+5}又来？！真的？"

translate schinese hscene25_Erik_Lyna_Helga_ba1f82fd:
    l "准确地说，我是在自慰！"

translate schinese hscene25_Erik_Lyna_Helga_5b55cce9:
    l "抱歉弄脏了一点，嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_f05c72fb:
    e "所以那边那些是你的呃……体液？！太恶心了！"

translate schinese hscene25_Erik_Lyna_Helga_e0f0deee:
    l "我还能说什么，你刚才表现得太棒了……"

translate schinese hscene25_Erik_Lyna_Helga_97dde21b:
    e "{size=+5}呃！你和你那些该死的计划……"

translate schinese hscene25_Erik_Lyna_Helga_efe9a735:
    e "{size=+5}你已经彻底疯了，莱娜！"

translate schinese hscene25_Erik_Lyna_Helga_13e94d4c:
    l "哦，我疯了……？对妈妈做那些事的又不是我，大哥哥。"

translate schinese hscene25_Erik_Lyna_Helga_46048355:
    l "那就是你说的「按摩」？"

translate schinese hscene25_Erik_Lyna_Helga_04d2d646:
    l "我全都看到了，你知道的吧？"

translate schinese hscene25_Erik_Lyna_Helga_bafc75ec:
    l "而且我得说，那场面真精彩！"

translate schinese hscene25_Erik_Lyna_Helga_b970e88b:
    l "你们刚才在说什么呢？听起来聊得很开心啊……"

translate schinese hscene25_Erik_Lyna_Helga_16033a90:
    e "莱娜，这不是游戏。这是很严重的事！"

translate schinese hscene25_Erik_Lyna_Helga_02847563:
    l "告诉我，她为什么允许你对她做那些恶心的事？"

translate schinese hscene25_Erik_Lyna_Helga_86f69592:
    e "妈妈她……现在不太正常。她喝了很多。"

translate schinese hscene25_Erik_Lyna_Helga_3209e795:
    l "我知道，埃里克。在她跟我们说了那些之后……我想妈妈确实需要那个。"

translate schinese hscene25_Erik_Lyna_Helga_22e7eaf0:
    l "但也许，也许吧……她需要更多。"

translate schinese hscene25_Erik_Lyna_Helga_2ed34084:
    e "不、不……别开始，求你了。我们得走了。"

translate schinese hscene25_Erik_Lyna_Helga_333d293b:
    l "嘘。没事的，哥哥。有这种感觉完全没关系。"

translate schinese hscene25_Erik_Lyna_Helga_32c323b7:
    l "妈妈很美，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_a4f444a3:
    l "而且她需要我们，埃里克。她需要我们的爱。"

translate schinese hscene25_Erik_Lyna_Helga_59351a8b:
    l "你也需要这个，对吧？我从你的眼睛、从你的身体看得出来……"

translate schinese hscene25_Erik_Lyna_Helga_b7804a71:
    l "你知道自己想要这个。"

translate schinese hscene25_Erik_Lyna_Helga_5f1afbfd:
    e "莱娜，不！我知道你在想什么，但我们绝对不能。"

translate schinese hscene25_Erik_Lyna_Helga_1d38c00d:
    l "为什么就错了，嗯？因为她是我们妈妈？"

translate schinese hscene25_Erik_Lyna_Helga_2b0c664d:
    l "我知道你的秘密，老哥。"

translate schinese hscene25_Erik_Lyna_Helga_d0025ad1:
    e "什、什么秘密……？"

translate schinese hscene25_Erik_Lyna_Helga_ca563424:
    l "你{i}喜欢{/i}妈妈，对吧？就像你{i}喜欢{/i}我一样。"

translate schinese hscene25_Erik_Lyna_Helga_01f877e1:
    e "那不是真的！"

translate schinese hscene25_Erik_Lyna_Helga_f88b5fa4:
    l "真的？你也醉了？"

translate schinese hscene25_Erik_Lyna_Helga_9152acf2:
    e "啥？当然没有！"

translate schinese hscene25_Erik_Lyna_Helga_df363fbf:
    l "那给我解释一件事……"

translate schinese hscene25_Erik_Lyna_Helga_9a1640f7:
    l "什么样的儿子会同意那样摸自己脆弱的妈妈？而且你当时明明还很清醒！"

translate schinese hscene25_Erik_Lyna_Helga_1c294d9b:
    l "你真以为我会相信，你摸她的奶子只是为了缓解她的情绪痛苦之类的？"

translate schinese hscene25_Erik_Lyna_Helga_11542c93:
    l "果然。跟我猜的一样。"

translate schinese hscene25_Erik_Lyna_Helga_58f6e154:
    l "最近我看你色眯眯地盯着我们妈妈，次数多到数不清。"

translate schinese hscene25_Erik_Lyna_Helga_cf010736:
    l "你一直在幻想她，对吧……？"

translate schinese hscene25_Erik_Lyna_Helga_3c07612c:
    e "不……我只是——"

translate schinese hscene25_Erik_Lyna_Helga_d05b71da:
    l "听着，一开始我也很嫉妒，你知道的……"

translate schinese hscene25_Erik_Lyna_Helga_acd2a1b3:
    l "但现在，我觉得自己好像开始享受了。"

translate schinese hscene25_Erik_Lyna_Helga_4d9bf917:
    e "你什么……？"

translate schinese hscene25_Erik_Lyna_Helga_e9223d35:
    l "对……看看她，埃里克。看看妈妈的身体。"

translate schinese hscene25_Erik_Lyna_Helga_ed72e9ca:
    l "她是个他妈的绝世美人，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_7ea3a7ee:
    l "天哪天哪！你下面还在发育呢！"

translate schinese hscene25_Erik_Lyna_Helga_f3441b32:
    l "看吧老哥？你就是想要这个。"

translate schinese hscene25_Erik_Lyna_Helga_5ca24b7e:
    l "那可真是够劲爆！这还是我第一次见你这么硬……"

translate schinese hscene25_Erik_Lyna_Helga_5aee51ae:
    l "你就那么喜欢妈妈{i}那样{/i}，嗯？"

translate schinese hscene25_Erik_Lyna_Helga_b007a128:
    e "莱娜，停下！你在说什么？！"

translate schinese hscene25_Erik_Lyna_Helga_a192af6e:
    l "喂、喂，别担心……大哥哥。"

translate schinese hscene25_Erik_Lyna_Helga_4ff0a8a1:
    l "对她有这种感觉也没关系，反正我们已经在自己这个秘密里陷得很深了。"

translate schinese hscene25_Erik_Lyna_Helga_7dea2f2e:
    e "别再说那种话！你疯了吗？！"

translate schinese hscene25_Erik_Lyna_Helga_e77fe9b6:
    l "没有！你疯了吗？在亲手摸过{i}它们{/i}之后，我可不怪你。"

translate schinese hscene25_Erik_Lyna_Helga_f0f0eaa9:
    lm "啊，好可爱……他以为我没看到他！"

translate schinese hscene25_Erik_Lyna_Helga_88d55146:
    lm "我哥哥就是个色迷迷的乱伦变态，跟我一样。"

translate schinese hscene25_Erik_Lyna_Helga_b0bb83ec:
    lm "操，我可真会让自己湿起来！"

translate schinese hscene25_Erik_Lyna_Helga_79ba93a3:
    lm "现在我好想再摸一次它们，可是首先……"

translate schinese hscene25_Erik_Lyna_Helga_70a3df77:
    l "让我来帮你，好吗？让我让你舒服起来。"

translate schinese hscene25_Erik_Lyna_Helga_77fbad83:
    e "{size=-5}我们不该在这里做这个……"

translate schinese hscene25_Erik_Lyna_Helga_43de61c5:
    l "嘘……放松点。"

translate schinese hscene25_Erik_Lyna_Helga_946cd8c4:
    l "哇！好大的帐篷，哈哈！有人去露营了……"

translate schinese hscene25_Erik_Lyna_Helga_ebfa65bf:
    l "妈妈到底在期待什么啊，埃里克？在像你这么年轻的猛男面前那样暴露自己……"

translate schinese hscene25_Erik_Lyna_Helga_fa82a369:
    e "求你别这么说！她……只是想按摩。"

translate schinese hscene25_Erik_Lyna_Helga_c787ced7:
    l "好好好！好吧，反正也无所谓了……"

translate schinese hscene25_Erik_Lyna_Helga_611b347c:
    centered "{font=font_narration}{cps=25}{color=#00bfff}因为现在你妹妹在这里照顾你了。"

translate schinese hscene25_Erik_Lyna_Helga_c21a3a13:
    l "你今晚真是欲火焚身！我连帮你脱都不用。"

translate schinese hscene25_Erik_Lyna_Helga_8862f9c4:
    e "啧……"

translate schinese hscene25_Erik_Lyna_Helga_1e2e4013:
    l "怎么了大哥哥？嘿嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_231e3099:
    e "就……{size=-5}快点做点什么吧……"

translate schinese hscene25_Erik_Lyna_Helga_fcb80658:
    e "{size=+5}呃嗯！"

translate schinese hscene25_Erik_Lyna_Helga_9ef80250:
    e "操，莱娜……！"

translate schinese hscene25_Erik_Lyna_Helga_745a8a63:
    l "看？这样很舒服吧？"

translate schinese hscene25_Erik_Lyna_Helga_76e882ed:
    l "慢慢地、好好地撸着……"

translate schinese hscene25_Erik_Lyna_Helga_90c76d87:
    l "今晚我可不会让你吊着不放的，你知道吧！"

translate schinese hscene25_Erik_Lyna_Helga_86b2f274:
    l "我喜欢奖励我的双胞胎……因为我可以玩你漂亮的小鸡巴。"

translate schinese hscene25_Erik_Lyna_Helga_8e4b6001:
    l "{cps=25}我哥哥的……{w=0.5}大的……{w=0.5}漂亮的……{w=0.5}鸡巴。"

translate schinese hscene25_Erik_Lyna_Helga_d30c6049:
    e "啊啊……！为什么停了？"

translate schinese hscene25_Erik_Lyna_Helga_fd0ef341:
    l "我要你在我给你打飞机的时候看着她。"

translate schinese hscene25_Erik_Lyna_Helga_60e163d1:
    e "什么？！为什么？"

translate schinese hscene25_Erik_Lyna_Helga_019278d8:
    l "要我再重复一遍吗？我说得更清楚一点……"

translate schinese hscene25_Erik_Lyna_Helga_cd482a8e:
    l "{cps=20}看。{w=0.35}着。{w=0.35}妈。"

translate schinese hscene25_Erik_Lyna_Helga_43bf6986:
    l "因为你用那种饥渴的眼神看她的时候，真的很让我兴奋。"

translate schinese hscene25_Erik_Lyna_Helga_6836bd11:
    l "她就像一位沉睡的女神，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_a006af55:
    l "那对奶子，那腹肌，还有那……草丛。"

translate schinese hscene25_Erik_Lyna_Helga_4d407dc5:
    e "{size=-5}对、对……她真是……{size=-10}太完美了。"

translate schinese hscene25_Erik_Lyna_Helga_1bf983f9:
    e "{size=-5}可她也是——"

translate schinese hscene25_Erik_Lyna_Helga_a42855eb:
    l "「她是我们妈妈，莱娜，我们不该这样！」少废话啦……"

translate schinese hscene25_Erik_Lyna_Helga_95f343a0:
    l "可我们他妈还是在这儿，埃里克。"

translate schinese hscene25_Erik_Lyna_Helga_f7e231aa:
    l "就在我们妈妈昏倒在那边的时候，我给你打手枪。"

translate schinese hscene25_Erik_Lyna_Helga_f106b370:
    e "{size=+5}啊啊……妹妹！"

translate schinese hscene25_Erik_Lyna_Helga_474cebcd:
    l "因为这样很爽。而且你想要更多，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_ae656543:
    l "你想再摸她一次。你想感受她的身体贴在你身上，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_95725078:
    e "是的……{size=-5}我想……{size=-10}摸她。"

translate schinese hscene25_Erik_Lyna_Helga_efdb6c39:
    e "{size=+5}不！妹妹，我这是怎么了？！"

translate schinese hscene25_Erik_Lyna_Helga_0ab58cee:
    e "我不是我自己了！我感觉像个怪物……"

translate schinese hscene25_Erik_Lyna_Helga_36f9c655:
    l "喂，冷静点！我还以为你不那么爱操心了。"

translate schinese hscene25_Erik_Lyna_Helga_c2b4040d:
    l "你真以为，如果妈妈不是偷偷想要，她会让你那样摸她吗？"

translate schinese hscene25_Erik_Lyna_Helga_4221f3ab:
    e "我不知道……"

translate schinese hscene25_Erik_Lyna_Helga_15302504:
    e "呃嗯嗯！{size=-5}操……"

translate schinese hscene25_Erik_Lyna_Helga_ec4de492:
    l "只有我们说它错，它才是错的。而现在，对我们所有人来说都感觉那么对。"

translate schinese hscene25_Erik_Lyna_Helga_1220ce8f:
    e "你知道没那么容易的！"

translate schinese hscene25_Erik_Lyna_Helga_3ec4f2bd:
    l "听着，如果你我之间没有那个秘密，我能理解你的犹豫……"

translate schinese hscene25_Erik_Lyna_Helga_c07f1e30:
    l "但我们有，埃里克。你正在和自己的妹妹做坏事，而且我知道你完全享受其中。"

translate schinese hscene25_Erik_Lyna_Helga_10b84914:
    e "{size=-5}我们之间……不一样。"

translate schinese hscene25_Erik_Lyna_Helga_75037be2:
    l "哪里不一样？我亲爱的双胞胎，你还在自欺欺人。"

translate schinese hscene25_Erik_Lyna_Helga_00020de1:
    l "{cps=25}我们都是血亲。{w=0.5}这仍然是……{w=0.35}乱伦。"

translate schinese hscene25_Erik_Lyna_Helga_d667c05c:
    e "不！你休想说服我……"

translate schinese hscene25_Erik_Lyna_Helga_c1cb1e2f:
    l "但她需要我们！她需要我们的爱。"

translate schinese hscene25_Erik_Lyna_Helga_f2596a4c:
    l "而且也许，也许吧……她也需要我们{i}特别{/i}的关注。"

translate schinese hscene25_Erik_Lyna_Helga_0f57a7d6:
    l "{cps=30}如果你多摸她一点点，{w=0.35}会有那么错吗，嗯？"

translate schinese hscene25_Erik_Lyna_Helga_cc11114f:
    l "{cps=30}如果你就在这里、{w=0.5}现在、{w=0.5}当着你变态妹妹的面摸妈妈？"

translate schinese hscene25_Erik_Lyna_Helga_46a784a7:
    e "我不该……{size=-5}她昏着呢……"

translate schinese hscene25_Erik_Lyna_Helga_2a100da8:
    e "喂！怎么了？你要去哪儿？"

translate schinese hscene25_Erik_Lyna_Helga_91bb845f:
    l "我受够你那套胡闹了。"

translate schinese hscene25_Erik_Lyna_Helga_6ffbb843:
    e "等、等等……可是我——"

translate schinese hscene25_Erik_Lyna_Helga_c0c2f86f:
    l "你需要更多鼓励，是这样吗？"

translate schinese hscene25_Erik_Lyna_Helga_85ec7afe:
    e "莱娜，你在干什……？"

translate schinese hscene25_Erik_Lyna_Helga_cee15bbc:
    l "摸起来好软，老哥。好暖……"

translate schinese hscene25_Erik_Lyna_Helga_5bcd408a:
    l "再看这个。看看我们妈妈下面多毛。"

translate schinese hscene25_Erik_Lyna_Helga_7384da98:
    em "她在干什么？！我为什么移不开眼？"

translate schinese hscene25_Erik_Lyna_Helga_ba403e54:
    l "这他妈性感死了，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_f86e8c53:
    l "这么一大片草丛……我他妈爱死了。"

translate schinese hscene25_Erik_Lyna_Helga_b7e4186f:
    l "真正熟女的标志，不是吗？"

translate schinese hscene25_Erik_Lyna_Helga_4b7ef908:
    e "{size=+5}莱娜，够了吧！"

translate schinese hscene25_Erik_Lyna_Helga_0833460e:
    e "妈妈喝醉了昏过去，她没法同意这件事！"

translate schinese hscene25_Erik_Lyna_Helga_bdac4625:
    l "你说得对，可是……"

translate schinese hscene25_Erik_Lyna_Helga_be04fb50:
    l "{size=-5}{cps=25}这也意味着她永远不会知道。"

translate schinese hscene25_Erik_Lyna_Helga_b346ee5c:
    l "我们可以给她需要的东西，却永远不敢说出口。"

translate schinese hscene25_Erik_Lyna_Helga_b9c5c449:
    e "妹妹，求你了……我们不能。不该这样！"

translate schinese hscene25_Erik_Lyna_Helga_90a723c4:
    l "这样摸她，真的会有那么糟吗，嗯？"

translate schinese hscene25_Erik_Lyna_Helga_73c32dc6:
    l "你可以把脸埋进她两腿之间，去闻妈妈那片又大又密的草丛的甜腻气味。"

translate schinese hscene25_Erik_Lyna_Helga_82b994e4:
    l "那么浓密，那么女人味……而且全是天然的。"

translate schinese hscene25_Erik_Lyna_Helga_f35f6446:
    l "又或者你可以用这对又大又美的乳房来取悦自己。"

translate schinese hscene25_Erik_Lyna_Helga_b3b2b63e:
    l "想象一下……把你的鸡巴插进这条紧致、温热、肥厚的甬道里。"

translate schinese hscene25_Erik_Lyna_Helga_3bc8de8a:
    l "随你把还没用过的鸡巴一次又一次插进去，直到你把精液全射在她那对巨乳上。"

translate schinese hscene25_Erik_Lyna_Helga_13e6bce9:
    em "天啊，她的话快把我逼疯了！我受不了了……"

translate schinese hscene25_Erik_Lyna_Helga_9a22a198:
    em "对不起妈妈。"

translate schinese hscene25_Erik_Lyna_Helga_9e043e62:
    l "就是这样老哥。感觉就好。放开吧。"

translate schinese hscene25_Erik_Lyna_Helga_dbcf77bc:
    l "让我来引导你。让我给你看看我们一起能有多好玩。"

translate schinese hscene25_Erik_Lyna_Helga_8745c668:
    e "{size=-5}我不能相信你居然让我做这个……"

translate schinese hscene25_Erik_Lyna_Helga_06270dc4:
    l "我有吗？你可以直接跑掉，像那天在山洞对我做的那样……"

translate schinese hscene25_Erik_Lyna_Helga_d392d942:
    e "{size=-5}对、对不起，我——"

translate schinese hscene25_Erik_Lyna_Helga_4548ffb8:
    l "来！摸妈妈。感受她的温度……"

translate schinese hscene25_Erik_Lyna_Helga_a62667b3:
    l "对，就是这样！现在把手再往上移。"

translate schinese hscene25_Erik_Lyna_Helga_8236f872:
    l "抓一把她的草丛。感受她有多他妈毛。"

translate schinese hscene25_Erik_Lyna_Helga_bd35f451:
    l "摸起来他妈这么软，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_8705ca9b:
    e "嗯，{size=-5}非常……"

translate schinese hscene25_Erik_Lyna_Helga_192b2d6f:
    l "天啊，那太色了！看着你的手放在这些阴毛上……"

translate schinese hscene25_Erik_Lyna_Helga_706e93a2:
    l "再看看那儿……那是一颗肥大的阴蒂！"

translate schinese hscene25_Erik_Lyna_Helga_8571df8f:
    l "我也是第一次这么近地看到它。"

translate schinese hscene25_Erik_Lyna_Helga_02daccb6:
    l "自从我们一起洗澡之后，我就一直等不及要做这个了……"

translate schinese hscene25_Erik_Lyna_Helga_db4c75b5:
    e "嗯？所以你之前不是在开玩笑？！"

translate schinese hscene25_Erik_Lyna_Helga_9299eadd:
    l "不是！抱歉老哥，可前两天我和她真的洗了。"

translate schinese hscene25_Erik_Lyna_Helga_6b6bb078:
    l "我先看到了她裸体！好久没在什么上面赢过你了……嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_84b2a339:
    em "该死，莱娜是不是对妈妈做了奇怪的事？所以她才这么——"

translate schinese hscene25_Erik_Lyna_Helga_9c56f678:
    l "该死，这太他妈色了……"

translate schinese hscene25_Erik_Lyna_Helga_0bb51e4f:
    l "她的身体跟我的这么不同，那么成熟……那么丰腴。"

translate schinese hscene25_Erik_Lyna_Helga_6602dcd3:
    l "还有那股浓烈的味道……操！"

translate schinese hscene25_Erik_Lyna_Helga_33be3941:
    l "而这里就是我们的第一个小窝……"

translate schinese hscene25_Erik_Lyna_Helga_d7e74451:
    e "什么？呃，莱娜……认真的？"

translate schinese hscene25_Erik_Lyna_Helga_f6d2c937:
    l "可这是真的！婴儿不就是这么来的，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_0b5ce5f9:
    l "我们俩都是从这个小小洞里出来的……"

translate schinese hscene25_Erik_Lyna_Helga_56f60eb3:
    l "你敢相信吗？！简直太疯狂了！"

translate schinese hscene25_Erik_Lyna_Helga_77e7e65a:
    lm "不知道生双胞胎是什么感觉呢，嗯……"

translate schinese hscene25_Erik_Lyna_Helga_fa3a0694:
    h "{size=-5}呃……" with hpunch

translate schinese hscene25_Erik_Lyna_Helga_6c3fe844:
    e "喂，别弄了！你会把她弄醒的！"

translate schinese hscene25_Erik_Lyna_Helga_1d8bc4f9:
    l "可这不是很刺激吗？不是同时又错又对吗？"

translate schinese hscene25_Erik_Lyna_Helga_35737068:
    e "莱娜，这太过分了。我做不到……"

translate schinese hscene25_Erik_Lyna_Helga_ca016697:
    l "你可以！因为你想……{size=-5}而且你需要。"

translate schinese hscene25_Erik_Lyna_Helga_6b03fc6c:
    l "你今晚不想射吗？「小」埃里克一定很难受……"

translate schinese hscene25_Erik_Lyna_Helga_a219b68e:
    l "而我知道该怎么帮你。"

translate schinese hscene25_Erik_Lyna_Helga_73aaebd6:
    l "跪到妈妈面前。我给你准备了东西……"

translate schinese hscene25_Erik_Lyna_Helga_12be8bd4:
    e "我……{size=-5}我不确定这是个好主意……"

translate schinese hscene25_Erik_Lyna_Helga_1738f3d3:
    l "拜托，你怕什么？她醉得根本不在乎！"

translate schinese hscene25_Erik_Lyna_Helga_d6abb29a:
    l "看？我给你弄了个特别的洞。我敢说里面超级软……"

translate schinese hscene25_Erik_Lyna_Helga_925e0bce:
    l "{cps=20}所以来操我们吧……{w=0.35}操我的小手，{w=0.5}哥哥。"

translate schinese hscene25_Erik_Lyna_Helga_28c11259:
    e "{size=-5}这感觉很不对，莱娜……"

translate schinese hscene25_Erik_Lyna_Helga_cc3f50a3:
    l "可你连犹豫都没有！"

translate schinese hscene25_Erik_Lyna_Helga_bf3d21c8:
    l "这不对吗？你看，既然你已经在跟我做那种事了……"

translate schinese hscene25_Erik_Lyna_Helga_57747217:
    l "既然我们已经一起越过这么多界线了……"

translate schinese hscene25_Erik_Lyna_Helga_44c11e5a:
    l "既然妈妈那么爱你。她简直愿意为她「小宝贝儿子」做任何事。"

translate schinese hscene25_Erik_Lyna_Helga_ef7f3456:
    e "{size=+5}啊啊！操……" with vpunch

translate schinese hscene25_Erik_Lyna_Helga_73c4761d:
    l "你很喜欢我的脏话，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_ea935753:
    e "对、对！但你什么时候学会说这种话的……？！"

translate schinese hscene25_Erik_Lyna_Helga_6cb06fc3:
    l "嗯，也许哪天得给你看看我的搜索记录。"

translate schinese hscene25_Erik_Lyna_Helga_e208fe81:
    l "看这对巨乳，老哥。我希望我的以后也能长得一样大……"

translate schinese hscene25_Erik_Lyna_Helga_9547b442:
    l "很美对吧？我们很久以前还从里面喝过奶……"

translate schinese hscene25_Erik_Lyna_Helga_4ca2020c:
    l "就像她以前告诉我们的。一边一个奶子，把温热的奶全吸出来……"

translate schinese hscene25_Erik_Lyna_Helga_9ef7f9a1:
    l "快二十年过去了，我们又在这里使用妈妈的身体。"

translate schinese hscene25_Erik_Lyna_Helga_481c4be7:
    e "莱、莱娜……！你别、别……"

translate schinese hscene25_Erik_Lyna_Helga_ce8e5cec:
    l "别什么？你最好继续插，哥哥，不然……"

translate schinese hscene25_Erik_Lyna_Helga_17475180:
    l "我就用力吸这两个肥乳头，吸到妈妈醒来，然后发现她儿子变成了多么变态的一个人。"

translate schinese hscene25_Erik_Lyna_Helga_57490834:
    l "就是这样！进，出……继续。"

translate schinese hscene25_Erik_Lyna_Helga_57cfc6e8:
    l "还有小心点！尽量别把蛋拍在她的阴部上……"

translate schinese hscene25_Erik_Lyna_Helga_e4cf4a09:
    l "那样就非常他妈调皮了，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_7879397c:
    e "该死、该死、该死！我快到了。" with hpunch

translate schinese hscene25_Erik_Lyna_Helga_b0062777:
    l "哦？！你这么急着结束！{size=-5}我的小乱伦变态……"

translate schinese hscene25_Erik_Lyna_Helga_9f732671:
    l "要是我没进来，你会对昏迷的妈妈做什么？"

translate schinese hscene25_Erik_Lyna_Helga_34ac066f:
    e "什、什么都不会！{size=-5}我绝不敢……"

translate schinese hscene25_Erik_Lyna_Helga_6e5786ee:
    l "骗子！快点，哥哥。像你对我做的那样，把她标记成你的。"

translate schinese hscene25_Erik_Lyna_Helga_ed205bbf:
    e "啊啊，莱娜……！"

translate schinese hscene25_Erik_Lyna_Helga_0b9d9fd8:
    l "来吧，射！为了我，为了{i}妈咪{/i}。"

translate schinese hscene25_Erik_Lyna_Helga_ea0507be:
    e "妹妹！我要射了。我要射在她身上。射在妈咪身上……！"

translate schinese hscene25_Erik_Lyna_Helga_32e3116e:
    l "他妈的太好了！放出来！释放出来，感受快感！"

translate schinese hscene25_Erik_Lyna_Helga_0c0d0e72:
    l "对！还要更多！继续用这个温暖柔软毛茸茸的小洞。"

translate schinese hscene25_Erik_Lyna_Helga_ed3e2fb8:
    l "没错！把所有精液都射出来……"

translate schinese hscene25_Erik_Lyna_Helga_40aab793:
    lm "他在干什么？！他还有更多吗？！"

translate schinese hscene25_Erik_Lyna_Helga_3492a079:
    lm "他插起来简直像头野兽！嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_52462ff3:
    em "对不起妈妈……但这感觉太他妈爽了！" with vpunch

translate schinese hscene25_Erik_Lyna_Helga_b81ba251:
    lm "哦，当然！他紧绷着呢！"

translate schinese hscene25_Erik_Lyna_Helga_e547ff29:
    lm "我敢说他已经幻想过妈妈无数次了，可能在这个夏天之前就……"

translate schinese hscene25_Erik_Lyna_Helga_acc71a3a:
    e "{size=+5}呃呜呜呜……啊啊啊！"

translate schinese hscene25_Erik_Lyna_Helga_5ef7ff4c:
    lm "很好！用你的肮脏种子把她涂满，我完美的妈咪乖儿子……"

translate schinese hscene25_Erik_Lyna_Helga_26ce823e:
    e "呃……呃……该死……"

translate schinese hscene25_Erik_Lyna_Helga_8f92f155:
    lm "再来一次！我知道你还有。"

translate schinese hscene25_Erik_Lyna_Helga_c16593e4:
    lm "我知道你想把全部肮脏的奶水都给妈妈……"

translate schinese hscene25_Erik_Lyna_Helga_d7a20762:
    lm "{size=+5}来吧！射、射、射！"

translate schinese hscene25_Erik_Lyna_Helga_34fd7625:
    lm "对！射满她又大又美的熟女草丛！"

translate schinese hscene25_Erik_Lyna_Helga_acf6e0c7:
    e "啊啊……*喘气*呼……"

translate schinese hscene25_Erik_Lyna_Helga_8c9cb595:
    l "我勒个去老哥……"

translate schinese hscene25_Erik_Lyna_Helga_e82648f2:
    l "{size=+5}那是我见过最火辣的东西。"

translate schinese hscene25_Erik_Lyna_Helga_a574f14f:
    l "而且看，她还昏着。妈妈一点都不知道……"

translate schinese hscene25_Erik_Lyna_Helga_41d93b7d:
    l "{cps=30}这是我们的秘密。{w=0.5}我们肮脏的小秘密。"

translate schinese hscene25_Erik_Lyna_Helga_17a9479a:
    l "操，这浆液真浓……"

translate schinese hscene25_Erik_Lyna_Helga_ab5db225:
    l "你真的射了妈咪一身，嗯？还是射在她完美的草丛上。"

translate schinese hscene25_Erik_Lyna_Helga_9c67a5b0:
    l "你刚刚让她看到了你有多爱她、多渴望她。"

translate schinese hscene25_Erik_Lyna_Helga_435dd011:
    l "嗯！你的精液味道真好，大哥哥。"

translate schinese hscene25_Erik_Lyna_Helga_9e78b753:
    l "来，看看她。看看你弄出的这堆淫荡痕迹。"

translate schinese hscene25_Erik_Lyna_Helga_166d9671:
    e "天啊……{size=-5}这……{size=-10}这是——"

translate schinese hscene25_Erik_Lyna_Helga_8bc71f4b:
    e "{size=+5}我们刚才都做了什么，莱娜？！"

translate schinese hscene25_Erik_Lyna_Helga_1f1e5969:
    l "没关系老哥。爱她、想要她都没关系。"

translate schinese hscene25_Erik_Lyna_Helga_b675c8a3:
    l "她是我们亲妈，没错……但她也是个女人。"

translate schinese hscene25_Erik_Lyna_Helga_f414be6c:
    centered "{font=font_narration}{cps=25}{color=#00bfff}一个美丽而诱人的成熟女人。"

translate schinese hscene25_Erik_Lyna_Helga_7ec68b35:
    lm "晚安妈妈。做个好梦。"

translate schinese hscene25_Erik_Lyna_Helga_abe65c48:
    l "喂、喂……现在别慌，求你了。"

translate schinese hscene25_Erik_Lyna_Helga_9b69d915:
    l "你做得太好了，老哥。好得难以置信。可还没完。"

translate schinese hscene25_Erik_Lyna_Helga_75f6af25:
    e "什么？！不莱娜，这已经太过分了！{size=-5}我们不该再拿妈妈冒险……"

translate schinese hscene25_Erik_Lyna_Helga_05fc545e:
    l "我也同意！我们最好先让她休息。"

translate schinese hscene25_Erik_Lyna_Helga_aa1e6a5b:
    l "但跟我……？你想怎么疯都行。"

translate schinese hscene25_Erik_Lyna_Helga_44812433:
    l "来吧，埃里克。摸我。摸一个真女人的小穴。"

translate schinese hscene25_Erik_Lyna_Helga_459bd77a:
    l "感受我为你有多饥渴。感受这一切让我湿成什么样。"

translate schinese hscene25_Erik_Lyna_Helga_64072a15:
    l "别害羞……你知道自己想要。"

translate schinese hscene25_Erik_Lyna_Helga_df186e36:
    l "她的可能是禁忌，但你运气好，拿到的是我的，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_6f413912:
    l "我觉得是时候也给你的双胞胎一点「奖励」了，嗯？"

translate schinese hscene25_Erik_Lyna_Helga_fadc736b:
    l "所以摸我吧，哥哥。摸我的处女穴。"

translate schinese hscene25_Erik_Lyna_Helga_cfb14368:
    em "该死，这个夜晚越来越疯狂了！"

translate schinese hscene25_Erik_Lyna_Helga_e691032b:
    em "可我停不下来……我抵抗不了我的妹妹！"

translate schinese hscene25_Erik_Lyna_Helga_75f359b4:
    e "该死……你已经这么湿了。"

translate schinese hscene25_Erik_Lyna_Helga_6ab22ec3:
    l "能怪我吗？我们今晚太他妈调皮了……"

translate schinese hscene25_Erik_Lyna_Helga_b0942985:
    e "我该……？"

translate schinese hscene25_Erik_Lyna_Helga_288109b9:
    l "是的，埃里克。它全是你的……"

translate schinese hscene25_Erik_Lyna_Helga_689397fc:
    l "现在像你摸我们亲妈那样摸我。感受我有多需要你。"

translate schinese hscene25_Erik_Lyna_Helga_5d221cd8:
    l "对！干得好……"

translate schinese hscene25_Erik_Lyna_Helga_8920a757:
    l "现在把一根手指滑进去。感受我里面有多温暖、多紧……"

translate schinese hscene25_Erik_Lyna_Helga_f56c6663:
    l "但小心点，好吗？别太用力，不然会弄坏我的……{size=-5}你懂的。"

translate schinese hscene25_Erik_Lyna_Helga_958d6b1e:
    l "呃啊啊……！就是这样！" with hpunch

translate schinese hscene25_Erik_Lyna_Helga_450ee454:
    l "可、可我的小洞在下面一点，老哥……"

translate schinese hscene25_Erik_Lyna_Helga_5661f316:
    e "{size=-5}我知道……"

translate schinese hscene25_Erik_Lyna_Helga_c30ec49e:
    l "{size=+5}啊啊！操！" with vpunch

translate schinese hscene25_Erik_Lyna_Helga_a0ce095c:
    em "天啊，好紧！简直像在吸着它……"

translate schinese hscene25_Erik_Lyna_Helga_281764c1:
    l "来吧大哥哥，用手指操我！"

translate schinese hscene25_Erik_Lyna_Helga_617f56b0:
    n "埃里克的手指带着新生的自信，在双胞胎妹妹的湿润中进出。"

translate schinese hscene25_Erik_Lyna_Helga_594dadcb:
    l "{size=+5}耶！你让我感觉太他妈爽了……！" with hpunch

translate schinese hscene25_Erik_Lyna_Helga_98427989:
    n "他能感觉到她全部的温度包裹着自己，她的紧致，她的渴望……"

translate schinese hscene25_Erik_Lyna_Helga_0c714c71:
    l "你想让我感觉更爽，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_17883071:
    l "你想让我狠狠射出来？！"

translate schinese hscene25_Erik_Lyna_Helga_849aed83:
    e "我确实想，莱娜。你也该享受一下。"

translate schinese hscene25_Erik_Lyna_Helga_5fcdc407:
    l "当然！{size=-5}我一直给你太多关注了……"

translate schinese hscene25_Erik_Lyna_Helga_e1e54d31:
    l "{size=+5}所以来吧，把嘴凑近点！"

translate schinese hscene25_Erik_Lyna_Helga_730e4b02:
    e "你想让我——"

translate schinese hscene25_Erik_Lyna_Helga_9a2d7378:
    l "是的哥哥。正是你在想的……"

translate schinese hscene25_Erik_Lyna_Helga_8756c238:
    l "我想让你尝我。我想让你舔我的小穴。"

translate schinese hscene25_Erik_Lyna_Helga_84dd2821:
    e "可我从没做过那种事……"

translate schinese hscene25_Erik_Lyna_Helga_d2e7f3c9:
    l "凡事总得有第一次，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_00311737:
    e "我……{size=-5}大概吧……"

translate schinese hscene25_Erik_Lyna_Helga_b04bec95:
    l "你还真是「大概」？哈哈哈！来吧……"

translate schinese hscene25_Erik_Lyna_Helga_7f15dd46:
    l "我们就是一对毫无经验的愚蠢处女废物……"

translate schinese hscene25_Erik_Lyna_Helga_8e1a0beb:
    l "所以你真以为我在乎你做得不到位之类的吗？"

translate schinese hscene25_Erik_Lyna_Helga_195fda52:
    e "那个，我以为——"

translate schinese hscene25_Erik_Lyna_Helga_8f87f177:
    l "我他妈不在乎，埃里克。我只想感受你的舌头在我小穴上。"

translate schinese hscene25_Erik_Lyna_Helga_1942bc3b:
    l "因为我要你让你妹妹在你嘴里高潮，明白吗？"

translate schinese hscene25_Erik_Lyna_Helga_bfbab9e6:
    e "小……？你为什么这么说？你知道我们一样大——"

translate schinese hscene25_Erik_Lyna_Helga_0aa44ab5:
    l "嘘，埃里克。别想太多。按我说的做。"

translate schinese hscene25_Erik_Lyna_Helga_6fe71580:
    l "现在舔我。尝尝你那个淫荡的小妹妹。一直舔到我射为止。"

translate schinese hscene25_Erik_Lyna_Helga_8e064b6b:
    n "她尝起来像罪恶又像甜美，这种致命组合让没经验的男孩愈发渴望。"

translate schinese hscene25_Erik_Lyna_Helga_83e16816:
    n "他舌尖每一次掠过她的肉缝，都是对他们共同欲望的坦白，是对他们在甘愿拥抱的禁忌的承认。"

translate schinese hscene25_Erik_Lyna_Helga_8d5f3fef:
    lm "操，那真是我亲哥哥！我的双胞胎哥哥在舔我！"

translate schinese hscene25_Erik_Lyna_Helga_5e392fdc:
    lm "就是那个总是在女士面前脸红的孩子……"

translate schinese hscene25_Erik_Lyna_Helga_8d07d702:
    lm "就是那个总是照顾我、帮我收拾愚蠢错误的人……"

translate schinese hscene25_Erik_Lyna_Helga_1c545aad:
    lm "也是那个和我共享同一个子宫整整九个月的人！"

translate schinese hscene25_Erik_Lyna_Helga_2499beb2:
    l "{size=+5}操！那太他妈烫了……！"

translate schinese hscene25_Erik_Lyna_Helga_a9b43ead:
    lm "{size=+5}他真他妈可爱，天啊！"

translate schinese hscene25_Erik_Lyna_Helga_6136c37c:
    lm "{size=+5}我爱他！我完全迷上他了！"

translate schinese hscene25_Erik_Lyna_Helga_ada53f0c:
    l "{size=+5}老、老哥……我觉得我要射了！"

translate schinese hscene25_Erik_Lyna_Helga_a380e9c1:
    l "{size=+10}你要让你可爱的小妹妹射了……！" with vpunch

translate schinese hscene25_Erik_Lyna_Helga_228fc494:
    l "{size=+10}操！又来了……！"

translate schinese hscene25_Erik_Lyna_Helga_cf47a70d:
    em "该死，她叫得太大了！"

translate schinese hscene25_Erik_Lyna_Helga_92d4508c:
    l "{size=-10}嗯啊啊啊嗯嗯嗯呃呃呃！"

translate schinese hscene25_Erik_Lyna_Helga_3614a6ed:
    e "妹妹？！你没事吧？"

translate schinese hscene25_Erik_Lyna_Helga_c0cf2c7b:
    e "天啊，我弄疼你了吗？！"

translate schinese hscene25_Erik_Lyna_Helga_69f8a059:
    l "哈哈哈，埃里克！你的脸——"

translate schinese hscene25_Erik_Lyna_Helga_8af01e94:
    l "天啊，对不起！我射得有点太猛了！"

translate schinese hscene25_Erik_Lyna_Helga_2474eb1d:
    e "没关系，你看起来真的很享受……"

translate schinese hscene25_Erik_Lyna_Helga_b29cdc50:
    l "对！那太棒了！你太棒了！"

translate schinese hscene25_Erik_Lyna_Helga_4d5a6f97:
    l "我当时好想喊你的名字。"

translate schinese hscene25_Erik_Lyna_Helga_3376651e:
    e "那你知道我为什么有点粗暴了。抱歉……"

translate schinese hscene25_Erik_Lyna_Helga_0e028d67:
    l "没关系！你总是罩着你小妹妹，嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_bef8f3f5:
    e "你现在为什么老这么叫自己？我们是双胞胎……"

translate schinese hscene25_Erik_Lyna_Helga_13b909eb:
    l "又来了？哦埃里克，老这么严肃。"

translate schinese hscene25_Erik_Lyna_Helga_a089534b:
    l "这只是个简单的幻想而已！"

translate schinese hscene25_Erik_Lyna_Helga_a4c0ebaa:
    l "就是点老派角色扮演。这会让一切更火辣，不是吗？"

translate schinese hscene25_Erik_Lyna_Helga_95c2cd92:
    e "具体怎么说……？"

translate schinese hscene25_Erik_Lyna_Helga_3b35036f:
    l "{size=-5}这个设定让我湿死了，因为……"

translate schinese hscene25_Erik_Lyna_Helga_794a705c:
    l "{size=-5}我把你想象成哥哥，高大强壮……"

translate schinese hscene25_Erik_Lyna_Helga_aea135aa:
    l "{size=-5}照顾他年纪小很多的妹妹……"

translate schinese hscene25_Erik_Lyna_Helga_5476bda8:
    l "而且还非常可爱、超级天真！"

translate schinese hscene25_Erik_Lyna_Helga_01853fc4:
    e "你？「天真？」哈！"

translate schinese hscene25_Erik_Lyna_Helga_a0ace760:
    l "快点嘛！嘿嘿！你要告诉我，让小妹妹舒服、让我高潮……你不享受吗？"

translate schinese hscene25_Erik_Lyna_Helga_90c94477:
    e "嗯。我是说，好像是说得通。我一直在照顾你。"

translate schinese hscene25_Erik_Lyna_Helga_93b8d82b:
    l "{size=-5}而且现在比任何时候都好……"

translate schinese hscene25_Erik_Lyna_Helga_77ba2927:
    e "你希望我那么叫你吗？当我们……你懂的。"

translate schinese hscene25_Erik_Lyna_Helga_a3e418e7:
    l "当然！我是说……如果你想的话。嘿嘿~"

translate schinese hscene25_Erik_Lyna_Helga_10b65dd5:
    e "该死，莱娜……你太疯了！"

translate schinese hscene25_Erik_Lyna_Helga_28adde33:
    e "但我喜欢。我喜欢我可爱的……{size=-5}小妹妹。"

translate schinese hscene25_Erik_Lyna_Helga_6b651f38:
    l "嘻嘻~！好痒！"

translate schinese hscene25_Erik_Lyna_Helga_8cc58f54:
    e "而且我想让你舒服。一直都。"

translate schinese hscene25_Erik_Lyna_Helga_3e892d7c:
    l "你也确实做到了，老哥。你让我感觉太爽了……"

translate schinese hscene25_Erik_Lyna_Helga_e1759962:
    e "等等！该死，我差点忘了！妈妈怎么办？我们——"

translate schinese hscene25_Erik_Lyna_Helga_6b78c561:
    l "我知道！但求你了，我们能保持这样一会儿吗？"

translate schinese hscene25_Erik_Lyna_Helga_5accddc0:
    l "因为我喜欢我们赤裸的身体贴在一起的感觉。"

translate schinese hscene25_Erik_Lyna_Helga_f66c8cfc:
    e "对、对。我也挺喜欢……"

translate schinese hscene25_Erik_Lyna_Helga_89f0cded:
    l "我真的不想放开你……"

translate schinese hscene25_Erik_Lyna_Helga_5077b484:
    l "但我们不能让妈妈起疑，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_165af337:
    e "对，我们不能……"

translate schinese hscene25_Erik_Lyna_Helga_0166f8c5:
    l "那就来吧。我们把房间收拾干净，还有你留下的{i}小{/i}痕迹。"

translate schinese hscene25_Erik_Lyna_Helga_0b900e19:
    e "折腾了这么久居然没吵醒她，真是奇迹……"

translate schinese hscene25_Erik_Lyna_Helga_a913527a:
    l "也许我们得多灌她喝酒！"

translate schinese hscene25_Erik_Lyna_Helga_eaa50929:
    e "认真的？！莱娜……"

translate schinese hscene25_Erik_Lyna_Helga_159a0cd0:
    l "哈哈哈！我开玩笑的，老哥，天哪。"

translate schinese hscene25_Erik_Lyna_Helga_90527855:
    e "不好笑。"

translate schinese hscene25_Erik_Lyna_Helga_2128cb45:
    l "呸，总之！你现在该去跟她睡了，本来就该这样。"

translate schinese hscene25_Erik_Lyna_Helga_9af0e512:
    e "妹妹，你觉得她会记得……我对她做的事吗？"

translate schinese hscene25_Erik_Lyna_Helga_d9871257:
    l "你问我？我到现在都不知道那是怎么发生的！"

translate schinese hscene25_Erik_Lyna_Helga_6e1374b6:
    e "是……她自己坚持的。"

translate schinese hscene25_Erik_Lyna_Helga_8bca933c:
    l "所以真的是妈妈主动叫你摸她的奶子？"

translate schinese hscene25_Erik_Lyna_Helga_011b3ed6:
    l "我是说，那酒确实挺烈……哇！"

translate schinese hscene25_Erik_Lyna_Helga_ad8a7c7e:
    e "啧。她要真记得了，我该怎么办？"

translate schinese hscene25_Erik_Lyna_Helga_02c62304:
    l "嗯，这个问题应该是……你到底想做什么？"

translate schinese hscene25_Erik_Lyna_Helga_50815c75:
    e "嗯？我不明白。"

translate schinese hscene25_Erik_Lyna_Helga_d21bf56e:
    l "你很想拥有她，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_21ce7b1b:
    e "不、不！什么？！"

translate schinese hscene25_Erik_Lyna_Helga_47ea2c6a:
    l "看！兄弟，你又硬成石头了！"

translate schinese hscene25_Erik_Lyna_Helga_c8feedde:
    l "你停不下来盯着她的身体看，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_3d187d3b:
    l "听着，妈妈喝了很多，所以她可能不太记得了。"

translate schinese hscene25_Erik_Lyna_Helga_9507a94b:
    l "但如果她记得……也别担心，我有个主意。"

translate schinese hscene25_Erik_Lyna_Helga_2a24760c:
    e "又是你的主意？{size=-5}我一点都不想知道。"

translate schinese hscene25_Erik_Lyna_Helga_67db1ae4:
    l "嘿嘿嘿……"

translate schinese hscene25_Erik_Lyna_Helga_dac41d84:
    l "不过总之，那是以后的问题！"

translate schinese hscene25_Erik_Lyna_Helga_0af1e136:
    l "我觉得我们现在有更大的{i}问题{/i}，对吧？"

translate schinese hscene25_Erik_Lyna_Helga_37e531df:
    l "你现在这样肯定没法跟妈妈睡……"

translate schinese hscene25_Erik_Lyna_Helga_a17c7cea:
    centered "{font=font_narration}{size=+15}{cps=20}{color=#69d9fe}( ~第二轮时间到了~ )"

translate schinese story43_Erik_Lyna_7a5866dd:
    h "{size=-5}嗯？什……？"

translate schinese story43_Erik_Lyna_ccd25255:
    centered "{font=font_narration}{size=+10}{cps=20}过了一段时间……"

translate schinese story43_Erik_Lyna_7e4ff950:
    l "埃里克，埃里克，埃里——克！"

translate schinese story43_Erik_Lyna_b4a8b871:
    l "快起来，快醒醒！"

translate schinese story43_Erik_Lyna_aecb74ea:
    e "呃……也跟你道早安，姐。"

translate schinese story43_Erik_Lyna_15c8d508:
    e "怎么了？你看起来很难过。"

translate schinese story43_Erik_Lyna_881c3ce1:
    l "你看见妈了吗？我找不到她……"

translate schinese story43_Erik_Lyna_6549633b:
    e "我……没有。你刚把我叫醒。"

translate schinese story43_Erik_Lyna_72145bd1:
    l "她不见了！车也不见了！"

translate schinese story43_Erik_Lyna_b39579d9:
    l "看，我还给她发了消息。"

translate schinese story43_Erik_Lyna_e24ae799:
    nvl_narrator "赫尔加 —— 2024年7月8日{nw}"

translate schinese story43_Erik_Lyna_294011b1:
    lmc_nvl "妈你在哪？？我在哪儿都找不到你！{nw}"

translate schinese story43_Erik_Lyna_f8a3d272:
    lmc_nvl "快回我们消息！"

translate schinese story43_Erik_Lyna_079e7784:
    l "她看了却没回……"

translate schinese story43_Erik_Lyna_f3f3ff84:
    e "可能她去了什么地方开车。你打过电话了吗？"

translate schinese story43_Erik_Lyna_a31b4c1b:
    l "对哦，完全忘了……"

translate schinese story43_Erik_Lyna_9e13389e:
    l "妈？！终于回了！你在哪？！我好担心！"

translate schinese story43_Erik_Lyna_f09eb7e1:
    l "我在别墅里找了一个小时了！"

translate schinese story43_Erik_Lyna_a8e02538:
    h "{size=-5}你好宝贝，抱歉久等。"

translate schinese story43_Erik_Lyna_5958588f:
    h "{size=-5}我只是出去透透气，在海边散了散步。"

translate schinese story43_Erik_Lyna_6a230c7e:
    l "嗯？开车出去的？"

translate schinese story43_Erik_Lyna_a08fa32b:
    h "{size=-5}对，我……呃……晚点就回来。"

translate schinese story43_Erik_Lyna_3e2cc95f:
    l "什么时候？"

translate schinese story43_Erik_Lyna_4623d805:
    h "{size=-5}大概晚上吧。我会带晚饭回来。"

translate schinese story43_Erik_Lyna_847654ea:
    l "你、你一个人一整天要干什么？"

translate schinese story43_Erik_Lyna_4f57c0b6:
    h "{size=-5}我也有些事要办。别担心，好吗？"

translate schinese story43_Erik_Lyna_7b97e8a3:
    h "{size=-5}拜托告诉你哥哥。再见。"

translate schinese story43_Erik_Lyna_261b672b:
    lm "什么？她就这样……？"

translate schinese story43_Erik_Lyna_815e3dbe:
    l "喂，别闹了！我不敢相信你变得这么不安分……"

translate schinese story43_Erik_Lyna_9b607b27:
    e "抱歉姐。你穿那身太好看了。"

translate schinese story43_Erik_Lyna_2570442d:
    e "所以？她说什么了？"

translate schinese story43_Erik_Lyna_831df65f:
    l "她就把我晾在那儿！你敢信吗？"

translate schinese story43_Erik_Lyna_0cc6ba3b:
    e "她至少告诉你去哪儿了吗？"

translate schinese story43_Erik_Lyna_62f45df5:
    l "完全没说。妈就说今晚会回来……"

translate schinese story43_Erik_Lyna_afb05df8:
    l "天哪，她听起来好冷淡！"

translate schinese story43_Erik_Lyna_6d56c5fe:
    em "妈要消失一整天？千万别是——"

translate schinese story43_Erik_Lyna_3b05c82e:
    em "不。我有种很不好的预感……"

translate schinese story43_Erik_Lyna_737dc4b0:
    e "莉妮，你觉得她是不是……？"

translate schinese story43_Erik_Lyna_caf8141b:
    l "对！她肯定想起了什么。"

translate schinese story43_Erik_Lyna_4aeab9a4:
    e "是关于我的，还是更糟……关于我们对她做的事？！"

translate schinese story43_Erik_Lyna_f94a2906:
    l "不可能，她不可能知道后面那件事。她当时完全不省人事，埃里克。"

translate schinese story43_Erik_Lyna_5c373a31:
    e "那妈为什么急着走？"

translate schinese story43_Erik_Lyna_8058ae08:
    e "靠！她现在是想躲着我吗？！"

translate schinese story43_Erik_Lyna_f8a8f5e3:
    e "我们搞砸了，姐！不……是我搞砸的！"

translate schinese story43_Erik_Lyna_d97ade13:
    l "别慌！她可能只是需要一个人待会儿。"

translate schinese story43_Erik_Lyna_9c68f0c9:
    e "不！全完了……靠！"

translate schinese story43_Erik_Lyna_e2e1996f:
    l "喂！说了别慌。还记得我昨晚跟你说的吗？"

translate schinese story43_Erik_Lyna_250373d1:
    l "我有个以防妈没忘的对策。"

translate schinese story43_Erik_Lyna_a692e7d7:
    l "想想看，这可是个难得的机会！"

translate schinese story43_Erik_Lyna_7d1414c3:
    l "妈想起了一些事，她现在明显既困惑又脆弱。"

translate schinese story43_Erik_Lyna_564f5a6e:
    l "{size=-5}而我们可以利用这一点……"

translate schinese story43_Erik_Lyna_21c12b88:
    e "莱娜？！不行！我们昨天做的事已经太过分了！"

translate schinese story43_Erik_Lyna_8de978bd:
    e "那都差点弄成谋、谋……"

translate schinese story43_Erik_Lyna_d7e28708:
    l "差点弄成什么？说啊。"

translate schinese story43_Erik_Lyna_40a783c8:
    e "没、没什么……"

translate schinese story43_Erik_Lyna_8ca0d978:
    e "可你说的「利用」到底是什么意思？！"

translate schinese story43_Erik_Lyna_5b457ae2:
    e "我一点都不喜欢那个说法……"

translate schinese story43_Erik_Lyna_c9c94b1b:
    l "放轻松哥！不是那种「利用」……不是剥削的意思。我是说趁她想起昨晚的事把握机会。"

translate schinese story43_Erik_Lyna_378b620d:
    l "因为她现在需要有人安慰，你懂吧？需要有人带她走过这堆怪事。"

translate schinese story43_Erik_Lyna_601e27ac:
    e "可、可是怎么做？还有内疚怎么办？{size=-5}它已经快把我逼疯了……"

translate schinese story43_Erik_Lyna_25023ee3:
    l "她永远不会知道我们做了什么。"

translate schinese story43_Erik_Lyna_8f4ad2ff:
    l "再说了，我完全知道该按哪些按钮。她会是我们的。"

translate schinese story43_Erik_Lyna_6be0d12c:
    e "{size=+5}莱娜！别用那种口气说话！"

translate schinese story43_Erik_Lyna_3dff2156:
    l "嗯？你这是怎么了？"

translate schinese story43_Erik_Lyna_2312973b:
    e "我受够你那些把戏了！受够你这么会操纵人、这么……执着！"

translate schinese story43_Erik_Lyna_4353fa03:
    e "你对我、现在又对妈这种痴迷，那不是真正的你！"

translate schinese story43_Erik_Lyna_c9009feb:
    e "你真的有问题。去年之后有什么东西变了。"

translate schinese story43_Erik_Lyna_4ce76f77:
    l "你现在才发现？我都已经含过你的鸡巴十几回了？！"

translate schinese story43_Erik_Lyna_32cdead7:
    l "哈哈哈……真他妈好笑的玩笑，哥。"

translate schinese story43_Erik_Lyna_37275bcf:
    l "{size=-5}我以为我们已经过了这种狗屁阶段……"

translate schinese story43_Erik_Lyna_aa5ae351:
    e "啧。不是说我们之间的事！先听我说完。"

translate schinese story43_Erik_Lyna_e2fcbb26:
    e "你别——呃！看着我，莱娜。我是认真的。"

translate schinese story43_Erik_Lyna_9b93ce95:
    e "在国外那一年……把你改变了。"

translate schinese story43_Erik_Lyna_3fd6190b:
    e "我想弄清发生了什么，求你了。"

translate schinese story43_Erik_Lyna_5435109d:
    e "你一向是有点古灵精怪没错，但这不一样。你变了。"

translate schinese story43_Erik_Lyna_6e481ad4:
    l "哼！怎么个不一样法？"

translate schinese story43_Erik_Lyna_9c8a61a3:
    e "自从我们开始一起做这些事，我就觉得你……觉得你像……"

translate schinese story43_Erik_Lyna_5dd166a3:
    l "像什么，嗯？说啊。"

translate schinese story43_Erik_Lyna_8edba77f:
    e "像很饥渴！像很渴望被关注。"

translate schinese story43_Erik_Lyna_a4e0b33e:
    l "饥渴？我？！哈！{size=-5}你想得美……"

translate schinese story43_Erik_Lyna_e843edbd:
    l "我只是意识到自己有多渴求，好吗？新体验、亲密感……"

translate schinese story43_Erik_Lyna_ba3c35fc:
    l "既然现在就能和你拥有全部，我为什么要去走那条无聊又传统的人生路？"

translate schinese story43_Erik_Lyna_d1415d35:
    e "那不是——"

translate schinese story43_Erik_Lyna_d3587dc1:
    l "那不是我什么扭曲的癖好……这是生理本能，是进化。"

translate schinese story43_Erik_Lyna_b321e6d7:
    l "你难道从没感受过那种拉力？那种想和另一个人体验世间一切的渴望？"

translate schinese story43_Erik_Lyna_81a5cd8d:
    e "我们之间跟你完全不一样，你知道！"

translate schinese story43_Erik_Lyna_dbec78a5:
    e "我们是家人，是亲兄妹！呃……{size=-5}当然是在一种奇怪的关系里。"

translate schinese story43_Erik_Lyna_3f4a9b33:
    l "嗯。所以你的意思是……？"

translate schinese story43_Erik_Lyna_cf0c1c9b:
    e "说我们不是普通的情侣！这不一样。"

translate schinese story43_Erik_Lyna_3ead4eff:
    l "是好的不一样，还是坏的……不一样？"

translate schinese story43_Erik_Lyna_1b2f9f54:
    e "别这样……你知道我爱你，爱得过头了。"

translate schinese story43_Erik_Lyna_dee832e8:
    l "对！我也爱你，所以呢？"

translate schinese story43_Erik_Lyna_5d54e073:
    e "我只是想说，你的爱几乎有点占有欲，莱娜……"

translate schinese story43_Erik_Lyna_51b77c5a:
    e "其实我会说，这有时候已经有点渗人了。"

translate schinese story43_Erik_Lyna_53bee179:
    l "渗人……？所以你、你觉得{i}我{/i}很渗人？"

translate schinese story43_Erik_Lyna_77dafea2:
    e "抱歉莉妮，我——"

translate schinese story43_Erik_Lyna_6af7e9de:
    l "你说得好像这只是我一时发疯！"

translate schinese story43_Erik_Lyna_a59e539b:
    l "我们几乎是被保姆和家教带大的，埃里克！"

translate schinese story43_Erik_Lyna_51475bc8:
    l "还记得我们住过多少该死的房子吗？多少个国家？"

translate schinese story43_Erik_Lyna_e28346c4:
    l "因为爸爸的工作总是搬来搬去，{size=-5}下一个该死的大合同……"

translate schinese story43_Erik_Lyna_e01e7452:
    l "{size=-5}一直被塞进某个该死的新学校、某个新活动……"

translate schinese story43_Erik_Lyna_5b6aa792:
    l "「莱娜！六点去上芭蕾课！」「埃里克！七点练钢琴！」"

translate schinese story43_Erik_Lyna_b657ca8c:
    l "呃！还有在他们那该死的出差之间塞得满满的家教课……"

translate schinese story43_Erik_Lyna_1629bae1:
    l "我们是被训练成优秀、完美的小天才！"

translate schinese story43_Erik_Lyna_92663709:
    l "爸妈有没有停下来问过我们想不想要那些狗屁东西，嗯？"

translate schinese story43_Erik_Lyna_667071e3:
    l "他们从来没给我们时间只是「做自己」！"

translate schinese story43_Erik_Lyna_82ca6097:
    l "去交真正稳定的朋友……去经历一个正常的童年。"

translate schinese story43_Erik_Lyna_5841859e:
    l "我们什么时候有机会谈爱了，埃里克？有机会弄清离开他们那些愚蠢野心之后的自己是谁？"

translate schinese story43_Erik_Lyna_2e26d24c:
    e "那个……我们——"

translate schinese story43_Erik_Lyna_5ae5025f:
    l "他们忙着建立自己的帝国！忙着往上爬，忙着确保我们拿到「最好的」机会……"

translate schinese story43_Erik_Lyna_92822fcf:
    e "可我们做到了，不是吗？"

translate schinese story43_Erik_Lyna_7010ff81:
    l "可代价是什么，嗯？！他们从不在乎我们的真实感受。"

translate schinese story43_Erik_Lyna_92c66efc:
    l "就算难得地表现出关心，也永远是有条件的！好成绩、完美表现、无懈可击的成就……"

translate schinese story43_Erik_Lyna_daf019c9:
    l "不给乱七八糟的情绪留空间，也不给像正常孩子那样探索欲望留空间！"

translate schinese story43_Erik_Lyna_38bcb29b:
    l "呃……我只是他妈累坏了。"

translate schinese story43_Erik_Lyna_5d356f6e:
    e "我懂，莱娜。我真的懂。但是……"

translate schinese story43_Erik_Lyna_a9eab826:
    e "但这也不代表你可以利用妈的感情、把她当成一块肉。"

translate schinese story43_Erik_Lyna_3f8b4dec:
    l "瞧瞧！白马王子先生开始给我上道德课了……"

translate schinese story43_Erik_Lyna_c3b92035:
    l "昨晚占完她便宜之后，你可没这么犹豫。"

translate schinese story43_Erik_Lyna_5c4e6ced:
    e "这不公平！明明是你——"

translate schinese story43_Erik_Lyna_0020fa4a:
    l "这可不是我在国外染上的什么怪病，好吗？！"

translate schinese story43_Erik_Lyna_dbbb4fb9:
    l "你以为我是自愿的吗？！自愿有这种饥渴、这种……渴望？"

translate schinese story43_Erik_Lyna_2811cd79:
    l "{size=+5}要是我们是个他妈正常家庭……！"

translate schinese story43_Erik_Lyna_4ce1b790:
    l "{size=+5}要是爸妈没有一辈子把我们当成小奖杯一样打磨、四处炫耀……"

translate schinese story43_Erik_Lyna_18bf55f5:
    l "那我现在……{size=-5}就不会……"

translate schinese story43_Erik_Lyna_ec64770c:
    l "{size=-10}……变成这样。"

translate schinese story43_Erik_Lyna_6ce4cea7:
    e "姐，过来……"

translate schinese story43_Erik_Lyna_db0ea58c:
    e "你知道他们一直爱我们吧？用他们自己的方式。"

translate schinese story43_Erik_Lyna_0142b5a6:
    l "你说得倒轻巧……{size=-5}你一直是他们的最爱。"

translate schinese story43_Erik_Lyna_0a939c7c:
    l "反正对他们来说「爱」是什么？*抽泣*一段毁掉的婚姻？！"

translate schinese story43_Erik_Lyna_4c2f937c:
    l "他们从没时间爱。彼此之间都没有，更别说我们了！"

translate schinese story43_Erik_Lyna_bb10574b:
    l "我们需要学习生活、关系、性知识的时候，他们人呢？"

translate schinese story43_Erik_Lyna_bf15945a:
    l "去年是我第一次感到……自由。摆脱他们那些令人窒息的期待，自在地探索生活。"

translate schinese story43_Erik_Lyna_0e2ad261:
    l "所以没错，当我终于有自由去选择、去感受而不被他们评判时，心里确实有什么东西扭曲了！"

translate schinese story43_Erik_Lyna_5e9a02f2:
    l "而我现在正在拥抱他们那套该死的工作狂生活从不让我们体验的一切，埃里克。"

translate schinese story43_Erik_Lyna_1e599040:
    e "可莱娜，你……"

translate schinese story43_Erik_Lyna_4ca610d3:
    l "不！你休想因为我在别处找到了爱就评判我……{size=-5}在你身上。"

translate schinese story43_Erik_Lyna_b26f6e08:
    l "我们都找到了。是我让你看清的，不是吗？"

translate schinese story43_Erik_Lyna_dd660ed2:
    l "自从他那样对妈以后，爸爸早就不在乎我们了。"

translate schinese story43_Erik_Lyna_20857cf0:
    l "没错，妈几年前确实辞了工作，想多陪我们……"

translate schinese story43_Erik_Lyna_5a95f703:
    l "但她意识到自己的错误时已经太晚了！伤口要很久才能愈合。"

translate schinese story43_Erik_Lyna_1f361a13:
    l "也许他们本该给我们的就是这个……{size=+5}爱！"

translate schinese story43_Erik_Lyna_de64996c:
    l "{size=-5}而不是那种我们曾称之为生活的、无菌的、被野心驱动的人生……"

translate schinese story43_Erik_Lyna_7775037c:
    l "这些话我憋在心里太久了……"

translate schinese story43_Erik_Lyna_2d82ce47:
    l "现在你知道了全部真相。这就是我变了的原因，也是我不能再只用言语向你表达爱的原因。"

translate schinese story43_Erik_Lyna_b0bad3a6:
    l "这也是我如此他妈……拼命地渴求亲密的原因。"

