# -*- coding: utf-8 -*-
# Generated by tools/generate.py - do not edit by hand.
# Sinful Summer (Chapter 3.6) - Simplified Chinese localisation.

translate schinese hscene20_Lyna_Helga_adad3a7c:
    l "{size=-5}妈妈？"

translate schinese hscene20_Lyna_Helga_a4844007:
    h "什么事，亲爱的？"

translate schinese hscene20_Lyna_Helga_e03f3233:
    l "{size=-5}我能……再问你一件事吗？"

translate schinese hscene20_Lyna_Helga_6985a5ca:
    h "当然。什么都行。"

translate schinese hscene20_Lyna_Helga_aa34ced1:
    l "{size=-5}不过有点难为情……"

translate schinese hscene20_Lyna_Helga_faf30c58:
    h "我们说过了亲爱的，我就在这儿。"

translate schinese hscene20_Lyna_Helga_a6910f89:
    lm "到时候可别说我没提醒你哦。嘿嘿~"

translate schinese hscene20_Lyna_Helga_5857718b:
    l "你觉得……也许……"

translate schinese hscene20_Lyna_Helga_4e1f803a:
    l "你觉得我是不是可以……就摸一小下？"

translate schinese hscene20_Lyna_Helga_dedb4c69:
    h "摸……？你在说什么？"

translate schinese hscene20_Lyna_Helga_077934da:
    l "只是想看看是什么感觉。"

translate schinese hscene20_Lyna_Helga_99622e81:
    l "这次当然是经过你完全同意的。不会有意外。"

translate schinese hscene20_Lyna_Helga_d9cd587f:
    hm "天啊，她说的是那个？！不！她不会的！"

translate schinese hscene20_Lyna_Helga_a028978e:
    hm "不、不！她当真的吗？！"

translate schinese hscene20_Lyna_Helga_901eecd1:
    h "莱、莱娜你该不会是指……哎呀。"

translate schinese hscene20_Lyna_Helga_d6f9b661:
    l "你自己说的，我这个年纪的女孩对身体和其他事好奇很正常。"

translate schinese hscene20_Lyna_Helga_35c9788e:
    l "而你是我唯一信得过、愿意去问的女人……"

translate schinese hscene20_Lyna_Helga_f6a3a93a:
    h "所以那天在店里你才会{i}那样{/i}？"

translate schinese hscene20_Lyna_Helga_49d9e4cd:
    h "那不对。你不能就那样——"

translate schinese hscene20_Lyna_Helga_0dd3332a:
    l "我知道，妈妈，真的对不起！"

translate schinese hscene20_Lyna_Helga_fd9806fd:
    l "我只是……我慌了。我觉得自己被排除在外！"

translate schinese hscene20_Lyna_Helga_e40aec3e:
    l "那天我们玩得很开心，而你……"

translate schinese hscene20_Lyna_Helga_6a50f7e6:
    l "你和埃里克那么亲近，我也想成为其中的一部分，想找到一个能和你一起投入的东西。"

translate schinese hscene20_Lyna_Helga_37962821:
    hm "这就是全部原因？只是嫉妒？"

translate schinese hscene20_Lyna_Helga_ad2c2c89:
    hm "还是说其实是天真？我真搞不懂。"

translate schinese hscene20_Lyna_Helga_355cf31f:
    l "求你了妈妈？{size=-5}这会让我好开心的……"

translate schinese hscene20_Lyna_Helga_d6e8e635:
    centered "{font=font_narration}{cps=30}{color=#07ff93}我不想再看到你们像以前那样吵架了，{w=0.35}好吗？"

translate schinese hscene20_Lyna_Helga_7c927185:
    centered "{font=font_narration}{cps=30}{color=#07ff93}不管她做了什么，{w=0.35}就再给她一次机会。{w=0.35}拜托了。"

translate schinese hscene20_Lyna_Helga_72216945:
    hm "天啊，我居然真的在考虑这个？！"

translate schinese hscene20_Lyna_Helga_04469f30:
    l "你说过我们可以聊任何事，{size=-5}包括我的性……"

translate schinese hscene20_Lyna_Helga_b0cbd44b:
    l "如果我有什么问题，应该来找你。"

translate schinese hscene20_Lyna_Helga_450406ba:
    h "莱娜……"

translate schinese hscene20_Lyna_Helga_2cc22bd8:
    l "妈妈，我……我只是想知道自己错过了什么。"

translate schinese hscene20_Lyna_Helga_f7f03b77:
    hm "啊，多可爱啊！她只是好奇……"

translate schinese hscene20_Lyna_Helga_08b07b4e:
    hm "也许这能成为一种无害的方式，排解她的不安和一时冲动。"

translate schinese hscene20_Lyna_Helga_5505460a:
    hm "这不代表什么，对吧……？"

translate schinese hscene20_Lyna_Helga_55d3120e:
    h "*叹气* 好吧，宝贝。{size=-5}你赢了。"

translate schinese hscene20_Lyna_Helga_c45d661a:
    h "我允许，就这一次。而且只能一小会儿，好吗？"

translate schinese hscene20_Lyna_Helga_748da3aa:
    l "{size=+5}太好了~！别担心，我会很轻的！"

translate schinese hscene20_Lyna_Helga_c66a2b39:
    l "那么……我、现在可以吗……？"

translate schinese hscene20_Lyna_Helga_8f7cc9d7:
    h "可以。你以为我摆出这副样子是在等什么？"

translate schinese hscene20_Lyna_Helga_1bf2e358:
    h "来。快点就行。"

translate schinese hscene20_Lyna_Helga_ab9c9b91:
    lm "啥？她……在帮我？"

translate schinese hscene20_Lyna_Helga_85819483:
    lm "哇！我去……？真有那么容易？！"

translate schinese hscene20_Lyna_Helga_af98a9b7:
    lm "我还以为她会让我费一番功夫呢。"

translate schinese hscene20_Lyna_Helga_be3bb1cb:
    n "饥渴的少女察觉到母亲的投降，片刻也不耽搁。"

translate schinese hscene20_Lyna_Helga_6da3b70e:
    n "上衣的布料在两人之间隔出一层薄薄的屏障，却几乎无法抑制从母亲肌肤辐射出来的热度。"

translate schinese hscene20_Lyna_Helga_42018e72:
    l "妈妈……？"

translate schinese hscene20_Lyna_Helga_86c2bf96:
    h "来吧，宝、宝贝。{size=-5}没……{size=-10}关系的。"

translate schinese hscene20_Lyna_Helga_eaf95a69:
    h "哎呀！别那么用力……"

translate schinese hscene20_Lyna_Helga_d5940537:
    l "对不起！"

translate schinese hscene20_Lyna_Helga_0067f34e:
    hm "她要摸到什么时候？！我要阻止她吗？"

translate schinese hscene20_Lyna_Helga_7b4d6d66:
    hm "这太疯狂了！我肯定会后悔的。我知道。"

translate schinese hscene20_Lyna_Helga_b6bcfc23:
    lm "该死，那是……？"

translate schinese hscene20_Lyna_Helga_66d5d77a:
    lm "不敢相信，我妈咪的乳头硬起来了！"

translate schinese hscene20_Lyna_Helga_cd1684a1:
    lm "瞧瞧！她这次好像也有点好奇……"

translate schinese hscene20_Lyna_Helga_bd8efa2d:
    lm "也许这一注没那么糟。"

translate schinese hscene20_Lyna_Helga_93ac379a:
    l "妈妈，我能摸摸另一边吗？只是……比较一下。"

translate schinese hscene20_Lyna_Helga_548852b9:
    hm "我必须停下。马上！"

translate schinese hscene20_Lyna_Helga_e6c80cc9:
    centered "{font=font_narration}{cps=25}然而……"

translate schinese hscene20_Lyna_Helga_778eabec:
    h "{cps=15}来吧，亲爱的。"

translate schinese hscene20_Lyna_Helga_870464a8:
    l "哇……摸起来好软啊，妈妈。"

translate schinese hscene20_Lyna_Helga_7b8df64e:
    h "哎呀，别、别这么说……"

translate schinese hscene20_Lyna_Helga_f0e7cb7c:
    h "不过就是一对胸部而已！"

translate schinese hscene20_Lyna_Helga_079abf7f:
    l "可真的好软！难怪男人这么爱摸奶子……"

translate schinese hscene20_Lyna_Helga_fe4640bc:
    lm "该死，跟它们比起来我的手指好小……"

translate schinese hscene20_Lyna_Helga_9e32a401:
    lm "我敢说埃里克的手都握不下。"

translate schinese hscene20_Lyna_Helga_034ec585:
    lm "我真希望现在就在这儿把妈妈的衣服扒了，用我的他妈舌头把那两个乳头吸干。"

translate schinese hscene20_Lyna_Helga_b5f05d3b:
    hm "天啊……她为什么那样看我？！"

translate schinese hscene20_Lyna_Helga_2b31daf1:
    hm "这太不对了！我是她妈妈，不是……{size=-5}不是……"

translate schinese hscene20_Lyna_Helga_2079b5ed:
    l "妈妈……？你好僵硬。要我停下吗？"

translate schinese hscene20_Lyna_Helga_149564fa:
    h "我、我不知道。这样……{size=-5}对你有帮助吗？"

translate schinese hscene20_Lyna_Helga_4049ff30:
    lm "靠，我绝对得停手！我不能再搞砸了！"

translate schinese hscene20_Lyna_Helga_1187abe0:
    l "对不起妈妈！我不该提这种要求的。"

translate schinese hscene20_Lyna_Helga_c51e5a70:
    l "我又让你很不自在了，对不对？"

translate schinese hscene20_Lyna_Helga_5e48f4be:
    hm "她的声音那么无辜，那么……浑然不觉。"

translate schinese hscene20_Lyna_Helga_edfd6f0a:
    hm "也许是我的错？也许我在某种程度上助长了她这份兴趣。"

translate schinese hscene20_Lyna_Helga_ff16481c:
    h "不、不，宝贝，没关系的。"

translate schinese hscene20_Lyna_Helga_cb1c43f2:
    h "我只需要一点时间……呃……适应一下。"

translate schinese hscene20_Lyna_Helga_5c4da3c0:
    l "你要是想的话，我们可以换个姿势。"

translate schinese hscene20_Lyna_Helga_cdddfd3b:
    h "换……别的？"

translate schinese hscene20_Lyna_Helga_119e1711:
    hm "天啊，又是什么？！"

translate schinese hscene20_Lyna_Helga_a7c81560:
    l "我是说瑜伽啊！这不是我们来这里的目的吗？"

translate schinese hscene20_Lyna_Helga_8b811179:
    l "前几天我看到一个很酷的双人姿势，想和你一起试试。"

translate schinese hscene20_Lyna_Helga_7fb49f99:
    l "看？它字面上就叫「方形」。酷吧？"

translate schinese hscene20_Lyna_Helga_3ded7a4c:
    h "那个……我想我们可以试试。"

translate schinese hscene20_Lyna_Helga_64813dd8:
    h "但再来一个就好，行吗？我没心情练很久。"

translate schinese hscene20_Lyna_Helga_8204c3b7:
    l "好嘞！"

translate schinese hscene20_Lyna_Helga_f29c9241:
    lm "该死，那就是说我差点把她逼过头了……"

translate schinese hscene20_Lyna_Helga_16d6676b:
    l "一开始可能有点难，但我相信我们一起能搞定！"

translate schinese hscene20_Lyna_Helga_6182102b:
    l "这样可以吗，妈妈？我们做得对吗？"

translate schinese hscene20_Lyna_Helga_78b6e779:
    h "应该是……"

translate schinese hscene20_Lyna_Helga_99346356:
    l "据说能让我们的能量同步，或者类似的东西。"

translate schinese hscene20_Lyna_Helga_f3975ed9:
    h "嗯哼……"

translate schinese hscene20_Lyna_Helga_36e8f567:
    l "开心吗妈妈？这样超棒的对吧？！"

translate schinese hscene20_Lyna_Helga_fda05795:
    h "开、开心，你知道我喜欢这样和你亲近……"

translate schinese hscene20_Lyna_Helga_93cd9674:
    l "耶~！我也爱你！"

translate schinese hscene20_Lyna_Helga_149fe276:
    l "那一下……呼……真不错。该死，我出汗了！"

translate schinese hscene20_Lyna_Helga_cb5ee5bd:
    h "确实，我觉得今天差不多够了……"

translate schinese hscene20_Lyna_Helga_ad7436a8:
    l "谢谢你，妈妈。也对不起，我最近表现得这么奇怪……"

translate schinese hscene20_Lyna_Helga_f80b67f0:
    l "我只是不知道该怎么应对这些新的感情。"

translate schinese hscene20_Lyna_Helga_dc900907:
    h "没……没事。"

translate schinese hscene20_Lyna_Helga_ed1cc2b4:
    l "那天发生的事，你原谅我了吗？"

translate schinese hscene20_Lyna_Helga_23d78d01:
    h "原谅了……我们一起想办法，好吗？"

translate schinese hscene20_Lyna_Helga_63e0a76d:
    l "我爱你妈妈！谢谢你这么体谅我。"

translate schinese hscene20_Lyna_Helga_e5f16c8d:
    h "莱娜，我……"

translate schinese hscene20_Lyna_Helga_9c6478d2:
    h "咳咳！我也爱你，{size=-5}宝贝……"

translate schinese hscene20_Lyna_Helga_c70d6d44:
    hm "这就是她道歉的方式？"

translate schinese hscene20_Lyna_Helga_c0dab460:
    hm "她那个请求，天啊……"

translate schinese hscene20_Lyna_Helga_68ffe065:
    hm "尽管我心里有一部分真的很想再信任她，另一部分却觉得她只是把我当玩具一样摆弄。"

translate schinese hscene20_Lyna_Helga_c132ba7a:
    hm "但怎么说呢，我不能否认，能再和女儿一起做瑜伽我很享受。"

translate schinese hscene20_Lyna_Helga_e98a7203:
    l "妈妈？你没事吧？"

translate schinese hscene20_Lyna_Helga_5cb1a81d:
    h "莱娜，呃……你觉得我们该多做一些吗？"

translate schinese hscene20_Lyna_Helga_921581a2:
    l "什么？！当然！我们应该把它变成每天的仪式！"

translate schinese hscene20_Lyna_Helga_52e5b8d9:
    l "就像第一天你叫它的「赫尔加的快乐时光」！哈哈哈！"

translate schinese hscene20_Lyna_Helga_2c121d30:
    h "是的，像这样亲近对我们很好……"

translate schinese hscene20_Lyna_Helga_2c7cf6f1:
    l "好了，我现在要去泡个长澡！"

translate schinese hscene20_Lyna_Helga_2c1cb2d4:
    l "这次我先去吧？前天你可独占了整个浴缸。"

translate schinese hscene20_Lyna_Helga_66fe0dd5:
    h "对、对，你去吧。反正我也要忙着做饭。"

translate schinese hscene20_Lyna_Helga_342d6d6c:
    l "一会儿见啦！嘻嘻~"

translate schinese hscene20_Lyna_Helga_14a33e06:
    hm "可恶。她到底在打什么主意？"

translate schinese hscene20_Lyna_Helga_8078650a:
    hm "当了这么多年律师，我居然完全看不透自己的女儿……"

translate schinese hscene20_Lyna_Helga_1102e72a:
    hm "她是真心想和我共度时光？还是完全另有目的？比如……"

translate schinese hscene20_Lyna_Helga_62db3eec:
    centered "{font=font_narration}{cps=25}{color=#f1d377}( 我很多年前和她做的那件事—— )"

translate schinese hscene20_Lyna_Helga_20451aba:
    hm "天啊！不！我大概想太多了……" with vpunch

translate schinese hscene20_Lyna_Helga_63139639:
    hm "她只是到了那个年纪特有的阶段而已。"

translate schinese hscene20_Lyna_Helga_6d88a15a:
    hm "可哪有女儿会要求摸自己母亲的胸的？"

translate schinese hscene20_Lyna_Helga_4e87fa35:
    hm "我怎么会答应这种事？！"

translate schinese hscene20_Lyna_Helga_dc730e53:
    hm "大概是她看起来那么……脆弱。我想在那一刻让她开心起来，因为我孩子的幸福才是一切。"

translate schinese hscene20_Lyna_Helga_37222dcf:
    hm "但真的是这样吗……？这不太对劲。"

translate schinese hscene20_Lyna_Helga_5edfcea3:
    hm "不过说公道话，我可能有那么一……{size=-5}点点享受。"

translate schinese hscene20_Lyna_Helga_f94d678f:
    hm "再说了，跟我对儿子做的事比起来，这根本不算什么。"

translate schinese hscene20_Lyna_Helga_5e89308f:
    hm "{cps=20}跟我对……{w=0.35}我对……{size=-5}{w=0.5}我儿子……{size=-10}{w=0.5}昨晚做的事？"

translate schinese hscene21_Erik_Lyna_d33da684:
    centered "{font=font_narration}{size=+10}{cps=20}洗完一个放松的澡之后……"

translate schinese hscene21_Erik_Lyna_02c2ea8b:
    l "{size=+5}埃里克，埃里克，埃里克，埃里克！"

translate schinese hscene21_Erik_Lyna_713b5e7f:
    h "{size=-5}喂！小心门，宝贝！"

translate schinese hscene21_Erik_Lyna_3c993cea:
    e "妹？！你怎么跟疯了似的闯进来？"

translate schinese hscene21_Erik_Lyna_9e9af64c:
    l "我他妈的老兄！"

translate schinese hscene21_Erik_Lyna_cfef4231:
    l "我不知道你对她施了什么黑魔法，但是……"

translate schinese hscene21_Erik_Lyna_7df71a76:
    l "和妈妈那档事彻底疯了！比我预想的爽一百倍！"

translate schinese hscene21_Erik_Lyna_300a824f:
    e "真的？听你这么说我很高兴，妹妹。"

translate schinese hscene21_Erik_Lyna_38021e2b:
    em "我到底做了什么？我只是跟她说了说话……"

translate schinese hscene21_Erik_Lyna_fe5732d7:
    n "有意识地说。那天促使他们母亲那样行动的是……"

translate schinese hscene21_Erik_Lyna_c0c11d5e:
    centered "{font=font_narration}{cps=25}完全是另一回事。"

translate schinese hscene21_Erik_Lyna_6de7b31f:
    l "{cps=30}你和我……{w=0.5}妈妈的房间……{w=0.5}五分钟后。"

translate schinese hscene21_Erik_Lyna_74d15db7:
    e "咦？什么……？"

translate schinese hscene21_Erik_Lyna_554e3448:
    l "{cps=25}我要奖励你，{w=0.35}大哥。{cps=20}{w=0.5}这次是来真的。"

translate schinese hscene21_Erik_Lyna_fa2a0621:
    e "*咽口水* 别在她卧室里，莱娜……"

translate schinese hscene21_Erik_Lyna_cc1abb0f:
    l "拜托，她在厨房做她的拿手菜呢！"

translate schinese hscene21_Erik_Lyna_ac61d591:
    l "我估计起码得花一个小时！"

translate schinese hscene21_Erik_Lyna_eaa09ed2:
    e "我说了不行！我看得出你很兴奋，妹妹，相信我，我也非常……"

translate schinese hscene21_Erik_Lyna_1fcd7e80:
    e "可你知道我们不能这么鲁莽！"

translate schinese hscene21_Erik_Lyna_9d36a295:
    e "浴室那件事你这么快就忘了？太冒险了。"

translate schinese hscene21_Erik_Lyna_b62b5965:
    l "啧，好吧。看来你说得对……"

translate schinese hscene21_Erik_Lyna_bd63ad99:
    e "也许我们该等到晚上她睡了之类的？"

translate schinese hscene21_Erik_Lyna_36b96d31:
    l "不行，我们去外面！她在那儿听不见。"

translate schinese hscene21_Erik_Lyna_a69fafff:
    e "喂！我刚说了——"

translate schinese hscene21_Erik_Lyna_a6b9b911:
    l "你看，你不是想用那些点数换点什么奖励吗……？"

translate schinese hscene21_Erik_Lyna_232ec455:
    em "靠，我现在就想要我妹妹。"

translate schinese hscene21_Erik_Lyna_2dd93bf1:
    em "我已经堕化了。没有她，我再也感受不到任何快感……"

translate schinese hscene21_Erik_Lyna_29bea697:
    l "妈妈，我和埃里克出去散散步，好吗？"

translate schinese hscene21_Erik_Lyna_857599a5:
    h "好吧，去玩吧孩子们！但午饭不许迟到一秒！"

translate schinese hscene21_Erik_Lyna_6f147c3c:
    l "知道啦知道啦！"

translate schinese hscene21_Erik_Lyna_48079986:
    h "等等，莱娜……？！你穿成这样要去哪儿？至少把衣服穿上！"

translate schinese hscene21_Erik_Lyna_140692b0:
    l "别担心妈，我里面穿了比基尼！"

translate schinese hscene21_Erik_Lyna_09505ea3:
    e "对、对啊，我也想去游一会儿泳……"

translate schinese hscene21_Erik_Lyna_d058fc4d:
    h "好吧，行！但二十分钟后我要在这儿看到你们俩！"

translate schinese hscene21_Erik_Lyna_84bb02df:
    l "好的好的！当然！"

translate schinese hscene21_Erik_Lyna_9780b466:
    em "而莱娜说的是一个小时。哼……"

translate schinese hscene21_Erik_Lyna_e6291c6a:
    l "快点嘛，大哥~"

translate schinese hscene21_Erik_Lyna_7cba15fe:
    hm "哎呀，他们两个凑在一起怎么这么可爱？"

translate schinese hscene21_Erik_Lyna_b41c1cea:
    em "靠，我妹妹疯了！她居然想在妈妈还在家的时候去她房间里做事？！"

translate schinese hscene21_Erik_Lyna_24dc16e7:
    em "我是说，听起来确实很刺激，可是——"

translate schinese hscene21_Erik_Lyna_4afccba7:
    em "不！我得盯着她！我们不能这么鲁莽。"

translate schinese hscene21_Erik_Lyna_8584af7d:
    l "脱。"

translate schinese hscene21_Erik_Lyna_2b40a022:
    e "咦？"

translate schinese hscene21_Erik_Lyna_0093ed0e:
    l "{cps=25}脱。{w=0.35}掉。{w=0.35}把你他妈的衣服脱光。"

translate schinese hscene21_Erik_Lyna_fc4c55fd:
    e "好吧好吧！"

translate schinese hscene21_Erik_Lyna_53a80a25:
    l "那你还等什么？过来。"

translate schinese hscene21_Erik_Lyna_03c5ba87:
    e "可是莱娜，妈妈她……"

translate schinese hscene21_Erik_Lyna_d3b6c525:
    l "她正忙着呢！放心吧。"

translate schinese hscene21_Erik_Lyna_76489db6:
    l "她要是起疑，我们就绕到转角那边去……"

translate schinese hscene21_Erik_Lyna_3a494834:
    l "拜托，你真不想错过这个……？"

translate schinese hscene21_Erik_Lyna_7bbfe390:
    l "这不就对了！嘿嘿嘿~"

translate schinese hscene21_Erik_Lyna_6b5cc912:
    e "我满脑子都是你，妹……"

translate schinese hscene21_Erik_Lyna_96dcbfc6:
    l "嗯哼。"

translate schinese hscene21_Erik_Lyna_6e1e4d7c:
    e "而我也满脑子都是你的身体……"

translate schinese hscene21_Erik_Lyna_bc4824c5:
    l "对……{size=-5}哥……"

translate schinese hscene21_Erik_Lyna_dc620a97:
    e "靠，真不敢相信我们在干这种事……"

translate schinese hscene21_Erik_Lyna_2b356266:
    l "你最好习惯起来，嘿嘿~"

translate schinese hscene21_Erik_Lyna_bdf13b87:
    l "操。你的鸡巴贴在我小腹上感觉真他妈暖和……"

translate schinese hscene21_Erik_Lyna_607a7694:
    e "那我的……奖励是什么？"

translate schinese hscene21_Erik_Lyna_6614af0a:
    l "哦，你问得好。"

translate schinese hscene21_Erik_Lyna_a496c80e:
    e "不会吧！我们要去……要、要……？！"

translate schinese hscene21_Erik_Lyna_ffd745a7:
    l "要、要干什么，结巴小子？"

translate schinese hscene21_Erik_Lyna_f58df7f7:
    e "莱娜，我不知道自己对……{size=-5}那个会不会自在。"

translate schinese hscene21_Erik_Lyna_3df01e2d:
    l "咦？你在想什么呢，变态？"

translate schinese hscene21_Erik_Lyna_ef8050ee:
    l "我们按我的规矩来，埃里克。"

translate schinese hscene21_Erik_Lyna_e29606db:
    l "但别担心，我不会逼你做任何你不自在的事……"

translate schinese hscene21_Erik_Lyna_658d4c8d:
    l "来，把你那害羞的小鸡巴掏出来，塞进中间。"

translate schinese hscene21_Erik_Lyna_4f79ac65:
    l "{cps=25}塞进你妹妹的大屁股缝里……"

translate schinese hscene21_Erik_Lyna_0bf6bd72:
    l "现在别害羞了，哥。"

translate schinese hscene21_Erik_Lyna_44941e1b:
    l "我要你蹭着我。我要感受你贴在我身上，埃里克。"

translate schinese hscene21_Erik_Lyna_f9cfb92e:
    l "对，就这样，继续……"

translate schinese hscene21_Erik_Lyna_977f2a12:
    e "哦，莱娜……我不知道我——"

translate schinese hscene21_Erik_Lyna_ea581137:
    l "信我一次，哥。再来一点点……"

translate schinese hscene21_Erik_Lyna_babfec82:
    e "靠，好他妈暖和……"

translate schinese hscene21_Erik_Lyna_47cf2e38:
    l "嘿嘿～我知道有几个地方更暖和。"

translate schinese hscene21_Erik_Lyna_6548b141:
    n "当埃里克意识到当下处境的分量、以及她刚才那句玩笑指的是什么时，他的手指剧烈地颤抖起来。"

translate schinese hscene21_Erik_Lyna_e4c80322:
    n "这是不对，是禁忌，是危险……可感觉却难以置信地正确。"

translate schinese hscene21_Erik_Lyna_f84e8978:
    l "快点嘛！你还在等什么……？"

translate schinese hscene21_Erik_Lyna_f804f421:
    l "开始动。磨蹭它们。让我好好感觉你！"

translate schinese hscene21_Erik_Lyna_15fd179e:
    e "妹妹，你确定吗？我们不能……换个地方吗？"

translate schinese hscene21_Erik_Lyna_0b40f2c0:
    l "嘘……就这样。{size=-5}感觉就好，拜托。"

translate schinese hscene21_Erik_Lyna_72b54292:
    l "{cps=25}{size=-10}因为我想要你，{w=0.35}埃里克。{w=0.5}我需要你。"

translate schinese hscene21_Erik_Lyna_53d5c2ea:
    em "操，这他妈太冒险了！可是……"

translate schinese hscene21_Erik_Lyna_4a20999f:
    centered "{font=font_narration}{cps=25}危险本身就带着一种有趣的刺激。"

translate schinese hscene21_Erik_Lyna_66590cfa:
    centered "{font=font_narration}{cps=25}一种共同的兴奋，助长了他们禁忌的欲望。"

translate schinese hscene21_Erik_Lyna_adb8d271:
    n "埃里克的鸡巴以前所未有的力度搏动着，开始滑进他双胞胎妹妹柔软的臀缝之间。"

translate schinese hscene21_Erik_Lyna_837bb1be:
    l "对！用我的屁股！"

translate schinese hscene21_Erik_Lyna_06f96810:
    e "靠，妹妹……你好软。"

translate schinese hscene21_Erik_Lyna_eae9fb53:
    l "唔嗯！好舒服，大哥。别停！"

translate schinese hscene21_Erik_Lyna_b07392fd:
    l "来……我帮你。"

translate schinese hscene21_Erik_Lyna_82c80e03:
    e "天哪，莱娜……我们真是乱透了。"

translate schinese hscene21_Erik_Lyna_a6b9b78f:
    l "也许吧。可舒服得让人停不下来，不是吗？"

translate schinese hscene21_Erik_Lyna_4a038b5c:
    l "再用力点，哥。我要感受你失控！"

translate schinese hscene21_Erik_Lyna_f8b2bdab:
    n "那种无时无刻不在的被发现的恐惧，怕他们的妈妈撞见自己孩子们乱伦的场面……"

translate schinese hscene21_Erik_Lyna_3afb7763:
    n "这丝毫没有让埃里克退缩，反而只让他的兴奋更加高涨。"

translate schinese hscene21_Erik_Lyna_ee4b9ef4:
    l "告诉我你爱我，埃里克。告诉我我是你唯一想要的女孩。"

translate schinese hscene21_Erik_Lyna_7e05c665:
    e "我……我爱你，莱娜。超过我应该爱的程度。也超过其他任何人。"

translate schinese hscene21_Erik_Lyna_09a50554:
    lm "没错，大哥。向我投降吧……"

translate schinese hscene21_Erik_Lyna_ce954ee7:
    l "快点，往那屁股里插快点！"

translate schinese hscene21_Erik_Lyna_42eff5a0:
    l "对！把你那处男的鸡巴在我臀缝里猛插！"

translate schinese hscene21_Erik_Lyna_9510512a:
    l "拿你妹妹的屁股来满足你他妈的欲望吧！"

translate schinese hscene21_Erik_Lyna_409757cd:
    e "靠，莱娜……你好下流。"

translate schinese hscene21_Erik_Lyna_a9da6bfd:
    l "再用力点，埃里克！我要感受你有多想要我！"

translate schinese hscene21_Erik_Lyna_8e451eb9:
    n "可两人太迷失在禁忌的快感中，双胞胎突然失去了平衡……"

translate schinese hscene21_Erik_Lyna_998da8d1:
    l "哎呀！我的错，对不起……"

translate schinese hscene21_Erik_Lyna_f2cb4160:
    e "没……没事，妹妹。"

translate schinese hscene21_Erik_Lyna_3233a1bc:
    e "别担心。我没事，因为……"

translate schinese hscene21_Erik_Lyna_345336c6:
    e "因为你摸起来太他妈舒服了！"

translate schinese hscene21_Erik_Lyna_b5906795:
    l "哦？！原来如此，哈哈！还没完呢……"

translate schinese hscene21_Erik_Lyna_b4d2800d:
    l "不过接下来全交给我来，好吗？这是你应得的。"

translate schinese hscene21_Erik_Lyna_174c9880:
    l "嗯，你喜欢这样对吧？你那个色情的妹妹正磨蹭着你那根大鸡巴？"

translate schinese hscene21_Erik_Lyna_3119041d:
    e "嗯……喜欢！"

translate schinese hscene21_Erik_Lyna_5ccaf216:
    n "他们作为双胞胎的羁绊一直很牢固，但最近演变成了一种他们既难以定义、也难以抗拒的东西。"

translate schinese hscene21_Erik_Lyna_ce4dc9a3:
    n "明知自己的行为有多错乱，心里却涌起一种强烈的「本该如此」之感……"

translate schinese hscene21_Erik_Lyna_b42da55c:
    e "这太他妈离谱了，妹妹……"

translate schinese hscene21_Erik_Lyna_dd4b4e2e:
    e "可我停不下来。我也不想停！"

translate schinese hscene21_Erik_Lyna_991fd5f8:
    l "那就别停！一起离谱下去。离谱的双胞胎！"

translate schinese hscene21_Erik_Lyna_69b230f8:
    l "操，埃里克……我好喜欢你的鸡巴抵在我大屁股上的感觉！"

translate schinese hscene21_Erik_Lyna_0a99326a:
    l "明知道干蹭的是自己的亲妹妹，你还会硬吗？！"

translate schinese hscene21_Erik_Lyna_9422559d:
    e "靠……你什么时候学会这样说话的？！"

translate schinese hscene21_Erik_Lyna_6f3e0644:
    n "她那些淫荡的话让他的鸡巴剧烈搏动，前端肿胀湿润，不断在莱娜柔软青涩的臀缝间滑动。"

translate schinese hscene21_Erik_Lyna_3802b29b:
    em "我不该这么想要这个，可感觉太他妈爽了！"

translate schinese hscene21_Erik_Lyna_e6944b0b:
    em "我妹妹快把我逼疯了！"

translate schinese hscene21_Erik_Lyna_60111510:
    l "告诉我你有多想要我，埃里克。你有多爱你的双胞胎妹妹。"

translate schinese hscene21_Erik_Lyna_838758a7:
    e "我爱你，莱娜……我爱你的疯狂！"

translate schinese hscene21_Erik_Lyna_0f43f270:
    l "对！说点下流的！{size=-5}至少试着说点……"

translate schinese hscene21_Erik_Lyna_63d1712d:
    e "呃，好的……我……"

translate schinese hscene21_Erik_Lyna_9d587749:
    e "{size=-5}我就喜欢和自己的双胞胎妹妹偷偷做坏事。"

translate schinese hscene21_Erik_Lyna_8ffb82ea:
    l "{size=+5}对……哥，对啊啊啊！" with vpunch

translate schinese hscene21_Erik_Lyna_ad0725cd:
    e "{size=+5}啊啊妹妹……！我快到了！"

translate schinese hscene21_Erik_Lyna_7805bb55:
    l "等等！跟我来……"

translate schinese hscene21_Erik_Lyna_f76d67fb:
    l "来，大哥，射满我后背……"

translate schinese hscene21_Erik_Lyna_66667466:
    l "我要你用滚烫的精液把它涂成一片白。"

translate schinese hscene21_Erik_Lyna_2f935afd:
    l "快点，射吧！在你妹妹这具青涩的身体上打下你的烙印。"

translate schinese hscene21_Erik_Lyna_16f9c58c:
    e "莱、莱娜……天啊……我要射了……！"

translate schinese hscene21_Erik_Lyna_223bccb0:
    l "对啊大哥！继续射满你妹妹全身！"

translate schinese hscene21_Erik_Lyna_db5f02e0:
    e "操……妹妹！"

translate schinese hscene21_Erik_Lyna_e310a9cf:
    l "嗯，对！我能感觉到，埃里克。又烫又浓……"

translate schinese hscene21_Erik_Lyna_db7d424e:
    lm "我永远不会停，哥。"

translate schinese hscene21_Erik_Lyna_35424eff:
    centered "{font=font_narration}{cps=25}{color=#69d9fe}（ 在你完全属于我之前，我不会停。 ）"

translate schinese hscene21_Erik_Lyna_24d0af2e:
    e "靠……刚才太疯狂了。"

translate schinese hscene21_Erik_Lyna_fd8275f3:
    l "{size=+5}对！爽死了！" with vpunch

translate schinese hscene21_Erik_Lyna_9daf876c:
    e "不过我们真的得清理一下了。"

translate schinese hscene21_Erik_Lyna_946fd291:
    e "你有干净衣服吗？拜托告诉我有……"

translate schinese hscene21_Erik_Lyna_022ab46d:
    l "有！我以防万一在你房间放了一套。"

translate schinese hscene21_Erik_Lyna_d0358e56:
    e "好，那我们可以绕着房子走。"

translate schinese hscene21_Erik_Lyna_5ad069b8:
    e "还有莱娜，我们得更小心。不能再这样失控下去。"

translate schinese hscene21_Erik_Lyna_a10f4f89:
    l "我知道，我知道！可刚才不是超刺激吗？！"

translate schinese story39_Erik_Lyna_Helga_bf1d8937:
    h "你们俩来了！正好。"

translate schinese story39_Erik_Lyna_Helga_fd226cb3:
    h "散步愉快吗？"

translate schinese story39_Erik_Lyna_Helga_de3db4a6:
    e "嗯，妈。感觉非常……清爽。"

translate schinese story39_Erik_Lyna_Helga_eb3db42d:
    l "超棒！"

translate schinese story39_Erik_Lyna_Helga_8f543a61:
    l "妈妈，这个看起来好好吃……"

translate schinese story39_Erik_Lyna_Helga_140414bc:
    h "谢谢！希望你们喜欢，孩子们！"

translate schinese story39_Erik_Lyna_Helga_c2ac25b1:
    e "嗯，谢谢妈……"

translate schinese story39_Erik_Lyna_Helga_e5e8858a:
    centered "{font=font_narration}{cps=25}他们危险的游戏还远远没有结束……"

translate schinese story39_Erik_Lyna_Helga_b6e58928:
    e "姐，快来搭把手……"

translate schinese story39_Erik_Lyna_Helga_c9a533da:
    e "你为什么一直那样看我？"

translate schinese story39_Erik_Lyna_Helga_dba7e784:
    l "哦，我只是在欣赏这一切发展得有多完美。"

translate schinese story39_Erik_Lyna_Helga_6a13d396:
    e "嗯？你什么意思？"

translate schinese story39_Erik_Lyna_Helga_bf3a3647:
    l "你知道，我们那个小游戏……"

translate schinese story39_Erik_Lyna_Helga_aa88d11f:
    e "你以为这只是个……游戏？莉妮，这是很认真的事。"

translate schinese story39_Erik_Lyna_Helga_e738f531:
    l "是吗？我敢说一小时前的埃里克可不会这么担心。"

translate schinese story39_Erik_Lyna_Helga_1edf26e7:
    e "{size=-5}嘘！妈就在那儿！不管怎样这都得保密。"

translate schinese story39_Erik_Lyna_Helga_3eb118ff:
    l "{size=-5}放轻松，大哥。你太紧张了！"

translate schinese story39_Erik_Lyna_Helga_4b4218b1:
    e "{size=-5}我……没有。"

translate schinese story39_Erik_Lyna_Helga_b8689b3d:
    l "{size=-5}我说过了，一切都在掌控中。"

translate schinese story39_Erik_Lyna_Helga_48cab494:
    l "{size=-5}你只要继续做你最擅长的——当妈妈的乖儿子……"

translate schinese story39_Erik_Lyna_Helga_0f711061:
    l "{size=-5}剩下的我来处理，好吗？"

translate schinese story39_Erik_Lyna_Helga_7b150290:
    e "{size=-5}呃……呃嗯……"

translate schinese story39_Erik_Lyna_Helga_5e92148e:
    centered "{font=font_narration}{size=+10}{cps=20}接下来的几周是一场缓慢而{w=0.25}煎熬的舞蹈。"

translate schinese story39_Erik_Lyna_Helga_9d2b524a:
    n "莱娜像个牵着无形丝线的提线木偶师，为达成自己的目的编排着各种局面……"

translate schinese story39_Erik_Lyna_Helga_559575bb:
    centered "{font=font_narration}{cps=25}一点点的笨手笨脚……"

translate schinese story39_Erik_Lyna_Helga_cfde1909:
    e "妈，你确定不需要帮忙吗？"

translate schinese story39_Erik_Lyna_Helga_b57d7bd8:
    h "不用了宝贝，家里你帮得够多了。"

translate schinese story39_Erik_Lyna_Helga_e368067b:
    h "这次就让我来收拾……{size=-5}你妹妹的烂摊子。"

translate schinese story39_Erik_Lyna_Helga_3680e177:
    l "喂！我说了对不起，妈。"

translate schinese story39_Erik_Lyna_Helga_4d99123b:
    h "呃，没……事。"

translate schinese story39_Erik_Lyna_Helga_5ad53ecc:
    h "对不起宝贝，我不是那个意思。"

translate schinese story39_Erik_Lyna_Helga_232e7d9f:
    l "别担心，我知道我最近有点笨手笨脚……"

translate schinese story39_Erik_Lyna_Helga_2ae41691:
    l "我只知道要是没有你们，我可怎么办！"

translate schinese story39_Erik_Lyna_Helga_6a6b2652:
    l "你绝对不会想看我去年这时候的房间什么样。"

translate schinese story39_Erik_Lyna_Helga_656904fa:
    h "好了宝贝，不至于那么糟。"

translate schinese story39_Erik_Lyna_Helga_9f9d5b75:
    l "嗯……也是。说到底你确实教过我一些规矩。"

translate schinese story39_Erik_Lyna_Helga_77ba9523:
    h "看吧？我说过我为你们俩做的一切都有理由！"

translate schinese story39_Erik_Lyna_Helga_99455dc4:
    lm "我觉得埃里克肯定也这么认为，嘿嘿~"

translate schinese story39_Erik_Lyna_Helga_77383949:
    centered "{font=font_narration}{cps=25}一起去镇上办件事……"

translate schinese story39_Erik_Lyna_Helga_b99d890d:
    l "妈你说，我关于他的话完全没错吧！"

translate schinese story39_Erik_Lyna_Helga_409940d2:
    l "你犹豫什么？你美极了！"

translate schinese story39_Erik_Lyna_Helga_db4aa9d4:
    h "不是那样，莱娜……"

translate schinese story39_Erik_Lyna_Helga_89fc0a88:
    l "那是什么？我还以为你很喜欢单独和埃里克待着呢……"

translate schinese story39_Erik_Lyna_Helga_38e6910e:
    l "拜托嘛？我保证不会嫉妒，妈。"

translate schinese story39_Erik_Lyna_Helga_a2a9cabd:
    h "好吧，好吧……你哥哥有你真幸运。"

translate schinese story39_Erik_Lyna_Helga_de4d3849:
    h "我准备好了，儿子。抱歉耽误了一点。"

translate schinese story39_Erik_Lyna_Helga_d0f807e0:
    e "别担心。不过你还好吗？"

translate schinese story39_Erik_Lyna_Helga_d73f2013:
    h "嗯。走吧。"

translate schinese story39_Erik_Lyna_Helga_3713f35f:
    e "真的有必要吗？我是说，你看起来不太情愿，而且我也——"

translate schinese story39_Erik_Lyna_Helga_0613aab1:
    h "不不，你妹妹说得对！你确实该换身新行头了。"

translate schinese story39_Erik_Lyna_Helga_ac0ab01a:
    h "再说了，之后你还能陪我一起逛街狂欢呢，对吧？"

translate schinese story39_Erik_Lyna_Helga_da7896e1:
    e "好吧妈。那虽然不是我最喜欢的消遣，不过……"

translate schinese story39_Erik_Lyna_Helga_db0a805f:
    e "只要能让你开心……"

translate schinese story39_Erik_Lyna_Helga_517d8782:
    h "呃……？好、好！{size=-5}谢谢。"

translate schinese story39_Erik_Lyna_Helga_04ae2f97:
    h "那就走吧宝贝，我们还有一整天呢！"

translate schinese story39_Erik_Lyna_Helga_30b38cdf:
    centered "{font=font_narration}{cps=25}一场临时兴起的走秀……"

translate schinese story39_Erik_Lyna_Helga_7702a297:
    h "你好呀……"

translate schinese story39_Erik_Lyna_Helga_538c5ed3:
    l "天哪，你真听我的！"

translate schinese story39_Erik_Lyna_Helga_37fb715d:
    h "对宝贝，你这主意真好。"

translate schinese story39_Erik_Lyna_Helga_608a5571:
    l "说了吧！哥你怎么拉着长脸？嘿嘿嘿~"

translate schinese story39_Erik_Lyna_Helga_31905f6e:
    e "我不喜欢。感觉怪怪的……"

translate schinese story39_Erik_Lyna_Helga_aa23af8e:
    l "哦，埃里克，埃里克……"

translate schinese story39_Erik_Lyna_Helga_87e385d9:
    l "换个角度想，你本来就是个乖儿子，所以……"

translate schinese story39_Erik_Lyna_Helga_5f95e205:
    l "这样只是让你更配得上这身！"

translate schinese story39_Erik_Lyna_Helga_0add5688:
    l "他比以前更帅了。妈你也这么觉得吧？"

translate schinese story39_Erik_Lyna_Helga_3e8a1376:
    h "哦，确实！就像当年他还是个小不点的时候。"

translate schinese story39_Erik_Lyna_Helga_a37149fa:
    h "我以前总用那些小西装配上最可爱的发型，把你打扮得漂漂亮亮！记得吗，儿子？"

translate schinese story39_Erik_Lyna_Helga_400240de:
    e "嗯……"

translate schinese story39_Erik_Lyna_Helga_3f874e3b:
    l "但现在我哥可是相当像个男人了！长得又高又壮。"

translate schinese story39_Erik_Lyna_Helga_39a83748:
    h "可他永远都是我的小王子……"

translate schinese story39_Erik_Lyna_Helga_1a015dd4:
    h "不过莱娜，你说得对。"

translate schinese story39_Erik_Lyna_Helga_7689bb5d:
    h "{cps=25}你哥哥确实长大了很多……{w=0.35}{size=-5}很多方面都是。"

translate schinese story39_Erik_Lyna_Helga_3ae0fbba:
    h "{cps=20}他如今是我英俊的……{w=0.35}可靠的……{w=0.35}大男孩。"

translate schinese story39_Erik_Lyna_Helga_3afbdcc5:
    lm "该死！她这是怎么了？"

translate schinese story39_Erik_Lyna_Helga_74e1da20:
    h "宝、宝贝！我们大概该给他一点空间了……"

translate schinese story39_Erik_Lyna_Helga_b021e602:
    l "对，我们可不想让他脸红得像番茄。嘻嘻~！"

translate schinese story39_Erik_Lyna_Helga_125b34be:
    l "哇妈……"

translate schinese story39_Erik_Lyna_Helga_8b6d6369:
    h "怎么了？"

translate schinese story39_Erik_Lyna_Helga_02cc3aee:
    l "我得说，你真的很会穿！"

translate schinese story39_Erik_Lyna_Helga_adbb4a97:
    h "哦，谢谢！我忍不住又买了几件。"

translate schinese story39_Erik_Lyna_Helga_498c63ad:
    h "这些很好看吧？"

translate schinese story39_Erik_Lyna_Helga_324e96df:
    l "嗯……说不好。你能摆个更好看的姿势吗？"

translate schinese story39_Erik_Lyna_Helga_3613b883:
    h "当然宝贝！看好了学。"

translate schinese story39_Erik_Lyna_Helga_689ac584:
    l "太棒了！不过我敢说你可以摆得更性感一点……"

translate schinese story39_Erik_Lyna_Helga_dd7d1437:
    l "拜托，你知道的我说得对！"

translate schinese story39_Erik_Lyna_Helga_2d71265e:
    l "我也该用相机拍几张。"

translate schinese story39_Erik_Lyna_Helga_42413d1b:
    h "那……呃……{size=-5}我已经过了最佳年纪了。"

translate schinese story39_Erik_Lyna_Helga_9630a6b8:
    l "胡说什么呢妈！你完全是当模特的料！"

translate schinese story39_Erik_Lyna_Helga_0e8f4fb1:
    hm "她真这么想……？"

translate schinese story39_Erik_Lyna_Helga_05643506:
    l "你得多练练才行，就像我练瑜伽一样，你懂的？"

translate schinese story39_Erik_Lyna_Helga_3baf19cc:
    h "像这样……？"

translate schinese story39_Erik_Lyna_Helga_a5b8000a:
    l "对！就是要这样！"

translate schinese story39_Erik_Lyna_Helga_fcdf48fe:
    l "呜呼！你太帅了妈！"

translate schinese story39_Erik_Lyna_Helga_fac7344d:
    l "说真的，你看起来……{size=-5}完全是熟女。"

translate schinese story39_Erik_Lyna_Helga_8d9c9113:
    h "嗯，宝贝？熟——什么……？"

translate schinese story39_Erik_Lyna_Helga_c9447dd7:
    l "哎呀！我不小心说出口了吗？我是说，那只是网上的黑话。"

translate schinese story39_Erik_Lyna_Helga_d6fae3cd:
    l "大概就是年轻人觉得成熟女性……特别漂亮！"

translate schinese story39_Erik_Lyna_Helga_1de99424:
    hm "我明白了……"

translate schinese story39_Erik_Lyna_Helga_d5acdf20:
    l "来嘛妈，再来一张，再一张！"

translate schinese story39_Erik_Lyna_Helga_c28073ab:
    em "嗯？她们在干什么？"

translate schinese story39_Erik_Lyna_Helga_8391f02e:
    h "所以你的最终评价是？我觉得今天的走秀就到此为止……"

translate schinese story39_Erik_Lyna_Helga_11846d32:
    em "搞什么？！她疯了吗？！"

translate schinese story39_Erik_Lyna_Helga_c117ac47:
    h "莱娜……？听见我说话了吗？"

translate schinese story39_Erik_Lyna_Helga_762eb708:
    e "妈、妈妈你好好看！"

translate schinese story39_Erik_Lyna_Helga_4be173bb:
    h "哦，你好呀帅哥！做白日梦做完了？"

translate schinese story39_Erik_Lyna_Helga_b002a3de:
    e "对，抱歉。我不能让你们两位女士独享乐趣……"

translate schinese story39_Erik_Lyna_Helga_fa8eb34e:
    h "哈！不过你妹妹还没告诉我她的——"

translate schinese story39_Erik_Lyna_Helga_1e4bc79f:
    e "咳咳！等一下！" with hpunch

translate schinese story39_Erik_Lyna_Helga_093e09f2:
    h "嗯？怎么了宝贝？"

translate schinese story39_Erik_Lyna_Helga_67714043:
    e "没、没什么，我只想说那身衣服你穿着真好看。"

translate schinese story39_Erik_Lyna_Helga_a5539902:
    h "谢谢你，我的儿子……"

translate schinese story39_Erik_Lyna_Helga_592f8993:
    hm "天哪，他看到我的小表演了吗？"

translate schinese story39_Erik_Lyna_Helga_5070cc12:
    hm "好羞耻！我还以为只有他妹妹在看……"

translate schinese story39_Erik_Lyna_Helga_39c0e21d:
    h "儿子，你能不能呃……先去做晚饭？"

translate schinese story39_Erik_Lyna_Helga_2e3cf93b:
    h "我还得给莱娜看看我们给她买的东西……"

translate schinese story39_Erik_Lyna_Helga_451a4eaf:
    l "惊喜？！我就喜欢这个~！"

translate schinese story39_Erik_Lyna_Helga_cc60cc6c:
    h "那件你穿着……太美了，宝贝。"

translate schinese story39_Erik_Lyna_Helga_c9d63d31:
    l "对！我喜欢，妈！谢谢你的小礼物。"

translate schinese story39_Erik_Lyna_Helga_f0c73fc8:
    h "我不想让你整天待在这里、又被冷落了……"

translate schinese story39_Erik_Lyna_Helga_e75cde3d:
    l "喂，那是我自己选的！我说了不用担心。"

translate schinese story39_Erik_Lyna_Helga_88a0ebe0:
    l "你跟埃里克玩得开心吗？"

translate schinese story39_Erik_Lyna_Helga_b08e4a9a:
    h "嗯……？当、当然开心！"

translate schinese story39_Erik_Lyna_Helga_0df469b7:
    l "他乖吗？"

translate schinese story39_Erik_Lyna_Helga_0c532795:
    h "你具体什么意思？"

translate schinese story39_Erik_Lyna_Helga_e9610ed2:
    l "哦，没什么，没什么……随口问问。"

translate schinese story39_Erik_Lyna_Helga_505bdd4c:
    hm "天哪，她穿那些比我好看多了。"

translate schinese story39_Erik_Lyna_Helga_7c7d32f6:
    l "妈，改天我可以教你几个摆姿势的技巧，你知道的吧？"

translate schinese story39_Erik_Lyna_Helga_001c59d5:
    l "拍照可不是我在学校学的唯一东西。"

translate schinese story39_Erik_Lyna_Helga_2215adc1:
    h "好啊，听起来不错。"

translate schinese story39_Erik_Lyna_Helga_db415c48:
    l "那个拍照的事你也考虑一下，好吗？"

translate schinese story39_Erik_Lyna_Helga_04ef84c7:
    h "嗯，那应该挺有意思……"

translate schinese story39_Erik_Lyna_Helga_6244783a:
    l "所以，最终感想？"

translate schinese story39_Erik_Lyna_Helga_bcad9f7f:
    h "我就知道那身很适合你，小南瓜。"

translate schinese story39_Erik_Lyna_Helga_e26d4666:
    h "而且说实话，我觉得这套装你穿着比我还好看。"

translate schinese story39_Erik_Lyna_Helga_8a898fc1:
    l "哇！这从你嘴里说出来可是极高的评价！"

translate schinese story39_Erik_Lyna_Helga_296a0286:
    h "哈哈哈！别这样说……"

translate schinese story39_Erik_Lyna_Helga_c37844e5:
    h "话说，你最近在锻炼吗？"

translate schinese story39_Erik_Lyna_Helga_7ee5768e:
    l "有！而且我现在「好好吃饭」了，别担心。"

translate schinese story39_Erik_Lyna_Helga_7b617689:
    h "喂！那次我那么说只是开玩笑……"

translate schinese story39_Erik_Lyna_Helga_c9ce5c6a:
    l "我知道妈，我只是在逗你！"

translate schinese story39_Erik_Lyna_Helga_88c2b731:
    l "不过说真的，我觉得你做的饭也确实很神奇！"

translate schinese story39_Erik_Lyna_Helga_3f364450:
    l "我真的不想明年再没有你们两个就一个人生活了……"

translate schinese story39_Erik_Lyna_Helga_dc39454e:
    h "嗯，人一旦长大，生活就没那么简单了。"

translate schinese story39_Erik_Lyna_Helga_1223253d:
    h "你会慢慢习惯的，就像我们所有人一样。"

translate schinese story39_Erik_Lyna_Helga_05989b31:
    l "不过至少在那之前，我们已经会创造很多新回忆了！"

translate schinese story39_Erik_Lyna_Helga_19cebad7:
    l "要是我能给你拍更多照片就更多了，嘿嘿~"

translate schinese story39_Erik_Lyna_Helga_57c6bd93:
    l "我也可以教你用相机！埃里克学得很快……"

translate schinese story39_Erik_Lyna_Helga_bf9e9b78:
    l "这样你也能给我拍些好看的照片。"

translate schinese story39_Erik_Lyna_Helga_df435c8c:
    h "咳咳！再说吧……"

translate schinese story39_Erik_Lyna_Helga_4f235a0b:
    h "我们现在过去吧，你哥哥在厨房可能需要帮忙。"

translate schinese story39_Erik_Lyna_Helga_618b16bd:
    centered "{font=font_narration}{cps=25}泳池边的一天……"

translate schinese story39_Erik_Lyna_Helga_606f3837:
    l "埃里克，你作业写了吗？"

translate schinese story39_Erik_Lyna_Helga_7cf18560:
    e "什么……？"

translate schinese story39_Erik_Lyna_Helga_d6278bb7:
    l "妈，她好像有点不开心。"

translate schinese story39_Erik_Lyna_Helga_5fa54525:
    e "我觉得她没事。不是每个人都像你这么无忧无虑的，姐。"

translate schinese story39_Erik_Lyna_Helga_7477d44f:
    l "我也就是说说！她没再叫我去练瑜伽了。"

translate schinese story39_Erik_Lyna_Helga_7126d5a1:
    l "而上次我知道她挺喜欢的，所以也许……"

translate schinese story39_Erik_Lyna_Helga_8f2ef5fc:
    l "{cps=25}你得再给她多一点……"

translate schinese story39_Erik_Lyna_Helga_6ac097c3:
    l "{cps=20}动力……？"

translate schinese story39_Erik_Lyna_Helga_f61099c6:
    centered "{font=font_narration}{cps=25}一个电影之夜……"

translate schinese story39_Erik_Lyna_Helga_9fadb129:
    n "每一次家庭互动，哪怕表面看起来再无害……"

translate schinese story39_Erik_Lyna_Helga_2c9f3a60:
    n "都在助长着他们那些未说出口的欲望之火……"

translate schinese story39_Erik_Lyna_Helga_9209e70c:
    n "营造出一种令人窒息的张力，几乎要把赫尔加拼命抓住的那层脆弱的日常幻象击碎。"

translate schinese story39_Erik_Lyna_Helga_628842db:
    n "即便如此，她还是忍不住以意想不到的方式被自己的儿子吸引。"

translate schinese story39_Erik_Lyna_Helga_8f9e9cbd:
    n "而看着他们在一起……在这狡猾的少女心里开始点燃些什么。"

translate schinese story39_Erik_Lyna_Helga_e5004606:
    n "就像一枚禁果，每过一天就更甜一分。"

translate schinese story39_Erik_Lyna_Helga_a14971e7:
    n "{cps=25}一枚……她迫切想要品尝的果实。"

translate schinese story39_Erik_Lyna_Helga_11a29bca:
    n "日子一天天过去，莱娜的话不断在少年脑海里回响。"

translate schinese story39_Erik_Lyna_Helga_9584b572:
    n "他发现自己被卷进了她那扭曲的游戏……"

translate schinese story39_Erik_Lyna_Helga_087d448d:
    n "一边扮演着孝顺的儿子，一边被那种「母亲变了」的不安感折磨。"

translate schinese story39_Erik_Lyna_Helga_8a25bf4e:
    n "尽管如此，他仍不断提醒她多陪陪妹妹，希望缓解紧张的气氛，也希望她能多一点点开朗。"

translate schinese story39_Erik_Lyna_Helga_6f0aa6b2:
    n "而尽管在女儿提出那个{i}过分亲昵{/i}的要求后赫尔加满心犹豫……"

translate schinese story39_Erik_Lyna_Helga_8baa11bd:
    n "她的儿子实在太有魅力了。"

translate schinese story39_Erik_Lyna_Helga_bb6a1ed2:
    n "埃里克继续演好自己的角色，不断把她们推近，无意中给一场可能吞没所有人的火添着柴。"

translate schinese story39_Erik_Lyna_Helga_8269f4a2:
    n "但这已经不再像他一生中大半时候那样，是为了让她们幸福而做出的无私举动了，不……"

translate schinese story39_Erik_Lyna_Helga_269486e0:
    n "{cps=30}如今有了更深的含义，{w=0.35}一个更险恶的目的……"

translate schinese story39_Erik_Lyna_Helga_d406f924:
    n "{cps=30}一个共同守护的秘密，那个……"

translate schinese story39_Erik_Lyna_Helga_3aefd8b5:
    n "{cps=25}那对发情的双胞胎迫不及待想去探索。"

translate schinese story39_Erik_Lyna_Helga_7e7f9a01:
    n "这对男孩来说是一种获得{i}奖励{/i}的方式。为那些不断侵蚀他曾经纯洁心灵的新情感寻找一个正当的出口。"

translate schinese story39_Erik_Lyna_Helga_9f9000a4:
    n "因为他似乎再也抵抗不住禁忌的诱惑。"

translate schinese story39_Erik_Lyna_Helga_c4e59454:
    centered "{font=font_narration}{size=+10}{cps=20}随着日子模糊成一片，{w=0.35}一种规律渐渐浮现……"

translate schinese story39_Erik_Lyna_Helga_e44b5d48:
    n "母女之间的瑜伽课变成了一种仪式，一场未说出口的欲望彼此厮杀的战场。"

translate schinese story39_Erik_Lyna_Helga_be4e64f5:
    n "莱娜不断把妈妈的底线往前推，乐见她越来越不安。"

translate schinese story39_Erik_Lyna_Helga_926d506f:
    n "但母亲却慢慢学着去接受这种亲近……"

translate schinese story39_Erik_Lyna_Helga_6bab78e6:
    n "因为这是帮助女儿达到她的水平所必需的。"

translate schinese story39_Erik_Lyna_Helga_4a9515de:
    n "至少，赫尔加告诉自己的理由是这样……"

translate schinese story39_Erik_Lyna_Helga_8a2cb3d5:
    centered "{font=font_narration}{cps=25}与此同时，兄妹之间那场危险的游戏仍在继续……"

translate schinese story39_Erik_Lyna_Helga_90200e7c:
    n "而莱娜越来越大胆……"

translate schinese story39_Erik_Lyna_Helga_adb4c013:
    n "但要阻止她已经有点晚了……"

translate schinese story39_Erik_Lyna_Helga_eda6807f:
    n "因为兄妹俩被彼此吸引的程度前所未有。"

translate schinese story39_Erik_Lyna_Helga_ed31df63:
    centered "{font=font_narration}{cps=25}那几乎成了一种无法抗拒的需求……"

translate schinese hscene22_Erik_Lyna_221c0b21:
    nvl_narrator "莱娜 —— 2024年6月28日"

translate schinese hscene22_Erik_Lyna_8b92aed8:
    l_nvl "嘿，我睡不着"

translate schinese hscene22_Erik_Lyna_b0e39664:
    emc_nvl "我也是……"

translate schinese hscene22_Erik_Lyna_2f87b63d:
    l_nvl "真的？为什么呀？"

translate schinese hscene22_Erik_Lyna_678caf10:
    emc_nvl "我满脑子都是你，停不下来。"

translate schinese hscene22_Erik_Lyna_84a7c424:
    nvl_narrator "莱娜正在输入……"

translate schinese hscene22_Erik_Lyna_641c0af5:
    l_nvl "这样有用吗？{image=images/phone/emoji/wink.png} {image=images/phone/photos/LynaSelfie3.png}"

translate schinese hscene22_Erik_Lyna_9b528cfe:
    emc_nvl "哇！你怎么能这么性感？！"

translate schinese hscene22_Erik_Lyna_e854a20a:
    l_nvl "嘿嘿，谢谢！{image=images/phone/emoji/blush1.png}"

translate schinese hscene22_Erik_Lyna_c91fe979:
    l_nvl "介意也给我「搭把手」吗？"

translate schinese hscene22_Erik_Lyna_e40b1356:
    l_nvl "因为我对你也一样……{image=images/phone/photos/LynaSelfie4.png}"

translate schinese hscene22_Erik_Lyna_c8b0d82e:
    e_nvl "好烫……等我一下。"

translate schinese hscene22_Erik_Lyna_f8219b9d:
    nvl_narrator "埃里克正在输入……"

translate schinese hscene22_Erik_Lyna_8f06aa77:
    e_nvl "喜欢这个吗，姐？{image=images/phone/photos/ErikSelfie1.png}"

translate schinese hscene22_Erik_Lyna_c9fbee4d:
    lmc_nvl "啊啊啊！我不敢相信我哥居然敢给我发这个！"

translate schinese hscene22_Erik_Lyna_09343c97:
    e_nvl "谁让你自己要的。"

translate schinese hscene22_Erik_Lyna_91e183d1:
    lmc_nvl "哥，我下面湿透了……"

translate schinese hscene22_Erik_Lyna_b0cb0511:
    e_nvl "我这边也有些「问题」，你看得出来。"

translate schinese hscene22_Erik_Lyna_21b438e5:
    e_nvl "它就是不下去，小莱……"

translate schinese hscene22_Erik_Lyna_fe9c18c0:
    l_nvl "哦～！那我知道你正好需要什么了"

translate schinese hscene22_Erik_Lyna_1118e4df:
    l_nvl "{image=images/phone/photos/LynaSelfie5.png}"

translate schinese hscene22_Erik_Lyna_05e408aa:
    emc_nvl "你快把我搞死了……"

translate schinese hscene22_Erik_Lyna_93df2b9f:
    emc_nvl "我能现在就来你房间吗？"

translate schinese hscene22_Erik_Lyna_1ca6b11f:
    l_nvl "抱歉！今晚不行{image=images/phone/emoji/tongue.png}"

translate schinese hscene22_Erik_Lyna_84a7c424_1:
    nvl_narrator "莱娜正在输入……"

translate schinese hscene22_Erik_Lyna_b8b98a74:
    l_nvl "不过你可以随便看，因为我就喜欢逗你"

translate schinese hscene22_Erik_Lyna_bf966fd0:
    emc_nvl "你太坏了……"

translate schinese hscene22_Erik_Lyna_d9397b4b:
    l_nvl "我才没有！你看，我还有更多礼物给你"

translate schinese hscene22_Erik_Lyna_39de513d:
    l "抱紧点，胖墩！"

translate schinese hscene22_Erik_Lyna_1b8ff45a:
    l "你敢信吗？我正在跟我亲哥哥发色情短信，嘿嘿嘿~"

translate schinese hscene22_Erik_Lyna_7419bca2:
    emc_nvl "小莱？你在吗？"

translate schinese hscene22_Erik_Lyna_de7183e7:
    emc_nvl "我发誓你要是再吊我胃口……"

translate schinese hscene22_Erik_Lyna_9435cf52:
    l_nvl "哦？！那你想怎样啊？嗯？"

translate schinese hscene22_Erik_Lyna_8a67bc1e:
    l_nvl "你会不会急匆匆跑上来用……"

translate schinese hscene22_Erik_Lyna_64db0c11:
    l_nvl "这个？{image=images/phone/photos/LynaSelfie6.png}"

translate schinese hscene22_Erik_Lyna_9aa98e5b:
    lm "因为我不介意他用。"

translate schinese hscene22_Erik_Lyna_89df3186:
    lm "如果他强行进入我，进入我那稚嫩的小穴……"

translate schinese hscene22_Erik_Lyna_2675a337:
    e_nvl "哇……"

translate schinese hscene22_Erik_Lyna_317c200d:
    lmc_nvl "你说呢？{image=images/phone/emoji/wink.png}"

translate schinese hscene22_Erik_Lyna_b2a24858:
    e_nvl "难以置信。你不刮毛了？"

translate schinese hscene22_Erik_Lyna_4e099f31:
    lmc_nvl "才不！我从……某人那儿学的"

translate schinese hscene22_Erik_Lyna_bd61caf6:
    e_nvl "我受不了了，姐，你看……"

translate schinese hscene22_Erik_Lyna_4d362466:
    e_nvl "{image=images/phone/photos/ErikSelfie2.png}"

translate schinese hscene22_Erik_Lyna_bb639f05:
    l_nvl "天啊！你终于用上我送的礼物了{image=images/phone/emoji/eyes.png}"

translate schinese hscene22_Erik_Lyna_1da838cb:
    emc_nvl "把你的脏内裤留在我房间里……真坏。"

translate schinese hscene22_Erik_Lyna_d022fbfb:
    emc_nvl "你这个坏妹妹，知不知道！"

translate schinese hscene22_Erik_Lyna_89e385c0:
    l_nvl "能怪我吗？只要你在旁边我就硬得不行"

translate schinese hscene22_Erik_Lyna_07ba2179:
    l_nvl "我的内裤摸起来软不软呀？"

translate schinese hscene22_Erik_Lyna_a9699903:
    l_nvl "就那样把你的硬鸡巴裹得严严实实"

translate schinese hscene22_Erik_Lyna_d85d0b03:
    emc_nvl "嗯，爽极了……"

translate schinese hscene22_Erik_Lyna_a3c6a199:
    l_nvl "现在再想象一下真的会有多棒"

translate schinese hscene22_Erik_Lyna_df753574:
    l_nvl "{image=images/phone/photos/LynaSelfie7.png}"

translate schinese hscene22_Erik_Lyna_85c833ce:
    l_nvl "我敢打赌你现在一定又想摸我了"

translate schinese hscene22_Erik_Lyna_e0fd7d1f:
    emc_nvl "你根本不知道……"

translate schinese hscene22_Erik_Lyna_ace919d6:
    l_nvl "告诉我，你想对我做什么？"

translate schinese hscene22_Erik_Lyna_b74eaec4:
    l_nvl "对这副紧致又可爱的身体？{image=images/phone/emoji/hot.png}{image=images/phone/emoji/hot.png}{image=images/phone/photos/LynaSelfie8.png}"

translate schinese hscene22_Erik_Lyna_8ff36d11:
    e_nvl "该死……我好想吻你。"

translate schinese hscene22_Erik_Lyna_436c58dc:
    e_nvl "我还想再摸一次。"

translate schinese hscene22_Erik_Lyna_ad914f6a:
    lmc_nvl "你这个坏男孩{image=images/phone/emoji/devil.png}"

translate schinese hscene22_Erik_Lyna_61da9009:
    lmc_nvl "真对不起……是我让你上瘾了我这对小奶子！"

translate schinese hscene22_Erik_Lyna_a3bae9b4:
    e_nvl "可我爱它们……"

translate schinese hscene22_Erik_Lyna_695f5508:
    lmc_nvl "不过你不想再探索点别的吗？"

translate schinese hscene22_Erik_Lyna_4da05518:
    lmc_nvl "也许你可以摸摸我的阴毛有多软"

translate schinese hscene22_Erik_Lyna_1db0cd47:
    e_nvl "好！求你说点脏话……"

translate schinese hscene22_Erik_Lyna_84a7c424_2:
    nvl_narrator "莱娜正在输入……"

translate schinese hscene22_Erik_Lyna_880b4229:
    lmc_nvl "感受你妹妹的阴毛是怎么长出来的……"

translate schinese hscene22_Erik_Lyna_b9ea7fbd:
    lmc_nvl "只给你看，我亲爱的双胞胎"

translate schinese hscene22_Erik_Lyna_802aa43f:
    emc_nvl "小莱，我马上就到！"

translate schinese hscene22_Erik_Lyna_088f7503:
    l_nvl "我真的对你有那么大的影响力吗？？ {image=images/phone/emoji/heartred.png}"

translate schinese hscene22_Erik_Lyna_c4f2951b:
    emc_nvl "是的。我爱你的小小身体爱得不得了。"

translate schinese hscene22_Erik_Lyna_2789ec8d:
    l_nvl "那就来啊，继续用我穿过的内裤自慰……"

translate schinese hscene22_Erik_Lyna_34e1d7c5:
    l_nvl "然后把一大坨精射得到处都是"

translate schinese hscene22_Erik_Lyna_867ed105:
    l_nvl "我要你把你的精液好好盖满它们！"

translate schinese hscene22_Erik_Lyna_d05bf0dc:
    emc_nvl "好的姐！我要射在它们上面……"

translate schinese hscene22_Erik_Lyna_e508d5d1:
    emc_nvl "射在你的脏内裤上！"

translate schinese hscene22_Erik_Lyna_1c5e3cff:
    l_nvl "操对！如果你一直这么大胆，也许有一天我会让你……"

translate schinese hscene22_Erik_Lyna_1af5e498:
    l_nvl "拥有这个 {image=images/phone/photos/LynaSelfie9.png}"

translate schinese story40_Erik_Lyna_Helga_00a475f7:
    centered "{font=font_narration}{size=+10}{cps=20}一天又一天，{w=0.35}慢慢地屈从……"

translate schinese story40_Erik_Lyna_Helga_029f76fe:
    n "对双胞胎妹妹那份深沉的渴望正在吞噬埃里克。"

translate schinese story40_Erik_Lyna_Helga_b7159d1d:
    n "不过他心里想的还不止这些……"

translate schinese story40_Erik_Lyna_Helga_5a970465:
    n "可他对自己妈妈在那个可耻夜晚犯下的逾矩依然一无所知……"

translate schinese story40_Erik_Lyna_Helga_3f476953:
    n "可他发现自己被夹在了中间，身体一次又一次用不受欢迎的勃起背叛了他。"

translate schinese story40_Erik_Lyna_Helga_5e8b6e9b:
    n "随着家庭里的紧张升级，赫尔加只能在漫长而独自一人的沐浴中寻求慰藉。"

translate schinese story40_Erik_Lyna_Helga_64859c96:
    n "她想象自己回到了前夫的怀抱，在那些更单纯时光的回忆里寻找慰藉。"

translate schinese story40_Erik_Lyna_Helga_b3f37ba7:
    n "但不可避免地，儿子总会闯进她的思绪；他羞涩的笑容，他无辜触碰的温暖……"

translate schinese story40_Erik_Lyna_Helga_f53fbe62:
    centered "{font=font_narration}{cps=25}那个夜晚的罪孽……"

translate schinese story40_Erik_Lyna_Helga_fc2ff41d:
    n "而她会颤抖着留在原地，满心愧疚，还有一种她无法理解的渴望；她拼命想把它压下去。"

translate schinese story40_Erik_Lyna_Helga_d221aebc:
    n "她不断告诉自己，那一夜不过是一时软弱，是想缓解压力、应对孤独的错误尝试……"

translate schinese story40_Erik_Lyna_Helga_4b698ec2:
    centered "{font=font_narration}{cps=20}可心底深处，{w=0.35}她知道那不只是这样。"

translate schinese story40_Erik_Lyna_Helga_49da14a4:
    l "啊……这次练习太舒服了！"

translate schinese story40_Erik_Lyna_Helga_c1bc09e9:
    l "妈，你没事吧？"

translate schinese story40_Erik_Lyna_Helga_9e37c344:
    h "没事亲爱的。别担心，没什么。"

translate schinese story40_Erik_Lyna_Helga_0cf54ffe:
    l "哼，但愿吧……"

translate schinese story40_Erik_Lyna_Helga_99229c36:
    l "话说，你还记得我们第一天练瑜伽时我说过什么吗？"

translate schinese story40_Erik_Lyna_Helga_ae8597e2:
    h "嗯？说了什么？"

translate schinese story40_Erik_Lyna_Helga_e36d0440:
    l "就是关于……{i}那件事{/i}。"

translate schinese story40_Erik_Lyna_Helga_ccb6f990:
    h "有话直说吧。我今天可没心情猜谜。"

translate schinese story40_Erik_Lyna_Helga_8280db87:
    l "真是的，好吧！就是我说的关于……"

translate schinese story40_Erik_Lyna_Helga_a9b9d487:
    l "{cps=25}陪你一起洗澡……"

translate schinese story40_Erik_Lyna_Helga_df823d00:
    h "{size=+5}莱娜！你认真的？！"

translate schinese story40_Erik_Lyna_Helga_6bb18d42:
    h "你当时说只是在开玩笑，对吧？"

translate schinese story40_Erik_Lyna_Helga_dd86d951:
    h "我们都知道那样不合适……尤其在你这个年纪。"

translate schinese story40_Erik_Lyna_Helga_050ee174:
    l "我知道妈，我知道。可……你洗澡的时候不寂寞吗？"

translate schinese story40_Erik_Lyna_Helga_621d3c5b:
    l "你一直锁着门，在里面待好久好久。"

translate schinese story40_Erik_Lyna_Helga_78960e3c:
    l "而且你看我们的眼神总是那么……奇怪，还……{size=-5}我也说不上来。"

translate schinese story40_Erik_Lyna_Helga_9fcf1a24:
    l "就像你在躲着我们，我很担心。"

translate schinese story40_Erik_Lyna_Helga_b4f45a6b:
    h "哎呀，小南瓜……我说过不用担心我。"

translate schinese story40_Erik_Lyna_Helga_170bff61:
    h "你们知道我有多爱你们两个，可是……"

translate schinese story40_Erik_Lyna_Helga_245334d8:
    h "我只是想偶尔享一会儿清静，你懂吧？放松一下、减轻压力对我很重要。"

translate schinese story40_Erik_Lyna_Helga_df9fb1e2:
    lm "该死。她不信。"

translate schinese story40_Erik_Lyna_Helga_ca49ff2c:
    l "好吧。但要是一起进去不是更有意思吗？"

translate schinese story40_Erik_Lyna_Helga_536f62f6:
    l "我们可以聊天、做发型，说不定还能互相擦背！"

translate schinese story40_Erik_Lyna_Helga_e435bf27:
    l "就像闺蜜之夜……只不过是在浴缸里！"

translate schinese story40_Erik_Lyna_Helga_ab237017:
    h "莱娜，那不是——"

translate schinese story40_Erik_Lyna_Helga_9b32b4d5:
    l "总比你一个人闷着胡思乱想好多了，对吧？"

translate schinese story40_Erik_Lyna_Helga_6c5b0333:
    hm "她跟我一样执著，这点我承认。还有那个表情……"

translate schinese story40_Erik_Lyna_Helga_734c834a:
    hm "跟她说服我给她买贵东西时一模一样。天哪，这女孩真黏人……"

translate schinese story40_Erik_Lyna_Helga_1c9370c0:
    h "宝贝，谢谢你的心意和热情，可是……"

translate schinese story40_Erik_Lyna_Helga_c9b91e24:
    h "我还是想一个人洗，好吗？"

translate schinese story40_Erik_Lyna_Helga_6533ac2d:
    l "哎呀妈~！就这一次，求你了？"

translate schinese story40_Erik_Lyna_Helga_b4b3c26a:
    h "亲爱的，我……{size=-5}我不知道……"

translate schinese story40_Erik_Lyna_Helga_422fea13:
    l "我保证超好玩！求求你了~？"

translate schinese story40_Erik_Lyna_Helga_2f254779:
    h "不行……我们不能。抱歉。"

translate schinese story40_Erik_Lyna_Helga_e1c0c14c:
    l "好吧好吧。那我不施压了。"

translate schinese story40_Erik_Lyna_Helga_0fde5520:
    l "不过你哪天改主意了，就知道去哪儿找我了！"

translate schinese story40_Erik_Lyna_Helga_a0908c66:
    lm "行吧，妈妈，先吊着我……"

translate schinese story40_Erik_Lyna_Helga_4e0cf0e3:
    lm "但我也绝不会放弃你。我已经陷得太深了。"

translate schinese story40_Erik_Lyna_Helga_d88234bb:
    lm "很快，就只剩我们两个，皮肤贴着皮肤……"

translate schinese story40_Erik_Lyna_Helga_fad67cbc:
    lm "而你将无法抗拒我。"

translate schinese story40_Erik_Lyna_Helga_74c51901:
    n "但挣扎的可不止赫尔加一个……"

translate schinese story40_Erik_Lyna_Helga_2ed0bc84:
    n "仍被母亲那「医疗式」的触碰记忆纠缠，埃里克躲进了熟悉的东西里。"

translate schinese story40_Erik_Lyna_Helga_2ac1f2f7:
    n "「熟悉的东西」，当然是指他双胞胎妹妹的陪伴。"

translate schinese story40_Erik_Lyna_Helga_93c9cdf6:
    n "他沉溺于两人那套放荡的日常带来的安慰中，努力去忘记……"

translate schinese story40_Erik_Lyna_Helga_39cc3113:
    n "试图说服自己，妈妈那样照顾他不过是一桩奇怪的异常。"

translate schinese story40_Erik_Lyna_Helga_6aa6e61f:
    n "不过是一个离异女人在对抗严重孤独时犯下的小小疏忽。"

translate schinese story40_Erik_Lyna_Helga_81eb0a68:
    n "相比之下，妹妹只是为了他们共同的幸福帮他，毫无恶意……"

translate schinese story40_Erik_Lyna_Helga_b039e1c4:
    n "母亲对他而言是神圣的、不可侵犯的禁区；他绝不能用那些邪恶的念头去玷污她。"

translate schinese story40_Erik_Lyna_Helga_524f640f:
    n "于是，和莱娜的那些乱伦缠绵成了他最黑暗欲望的出口……"

translate schinese story40_Erik_Lyna_Helga_e6b8f624:
    n "因为这个男孩仍无法想象，自己竟会对赋予他生命的女人产生性吸引。"

translate schinese story40_Erik_Lyna_Helga_fba1a32c:
    centered "{font=font_narration}{cps=25}而他对此的抗拒如此强烈，{w=0.35}以至于……"

translate schinese story40_Erik_Lyna_Helga_5f533e71:
    n "反倒是把自己妹妹那张小嘴灌满，成了日常。"

translate schinese story40_Erik_Lyna_Helga_c08912e6:
    n "在他混乱的脑海里……这样做甚至不如一个带着暗示意味的母亲的抚弄。"

translate schinese story40_Erik_Lyna_Helga_e20e3c64:
    centered "{font=font_narration}{size=+10}{cps=20}然而，{w=0.35}即便过了好几天都专注于莱娜……"

translate schinese story40_Erik_Lyna_Helga_de01c103:
    n "他的目光还是无法从妈妈身上移开。"

translate schinese story40_Erik_Lyna_Helga_49ccc3ef:
    n "她香水的气味，她走动的姿态……"

translate schinese story40_Erik_Lyna_Helga_5c0037ca:
    n "哪怕只是她那平静嗓音的声音，就足以让他脊背发凉好几次。"

translate schinese story40_Erik_Lyna_Helga_74f39cd9:
    n "埃里克发现自己盯着她看得远比平常久，毫不掩饰……"

translate schinese story40_Erik_Lyna_Helga_121afda4:
    n "把她那迷人曲线的每一处细节都看进眼里。"

translate schinese story40_Erik_Lyna_Helga_cfe6411c:
    n "而即便被她发现，也没有惩罚，只有温柔。"

translate schinese story40_Erik_Lyna_Helga_32e0abfa:
    n "这个早已心乱如麻的少年仍在与自己的道德作战，而那场战役他毫无胜算。"

translate schinese story40_Erik_Lyna_Helga_e95bfc73:
    em "我满脑子都是妈。都是那个周末发生的事……"

translate schinese story40_Erik_Lyna_Helga_f5b880ea:
    em "她跟我聊我的勃起，就像那不是什么难为情的事！"

translate schinese story40_Erik_Lyna_Helga_466cb8f0:
    em "而且现在我盯着她看，她好像都无所谓了！"

translate schinese story40_Erik_Lyna_Helga_6988a3d5:
    em "她的手为什么总是他妈摸那么久？！"

translate schinese story40_Erik_Lyna_Helga_20dafd33:
    em "可更糟的是，那天她摸了我的鸡巴时……"

translate schinese story40_Erik_Lyna_Helga_29788da3:
    em "那看起来可不像只是她「治疗」的一部分……"

translate schinese story40_Erik_Lyna_Helga_af170188:
    n "而赫尔加则被困在自己亲手筑起的牢笼里。"

translate schinese story40_Erik_Lyna_Helga_edfbebed:
    n "她发现自己不断被儿子吸引，同时又害怕着他的靠近。"

translate schinese story40_Erik_Lyna_Helga_67221f74:
    n "他赤裸的身体贴着她的触感，他先射液留在她手心的黏滑……这些记忆始终纠缠着她。"

translate schinese story40_Erik_Lyna_Helga_de720c5b:
    n "以至于连最平常的互动都带上了一种令人不适的紧张感。"

translate schinese story40_Erik_Lyna_Helga_b9f11c69:
    n "而每一次她撇开忧虑、任由他再次盯着看，羞愧就会一阵阵冲上来。"

translate schinese story40_Erik_Lyna_Helga_d78cb806:
    n "提醒着她已经越过了那条危险的线……"

translate schinese story40_Erik_Lyna_Helga_c6586a76:
    centered "{font=font_narration}{cps=25}提醒着她心里揣着那个可怕的秘密。"

translate schinese story40_Erik_Lyna_Helga_a88fac2e:
    n "她试着转而专注地和莱娜重新亲近，做回女儿一直需要的那种母亲……"

translate schinese story40_Erik_Lyna_Helga_67bfee9a:
    n "可一天又一天，她的思绪总漂回和儿子共度的那个夜晚……"

translate schinese story40_Erik_Lyna_Helga_efabebc6:
    n "回到那个令她震惊的认知——自己潜意识里的渴望。"

translate schinese story40_Erik_Lyna_Helga_23c5fe45:
    hm "{size=+5}不！我为什么总在想这个？！"

translate schinese story40_Erik_Lyna_Helga_67448116:
    hm "{size=+5}我永远不能告诉任何人，所以我必须忘掉！我必须！"

translate schinese story40_Erik_Lyna_Helga_7a22da91:
    hm "我不能失去他。{size=-5}我不能两个都失去……"

translate schinese hscene23_Lyna_Helga_d62d7d7a:
    l "妈妈？你在里面吗？"

translate schinese hscene23_Lyna_Helga_d76c4bd3:
    h "{size=-5}莱、莱娜？！怎么了，宝贝？"

translate schinese hscene23_Lyna_Helga_f24bcabe:
    l "出什么事了吗？你今天结束瑜伽的时候那么急……"

translate schinese hscene23_Lyna_Helga_2b523fec:
    hm "她说得对。我一直在这些浴缸里寻求庇护……"

translate schinese hscene23_Lyna_Helga_d7534444:
    hm "而且不只是为了清静。是因为你们让我想起了那些回忆，那个已不复存在的人生的幽灵。"

translate schinese hscene23_Lyna_Helga_e378321d:
    hm "更重要的是，你们父亲的手贴在我皮肤上的温度，他充满爱意的拥抱，他嘴唇贴在我唇上的感觉……"

translate schinese hscene23_Lyna_Helga_ea60d2f7:
    hm "他那样对我之后，我居然还在想念你爸爸，真是难以置信。"

translate schinese hscene23_Lyna_Helga_2ca658fb:
    hm "但更糟的是，{size=-5}前几晚……"

translate schinese hscene23_Lyna_Helga_aa22020a:
    hm "我居然梦见了你哥哥！那双天真的眼睛。"

translate schinese hscene23_Lyna_Helga_08778940:
    hm "天啊，我这是怎么了？我简直一团糟。"

translate schinese hscene23_Lyna_Helga_a23ed871:
    l "{size=-5}妈妈？你还在吗？"

translate schinese hscene23_Lyna_Helga_26d4b063:
    h "在、在！对不起宝贝。我正准备脱衣服洗澡……"

translate schinese hscene23_Lyna_Helga_01ff6579:
    lm "时间刚刚好！嘿嘿嘿~"

translate schinese hscene23_Lyna_Helga_24a785c1:
    l "{size=-5}妈妈……我、我能进来吗？我……我真的需要跟你谈谈。"

translate schinese hscene23_Lyna_Helga_75187ec3:
    hm "她的声音听起来在发抖。她是在生我的气吗？"

translate schinese hscene23_Lyna_Helga_bf99da37:
    hm "我不能像以前那样一直推开她！她是我女儿！"

translate schinese hscene23_Lyna_Helga_2fa27552:
    hm "不管怎样我都得在她身边。"

translate schinese hscene23_Lyna_Helga_5c9d55da:
    h "好吧，宝贝。进来吧……"

translate schinese hscene23_Lyna_Helga_797819ab:
    l "嘿，你还好吗？"

translate schinese hscene23_Lyna_Helga_c0af60b7:
    h "嗯……"

translate schinese hscene23_Lyna_Helga_8c64c914:
    l "听着，我……我……对不起，为了所有事。"

translate schinese hscene23_Lyna_Helga_2681a713:
    l "为了这些年这么难搞，为了……总是把你推开。"

translate schinese hscene23_Lyna_Helga_d93d0bbb:
    h "莱娜，怎么了？"

translate schinese hscene23_Lyna_Helga_52f40048:
    l "只是……我觉得自己好迷茫。爸爸走了，而你……又有点疏远我了。"

translate schinese hscene23_Lyna_Helga_24fb7ef8:
    l "我只想一切回到从前，我们还是一家人的时候……"

translate schinese hscene23_Lyna_Helga_41228f34:
    h "唉……没事的，亲爱的。我在这儿。我们会一起挺过去的。"

translate schinese hscene23_Lyna_Helga_4308e435:
    l "妈妈……我可以留下来陪你吗？就待一会儿说说话。"

translate schinese hscene23_Lyna_Helga_9c8b9fc8:
    hm "好，也许这对我也有帮助……让我忘掉一切，重新感觉正常。"

translate schinese hscene23_Lyna_Helga_36b8d00a:
    h "当然。过来。"

translate schinese hscene23_Lyna_Helga_bf561545:
    l "你真正感觉怎么样？我知道你也在经历很多，妈妈。"

translate schinese hscene23_Lyna_Helga_fe52d2ef:
    h "莱娜，宝贝，你不用操心我。我说了我没事。"

translate schinese hscene23_Lyna_Helga_bc32c988:
    l "不，你不好！我在你眼睛里看得出来……你很悲伤。很孤单。"

translate schinese hscene23_Lyna_Helga_d324e5e8:
    l "而且我觉得这有我的责任！"

translate schinese hscene23_Lyna_Helga_4dedac49:
    h "不是——"

translate schinese hscene23_Lyna_Helga_f4fc36bd:
    l "我真希望我们之间能不一样。我十几岁初期对你那么刻薄……"

translate schinese hscene23_Lyna_Helga_a56d3e1c:
    h "嘿！你在说什么？！别那样说自己，求你了！"

translate schinese hscene23_Lyna_Helga_a03119e4:
    l "{size=-5}但那是真的……"

translate schinese hscene23_Lyna_Helga_6b3448ea:
    h "不是！你还是我女儿，我的小天使……"

translate schinese hscene23_Lyna_Helga_27bc5655:
    h "你知道不管怎样我都会永远爱你。"

translate schinese hscene23_Lyna_Helga_d87beca7:
    h "如果我不懂得原谅，那我算什么母亲？"

translate schinese hscene23_Lyna_Helga_f163ce69:
    l "嗯……"

translate schinese hscene23_Lyna_Helga_1b8bc2d2:
    l "妈妈，我想跟你更亲近。我想……{size=-5}我不知道……{/size}跟你分享一些事。把失去的时间补回来。"

translate schinese hscene23_Lyna_Helga_bf7c8ff1:
    l "所以今天我们……一起洗澡，你同意吗？"

translate schinese hscene23_Lyna_Helga_2fce7b66:
    l "我们可以聊聊天，放松一下……也许能让我们两个都感觉好些。"

translate schinese hscene23_Lyna_Helga_5c096a40:
    hm "真的？！她为什么又提洗澡的事？"

translate schinese hscene23_Lyna_Helga_5f075f28:
    hm "所以她才想进来？她真的那么热衷吗？"

translate schinese hscene23_Lyna_Helga_a9b93283:
    l "妈妈……我最近心情特别低落。"

translate schinese hscene23_Lyna_Helga_3f5b712f:
    l "真的是所有事。家庭、学业、男生……什么都算。"

translate schinese hscene23_Lyna_Helga_dd03cf0e:
    l "那会很舒服的，妈妈。{size=-5}你想想看……"

translate schinese hscene23_Lyna_Helga_a3c82b44:
    hm "和她一起洗澡。水，还有亲近……听起来确实很诱人。"

translate schinese hscene23_Lyna_Helga_94af3985:
    hm "我们已经很久没一起洗过了。让我有些怀念。"

translate schinese hscene23_Lyna_Helga_c25e574a:
    hm "但这是正确的做法吗？万一我——"

translate schinese hscene23_Lyna_Helga_376f2121:
    hm "不！我不能让自己的恐惧支配我的行为！我女儿需要我，也许……也许我也需要有人陪。"

translate schinese hscene23_Lyna_Helga_7221f8d2:
    hm "她只是想像任何女儿那样想亲近母亲。我不该拒绝她。过去我已经疏忽她太多次了。"

translate schinese hscene23_Lyna_Helga_adfe0eb9:
    h "好吧宝贝，我们可以一起洗澡。"

translate schinese hscene23_Lyna_Helga_a4879cf8:
    h "我觉得你在瑜伽里这么拼命，值得一点奖励，对吧？"

translate schinese hscene23_Lyna_Helga_ef299a1f:
    l "{size=+5}耶~！谢谢、谢谢、谢谢！" with vpunch

translate schinese hscene23_Lyna_Helga_cceb2909:
    h "就这一次，听见了吗？"

translate schinese hscene23_Lyna_Helga_ba247506:
    l "好！谢谢妈妈！你不会后悔的！"

translate schinese hscene23_Lyna_Helga_5cc29ddd:
    l "不过……你真的完全确定这是个好主意吗？"

translate schinese hscene23_Lyna_Helga_61253179:
    h "你什么意思，宝贝？一直问的人可是你啊。"

translate schinese hscene23_Lyna_Helga_6b981e8e:
    l "可是前几天你不愿意……"

translate schinese hscene23_Lyna_Helga_808d2600:
    l "还有你说的那些关于界限、关于适当接触的话……"

translate schinese hscene23_Lyna_Helga_daafb012:
    l "我不想再让你不自在了。"

translate schinese hscene23_Lyna_Helga_64ac7914:
    hm "她的声音听起来……很真诚。还是这只是她的另一个花招？"

translate schinese hscene23_Lyna_Helga_418851e3:
    hm "不，我想相信她！我必须相信她。"

translate schinese hscene23_Lyna_Helga_3847e312:
    hm "她大概也觉得寂寞。她那个哥哥对我来说仍是个谜。"

translate schinese hscene23_Lyna_Helga_eaeb8fef:
    hm "据我所知，她从来没认真谈过恋爱。对她来说肯定很难，青春期激素乱窜什么的……"

translate schinese hscene23_Lyna_Helga_f5d45e35:
    l "是我的请求让你不高兴了吗？对不起妈妈！"

translate schinese hscene23_Lyna_Helga_d2ae41c0:
    l "我不喜欢你对我生气。{size=-5}你一生气我就特别内疚……"

translate schinese hscene23_Lyna_Helga_3113cf44:
    h "别傻了，宝贝。我没生气。"

translate schinese hscene23_Lyna_Helga_de1c431e:
    h "只是洗个澡嘛。像你说的，放松一下聊聊天，对吧？"

translate schinese hscene23_Lyna_Helga_2e98f474:
    l "好、好的。当然，妈妈。"

translate schinese hscene23_Lyna_Helga_41316ead:
    h "你先脱衣服吧？我马上就来。"

translate schinese hscene23_Lyna_Helga_289c5806:
    hm "冷静点，赫尔加。这只是我们母女之间的一项活动。"

translate schinese hscene23_Lyna_Helga_bd485806:
    lm "和妈妈共浴，赤裸相对，感受她身体贴在我身上的温度……"

translate schinese hscene23_Lyna_Helga_f75572e2:
    lm "这不是我想要的吗？为什么我突然这么紧张？"

translate schinese hscene23_Lyna_Helga_36f552ee:
    l "我要不要去拿件……比、比基尼什么的？"

translate schinese hscene23_Lyna_Helga_6c378595:
    h "什么？哦小南瓜，你真逗！"

translate schinese hscene23_Lyna_Helga_5ecbc4a1:
    h "只是我们两个女人，没什么好害羞的。"

translate schinese hscene23_Lyna_Helga_8c5df2f7:
    l "对……对！我真傻，我刚才在想什么啊？"

translate schinese hscene23_Lyna_Helga_e208665a:
    lm "该死，我没想到她这么急切。"

translate schinese hscene23_Lyna_Helga_6cff0917:
    lm "操，这太疯狂了！我居然真的说服她了？！"

translate schinese hscene23_Lyna_Helga_6f5d4746:
    hm "她是在害羞作态？还是真的难为情？"

translate schinese hscene23_Lyna_Helga_055c98ab:
    hm "我完全看不透她。但也许……是我想太多了。"

translate schinese hscene23_Lyna_Helga_8fac67df:
    hm "这只是和女儿亲近的无害好方式，对吧。"

translate schinese hscene23_Lyna_Helga_8a621d0c:
    hm "但如果不是呢？万一……万一她想要——"

translate schinese hscene23_Lyna_Helga_a48663f6:
    hm "不！我必须做。为了她，也为了我。"

translate schinese hscene23_Lyna_Helga_9bee31d5:
    hm "也许这样我就能弄清她真正的意图……"

translate schinese hscene23_Lyna_Helga_894b55c5:
    hm "她最近实在太过分了。还有她那个请求……我还是不敢相信我竟然让她那样摸我的胸。"

translate schinese hscene23_Lyna_Helga_9541f08c:
    hm "但如果她只是想让我们更亲近，那就不会有奇怪的事发生。"

translate schinese hscene23_Lyna_Helga_8c091260:
    hm "只是两个女人一起洗澡、亲近。就像……"

translate schinese hscene23_Lyna_Helga_e522e9b0:
    hm "{cps=25}就像很多年前那样……{size=-5}和我的——"

translate schinese hscene23_Lyna_Helga_e94fbb80:
    lm "我就知道！她完全在看！"

translate schinese hscene23_Lyna_Helga_0daf5d56:
    lm "妈妈，你根本不知道自己正踏进什么。"

translate schinese hscene23_Lyna_Helga_98d7a5d1:
    lm "让你尝尝这个……"

translate schinese hscene23_Lyna_Helga_57b6f6d2:
    hm "天啊……她就光着身子站在我面前！"

translate schinese hscene23_Lyna_Helga_e91be435:
    hm "我的心肝宝贝，我十八岁的女儿。那是我亲手塑造的……"

translate schinese hscene23_Lyna_Helga_94865f2b:
    l "喂？妈妈……？"

translate schinese hscene23_Lyna_Helga_c733166a:
    hm "天啊，这身材真可爱！她的锻炼真的很有成效。"

translate schinese hscene23_Lyna_Helga_df869111:
    hm "她的胸部还是比不上我的，但我就喜欢这种尖尖的形状。"

translate schinese hscene23_Lyna_Helga_946aa30b:
    hm "不过发育得相当不错。上次我看到她裸体的时候，它们都还没成形……"

translate schinese hscene23_Lyna_Helga_4ae0070a:
    hm "她正在长成一个美丽的年轻女子。我真骄傲！"

translate schinese hscene23_Lyna_Helga_eca6a26a:
    l "我们到底洗不洗？还是你要在那儿站一整天……？"

translate schinese hscene23_Lyna_Helga_b0567ad9:
    hm "她怎么能这么可爱？！"

translate schinese hscene23_Lyna_Helga_abf4171c:
    lm "嗯？感觉她根本没在听我说话！"

translate schinese hscene23_Lyna_Helga_56133cee:
    lm "妈妈眼睛都挪不开我了，对吧？哈哈！"

translate schinese hscene23_Lyna_Helga_defbcb6a:
    l "妈、妈妈求你了……别再盯着看了！{size=-5}太尴尬了。"

translate schinese hscene23_Lyna_Helga_14a8e792:
    h "非常抱歉小南瓜！只是……{size=-5}呃……{/size}你，我是说……我——"

translate schinese hscene23_Lyna_Helga_1e5e893b:
    l "嘻嘻~！骗到你了！我开玩笑的，妈妈。"

translate schinese hscene23_Lyna_Helga_4831582b:
    h "什、什么……？"

translate schinese hscene23_Lyna_Helga_3a723daf:
    l "我刚才基本就是在给你摆姿势啊，笨蛋！"

translate schinese hscene23_Lyna_Helga_651de61e:
    l "我在自己妈妈面前有什么好害羞的？太傻了！"

translate schinese hscene23_Lyna_Helga_41c9099a:
    l "事实上……你想怎么看都行。我不介意。"

translate schinese hscene23_Lyna_Helga_bf6aec32:
    hm "天啊！她真的刚才那样说了？！"

translate schinese hscene23_Lyna_Helga_456c4d70:
    l "你不说出口也没关系，不过你那么喜欢我的身体我很高兴。"

translate schinese hscene23_Lyna_Helga_568b7d3c:
    l "这让人很安心……嘿嘿嘿~"

translate schinese hscene23_Lyna_Helga_727c70fe:
    hm "她说的这些话，摆的这些姿势……她根本不在乎！"

translate schinese hscene23_Lyna_Helga_281a3462:
    hm "我真是佩服！她怎么能在我面前这么大胆？！"

translate schinese hscene23_Lyna_Helga_3fff10ed:
    hm "她和哥哥是双胞胎，但在这方面还是差得远。"

translate schinese hscene23_Lyna_Helga_ba112cea:
    l "{size=+5}快点，快点嘛！快脱衣服！" with vpunch

translate schinese hscene23_Lyna_Helga_fffc1296:
    hm "这感觉……怪怪的。我到底为什么要答应？"

translate schinese hscene23_Lyna_Helga_f28698cc:
    hm "就好像我在跨越一条我知道不该跨的界线。"

translate schinese hscene23_Lyna_Helga_10154366:
    hm "但如果我女儿完全没问题，我为什么要犹豫……？"

translate schinese hscene23_Lyna_Helga_8c987ec3:
    l "怎么了？我的身体有什么问题吗？是那样吗？"

translate schinese hscene23_Lyna_Helga_8b4c933b:
    h "不不！当然没有。你很美……"

translate schinese hscene23_Lyna_Helga_eac32eff:
    l "那磨蹭什么……妈妈？你该不会是害羞了吧！"

translate schinese hscene23_Lyna_Helga_9abb175d:
    h "我……才没有！我们以前很多次都互相看光过。"

translate schinese hscene23_Lyna_Helga_4dc1439a:
    lm "我多希望能把那些事记得清清楚楚！"

translate schinese hscene23_Lyna_Helga_ee8da498:
    hm "但她已经不再是小女孩了。她现在是个成熟的女人，而——"

translate schinese hscene23_Lyna_Helga_0ef4dc7f:
    hm "{size=+5}天啊，我这是怎么了？！清醒一点！"

translate schinese hscene23_Lyna_Helga_517e681b:
    l "水舒服极了，妈妈。你快点！"

translate schinese hscene23_Lyna_Helga_67b68dfe:
    l "而且说真的，你要真去拿比基尼我也不介意……"

translate schinese hscene23_Lyna_Helga_4d1ff970:
    l "我说过了，我不想让你因为我而不自在。"

translate schinese hscene23_Lyna_Helga_2faa0c42:
    h "你刚在我面前那样脱完衣服？！想都别想，小姐！"

translate schinese hscene23_Lyna_Helga_2a3745d3:
    hm "可我为什么这么紧张？我很少紧张啊！"

translate schinese hscene23_Lyna_Helga_5e8cd194:
    lm "终于！她要脱了！我能好好看看她了……"

translate schinese hscene23_Lyna_Helga_fdd49c2a:
    lm "让我看看你在下面藏了什么，亲爱的妈妈。"

translate schinese hscene23_Lyna_Helga_2514c03e:
    h "求、求你了宝贝，尽量……别看太久。"

translate schinese hscene23_Lyna_Helga_18b75184:
    l "别担心妈妈，有我在你很安全！"

translate schinese hscene23_Lyna_Helga_85dc02fb:
    n "赫尔加的动作缓慢而小心翼翼，仿佛每件衣物都是一道她不愿跨出的屏障。"

translate schinese hscene23_Lyna_Helga_4d6fa4d2:
    hm "这只是莱娜。你的女儿，你的心肝宝贝……"

translate schinese hscene23_Lyna_Helga_6315b870:
    hm "清醒点赫尔加！这根本没什么不对。"

translate schinese hscene23_Lyna_Helga_77813c72:
    n "但即便这样告诉自己，赫尔加也无法忽视自己的目光在女儿裸体上流连。"

translate schinese hscene23_Lyna_Helga_44dcecf4:
    n "光滑苍白的肌肤。少女胸部的柔软隆起。正在绽放的浑圆臀线……"

translate schinese hscene23_Lyna_Helga_cb4f8837:
    hm "她真是该死地漂亮……就像我的——"

translate schinese hscene23_Lyna_Helga_3d8a4399:
    h "咳咳！水温合适吗，啊？"

translate schinese hscene23_Lyna_Helga_8b2c3b33:
    l "合适合适！妈妈你快点！"

translate schinese hscene23_Lyna_Helga_491ceed1:
    h "{size=+5}喂！我看到你了，嘿嘿！{/size}别盯那么紧……"

translate schinese hscene23_Lyna_Helga_7bb5f1f1:
    l "像你说的，没什么好害羞的，对吧？"

translate schinese hscene23_Lyna_Helga_1310fce6:
    n "赫尔加突然无比清晰地意识到自己的赤裸，意识到自己的胸部沉甸甸地暴露着。"

translate schinese hscene23_Lyna_Helga_14e5b7b4:
    n "她不敢回头看，害怕在自己女儿眼里看到什么。"

translate schinese hscene23_Lyna_Helga_3b2aa9b4:
    centered "{font=font_narration}{cps=25}但这场游戏，{w=0.35}似乎……{w=0.5}才刚刚开始。"

translate schinese hscene23_Lyna_Helga_93f4fe83:
    lm "{cps=30}{size=+10}我的。{w=0.35}天。{w=0.35}妈。"

translate schinese hscene23_Lyna_Helga_30691b01:
    lm "我妈妈……我亲妈正在给我看……{size=+5}一切！"

translate schinese hscene23_Lyna_Helga_cd51bf09:
    lm "她居然比我想象的还要性感！"

translate schinese hscene23_Lyna_Helga_5ac80357:
    lm "这身材！难怪埃里克忍不住……"

translate schinese hscene23_Lyna_Helga_8429b859:
    lm "等等，我这就兴奋起来了吗？！"

translate schinese hscene23_Lyna_Helga_3912d1af:
    lm "该死，也许朱丽叶特是对的。也许我终究同样爱着女人。"

translate schinese hscene23_Lyna_Helga_de24968e:
    n "赫尔加像佳酿一样，越陈越香。多年母职与辛劳几乎没有在她身上留下痕迹。"

translate schinese hscene23_Lyna_Helga_850e369d:
    l "妈妈你的奶子怎么能这么完美？！"

translate schinese hscene23_Lyna_Helga_e2f4edb0:
    l "现在我更嫉妒了！嘿嘿嘿~"

translate schinese hscene23_Lyna_Helga_59854d8f:
    hm "天啊，赫尔加你到底在干什么？！"

translate schinese hscene23_Lyna_Helga_bfb900f9:
    hm "这是个错误。我会后悔的……"

translate schinese hscene23_Lyna_Helga_845624d8:
    l "抱歉！烂梗！"

translate schinese hscene23_Lyna_Helga_176ddb56:
    h "没……{size=-5}没关系。"

translate schinese hscene23_Lyna_Helga_2783d942:
    l "你美得惊人，妈妈。是我见过最美的女人。"

translate schinese hscene23_Lyna_Helga_ea45b181:
    h "你、你真这么觉得吗，亲爱的？"

translate schinese hscene23_Lyna_Helga_4fb75003:
    l "对！你从头到脚都完美无缺！"

translate schinese hscene23_Lyna_Helga_d0f45788:
    h "谢谢……你知道，我一直在保养自己的身体。"

translate schinese hscene23_Lyna_Helga_05448c64:
    lm "嗯，我完全看得出来。你的身材像个他妈的女神！"

translate schinese hscene23_Lyna_Helga_bc0743e3:
    h "那就来吧宝贝，给我腾点位置……"

translate schinese hscene23_Lyna_Helga_560f723a:
    lm "{cps=25}完美的熟女……{w=0.35}还是我妈妈！"

translate schinese hscene23_Lyna_Helga_0c406ba9:
    lm "操，我终于能好好看清了！简直像一片该死的森林……"

translate schinese hscene23_Lyna_Helga_0bfca958:
    lm "没想到你这么大胆？！就这样在我面前把自己露出来。"

translate schinese hscene23_Lyna_Helga_3cc9786f:
    h "{size=+5}莱娜，拜托！你到底在不在听？！"

translate schinese hscene23_Lyna_Helga_9e759ede:
    lm "可同时你在我面前又这么害羞。"

translate schinese hscene23_Lyna_Helga_05d78167:
    lm "你，一直那么严厉；你，总是命令我。"

translate schinese hscene23_Lyna_Helga_9c320529:
    lm "可在那副硬壳之下……"

translate schinese hscene23_Lyna_Helga_3598036f:
    h "这位小姐！你能不能别那样盯着看？！"

translate schinese hscene23_Lyna_Helga_8128982c:
    h "我以为你说你不想让我难堪？现在我开始觉得这不是个好主意了……"

translate schinese hscene23_Lyna_Helga_2730c03d:
    l "不不不！对不起妈妈，非常抱歉……"

translate schinese hscene23_Lyna_Helga_85d5dd5c:
    l "你实在是太、太漂亮了！"

translate schinese hscene23_Lyna_Helga_6db90706:
    h "{size=+5}莱娜！快腾地方！"

translate schinese hscene23_Lyna_Helga_6d7cd3d5:
    lm "该死，我真蠢！我差点流口水了！"

translate schinese hscene23_Lyna_Helga_e128c899:
    lm "我不能急！我不想她又生气……"

translate schinese hscene23_Lyna_Helga_5061a2fc:
    lm "可我从没见她这么手足无措过！哈哈哈！"

translate schinese hscene23_Lyna_Helga_577f0b56:
    lm "有其母必有其子……他们俩一定很般配。"

translate schinese hscene23_Lyna_Helga_b1a7b15c:
    lm "不！别现在想那个！"

translate schinese hscene23_Lyna_Helga_dc0c9439:
    lm "可我他妈欲火焚身！那你说，我到底他妈……"

translate schinese hscene23_Lyna_Helga_1ea732f2:
    lm "……要怎么才能……"

translate schinese hscene23_Lyna_Helga_6d840018:
    lm "……在那具身材面前控制住自己？！"

translate schinese hscene23_Lyna_Helga_be04f9e4:
    n "她又花了很长时间欣赏这景色；妈妈那饱满浑圆的胸部，从近处看更加惊人。"

translate schinese hscene23_Lyna_Helga_ec881484:
    n "那确实是成熟而丰腴女人的标志，把莱娜自己那点可怜的胸部比得完全不值一提。"

translate schinese hscene23_Lyna_Helga_ad8dc237:
    hm "这真是……疯了。我们俩一起光着身子在浴缸里。"

translate schinese hscene23_Lyna_Helga_3aafacde:
    hm "什么样的母亲会跟已经成年的女儿这样？！"

translate schinese hscene23_Lyna_Helga_0a307a02:
    n "水成了赫尔加恰到好处的干扰。她几乎成功放松下来，可女儿的存在塞满了她的感官，让她无法无视内心的动荡。"

translate schinese hscene23_Lyna_Helga_1174ee32:
    n "而对莱娜来说，每一秒都像一分钟。她无法抗拒涌遍血管的兴奋浪潮……"

translate schinese hscene23_Lyna_Helga_447e4dd8:
    h "莱娜？你在干什——"

translate schinese hscene23_Lyna_Helga_2dc0f0e6:
    l "你在无视我，妈妈。"

translate schinese hscene23_Lyna_Helga_01d6a52f:
    h "宝贝，我觉得你不该——"

translate schinese hscene23_Lyna_Helga_eaf52dec:
    l "你更想尴尬地分开坐着沉默吗，嗯？"

translate schinese hscene23_Lyna_Helga_45b828c9:
    h "{size=-5}不、不是，我是说……"

translate schinese hscene23_Lyna_Helga_8254df9f:
    lm "靠得这么近……"

translate schinese hscene23_Lyna_Helga_0e724b4e:
    h "你想的话我们可以聊点什么。你……在想什么？"

translate schinese hscene23_Lyna_Helga_a79e6cd5:
    lm "我？我不知道该说什么。我只是想看你裸体，想感觉……离你近一点。这样很错吗？"

translate schinese hscene23_Lyna_Helga_711ca9ec:
    h "宝贝……？"

translate schinese hscene23_Lyna_Helga_189b1069:
    l "呃……我……"

translate schinese hscene23_Lyna_Helga_3ee1cc94:
    l "跟我说说你年轻时候的事。你有没有做过什么……疯狂的事？"

translate schinese hscene23_Lyna_Helga_70a8ecbc:
    h "疯狂？具体指什么？举个例子？"

translate schinese hscene23_Lyna_Helga_c1a6b5e1:
    lm "该死，她刚才说什么？我他妈脑子转不动了！"

translate schinese hscene23_Lyna_Helga_c440c0a1:
    lm "如果我……？"

translate schinese hscene23_Lyna_Helga_b600fab8:
    lm "操！我刚才……我刚才在妈妈背上蹭了！"

translate schinese hscene23_Lyna_Helga_a2fb7518:
    h "喂……？你说的{i}疯狂{/i}是什么意思？"

translate schinese hscene23_Lyna_Helga_bcced75d:
    l "哦！就是那种……{size=-5}呃……"

translate schinese hscene23_Lyna_Helga_20006145:
    l "你有没有偷偷溜出去见男生？或者……跟朋友做点尝试？"

translate schinese hscene23_Lyna_Helga_a2d71707:
    hm "尝试？！她知道我以前做过的事吗？"

translate schinese hscene23_Lyna_Helga_9382d9aa:
    hm "不，我只是在疑神疑鬼！她不可能知道。"

translate schinese hscene23_Lyna_Helga_40da2f8c:
    hm "可她问的方式……简直像她知道，还故意激我承认。"

translate schinese hscene23_Lyna_Helga_e0ba567a:
    h "莱娜，那些是……非常私密的问题。"

translate schinese hscene23_Lyna_Helga_ad82f31c:
    h "我不确定自己愿不愿意跟你讨论这个。"

translate schinese hscene23_Lyna_Helga_e7de0746:
    l "拜托，妈妈。我们都是成年人了……你可以告诉我。我不会评判。"

translate schinese hscene23_Lyna_Helga_7654d0b0:
    lm "该死，这感觉真爽……"

translate schinese hscene23_Lyna_Helga_24de239b:
    lm "我能用阴唇感觉到妈妈背部肌肉的起伏。"

translate schinese hscene23_Lyna_Helga_e9972b3a:
    lm "而且她还在挠我短短的小草丛，操……"

translate schinese hscene23_Lyna_Helga_2af31a08:
    h "宝贝，你能不能别再动了？！"

translate schinese hscene23_Lyna_Helga_f7e5a4ef:
    h "浴缸里空间够大。你不用贴这么近……"

translate schinese hscene23_Lyna_Helga_d9daf2ea:
    lm "该死，我刚才在干什么？！冷静点，莱娜！"

translate schinese hscene23_Lyna_Helga_91ab112a:
    l "对、对不起，抱歉！我只是在找一个舒服的姿势……"

translate schinese hscene23_Lyna_Helga_3c9092d6:
    h "现在好些了吗？"

translate schinese hscene23_Lyna_Helga_2136d869:
    l "好、好了。但妈妈，别回避问题！"

translate schinese hscene23_Lyna_Helga_608f2c96:
    h "呃，我……"

translate schinese hscene23_Lyna_Helga_5341ce2f:
    h "那时候我只是做了普通女孩都会做的事，好吗？"

translate schinese hscene23_Lyna_Helga_a80987b1:
    l "「普通的事？」我还以为你更狂野呢！还记得你的内衣吗？"

translate schinese hscene23_Lyna_Helga_95abab83:
    h "喂！你本来就不该找到那个。"

translate schinese hscene23_Lyna_Helga_d3870f85:
    h "等等，你哥哥也知道那件事吗？！"

translate schinese hscene23_Lyna_Helga_b70cce13:
    l "嗯……也许吧，嘿嘿嘿~"

translate schinese hscene23_Lyna_Helga_1051ede4:
    h "天啊，你当然给他看过了！他当时肯定尴尬死了……"

translate schinese hscene23_Lyna_Helga_bbeb1b09:
    l "没有，他其实挺喜欢的。"

translate schinese hscene23_Lyna_Helga_6a17955f:
    h "{size=+5}莱娜！别拿那种事开玩笑！"

translate schinese hscene23_Lyna_Helga_02b54a7d:
    l "所以你是打算一直回避问题，嗯？"

translate schinese hscene23_Lyna_Helga_32bc35e0:
    l "我是说，你买那套性感内衣肯定是为了某个人！对吧？"

translate schinese hscene23_Lyna_Helga_e3e4fabb:
    h "啧。什么都瞒不过你……"

translate schinese hscene23_Lyna_Helga_dbf3dcc0:
    h "你妈妈十几岁的时候是有点{i}狂野{/i}，没错。"

translate schinese hscene23_Lyna_Helga_1ffdb634:
    l "{size=+5}我就知道！"

translate schinese hscene23_Lyna_Helga_e4e97682:
    h "我就说到这里吧……"

translate schinese hscene23_Lyna_Helga_ea3c657d:
    l "坏妈妈！告诉我，告诉我！"

translate schinese hscene23_Lyna_Helga_fca6ab08:
    h "也许下次吧……"

translate schinese hscene23_Lyna_Helga_0ec2b66b:
    l "这是不是说明有机会？！"

translate schinese hscene23_Lyna_Helga_b45f0e04:
    h "谁知道呢……但不是今天！"

translate schinese hscene23_Lyna_Helga_2cdecdd5:
    l "你是个幸运的妈妈。我不追问了……{size=-5}暂时。"

translate schinese hscene23_Lyna_Helga_3a3c0e43:
    h "你说得对，亲爱的。这样感觉真不错。"

translate schinese hscene23_Lyna_Helga_c3b53a22:
    l "对！想知道怎样会更好吗？"

translate schinese hscene23_Lyna_Helga_b4e147ae:
    h "哦？请说。"

translate schinese hscene23_Lyna_Helga_7c3bb7b2:
    l "我可以帮你洗！还含按摩……"

translate schinese hscene23_Lyna_Helga_c181bb8e:
    h "哦，宝贝，你不用那样。我自己可以。"

translate schinese hscene23_Lyna_Helga_6b00439b:
    l "我知道，可是……我真的想做！求你了求你了！让我为你做这个吧。"

translate schinese hscene23_Lyna_Helga_77cb7aa1:
    h "好吧，你来吧……"

translate schinese hscene23_Lyna_Helga_21bb526d:
    lm "该死，我不敢相信我终于在做这个了！"

translate schinese hscene23_Lyna_Helga_1e58b425:
    lm "她这个年纪皮肤还这么柔软光滑……"

translate schinese hscene23_Lyna_Helga_5aa9c67d:
    lm "还有这些结实的背肌，真性感。"

translate schinese hscene23_Lyna_Helga_b7a0ee34:
    lm "我真希望能对她做更多……"

translate schinese hscene23_Lyna_Helga_e73e0f98:
    n "莱娜的双手缓慢而挑逗地移动，滑过母亲的肌肤。赫尔加能感觉到自己的肌肉正在放松……臣服于女儿温柔的触碰。"

translate schinese hscene23_Lyna_Helga_cbc008db:
    l "舒服吗，妈妈？"

translate schinese hscene23_Lyna_Helga_3410ea03:
    h "是的，亲爱的。感觉……{size=-5}太棒了。"

translate schinese hscene23_Lyna_Helga_2545880c:
    lm "我能感觉到她的心跳。跟我的一样快！"

translate schinese hscene23_Lyna_Helga_7a5bc189:
    lm "不知道她是不是在想……我想的那件事。"

translate schinese hscene23_Lyna_Helga_79e2b308:
    hm "她的触碰如此抚慰，可为什么感觉这么……像带电一样？！"

translate schinese hscene23_Lyna_Helga_8a5cf06b:
    hm "我该停下，可我不能，不。我不想停。"

translate schinese hscene23_Lyna_Helga_31924329:
    l "你太紧张了，妈妈。放松点。"

translate schinese hscene23_Lyna_Helga_241ce972:
    l "这样就对了，好多了。"

translate schinese hscene23_Lyna_Helga_ef4123ed:
    l "为什么不再往后靠一点？你可以把头枕在我身上。"

translate schinese hscene23_Lyna_Helga_3a3190d3:
    h "亲、亲爱的……我——"

translate schinese hscene23_Lyna_Helga_4ad897ff:
    l "来吧妈妈……就让我照顾你一次吧。"

translate schinese hscene23_Lyna_Helga_333e781b:
    l "很舒服，对吧？"

translate schinese hscene23_Lyna_Helga_e79ae4a1:
    h "是的……你确实是个很软的靠垫。哈哈！"

translate schinese hscene23_Lyna_Helga_ab60b51d:
    lm "我能感觉到她在放松。她很享受。她在享受……我！"

translate schinese hscene23_Lyna_Helga_5c2b77d9:
    l "我得说，{size=-5}你的身材好到爆。"

translate schinese hscene23_Lyna_Helga_164ab9b9:
    l "我一直都知道妈妈最漂亮，可是……哇。"

translate schinese hscene23_Lyna_Helga_561b4631:
    hm "她眼里那是什么表情？像是有什么……饥渴的东西。"

translate schinese hscene23_Lyna_Helga_04d10ac3:
    hm "不，这太荒唐了！她是我女儿。只是欣赏，仅此而已。"

translate schinese hscene23_Lyna_Helga_f1782408:
    l "妈妈，怎么了？放松……"

translate schinese hscene23_Lyna_Helga_e02e4176:
    l "在我手里你是安全的，别担心。"

translate schinese hscene23_Lyna_Helga_8cf4ad07:
    l "接下来我按摩你的手臂，好吗？你这么美又这么操心的母亲，完全值得……"

translate schinese hscene23_Lyna_Helga_7efae1c0:
    hm "天啊，她的声音这么让人安心，她的身体……好温暖。"

translate schinese hscene23_Lyna_Helga_5f163703:
    hm "还有她的触碰……简直像她完全知道我需要什么。"

translate schinese hscene23_Lyna_Helga_2d9a1639:
    lm "天啊！有效了？！她这次居然都没反驳我！"

translate schinese hscene23_Lyna_Helga_d3721a73:
    lm "我好想再摸一次那对大奶子……"

translate schinese hscene23_Lyna_Helga_0f9f02e0:
    lm "不，不！别搞砸了莱娜，打好你的牌！"

translate schinese hscene23_Lyna_Helga_921fc9ea:
    hm "这太放松了，天啊……"

translate schinese hscene23_Lyna_Helga_bef89397:
    hm "我知道我不该让女儿这样大胆地看，也不该允许她这样碰我……"

translate schinese hscene23_Lyna_Helga_d50a3b68:
    hm "可我某种程度上也允许了她哥哥，不是吗？"

translate schinese hscene23_Lyna_Helga_046f6fe2:
    hm "如果这是我儿子来要求，我也会答应吗？！"

translate schinese hscene23_Lyna_Helga_798e8bd4:
    n "赫尔加闭上眼睛，试图清空脑海……"

translate schinese hscene23_Lyna_Helga_a7e2b69f:
    n "试图专注于水的感觉，专注于除了关于她儿子那些罪恶的回忆、或女儿双手抚摸她肌肤的触感之外的任何事。"

translate schinese hscene23_Lyna_Helga_eb1ef32b:
    n "但没有用。随着莱娜纤细手指每一次温柔的抚过，她都能感觉到自己的意志在动摇，身体在背叛自己……"

translate schinese hscene23_Lyna_Helga_1696b01d:
    h "唔嗯！宝贝……" with hpunch

translate schinese hscene23_Lyna_Helga_f6b0af7a:
    l "你好像很享受这个……妈妈。"

translate schinese hscene23_Lyna_Helga_9aafd1ad:
    h "是的，我很喜欢……{size=-5}宝、宝贝……"

translate schinese hscene23_Lyna_Helga_5f6bb6c6:
    lm "宝贝……？操，她很少这么叫我。"

translate schinese hscene23_Lyna_Helga_f06512aa:
    h "就我们两个女人……放松一下，对吧？"

translate schinese hscene23_Lyna_Helga_520c3c26:
    l "对！就像从前那样。"

translate schinese hscene23_Lyna_Helga_e7572a7a:
    centered "{font=font_narration}{cps=25}{color=#f1d377}( 是的，{w=0.35}就像从前那样…… )"

translate schinese hscene23_Lyna_Helga_836ff260:
    au "{cps=30}来，{w=0.25}戴在你身上真好看！{w=0.35}别害羞……"

translate schinese hscene23_Lyna_Helga_26115336:
    au "{cps=30}接下来我会好好照顾你的，好吗？{w=0.35}放松。"

translate schinese hscene23_Lyna_Helga_cdc8271f:
    h "{cps=30}我们今天不该做这种事……太冒险了。"

translate schinese hscene23_Lyna_Helga_3315cdef:
    au "{cps=30}哎呀，{i}小兔子{/i}现在后悔了？"

translate schinese hscene23_Lyna_Helga_ad0f087c:
    au "{cps=30}现在说这个有点晚了吧，{w=0.35}你说呢？"

translate schinese hscene23_Lyna_Helga_9fe11a08:
    au "{cps=30}每次事后哭着求我更多的不是你吗，{w=0.35}嗯？"

translate schinese hscene23_Lyna_Helga_5a7b3aa1:
    centered "{cps=20}{color=#ea1570}我珍贵的小妹妹。"

translate schinese hscene23_Lyna_Helga_031824f3:
    l "妈妈……？怎么了？"

translate schinese hscene23_Lyna_Helga_9fc492d9:
    hm "{size=+5}我为什么现在才想起那件事？！」"

translate schinese hscene23_Lyna_Helga_0c533b78:
    hm "那些回忆，我不想它们回来！"

translate schinese hscene23_Lyna_Helga_0790daf5:
    hm "我不能再掉进那个烂泥坑，绝不能！尤其不能跟莱娜！"

translate schinese hscene23_Lyna_Helga_2a9eb585:
    hm "{size=+5}该死、该死、该死！这很糟，太糟了！"

translate schinese hscene23_Lyna_Helga_4053625a:
    hm "这正是我不想让女儿产生错误想法的原因！"

translate schinese hscene23_Lyna_Helga_9c3fe2d7:
    hm "跟她哥哥的事已经够糟了……"

translate schinese hscene23_Lyna_Helga_131c5ecd:
    l "嗯？你怎么了妈妈？你吓到我了！"

translate schinese hscene23_Lyna_Helga_202b1c78:
    h "宝贝，{size=-5}只是……"

translate schinese hscene23_Lyna_Helga_0804e472:
    hm "不！别往那想！那是过去，已经结束了。"

translate schinese hscene23_Lyna_Helga_f42bf40d:
    l "天啊！我做错什么了吗？！你又生我的气了吗……？"

translate schinese hscene23_Lyna_Helga_00c9b10a:
    h "不，亲爱的。不是你的错。{size=-5}是……"

translate schinese hscene23_Lyna_Helga_c599abd3:
    l "妈、妈妈？！求你了！你要去哪儿？！"

translate schinese hscene23_Lyna_Helga_d48f0c0c:
    h "我……我得走了。"

translate schinese hscene23_Lyna_Helga_7af9e0b1:
    l "为什么？！我以为我们玩得很开心……"

translate schinese hscene23_Lyna_Helga_45dc47eb:
    l "{size=-5}妈妈……*抽泣*"

translate schinese hscene23_Lyna_Helga_5d840bad:
    h "对不起，莱娜……{size=-5}我只是——"

translate schinese hscene23_Lyna_Helga_4e64b41d:
    l "{size=+10}别离开我，求你了……！"

translate schinese hscene23_Lyna_Helga_6bb0e4a5:
    l "{size=+5}我们可以聊聊困扰你的任何事！"

translate schinese hscene23_Lyna_Helga_abe91c55:
    hm "我在干什么？！我女儿跟这事毫无关系！"

translate schinese hscene23_Lyna_Helga_cb8661a6:
    hm "那是过去。早就过去了。放下吧，赫尔加！"

translate schinese hscene23_Lyna_Helga_cfb60e2a:
    l "{size=-5}求、求你……*抽泣*陪着我……"

translate schinese hscene23_Lyna_Helga_23e1afe6:
    hm "我不能就这样离开她……"

translate schinese hscene23_Lyna_Helga_2216f3f7:
    h "乖，乖……一切都好了，宝贝。"

translate schinese hscene23_Lyna_Helga_832adc10:
    l "*抽泣*你怎么了妈、妈妈？"

translate schinese hscene23_Lyna_Helga_89c9320a:
    l "是我说了什么吗？*抽泣*是我……做了什么吗？"

translate schinese hscene23_Lyna_Helga_5181c334:
    h "不……小南瓜。我说了不是你的错。"

translate schinese hscene23_Lyna_Helga_9b7f2978:
    h "事实上，你的按摩很棒。"

translate schinese hscene23_Lyna_Helga_7c115dfa:
    l "那到底是……什么事？"

translate schinese hscene23_Lyna_Helga_f4844085:
    hm "我到底该跟她说什么？！我一团糟……"

translate schinese hscene23_Lyna_Helga_184649a1:
    h "我们呃……先回浴缸里吧，好吗？"

translate schinese hscene23_Lyna_Helga_4c6c978c:
    l "耶~！"

translate schinese hscene23_Lyna_Helga_d1bcc56d:
    n "有一阵子浴室里一片寂静。赫尔加趁着浴缸够大，把自己挪到离莱娜最远的地方。"

translate schinese hscene23_Lyna_Helga_ccd6644c:
    n "但这仍无法阻止她注意到女儿那坚定不移的目光。她试着与女儿对视，报以一个安心的微笑，可是……"

translate schinese hscene23_Lyna_Helga_99dc3c87:
    n "赫尔加的心思在别处。"

translate schinese hscene23_Lyna_Helga_abfac215:
    l "怎么？你到底说不说？"

translate schinese hscene23_Lyna_Helga_3418aef8:
    h "嗯？我……好、好的，当然！"

translate schinese hscene23_Lyna_Helga_fb4a8428:
    h "好吧。听我说，我……"

translate schinese hscene23_Lyna_Helga_a4a6492c:
    h "{cps=20}我在想你的……{w=0.5}{size=-5}你的……"

translate schinese hscene23_Lyna_Helga_f2396d15:
    l "我的……什么？"

translate schinese hscene23_Lyna_Helga_e59ddd95:
    h "{cps=15}你的姨妈。"

translate schinese hscene23_Lyna_Helga_4aae40cc:
    l "{size=+5}什——什么？安娜阿姨……？！」" with vpunch

translate schinese hscene23_Lyna_Helga_bebab9bf:
    l "你从那以后就再也没提过她，那时候埃里克和我还小得很！"

translate schinese hscene23_Lyna_Helga_39f3ecba:
    l "你一直没跟我们好好说过她，真可惜……你知道的吧，我总有一天想好好见见她。"

translate schinese hscene23_Lyna_Helga_ff9e5a4c:
    h "嗯。是啊……"

translate schinese hscene23_Lyna_Helga_e4c36757:
    h "我们已经{i}很久{/i}没见了。"

translate schinese hscene23_Lyna_Helga_489ff00e:
    l "别告诉我……她要来这里？！"

translate schinese hscene23_Lyna_Helga_87fa049b:
    h "什……？"

translate schinese hscene23_Lyna_Helga_58dc6018:
    l "这又是你准备的惊喜，对吧？！"

translate schinese hscene23_Lyna_Helga_c106cbe5:
    h "当然不是！你姨妈为什么会来这里？"

translate schinese hscene23_Lyna_Helga_01970628:
    h "{size=-5}我甚至都不再跟她联系了。"

translate schinese hscene23_Lyna_Helga_0f3bbe1b:
    l "啊，真可惜……"

translate schinese hscene23_Lyna_Helga_f0df25f5:
    lm "{cps=30}我敢说{w=0.25}某个人{w=0.5}会很希望这里再多一个家人。"

translate schinese hscene23_Lyna_Helga_e13c0c72:
    h "莱娜，你指着什么？"

translate schinese hscene23_Lyna_Helga_0fac09b8:
    l "嘿嘿~没什么！妈妈你不会懂的。"

translate schinese hscene23_Lyna_Helga_edd8d7a9:
    hm "唉。现在这些青少年……"

translate schinese hscene23_Lyna_Helga_b9c7919b:
    h "总之！我以前和她很亲近，你知道的吧？"

translate schinese hscene23_Lyna_Helga_852306f6:
    h "我们形影不离。就像你和你的双胞胎哥哥……"

translate schinese hscene23_Lyna_Helga_b389137f:
    h "{size=-5}我们以前也一起洗过好几次澡。"

translate schinese hscene23_Lyna_Helga_e622beec:
    lm "哇！够劲爆！"

translate schinese hscene23_Lyna_Helga_00dab277:
    hm "我为什么要跟她说这些？！我本来可以随便编个别的借口！"

translate schinese hscene23_Lyna_Helga_b8d6d870:
    hm "事情失控得太快了。"

translate schinese hscene23_Lyna_Helga_2850f271:
    n "赫尔加闭了一会儿眼睛，用意志驱散那些即将浮上来的危险回忆……"

translate schinese hscene23_Lyna_Helga_922bf897:
    n "关于一段既令人沉醉、又为世所不容的羁绊的回忆。"

translate schinese hscene23_Lyna_Helga_382eba7b:
    l "{size=+5}告诉我，告诉我！发生了什么？！" with vpunch

translate schinese hscene23_Lyna_Helga_9ac9b046:
    l "你们两个为什么会疏远？我可喜欢小八卦了！"

translate schinese hscene23_Lyna_Helga_21bde82d:
    h "宝贝？求、求你了，冷静点……"

translate schinese hscene23_Lyna_Helga_8b72bbaf:
    l "你可以等我们再抱在一起的时候全都告诉我！嘿嘿~"

translate schinese hscene23_Lyna_Helga_095e8c83:
    l "妈妈？你还在吗？"

translate schinese hscene23_Lyna_Helga_71ab7a6b:
    h "嗯……？在、在！"

translate schinese hscene23_Lyna_Helga_c4ad643c:
    l "来！挪过来！"

translate schinese hscene23_Lyna_Helga_9e7accc2:
    h "你不会不再问了吧？"

translate schinese hscene23_Lyna_Helga_dcc12ee9:
    l "不会！"

translate schinese hscene23_Lyna_Helga_0e7e8489:
    h "好吧，过来……"

translate schinese hscene23_Lyna_Helga_aef6f10b:
    l "怎么了？刚才你靠在我身上那么放松。"

translate schinese hscene23_Lyna_Helga_c0e9c9b6:
    h "只是这边有点挤……"

translate schinese hscene23_Lyna_Helga_cb1be286:
    l "哼，占掉半个浴缸的大浮木又不是我，哈哈！"

translate schinese hscene23_Lyna_Helga_452e066b:
    h "{size=+5}这位小姐！那不是——"

translate schinese hscene23_Lyna_Helga_fc2e0452:
    h "唉，{size=-5}我懒得说了……"

translate schinese hscene23_Lyna_Helga_51d6bb6f:
    l "我就知道你喜欢我这些烂梗！嘻嘻~"

translate schinese hscene23_Lyna_Helga_da30e9ed:
    l "所以，你们为什么不说话了？"

translate schinese hscene23_Lyna_Helga_499fe8c3:
    h "那件事……挺复杂的。"

translate schinese hscene23_Lyna_Helga_72872227:
    l "快点嘛！你什么都可以告诉我。"

translate schinese hscene23_Lyna_Helga_15acc8ef:
    hm "除了这件事。这件不行。"

translate schinese hscene23_Lyna_Helga_45336c22:
    h "那是很久以前的事了，亲爱的。"

translate schinese hscene23_Lyna_Helga_bc804bee:
    l "我想知道，妈妈。我想理解你！"

translate schinese hscene23_Lyna_Helga_449f84ef:
    h "事情没那么简单，你懂的……"

translate schinese hscene23_Lyna_Helga_0b566380:
    h "我和我姐姐……我们做过一些选择。那些选择伤害了别人。"

translate schinese hscene23_Lyna_Helga_f989e1f8:
    h "最后，我们就渐渐疏远了。"

translate schinese hscene23_Lyna_Helga_3fb7d96b:
    l "哇！什么样的选择……？"

translate schinese hscene23_Lyna_Helga_823c1774:
    h "关于……爱的选择。关于……我们想和谁在一起的选择。"

translate schinese hscene23_Lyna_Helga_fa5918a2:
    l "什么意思？她是在和一个你不认可的人交往吗？"

translate schinese hscene23_Lyna_Helga_b303012e:
    h "差不多吧……"

translate schinese hscene23_Lyna_Helga_966c3cee:
    lm "关于爱的选择？这有什么见不得人的？除非……"

translate schinese hscene23_Lyna_Helga_fbc5d6a3:
    lm "这跟爸爸的离婚有关？！不，不可能！"

translate schinese hscene23_Lyna_Helga_03514d20:
    l "是因为……一个男人吗？"

translate schinese hscene23_Lyna_Helga_0e1fabbd:
    h "我觉得今天关于你姨妈的话题够多了，对吧？"

translate schinese hscene23_Lyna_Helga_cb568960:
    l "可是妈妈——"

translate schinese hscene23_Lyna_Helga_e178ad6d:
    h "我是认真的，莱娜。有些事最好留在过去。"

translate schinese hscene23_Lyna_Helga_3f933dbb:
    l "所以你从来没有在外面玩过一点小花样？我不信。"

translate schinese hscene23_Lyna_Helga_252c7df1:
    h "我……我不打算回答这个。"

translate schinese hscene23_Lyna_Helga_dc24d8fe:
    l "真的？拜托嘛！"

translate schinese hscene23_Lyna_Helga_93796363:
    h "我不知道，宝贝……"

translate schinese hscene23_Lyna_Helga_72808d93:
    l "你不信任我吗……妈妈？"

translate schinese hscene23_Lyna_Helga_dcb6f0fc:
    h "我当然信任你！你是我女儿。"

translate schinese hscene23_Lyna_Helga_193611be:
    h "但这件事我不能告诉你。求你了，别再问了……"

translate schinese hscene23_Lyna_Helga_d9013eea:
    l "你刚刚在我耳边扔了个炸弹，妈妈，你指望什么？！"

translate schinese hscene23_Lyna_Helga_46e9ebde:
    l "现在我超级好奇！好奇你做了什么选择……"

translate schinese hscene23_Lyna_Helga_dea2c2e7:
    l "也许知道这件事对我是一次不错的人生教训。"

translate schinese hscene23_Lyna_Helga_2f8089e5:
    h "不！那是很久以前的事了，而且……现在其实已经不重要了，好吗？"

translate schinese hscene23_Lyna_Helga_0ced371f:
    h "重要的是你、我和你的哥哥现在都在一起。"

translate schinese hscene23_Lyna_Helga_646fa0ad:
    l "哼！好吧妈妈，既然你这么说……"

translate schinese hscene23_Lyna_Helga_0ac2666d:
    h "咳咳！我们不如……好好享受剩下的洗澡时间？"

translate schinese hscene23_Lyna_Helga_b1e9052f:
    lm "该死，我的手老是乱摸！"

translate schinese hscene23_Lyna_Helga_ee3bbc4d:
    h "那你想的话可以洗洗我的腿……"

translate schinese hscene23_Lyna_Helga_bf319826:
    h "{size=-5}亲、亲爱的，你觉得……"

translate schinese hscene23_Lyna_Helga_27bfd038:
    h "{size=-5}你觉得我是个坏母亲吗？"

translate schinese hscene23_Lyna_Helga_898f4cea:
    l "你在说什么？！当然不是！"

translate schinese hscene23_Lyna_Helga_ccc08e36:
    h "真的吗……？"

translate schinese hscene23_Lyna_Helga_a6b3ed90:
    lm "在讨夸奖吗，嗯？"

translate schinese hscene23_Lyna_Helga_bed73a0c:
    l "对，你真的是最棒的！"

translate schinese hscene23_Lyna_Helga_45a9c2f2:
    l "而且我们俩都爱你爱得不得了！"

translate schinese hscene23_Lyna_Helga_ff040530:
    h "但是……过去我对你俩犯过太多错误……"

translate schinese hscene23_Lyna_Helga_85d8aaaf:
    h "{size=-5}我已经尽力在改进了，可是——"

translate schinese hscene23_Lyna_Helga_d3a41a31:
    l "妈妈？这是怎么了？"

translate schinese hscene23_Lyna_Helga_9f0a19cc:
    l "说真的！你是全世界最好的妈妈！"

translate schinese hscene23_Lyna_Helga_e37d990c:
    l "而且如果你哪天想聊聊你们兄妹之间的问题……"

translate schinese hscene23_Lyna_Helga_aa3351e1:
    l "我永远都会在旁边听着，好吗？我也是懂一些的。"

translate schinese hscene23_Lyna_Helga_02c5f69b:
    h "谢谢你，我的小天使……"

translate schinese hscene23_Lyna_Helga_4e00286d:
    l "{size=+5}嘛啊！" with vpunch

translate schinese hscene23_Lyna_Helga_59bd5f37:
    l "好了，弄完了。"

translate schinese hscene23_Lyna_Helga_809a2b81:
    h "你把我当女王伺候！"

translate schinese hscene23_Lyna_Helga_58a882fe:
    h "要不要再多洗一会儿？嘿嘿~"

translate schinese hscene23_Lyna_Helga_f3292920:
    lm "哦妈妈，我真的想，可是……"

translate schinese hscene23_Lyna_Helga_42004c71:
    lm "我不确定自己还能忍多久不把你全身摸个遍。"

translate schinese hscene23_Lyna_Helga_501b35eb:
    lm "你任由我看着你、抚摸你……"

translate schinese hscene23_Lyna_Helga_dd3650d1:
    lm "我这辈子从来没有这么饥渴过！"

translate schinese hscene23_Lyna_Helga_34524e31:
    lm "但我不想再做会让你生气的事……"

translate schinese hscene23_Lyna_Helga_27f4f8e4:
    h "小南瓜……？"

translate schinese hscene23_Lyna_Helga_d31fc1b7:
    l "对不起妈妈。我不该再待太久了。"

translate schinese hscene23_Lyna_Helga_a1cbd60b:
    l "我玩得很开心，可是呃……没有我，埃里克一定无聊死了！"

translate schinese hscene23_Lyna_Helga_2a4ef7c8:
    l "我今天答应了他一件有趣的事。{size=-5}你懂的……"

translate schinese hscene23_Lyna_Helga_76384e8a:
    h "真贴心！没关系宝贝。跟他去吧。"

translate schinese hscene23_Lyna_Helga_8625d366:
    h "我要在这里再待一会儿。你不介意吧？"

translate schinese hscene23_Lyna_Helga_80f03eeb:
    l "行行行。别担心妈妈！"

translate schinese hscene23_Lyna_Helga_7469670b:
    l "就像我说的，我得跟我家大哥哥去做些有趣的{i}事{/i}……"

translate schinese hscene23_Lyna_Helga_c8fbf967:
    l "嘿嘿嘿~"

translate schinese hscene23_Lyna_Helga_d7cb6155:
    n "赫尔加感到一股如释重负的浪潮涌过全身。莱娜只是她一贯的调侃。她没事，她很安全，没什么好担心的。"

translate schinese hscene23_Lyna_Helga_c979f50c:
    n "她女儿只是好奇心重；也许是渴望母女亲密显得有些过头，但看起来并无恶意。"

translate schinese hscene23_Lyna_Helga_77cc7a73:
    h "你看起来……美极了，亲爱的。"

translate schinese hscene23_Lyna_Helga_32a92011:
    h "再也不要为自己的身材感到不自信，听见了吗？"

translate schinese hscene23_Lyna_Helga_5e8fc647:
    l "啊，妈妈！你真这么觉得？！"

translate schinese hscene23_Lyna_Helga_9ceb7467:
    h "是的。我确实这么觉得……"

translate schinese hscene23_Lyna_Helga_17c9f38a:
    l "全靠你，我美丽的妈妈！"

translate schinese hscene23_Lyna_Helga_e3a744bd:
    l "嗯，几乎全是！只差让这两个小家伙再长大一点，嘿嘿~"

translate schinese hscene23_Lyna_Helga_279126be:
    l "我们一定得多来几次！感觉太棒了！"

translate schinese hscene23_Lyna_Helga_98e1a17c:
    h "对、对……{size=-5}也许吧……"

translate schinese hscene23_Lyna_Helga_92752131:
    l "我好爱你，妈妈！拜拜！"

translate schinese hscene23_Lyna_Helga_301d1779:
    hm "这次她没对我做什么奇怪的事，也许是我想太多了……？"

translate schinese hscene23_Lyna_Helga_6510850a:
    hm "可那些回忆为什么回来得这么鲜明？！"

translate schinese hscene23_Lyna_Helga_dae37a1e:
    hm "她不是她！这是莱娜，我亲生的女儿……我的心肝宝贝。"

translate schinese hscene23_Lyna_Helga_663eb821:
    hm "我刚才是在试探她吗？看她会怎么对我、对我的身体？"

translate schinese hscene23_Lyna_Helga_bf06b77b:
    hm "这就是我同意一起洗澡的原因？为了弄清她真正的意图？"

translate schinese hscene23_Lyna_Helga_3b7d8335:
    hm "我真恶心！什么样的母亲才会想这种事？"

translate schinese hscene23_Lyna_Helga_5d663bb0:
    hm "可在她那些奇怪的请求之后，在她做了那些事之后……我真的以为她对我有某种兴趣。"

translate schinese hscene23_Lyna_Helga_37e041e2:
    hm "我怎么可以怀疑她？！"

translate schinese hscene23_Lyna_Helga_be0315a7:
    centered "{font=font_narration}{cps=25}{color=#f1d377}( 毕竟，{w=0.35}什么样的女儿会对自己的母亲动心呢？ )"

translate schinese hscene23_Lyna_Helga_8dfaef6f:
    e "妹妹……等、等等！"

translate schinese hscene23_Lyna_Helga_df9ccaca:
    l "别担心，妈妈还要好一阵子呢……"

translate schinese hscene23_Lyna_Helga_b6b95899:
    lm "说起来，她是怎么回事？妈妈不是原谅我了吗？"

translate schinese hscene23_Lyna_Helga_24f1dd44:
    lm "那她最近为什么还是那么奇怪……？"

translate schinese hscene23_Lyna_Helga_1e4655db:
    lm "跟她刚提到的姨妈那件事有关吗？"

translate schinese hscene23_Lyna_Helga_2570e40d:
    lm "又或者是你。大哥哥，你的部分做了吗？"

translate schinese hscene23_Lyna_Helga_c221e350:
    lm "妈妈在你周围也表现得超级奇怪。"

translate schinese hscene23_Lyna_Helga_1537c184:
    lm "算了，管她呢！她大概是更年期什么的……"

translate schinese hscene23_Lyna_Helga_29bfa96c:
    lm "现在是不是该把你的奶给我了，大哥哥？"

translate schinese hscene23_Lyna_Helga_ab8083c3:
    lm "说真的，我不知道妈妈怎么了……"

translate schinese hscene23_Lyna_Helga_32fcd171:
    lm "但至少我今天让她笑了一点，不是吗？"

translate schinese hscene23_Lyna_Helga_0966a7de:
    lm "更棒的是，我终于看到了那对又大又肥的妈妈奶子……"

translate schinese hscene23_Lyna_Helga_9df7a6e7:
    l "{size=+5}唔嗯！"

translate schinese story41_Erik_Lyna_Helga_f75d7c2d:
    n "那场带着赫尔加过往不安回响的沐浴，标志着一个转折点。"

translate schinese story41_Erik_Lyna_Helga_16d76570:
    centered "{font=font_narration}{size=+10}{cps=20}接下来的几天里，{w=0.35}裂痕越来越大……"

translate schinese story41_Erik_Lyna_Helga_b8fc463f:
    n "赫尔加发现自己越来越封闭，只能躲进更孤独的时刻里。"

translate schinese story41_Erik_Lyna_Helga_3ed1fda9:
    n "可怀疑的种子已经种下，她精心在心周围筑起的墙上出现了一道口子。"

translate schinese story41_Erik_Lyna_Helga_40d5ff0e:
    n "她试图和莱娜亲近的努力显得生硬而空洞……"

translate schinese story41_Erik_Lyna_Helga_20b21321:
    n "对自己行为的愧疚，以及表面下暗涌的混乱渴望，让她无法真正投入。"

translate schinese story41_Erik_Lyna_Helga_e72af60d:
    h "今、今晚不行，{size=-5}宝贝……"

translate schinese story41_Erik_Lyna_Helga_26b15e00:
    n "就连儿子的存在，曾经是安慰的源泉，如今却让她充满无法逃避的不安。"

translate schinese story41_Erik_Lyna_Helga_4c423c1b:
    centered "{font=font_narration}{cps=20}然而……"

translate schinese story41_Erik_Lyna_Helga_f5eee029:
    hm "{size=+5}不！这太疯狂了！我不敢相信我刚才差点就……"

translate schinese story41_Erik_Lyna_Helga_1a7bc111:
    hm "{size=+5}我得离开他们！{/size}离开这份……{size=-5}致命的吸引。"

translate schinese story41_Erik_Lyna_Helga_89b9bc2d:
    hm "{size=+5}他们是我该死的孩子们！{size=+10}我的宝贝！"

translate schinese story41_Erik_Lyna_Helga_6acbcbdc:
    hm "我需要……保护他们，{size=+5}珍惜他们！"

translate schinese story41_Erik_Lyna_Helga_0177a726:
    hm "而不是用我自己的病态和怨气去污染他们！"

translate schinese story41_Erik_Lyna_Helga_6d97a8cc:
    n "那座曾经充满活力的别墅，不再……"

translate schinese story41_Erik_Lyna_Helga_c8780fc4:
    n "用餐时间变得紧绷：尴尬的沉默、字斟句酌的话……"

translate schinese story41_Erik_Lyna_Helga_51274d1b:
    n "埃里克不知道母亲内心动荡的真正原因，苦于理解她行为上的突然转变。"

translate schinese story41_Erik_Lyna_Helga_9fde8d10:
    n "同样不知情的莱娜发现自己精心设计的计划适得其反。"

translate schinese story41_Erik_Lyna_Helga_60ae7713:
    n "这不在剧本之内。赫尔加非但没有和儿子更亲近，反而像是在把他推开。"

translate schinese story41_Erik_Lyna_Helga_1a59d32f:
    n "尽管如此，莱娜却更加坚定地要查清真相，要试探他们扭曲的家庭关系的底线。"

translate schinese story41_Erik_Lyna_Helga_16a6569f:
    l "怎么了，埃里克？妈简直在躲着你跑！"

translate schinese story41_Erik_Lyna_Helga_caceadec:
    e "听着……我觉得她很不对劲。"

translate schinese story41_Erik_Lyna_Helga_f50da2e3:
    e "就好像妈在怕我似的。她最近几乎都不看我。"

translate schinese story41_Erik_Lyna_Helga_900dc3a4:
    l "我确实注意到了。所以我才问啊！"

translate schinese story41_Erik_Lyna_Helga_6c65347a:
    e "我完全不知道，莉妮。{size=-5}我好困惑……"

translate schinese story41_Erik_Lyna_Helga_7cd9bedd:
    l "她本该是迷上你的魅力，而不是躲着你。"

translate schinese story41_Erik_Lyna_Helga_a6df2ba5:
    l "所以也许你得加把劲，对吧？变得更……{size=-5}有说服力。"

translate schinese story41_Erik_Lyna_Helga_669cd455:
    e "有说服力？我该怎么办？强迫她跟我待在一起？"

translate schinese story41_Erik_Lyna_Helga_c2b8eece:
    l "别这么天真，哥！这才是取胜之道。"

translate schinese story41_Erik_Lyna_Helga_3b830fc7:
    e "可我不喜欢骗她，也不喜欢把她推进她明显想躲开的处境……"

translate schinese story41_Erik_Lyna_Helga_d8e5b159:
    e "整件事都让我觉得不对，莱娜。"

translate schinese story41_Erik_Lyna_Helga_5b779f60:
    l "哎呀，你这个戏剧鬼！"

translate schinese story41_Erik_Lyna_Helga_5657360b:
    l "你今天怎么了？过来！"

translate schinese story41_Erik_Lyna_Helga_b9f08d31:
    e "等、等等姐！"

translate schinese story41_Erik_Lyna_Helga_89ebc7e5:
    e "小心点莱娜！我差点撞到头！"

translate schinese story41_Erik_Lyna_Helga_550993e0:
    l "放心吧大哥，我接住你了~！"

translate schinese story41_Erik_Lyna_Helga_c976fa7a:
    l "好，回到我们的事……"

translate schinese story41_Erik_Lyna_Helga_9eeedfc3:
    l "分数，奖励？你还想要更多，对吧？"

translate schinese story41_Erik_Lyna_Helga_e6b1a155:
    e "不……不只是那个！"

translate schinese story41_Erik_Lyna_Helga_118e12da:
    l "「不只是」，哈哈哈！"

translate schinese story41_Erik_Lyna_Helga_143d3fe4:
    e "你知道我做这一切是为了帮你们两个……"

translate schinese story41_Erik_Lyna_Helga_e4c44b0c:
    e "再说了，最近感觉你想「奖励」我的时候还得看你心情！我也想有发言权！"

translate schinese story41_Erik_Lyna_Helga_456f35a4:
    l "噗！还想装出一副你不享受的样子，是吧？"

translate schinese story41_Erik_Lyna_Helga_b32fd606:
    l "还有，别那样指着我！"

translate schinese story41_Erik_Lyna_Helga_ec93c3ff:
    l "这么对一位女士可不行，亲爱的哥哥……"

translate schinese story41_Erik_Lyna_Helga_a23d90ce:
    l "也许你那根大手指该用在别的地方，你说呢？"

translate schinese story41_Erik_Lyna_Helga_1e3be464:
    e "莉妮，别在外面……"

translate schinese story41_Erik_Lyna_Helga_37eca8a8:
    l "要不要我提醒你，自几周前我们喝醉的那晚之后，你就再也没碰过我下面？"

translate schinese story41_Erik_Lyna_Helga_518c7807:
    e "可、可是你从没问过我啊！"

translate schinese story41_Erik_Lyna_Helga_c90790cf:
    l "啧。也许该换成我来享受全部关注才对……"

translate schinese story41_Erik_Lyna_Helga_3d35e3dc:
    e "那我想要的呢？你老是指使我！"

translate schinese story41_Erik_Lyna_Helga_2b31e35c:
    l "哈！那你说……你想要什么？"

translate schinese story41_Erik_Lyna_Helga_f278ca75:
    e "该由我来处理妈那边的事！"

translate schinese story41_Erik_Lyna_Helga_8dee8f22:
    l "哥哥，你耍小脾气的样子真是可爱死了……"

translate schinese story41_Erik_Lyna_Helga_9fedd1c4:
    l "好吧，你说得有道理，行了吧？我知道我是有点强势——"

translate schinese story41_Erik_Lyna_Helga_4f5ce450:
    em "她说只是「有点」而已！"

translate schinese story41_Erik_Lyna_Helga_49adcb37:
    l "但是！你得相信我，好吗？"

translate schinese story41_Erik_Lyna_Helga_810fe33c:
    e "我凭什么要听你那些奇怪的主意？"

translate schinese story41_Erik_Lyna_Helga_4f9cc530:
    e "重要的事一向都是我在管！"

translate schinese story41_Erik_Lyna_Helga_7ad57b1c:
    l "是啊，可这件事明显不是你的专长，你说呢？"

translate schinese story41_Erik_Lyna_Helga_6f2c9bea:
    l "如果我们不能让她分心……如果不能把这场戏继续演下去……"

translate schinese story41_Erik_Lyna_Helga_b46f84ca:
    l "{cps=25}我们的小游戏就藏不了多久了。"

translate schinese story41_Erik_Lyna_Helga_554dc58f:
    e "你这话什么意思……？"

translate schinese story41_Erik_Lyna_Helga_1e566e6b:
    l "就是说像你这样的「负责任先生」，会被这些压力压垮。"

translate schinese story41_Erik_Lyna_Helga_67fb17c3:
    l "你多半会跟妈坦白一切，把我们的{i}乐趣{/i}全毁了。"

translate schinese story41_Erik_Lyna_Helga_9ca9dbe9:
    e "*叹气* {size=-5}你……"

translate schinese story41_Erik_Lyna_Helga_63286e61:
    e "{size=-10}你也许是对的。"

translate schinese story41_Erik_Lyna_Helga_23a1d359:
    lm "我当然对！你成为我的双胞胎是有原因的……"

translate schinese story41_Erik_Lyna_Helga_9d9dd4b6:
    n "莱娜的话虽是想安慰哥哥，却几乎没能减轻他的苦恼。"

