# -*- coding: utf-8 -*-
# Generated by tools/generate.py - do not edit by hand.
# Sinful Summer (Chapter 3.6) - Simplified Chinese localisation.

translate schinese story60_Erik_Lyna_Helga_8ac04dd2:
    h "宝、宝贝……妈妈只是想保护你……"

translate schinese story60_Erik_Lyna_Helga_41b2cd68:
    l "{size=+10}{shader=jitter:2.0,2.0}保护我什么？！保护我连自己的人生都不能做主？！" with vpunch

translate schinese story60_Erik_Lyna_Helga_28fc5042:
    l "{size=+5}看见了吗？！这就是我刚才说的那种屁话！我早就不再是个傻乎乎的小女孩了！"

translate schinese story60_Erik_Lyna_Helga_8e67d218:
    l "{size=+5}{shader=jitter:2.0,2.0}我已经不怕你了，妈！我不是小孩子！我是他妈的一个成年女人！"

translate schinese story60_Erik_Lyna_Helga_45f385b1:
    l "{size=+5}{shader=jitter:1.0,1.0}那些照片里到底发生过什么、我用我自己的身体和这个你那么担心的男孩做什么……！"

translate schinese story60_Erik_Lyna_Helga_fecf7ac7:
    l "{size=+5}{shader=jitter:1.0,1.0}那都是我他妈自己的事，明白？！等我准备好跟你分享的时候，我自然会说。"

translate schinese story60_Erik_Lyna_Helga_07a5bf40:
    l "{size=+5}{shader=jitter:1.0,1.0}还有，别再纠结你那该死的心理创伤了！都过去几十年了！"

translate schinese story60_Erik_Lyna_Helga_89e0e474:
    l "{size=+5}{shader=jitter:1.0,1.0}你比{i}她{/i}好太多了！我也那么爱你！你不能拿我们之间真挚的感情去和……"

translate schinese story60_Erik_Lyna_Helga_b11678ff:
    l "{size=+5}{shader=jitter:3.0,3.0}……和你那个{i}恋童的贱人{/i}姐姐对你做过的事相提并论，{size=+10}行了吧？！"

translate schinese story60_Erik_Lyna_Helga_2dc46033:
    l "糟了。我……对不起。我不是故意——"

translate schinese story60_Erik_Lyna_Helga_b795e8b7:
    hm "我做的和我父母一模一样。就像{i}她{/i}做过的那样。"

translate schinese story60_Erik_Lyna_Helga_30333770:
    hm "我这一辈子不就是在做这个吗？永远都想掌控一切，因为我害怕。"

translate schinese story60_Erik_Lyna_Helga_29be75c3:
    hm "害怕别人，害怕自己不是那个说了算的人……"

translate schinese story60_Erik_Lyna_Helga_c4f4d465:
    centered "{font=font_narration}{cps=25}{color=#f1d377}( 害怕被伤害。 )"

translate schinese story60_Erik_Lyna_Helga_c18ae0c5:
    l "{size=-5}*啜泣* 对不起……现在只有我一个人变成了彻头彻尾的贱人……"

translate schinese story60_Erik_Lyna_Helga_3247618f:
    l "{size=-5}但你不能逼我把秘密告诉你，妈。"

translate schinese story60_Erik_Lyna_Helga_539fa58b:
    l "{size=-5}你刚刚把那个重磅炸弹扔给我，说你姐姐夺走了你的{/size}{i}选择{/i}……"

translate schinese story60_Erik_Lyna_Helga_5a1ba92a:
    l "{cps=20}求你别夺走我的。"

translate schinese story60_Erik_Lyna_Helga_79db55d5:
    h "{size=-5}我的小宝贝……"

translate schinese story60_Erik_Lyna_Helga_14d728dd:
    h "你说得对，哪一点都对！"

translate schinese story60_Erik_Lyna_Helga_f673a39b:
    h "我只是怕连你也失去。怕你受伤。"

translate schinese story60_Erik_Lyna_Helga_98e34f59:
    h "等你准备好告诉我的时候，我听着就好。我不会再逼你。"

translate schinese story60_Erik_Lyna_Helga_c915899f:
    h "但是莱娜，我发誓，如果你在这件严重的事上骗我……"

translate schinese story60_Erik_Lyna_Helga_7d3390fc:
    l "真是的，别想那么多了。"

translate schinese story60_Erik_Lyna_Helga_650c229a:
    l "就当我只是……也在保护我们吧。保护我们所有人。"

translate schinese story60_Erik_Lyna_Helga_210b4a28:
    h "安娜以前也是这么说的。"

translate schinese story60_Erik_Lyna_Helga_79dde431:
    l "喂！那不公平……"

translate schinese story60_Erik_Lyna_Helga_75975d75:
    l "我保证不是什么你不会认可的事，好吗？"

translate schinese story60_Erik_Lyna_Helga_e42c969c:
    l "我很清楚自己在做什么。我很安全。我很小心。"

translate schinese story60_Erik_Lyna_Helga_b9cddcf0:
    h "嗯……好吧。我相信你。"

translate schinese story60_Erik_Lyna_Helga_4d57ceee:
    hm "尽管我知道自己不该信。尽管每一种直觉都在说，我的两个孩子之间有什么在发生。"

translate schinese story60_Erik_Lyna_Helga_de381400:
    h "该死……我得去洗把脸。我现在样子糟透了。"

translate schinese story60_Erik_Lyna_Helga_20985835:
    l "慢慢来。我就在这儿！"

translate schinese story60_Erik_Lyna_Helga_c8517455:
    l "嘘，埃里克。出来。"

translate schinese story60_Erik_Lyna_Helga_52b47760:
    e "莱娜，我……我全都听到了！关于安娜阿姨，关于——"

translate schinese story60_Erik_Lyna_Helga_70e9c845:
    l "我知道。但你现在必须马上走，求你了。"

translate schinese story60_Erik_Lyna_Helga_5cef9b73:
    e "{size=+5}等等，为什么？！不！{size=+10}我不走！"

translate schinese story60_Erik_Lyna_Helga_58446022:
    l "嘘。别提高嗓门。"

translate schinese story60_Erik_Lyna_Helga_4fad5a2e:
    e "你为什么一直躲着她的问题？为什么要对她说那些难听的话？"

translate schinese story60_Erik_Lyna_Helga_123c4a56:
    e "我们必须把一切都告诉她，姐姐！真相。现在就说。"

translate schinese story60_Erik_Lyna_Helga_03eadf45:
    e "她肯定已经怀疑了。妈又不傻。"

translate schinese story60_Erik_Lyna_Helga_ff3267aa:
    l "老哥，你他妈疯了吗？！"

translate schinese story60_Erik_Lyna_Helga_a6962d20:
    e "可、可是她有权知道！她刚才跟你说了那些之后……"

translate schinese story60_Erik_Lyna_Helga_a07a8dd0:
    l "没错！她都那样说了！"

translate schinese story60_Erik_Lyna_Helga_082461ef:
    l "我故意凶她，就是为了让她别再盯着我、别再提这个话题。为什么？因为我爱她，因为我关心她。"

translate schinese story60_Erik_Lyna_Helga_b1ec3091:
    e "我……{size=-5}我不明白。"

translate schinese story60_Erik_Lyna_Helga_f3744ffe:
    l "她是在重温童年那段可怕的创伤！她觉得历史在重演，你看不出来吗？！"

translate schinese story60_Erik_Lyna_Helga_8502b8fb:
    l "如果我们现在告诉她，你和我正在乱伦，她一定会彻底{i}崩溃{/i}。"

translate schinese story60_Erik_Lyna_Helga_52cf0dcd:
    l "你想让妈妈大半夜开着车一去不回，是吗？！开到哪个该死的海里之类的？"

translate schinese story60_Erik_Lyna_Helga_7667e09e:
    l "{size=+5}{shader=jitter:2.0,2.0}白痴！白痴！"

translate schinese story60_Erik_Lyna_Helga_b94479ab:
    l "{shader=jitter:1.0,1.0}一个晚上我已经哭够了，天啊……"

translate schinese story60_Erik_Lyna_Helga_7932bb8c:
    e "啧。可我们还在骗她，这样不对。"

translate schinese story60_Erik_Lyna_Helga_8d7c7b05:
    l "你心太软，脑子却不够用！我们是在保护她，埃里克。"

translate schinese story60_Erik_Lyna_Helga_6dd8b5e5:
    e "让她以为自己疯了？以为她看错了、想多了？！"

translate schinese story60_Erik_Lyna_Helga_47873527:
    e "那不是我理解的爱，也不是我理解的关心人！"

translate schinese story60_Erik_Lyna_Helga_5d1b9039:
    e "她知道有很不对劲的事，莱娜。我们藏不了多久了。"

translate schinese story60_Erik_Lyna_Helga_41dc927f:
    l "她只是{i}怀疑{/i}。怀疑不等于证据。"

translate schinese story60_Erik_Lyna_Helga_1a7dca8d:
    l "明天先处理爸的事。先熬过那一关。"

translate schinese story60_Erik_Lyna_Helga_703acb65:
    l "然后我们再想办法怎么告诉她我们的事，好吗？用正确的方式。"

translate schinese story60_Erik_Lyna_Helga_46e50ff2:
    e "根本没有什么「方式」。这一切都他妈乱透了！"

translate schinese story60_Erik_Lyna_Helga_52b91427:
    e "今晚我们做的事，整个夏天我们一直在做的事……"

translate schinese story60_Erik_Lyna_Helga_026100c6:
    e "他妈的，{size=-5}你把我们拖进了什么烂摊子里……"

translate schinese story60_Erik_Lyna_Helga_75215ae9:
    e "{size=-5}这是真的吗？我感觉我要吐了。"

translate schinese story60_Erik_Lyna_Helga_1b2a676c:
    e "{size=-5}妈从小被她那个该死的姐姐一点点引诱，现在我们又——"

translate schinese story60_Erik_Lyna_Helga_f141132d:
    l "她没有在重复安娜当年做过的事！我们对她也没有。差得远着呢。"

translate schinese story60_Erik_Lyna_Helga_44b4bebf:
    e "我们不是吗？！我觉得这里只有你他妈疯了！"

translate schinese story60_Erik_Lyna_Helga_1b92599c:
    e "我们在操纵妈，把她灌醉，利用她的孤独……"

translate schinese story60_Erik_Lyna_Helga_8b35f2e6:
    e "今晚我差点就蒙住她的眼睛、让她以为那是假阳具而和她做爱了。"

translate schinese story60_Erik_Lyna_Helga_a082d713:
    e "我都说了不会再来一次她喝昏过去那回的事，可我还是……"

translate schinese story60_Erik_Lyna_Helga_e246e02f:
    l "但你没有。你停下来了。"

translate schinese story60_Erik_Lyna_Helga_b9e7729b:
    e "是她阻止了我们。我又一次失控了。不然的话，我早就——"

translate schinese story60_Erik_Lyna_Helga_c7cc31de:
    e "该死！我已经不知道自己是谁了……{size=-5}不知道你把我变成了什么……"

translate schinese story60_Erik_Lyna_Helga_1d4a86c4:
    e "{size=-5}妈妈一直在暗中受苦，而我……{size=-10}我居然——"

translate schinese story60_Erik_Lyna_Helga_239f3bdc:
    l "哥哥，听我说！我知道这很难。我知道你也为她难受。"

translate schinese story60_Erik_Lyna_Helga_14f0a643:
    l "但留在这里坦白真相对谁都没好处，好吗？"

translate schinese story60_Erik_Lyna_Helga_038a4edd:
    l "那只会把她毁得更彻底。毁掉我们。毁掉一切。"

translate schinese story60_Erik_Lyna_Helga_37c841ce:
    l "就再信我最后一次，求你了。再过一周，她就会准备好听我们说、准备好{i}接受{/i}我们。"

translate schinese story60_Erik_Lyna_Helga_b8634a68:
    e "然后呢？！我们在我们这个变态乱伦家庭里从此幸福快乐地生活下去？得了吧，我才不信。"

translate schinese story60_Erik_Lyna_Helga_3cdd378e:
    l "我……{size=-5}我真的不知道。"

translate schinese story60_Erik_Lyna_Helga_d27b864a:
    l "{size=-5}对不起。你从一开始就是对的，你那些怀疑都是对的。"

translate schinese story60_Erik_Lyna_Helga_234ddef5:
    l "{size=-5}当初你说这样会付出代价的时候……"

translate schinese story60_Erik_Lyna_Helga_79395f9c:
    e "哈！你可真是花了很久才看明白啊？！"

translate schinese story60_Erik_Lyna_Helga_3c55ad9b:
    e "这烂摊子是你挑起来的，莱娜。{size=-5}要是你当初听我的……"

translate schinese story60_Erik_Lyna_Helga_3e0ab2de:
    l "{size=-5}我知道。对不起。我保证会补偿你们俩。"

translate schinese story60_Erik_Lyna_Helga_75dadb46:
    l "{size=-5}但时间回不去。我们只能一起想办法解决。"

translate schinese story60_Erik_Lyna_Helga_70123f96:
    centered "{font=font_narration}{cps=25}{color=#00bfff}{cps=20}我们总是这样。"

translate schinese story60_Erik_Lyna_Helga_a0ecb333:
    l "快走，在她回来之前。我们明天再谈。"

translate schinese story60_Erik_Lyna_Helga_78891ae8:
    l "哦，还有，把你的内裤拿上。好在她没注意到。"

translate schinese story60_Erik_Lyna_Helga_f31ca61f:
    e "{size=-5}要是明天这一切全崩了，都是你的错。全都是，一如既往。"

translate schinese story60_Erik_Lyna_Helga_937a0be6:
    l "{size=-5}我知道……所有责任我一个人扛。"

translate schinese story60_Erik_Lyna_Helga_72f8c018:
    h "抱歉。花了点时间。"

translate schinese story60_Erik_Lyna_Helga_a39fd585:
    l "妈！好点了吗？过来坐我旁边。"

translate schinese story60_Erik_Lyna_Helga_63dd71a4:
    h "呃……大概吧。给我一分钟。"

translate schinese story60_Erik_Lyna_Helga_52ee0cf1:
    h "哎，你觉得我……我是个很糟糕的妈妈吗？"

translate schinese story60_Erik_Lyna_Helga_50eae980:
    l "不！别再说这种话了！你怎么会——"

translate schinese story60_Erik_Lyna_Helga_56f6dec0:
    h "因为这个夏天我没有阻止你们，明明我童年也发生过那种事。尤其还为了……"

translate schinese story60_Erik_Lyna_Helga_e25e7afb:
    h "……为了享受我们一起做的那些坏事。"

translate schinese story60_Erik_Lyna_Helga_6e90b3b8:
    l "你有{i}需求{/i}，妈。你是人。"

translate schinese story60_Erik_Lyna_Helga_615adadd:
    l "一个残缺又复杂——可我依然深深爱着的人。"

translate schinese story60_Erik_Lyna_Helga_fa48febe:
    h "{size=-5}你真会说话。"

translate schinese story60_Erik_Lyna_Helga_a932a251:
    l "但是真的！过来。"

translate schinese story60_Erik_Lyna_Helga_5faaa8f1:
    l "我们的新关系是我这辈子遇到过最好的事之一，好吗？拿全世界来换我都不换。"

translate schinese story60_Erik_Lyna_Helga_77499a31:
    l "我知道这很奇怪，而且你的过去让事情变得更复杂……"

translate schinese story60_Erik_Lyna_Helga_4c86aa1e:
    l "但我们比任何时候都更亲近，妈妈。这是你没法否认的事实。"

translate schinese story60_Erik_Lyna_Helga_8c03a311:
    h "我……我知道。我不想让我们再一次渐行渐远，宝贝。"

translate schinese story60_Erik_Lyna_Helga_28d4ecc5:
    h "只是一切都太难了。{size=-5}还有那些{i}回忆{/i}。"

translate schinese story60_Erik_Lyna_Helga_a4dc9a90:
    l "我明白。但我们会想办法做到的，好吗？"

translate schinese story60_Erik_Lyna_Helga_7cdcce42:
    h "保证？"

translate schinese story60_Erik_Lyna_Helga_d029d800:
    l "保证。"

translate schinese story60_Erik_Lyna_Helga_d4317bf7:
    l "对了，我们今晚能一起睡吗？"

translate schinese story60_Erik_Lyna_Helga_9cfb4f15:
    h "当然！本来我就是这个意思。而且我……"

translate schinese story60_Erik_Lyna_Helga_56413571:
    h "{size=-5}说真的，我现在一点也不想一个人待着。"

translate schinese story60_Erik_Lyna_Helga_a51ea155:
    l "哦妈妈，那我就像胶水一样黏着你~！"

translate schinese story60_Erik_Lyna_Helga_6e6fe235:
    h "我没意见，不过你不会是打算顶这个发型睡觉吧？"

translate schinese story60_Erik_Lyna_Helga_a0ca443f:
    l "啊？我喜欢啊。很酷的……"

translate schinese story60_Erik_Lyna_Helga_340dd845:
    h "而且肯定很不舒服！还很古怪。说真的，这一整晚它都让我很在意，宝贝。"

translate schinese story60_Erik_Lyna_Helga_026312fb:
    l "哈。你真的很不喜欢我做我自己，是吧。"

translate schinese story60_Erik_Lyna_Helga_68b1371d:
    h "完全相反，我一直都在努力让你展现最好的自己！"

translate schinese story60_Erik_Lyna_Helga_81066ceb:
    h "不过说真的，这太荒唐了。我来——"

translate schinese story60_Erik_Lyna_Helga_04b8a607:
    h "啊，这样就对了。好多了。"

translate schinese story60_Erik_Lyna_Helga_8af81c15:
    h "自从上次去理发店之后，它就长得很好看了。"

translate schinese story60_Erik_Lyna_Helga_6b719804:
    l "哼。既然你这么说……"

translate schinese story60_Erik_Lyna_Helga_6aa9e762:
    h "哎呀，我真的是这个意思。"

translate schinese story60_Erik_Lyna_Helga_51f99a57:
    h "世界上最可爱的女孩现在更可爱了。喜欢。"

translate schinese story60_Erik_Lyna_Helga_a41545b7:
    h "{cps=25}我美丽的{w=0.5}年轻{w=0.5}{i}女人{/i}……"

translate schinese story60_Erik_Lyna_Helga_10c6d46d:
    h "{cps=25}你今晚为了我打扮得这么漂亮，{w=0.5}对吧？"

translate schinese story60_Erik_Lyna_Helga_8faaaf3c:
    h "{cps=20}为了让{i}妈妈{/i}……这么好看。"

translate schinese story60_Erik_Lyna_Helga_4ae03c8e:
    h "宝贝，我们试着睡一会儿吧。"

translate schinese story60_Erik_Lyna_Helga_28c0af41:
    l "但是妈，我……{size=-5}我以为我们是——"

translate schinese story60_Erik_Lyna_Helga_9e2b92e4:
    h "拜托，今天太漫长了。我累了。"

translate schinese story60_Erik_Lyna_Helga_3062772b:
    l "{size=-5}好、好吧。是我的错。"

translate schinese story60_Erik_Lyna_Helga_691b9f75:
    lm "该死。我真的非常抱歉，妈。你告诉我的那些事，她对你做的事……我不知道！"

translate schinese story60_Erik_Lyna_Helga_58a36982:
    lm "埃里克说得对。这件事必须快点结束。"

translate schinese story60_Erik_Lyna_Helga_1636b8e1:
    lm "这些把戏、这些操纵、这些秘密……我一直都他妈的——"

translate schinese story60_Erik_Lyna_Helga_d18c6b97:
    hm "我就这么被蒙在鼓里吗？不……从那天晚上我就知道了。从我在她相机里看到那些可耻的照片开始。"

translate schinese story60_Erik_Lyna_Helga_d6dd7883:
    hm "明天我得面对我的前丈夫。明天一切可能会崩得更彻底。"

translate schinese story60_Erik_Lyna_Helga_c120c281:
    hm "总有一天，很快，我那对双胞胎孩子会承认我所怀疑的事。"

translate schinese story60_Erik_Lyna_Helga_374662d2:
    hm "天啊，我太累了，累得没法面对这一切疯狂。至少今晚不行。"

translate schinese story60_Erik_Lyna_Helga_eecb2e52:
    lm "我爱你，妈妈。就算这一切全都崩塌。"

translate schinese story60_Erik_Lyna_Helga_1abd0e38:
    lm "{cps=25}我真的真的很爱你……"

translate schinese story60_Erik_Lyna_Helga_b54b11c6:
    em "明天是离婚后我第一次见爸。我得想办法假装一切都正常。"

translate schinese story60_Erik_Lyna_Helga_40411db5:
    em "一边知道我母亲今晚把我含在嘴里，而我差点当着莱娜的面和她做爱。"

translate schinese story60_Erik_Lyna_Helga_3307123d:
    em "一边知道我和我姐早就越过了所有的线。"

translate schinese story60_Erik_Lyna_Helga_efecb8ca:
    em "{size=-5}一边知道妈、妈小时候被她姐姐伤害过……"

translate schinese story60_Erik_Lyna_Helga_6e8fcaf1:
    em "怎么办？！我们怎么才能从这个噩梦里走出来？我们还能回得去吗？"

translate schinese story61_Lyna_Helga_ba625b00:
    centered "{size=+15}{cps=20}{shader=flip}{font=font_narration}一小时后……"

translate schinese story61_Lyna_Helga_81b94458:
    hm "我又回到{i}他们{/i}身上了啊。"

translate schinese story61_Lyna_Helga_5f38198e:
    hm "真有意思，身体记得的东西，脑子却拼命想忘掉。"

translate schinese story61_Lyna_Helga_9f7d5e0e:
    hm "{cps=20}人生就是如此……"

translate schinese story61_Lyna_Helga_096e2914:
    h "{size=-5}啊……操，真舒服。"

translate schinese story61_Lyna_Helga_14474ba4:
    h "{size=-5}天啊，我太需要这样放松一下了。"

translate schinese story61_Lyna_Helga_6e872917:
    l "妈……？"

translate schinese story61_Lyna_Helga_f405966a:
    h "哦。嗨。"

translate schinese story61_Lyna_Helga_018c7d96:
    l "那是……烟？你在干什么？"

translate schinese story61_Lyna_Helga_28c81aee:
    h "回床上去，宝贝。"

translate schinese story61_Lyna_Helga_deeeb88d:
    l "等等，那……{size=+5}{i}香烟{/i}？！"

translate schinese story61_Lyna_Helga_d485fd7d:
    l "{size=+10}妈！你搞什么？！" with vpunch

translate schinese story61_Lyna_Helga_8732d5c2:
    h "嘘！小声点。要么出来，要么回屋去。别站在门口把虫子放进来。"

translate schinese story61_Lyna_Helga_c6d47393:
    l "到底怎么了？！你什么时候开始抽烟的？"

translate schinese story61_Lyna_Helga_fb7c4a24:
    h "你会在乎什么呢。"

translate schinese story61_Lyna_Helga_df17bd01:
    l "我在乎！告诉我。"

translate schinese story61_Lyna_Helga_9d0afd0c:
    h "从小就抽。虽然我也戒了很久……"

translate schinese story61_Lyna_Helga_341b5422:
    h "{size=-5}{cps=25}直到去年离婚协议下来的那一天，{w=0.3}就是这样。"

translate schinese story61_Lyna_Helga_1e8b11f7:
    l "该死……但不管该不该说，那玩意儿会害死人，妈！"

translate schinese story61_Lyna_Helga_0cf57b8b:
    l "对健康非常有害。现在就戒掉！"

translate schinese story61_Lyna_Helga_36da4b9c:
    h "丫头，你确定要在这个时候教训我吗？"

translate schinese story61_Lyna_Helga_9b34a8c6:
    l "不、不，抱歉。我只是……有点懵。"

translate schinese story61_Lyna_Helga_4151b98c:
    l "我们从来没见过你抽。一根都没有？整个夏天一次都没有。"

translate schinese story61_Lyna_Helga_69d7bc4e:
    h "你本来就不该看见！那就全露馅了。啧……"

translate schinese story61_Lyna_Helga_e34b9881:
    l "你到底把烟藏哪儿了？"

translate schinese story61_Lyna_Helga_81988663:
    h "女人不会把所有秘密都说出来。"

translate schinese story61_Lyna_Helga_40bf623f:
    l "认真的？你的底线就在这儿？"

translate schinese story61_Lyna_Helga_62775254:
    h "嗯。"

translate schinese story61_Lyna_Helga_48bfbb11:
    l "那个……我能试一根吗？"

translate schinese story61_Lyna_Helga_e9b51473:
    h "绝对不行。"

translate schinese story61_Lyna_Helga_800b5add:
    l "妈妈，拜托啦~？"

translate schinese story61_Lyna_Helga_6b7594cd:
    h "刚才是谁在担心它有多伤身体？闭嘴。"

translate schinese story61_Lyna_Helga_1ea5e188:
    l "哎，拜托……我也想当一小会儿真正的坏女人嘛。"

translate schinese story61_Lyna_Helga_f481b8f8:
    h "天啊，莱娜，我这么做可不是为了耍酷……"

translate schinese story61_Lyna_Helga_00e8003a:
    h "听着，我今晚大概已经有九个地方做得像坏妈妈了。"

translate schinese story61_Lyna_Helga_aaf813f6:
    h "但在「让我女儿在我的阳台上染上坏烟瘾」这件事上，我还是要划一条线。"

translate schinese story61_Lyna_Helga_d14e33ef:
    l "九个地方……？这数字还真具体。"

translate schinese story61_Lyna_Helga_adfa28ca:
    h "{cps=20}我一直在……{w=1.5}{nw}"

translate schinese story61_Lyna_Helga_306e5fe3:
    h "{cps=20}……数着。"

translate schinese story61_Lyna_Helga_7b9622a5:
    h "啊……这下到位了。"

translate schinese story61_Lyna_Helga_120de77b:
    l "*咳嗽* *咳嗽* {w=1.0}算了，还是算了！{size=-5}我一点也……"

translate schinese story61_Lyna_Helga_84aacfca:
    l "那味道太恶心了！*咳嗽* 为什么会有人故意抽烟？！"

translate schinese story61_Lyna_Helga_b0b4c0f5:
    h "因为有时候脑子太吵，你需要一个分心的事。"

translate schinese story61_Lyna_Helga_cd8a1b14:
    l "所以你今晚脑子很{i}吵{/i}，是吧……"

translate schinese story61_Lyna_Helga_5954acab:
    h "{cps=25}震耳欲聋。"

translate schinese story61_Lyna_Helga_ffbbb4a5:
    l "很遗憾听到这个。"

translate schinese story61_Lyna_Helga_c112886e:
    h "嗯？我那个臭丫头哪儿去了？"

translate schinese story61_Lyna_Helga_45f35206:
    l "我是认真的，妈。我也睡不着。"

translate schinese story61_Lyna_Helga_9318c5b0:
    l "我的脑子一直停不下来……{size=-5}刚才那些之后。"

translate schinese story61_Lyna_Helga_6ec9de80:
    h "是啊。今晚真难熬……"

translate schinese story61_Lyna_Helga_5c854904:
    l "不过这景色真不错。值了。"

translate schinese story61_Lyna_Helga_f569b107:
    h "嗯。"

translate schinese story61_Lyna_Helga_8f5346ba:
    h "你知道吗，我一直在想{i}记忆{/i}这回事。"

translate schinese story61_Lyna_Helga_1d0ad0c4:
    l "你是说记忆这个概念本身？怎么了？"

translate schinese story61_Lyna_Helga_1626173c:
    h "记忆真不可靠。我们以为自己记得清清楚楚，其实不过是在给自己讲一个关于当时发生了什么的故事。"

translate schinese story61_Lyna_Helga_1602a6b0:
    h "而这个故事会变。每次你回想起来，都会稍微改一点。加一点，减一点……"

translate schinese story61_Lyna_Helga_14b2841a:
    h "直到最后，你记住的已经不是最初那件事了。{w}你记住的只是上一次想起它时的样子。"

translate schinese story61_Lyna_Helga_65ed2e66:
    l "这还挺扭曲的。"

translate schinese story61_Lyna_Helga_2f5ad74c:
    h "是啊。它意味着那些最塑造了我们的事，或许并不是我们以为的那个样子。"

translate schinese story61_Lyna_Helga_81e9b30a:
    h "我花了几十年时间，把{i}她{/i}塑造成一个庞大的东西，定义了我的全部。我怎么想。我怎么爱……"

translate schinese story61_Lyna_Helga_1f6ee528:
    h "{size=-5}……我怎么把你和你哥哥养大。"

translate schinese story61_Lyna_Helga_2ce321d7:
    h "不过说来奇怪，我一直都害怕把关于{i}她{/i}的那段故事说出口。"

translate schinese story61_Lyna_Helga_69109af7:
    h "而现在我真的说出来了，我一直在等什么可怕的事发生。"

translate schinese story61_Lyna_Helga_ba35be12:
    l "什么都不会发生的，妈。"

translate schinese story61_Lyna_Helga_e3d3cb36:
    h "这才让我害怕。因为说出来，什么也没改变。"

translate schinese story61_Lyna_Helga_24896839:
    h "{cps=25}也许它从来就没有我以为的那么大。"

translate schinese story61_Lyna_Helga_924f67dd:
    l "那是好事还是坏事？"

translate schinese story61_Lyna_Helga_cf44772f:
    h "我还不知道。"

translate schinese story61_Lyna_Helga_09010108:
    h "我想这意味着，我死死抓着的东西早就变过太多次形状了，它甚至已经不是原来那个了。"

translate schinese story61_Lyna_Helga_564f6547:
    h "也许我怕的正是我对它的记忆本身。我记得的那个样子，而不是它实际发生的样子。"

translate schinese story61_Lyna_Helga_90cb0f9a:
    l "但它确实发生过，妈。不管你脑子里是哪个版本，最初那件事真实得不能再真实。"

translate schinese story61_Lyna_Helga_92ab7431:
    h "当然。但那个遭遇到它的小女孩……已经不存在了。"

translate schinese story61_Lyna_Helga_26909d1c:
    h "我一直护着她，一直替她做决定，一直害怕伤害她……"

translate schinese story61_Lyna_Helga_4b364538:
    h "但小赫尔加已经离开三十多年了。"

translate schinese story61_Lyna_Helga_d2437169:
    h "你知道你外婆以前总爱说什么吗？感情就像客人。你没必要让它们搬进来住。"

translate schinese story61_Lyna_Helga_91e68be1:
    h "可我还是让那一位搬进来了，莱娜。我给了它主卧，还给了它房子的钥匙。"

translate schinese story61_Lyna_Helga_2697cfbd:
    l "外婆说的话多了去了……"

translate schinese story61_Lyna_Helga_8c172643:
    h "{cps=20}是啊。{w=0.5}大部分都是错的。"

translate schinese story61_Lyna_Helga_57dc5aa1:
    h "我能问你一句真心话吗，宝贝？"

translate schinese story61_Lyna_Helga_8a2eb4d8:
    l "看问什么。"

translate schinese story61_Lyna_Helga_78bb5659:
    h "{cps=25}你从什么时候开始，不再是我乖乖的小女儿了……？"

translate schinese story61_Lyna_Helga_1ad862fd:
    l "你问的是我不再乖乖听话，还是不再想要乖乖听话？"

translate schinese story61_Lyna_Helga_83c6a690:
    h "有区别吗？"

translate schinese story61_Lyna_Helga_ea3f83c9:
    l "区别很大。"

translate schinese story61_Lyna_Helga_e194a6a8:
    l "我从来没有不想做过，你知道吗。"

translate schinese story61_Lyna_Helga_31ec9ae4:
    l "我是全世界最乖的孩子。我们俩都是。"

translate schinese story61_Lyna_Helga_568148ca:
    l "埃里克和莱娜，完美的双胞胎。七点练钢琴，六点学芭蕾。十岁就掌握三门语言。"

translate schinese story61_Lyna_Helga_d8836031:
    h "你们确实是了不起的孩子。"

translate schinese story61_Lyna_Helga_e8ace1dd:
    l "{cps=25}我们只是两只表演的猴子，{w=0.5}{size=-5}妈。"

translate schinese story61_Lyna_Helga_2868a7eb:
    l "而且一开始我甚至不介意。我以为那就是真爱该有的样子。"

translate schinese story61_Lyna_Helga_9408ecd6:
    l "你把一件事做到完美，然后有人注意到。有人夸一句「做得好」，并且在房间里多待一会儿，看你把它做完。"

translate schinese story61_Lyna_Helga_b18b026f:
    l "可从来没人留下过，对吧？你和爸总是要去忙下一件事。下一个案子，下一笔生意，下一个国家……"

translate schinese story61_Lyna_Helga_5fcd27f3:
    l "于是我们有了保姆。都是好女人，没错。可她们不是{size=+5}{i}你{/i}。"

translate schinese story61_Lyna_Helga_a53da4a3:
    l "她们不知道埃里克不开着走廊的灯就睡不着。也不知道我会给花园里每一条虫子起名字。"

translate schinese story61_Lyna_Helga_19ca0986:
    h "你真会这样……？"

translate schinese story61_Lyna_Helga_647b9b7b:
    l "看吧？你连这个都不知道。"

translate schinese story61_Lyna_Helga_c2a8997e:
    l "我还为一只该死的毛毛虫办过一次完整的葬礼。全套仪式。当时的主祭其实是埃里克。"

translate schinese story61_Lyna_Helga_00613af7:
    h "{size=-5}{cps=20}天啊……"

translate schinese story61_Lyna_Helga_b73e32be:
    l "所以你说，我是从什么时候开始不再是你的乖女儿的？"

translate schinese story61_Lyna_Helga_fdfbc12f:
    l "嗯，是我发现「乖」并不能让你下班更早回家的那一天。"

translate schinese story61_Lyna_Helga_d3c1ad22:
    l "妈，好几年里我把所有事都做对了。你和爸要求的一切。"

translate schinese story61_Lyna_Helga_60b15879:
    l "然后有一天我发现，做完美的奖赏，只是……被期待更完美。"

translate schinese story61_Lyna_Helga_d70915b0:
    l "从来不会有人说「够了莱娜，你终于可以做自己了」。"

translate schinese story61_Lyna_Helga_c98f0860:
    h "所以你就开始叛逆了。"

translate schinese story61_Lyna_Helga_14ef4fbe:
    l "我不再{i}表演{/i}了。"

translate schinese story61_Lyna_Helga_c5bfb102:
    l "不过你想听更深一层的真相？还有更深的。"

translate schinese story61_Lyna_Helga_0353b75b:
    h "请说吧……"

translate schinese story61_Lyna_Helga_9a2f53e8:
    l "{cps=20}我累了，{w=0.3}妈。{w=0.5}累于活成这个样子。"

translate schinese story61_Lyna_Helga_66af6d04:
    l "你知道永远都得靠我一个人往前推有多累吗？永远都是那个最大声、最难搞的人？"

translate schinese story61_Lyna_Helga_4d7a60f1:
    l "那个非得把事情推动起来、否则这个烂透了的家庭永远不会改变的人？"

translate schinese story61_Lyna_Helga_645938b2:
    l "埃里克只会等。爸从来不在。而你……"

translate schinese story61_Lyna_Helga_9653d180:
    l "{size=-5}你总是让我费好大劲才能换到。"

translate schinese story61_Lyna_Helga_a9f12584:
    h "换来什么，宝贝？"

translate schinese story61_Lyna_Helga_7f6b3882:
    l "{cps=25}换来你像注意到{size=+5}{i}他{/i}那样注意到我。"

translate schinese story61_Lyna_Helga_067f9690:
    l "我往前推，因为不推我就没人看见。我一直都隐形。"

translate schinese story61_Lyna_Helga_2c8d17c9:
    l "那个被宠坏的。难搞的那个。你不得不训斥的那个。"

translate schinese story61_Lyna_Helga_22722886:
    l "所以我不如闹出点动静，对吧？"

translate schinese story61_Lyna_Helga_4fcec187:
    h "我以前常在晚上十点坐在办公室里看案卷，心里会想：「至少我在养他们」。"

translate schinese story61_Lyna_Helga_43615872:
    h "「至少他们什么都不缺」。"

translate schinese story61_Lyna_Helga_64a0bb7e:
    h "而你们确实有。你们什么都不缺。除了……"

translate schinese story61_Lyna_Helga_a114bd46:
    l "{size=-5}……那唯一重要的东西。"

translate schinese story61_Lyna_Helga_e2f0c44a:
    h "相信我，我知道。"

translate schinese story61_Lyna_Helga_386dd629:
    h "当我终于辞职、全职陪你们的时候，你和埃里克已经是青少年了，各有各的生活、各有各的壳。"

translate schinese story61_Lyna_Helga_cedd0ef0:
    h "我一进房间你们两个就安静下来。就像我是个来做客的陌生人，走进自己家一样。"

translate schinese story61_Lyna_Helga_ada4dc6f:
    l "你当时确实就是，妈。"

translate schinese story61_Lyna_Helga_a2bfe62b:
    h "{size=-5}是啊……"

translate schinese story61_Lyna_Helga_80cc18a2:
    l "跟我说说。为什么{i}他{/i}一直都是你的最爱？"

translate schinese story61_Lyna_Helga_7caa9ed3:
    h "嗯。我曾经读到过一个说法……"

translate schinese story61_Lyna_Helga_8b8d517f:
    h "我们其实看不见别人，我们看见的永远只是自己对别人的期待。"

translate schinese story61_Lyna_Helga_d43cc4af:
    h "你看着一个人时，真正映入眼帘的是你投射在他身上的每一个假设、每一份恐惧、每一个愿望。"

translate schinese story61_Lyna_Helga_d0d37341:
    h "真实的人藏在那一切背后。而绝大多数时候，你根本走不过自己投射出的那个形象。"

translate schinese story61_Lyna_Helga_7df8198f:
    l "有点像刚才说的记忆那回事，是吧？一样让人郁闷。"

translate schinese story61_Lyna_Helga_ea615276:
    h "或者相反，是一种解脱。看你站在哪一边。"

translate schinese story61_Lyna_Helga_e1c75505:
    h "我想我们之间就是这样。我看着你哥哥，看到的是一个更容易拿捏的自己。顺从、谨慎、可以控制……"

translate schinese story61_Lyna_Helga_dfefeb4a:
    h "而我看着你，看到的全是让我害怕的东西。"

translate schinese story61_Lyna_Helga_b4b0a780:
    l "什么，具体是我？为什么？我那时还是个孩子……"

translate schinese story61_Lyna_Helga_19ee9822:
    h "不是你的问题。是我自己的那份强烈，被反射回了我身上。"

translate schinese story61_Lyna_Helga_eb186c51:
    h "你一直都很……那么强烈，莱娜。即使还是个小女孩的时候。"

translate schinese story61_Lyna_Helga_50114df8:
    h "而在我童年之后，我不幸地学会了把那种强烈和危险联系在一起。"

translate schinese story61_Lyna_Helga_7e892f27:
    h "安娜也一样。无畏。想要什么就拿什么，从不开口问。"

translate schinese story61_Lyna_Helga_8d4f5739:
    h "所以每次你往前推，每次你要求超出我舒适区的给予……"

translate schinese story61_Lyna_Helga_e0e109c7:
    h "我心里都会有一部分在痛。不只是当年，现在也一直在发生。"

translate schinese story61_Lyna_Helga_2dd7d954:
    h "不是因为你这个人。是因为对我来说，爱不该那么强烈。"

translate schinese story61_Lyna_Helga_babec2e0:
    centered "{font=font_narration}{cps=20}{color=#f1b500}尤其是在{size=+5}{i}她{/i}{/size}对我做了那些之后。"

translate schinese story61_Lyna_Helga_0512f5ec:
    l "所以我在为你姐姐的罪孽受罚。{size=-5}真是……"

translate schinese story61_Lyna_Helga_b6270d33:
    h "不！宝贝，请不要那样想。"

translate schinese story61_Lyna_Helga_72e05eb9:
    h "更像是……你从我这里得到的更少，因为我伤得太重，给不了你需要的爱。"

translate schinese story61_Lyna_Helga_839131b7:
    h "但……我想这同样不可原谅。对不起。"

translate schinese story61_Lyna_Helga_69717d25:
    l "哦，那{i}就是{/i}不可原谅的。"

translate schinese story61_Lyna_Helga_4882875a:
    h "{cps=20}我知道，{w=0.3}宝贝。{w=0.5}我知道。"

translate schinese story61_Lyna_Helga_4dfaabad:
    l "听着，我告诉你这些不是要让你内疚，好吗？不是这个原因。"

translate schinese story61_Lyna_Helga_d2698eea:
    h "那为什么？我也为我犯的错每天都在受苦，你知道吗。"

translate schinese story61_Lyna_Helga_7cb994ed:
    l "为什么？因为我恨了你一辈子，却从来不知道真正的原因。"

translate schinese story61_Lyna_Helga_eed070bf:
    l "现在我知道了。而且甚至不是你的错。真的不是。"

translate schinese story61_Lyna_Helga_c8e385ac:
    l "那只是……发生过的烂事。从你父母滚到安娜、滚到你、再滚到我们的烂事。"

translate schinese story61_Lyna_Helga_665a40bb:
    h "家庭就是这样。{size=-5}很不幸。"

translate schinese story61_Lyna_Helga_6ae8c701:
    h "把伤害一层层传下去，然后盼着下一代能想办法把它止住……"

translate schinese story61_Lyna_Helga_41cfb9dd:
    l "{cps=25}我们止住它了吗，{w=0.5}妈？"

translate schinese story61_Lyna_Helga_47190fc7:
    h "至少今晚在这阳台上陪着我的是你，对吧？不是……{i}他{/i}。"

translate schinese story61_Lyna_Helga_e29cd2e6:
    h "今晚我没有向你哥哥倾诉。他不是我的第一选择。"

translate schinese story61_Lyna_Helga_72ae0e49:
    h "{cps=20}你是，{w=0.3}莱娜。{w=0.5}你，{w=0.3}我的女儿。"

translate schinese story61_Lyna_Helga_f26283bd:
    h "我希望这个夏天是不一样的。"

translate schinese story61_Lyna_Helga_02f27e7e:
    h "至少我们在试着改变点什么，是的。"

translate schinese story61_Lyna_Helga_6a9a1281:
    l "哈。我们确实在做一些{size=+3}{i}事情{/i}{/size}，对吧~？"

translate schinese story61_Lyna_Helga_7cef4d7e:
    l "又来一根？！真是的，别抽了……"

translate schinese story61_Lyna_Helga_7ee7393e:
    h "{i}别{/i}耍脾气，我们就成交，好吗？"

translate schinese story61_Lyna_Helga_8c7585fa:
    l "哎，那边那颗亮的。特别亮的那颗。"

translate schinese story61_Lyna_Helga_453eac40:
    l "我喜欢那颗星星。"

translate schinese story61_Lyna_Helga_70637828:
    h "嗯。那不是星星。那是……木星？我想是。"

translate schinese story61_Lyna_Helga_77640ae8:
    h "不管怎样是一颗行星。不过不是火星，不然你肉眼就能看出那点红色。"

translate schinese story61_Lyna_Helga_02fe7791:
    l "等等……什么？！你怎么会知道这些？"

translate schinese story61_Lyna_Helga_6d6b35f0:
    l "你可是律师，不是天文学家。"

translate schinese story61_Lyna_Helga_f4369ed9:
    h "我能说什么呢，你有个聪明的妈妈。"

translate schinese story61_Lyna_Helga_77de0ac7:
    h "我敢说你哥哥也知道这个。我教你们俩认——的时候你们真该多用心。"

translate schinese story61_Lyna_Helga_4df68f4e:
    h "算了。抱歉……老毛病。"

translate schinese story61_Lyna_Helga_9b8a5354:
    l "是啊是啊，人生就是这样……"

translate schinese story61_Lyna_Helga_1aba6310:
    h "不过说真的，还记得我给你买过那本天文书吗？那种能弹出太阳系的。"

translate schinese story61_Lyna_Helga_e5913d3b:
    l "呃……哦对，你这么一说我记起来了！"

translate schinese story61_Lyna_Helga_c891853c:
    h "你不到一天就把一页上的木星撕下来了。"

translate schinese story61_Lyna_Helga_b2645fa5:
    l "那可是最大的行星！我想把它拿在手里。"

translate schinese story61_Lyna_Helga_72171560:
    h "你把它喂给了狗，莱娜。"

translate schinese story61_Lyna_Helga_bbc9d39c:
    l "呃……好吧，那部分可能是故意的。嘿嘿~"

translate schinese story61_Lyna_Helga_e69f4a84:
    h "我知道是故意的。我看着你做的。"

translate schinese story61_Lyna_Helga_1ad27748:
    l "{size=+5}什么？！不可能。"

translate schinese story61_Lyna_Helga_eb49d569:
    h "我还在厨房门口，记得吗？你非常故意地看了我一眼，然后把那个木星剪纸塞进了小饼干的嘴里。"

translate schinese story61_Lyna_Helga_0babf619:
    l "{size=+5}你居然没拦住我？！"

translate schinese story61_Lyna_Helga_7dcb7af3:
    h "我很好奇你下一步会做什么。"

translate schinese story61_Lyna_Helga_7b252038:
    l "妈，我那时才……{i}五岁{/i}！哈哈哈。"

translate schinese story61_Lyna_Helga_f9cdc30a:
    h "你那时就是个小恐怖分子。从那一刻起我就知道，养你会是……一场相当冒险的旅程。"

translate schinese story61_Lyna_Helga_63329d73:
    l "大概一小时后小饼干把木星吐在了那块白地毯上。呕。"

translate schinese story61_Lyna_Helga_b0c2aa73:
    h "在那块{i}昂贵{/i}的白色地毯上。你爸差点气疯了。"

translate schinese story61_Lyna_Helga_74ac4b66:
    l "不过你为什么纵容我这么干？"

translate schinese story61_Lyna_Helga_07932a19:
    h "因为有那么一瞬间……我看见你决定做{i}你自己{/i}，而不是我们希望你成为的样子。"

translate schinese story61_Lyna_Helga_a7582203:
    h "那是我第一次真正意识到，你里面住着另一个完全不同的人。"

translate schinese story61_Lyna_Helga_bbde934d:
    h "我不知道该怎么告诉一个孩子这种事，所以我就……任由你喂了狗一些纸。哈。"

translate schinese story61_Lyna_Helga_42018e72:
    l "妈妈……？"

translate schinese story61_Lyna_Helga_facaa24c:
    h "嗯？"

translate schinese story61_Lyna_Helga_ba84c92b:
    l "你觉得人真的能改变吗？还是我们只是越来越会隐藏真正的自己？"

translate schinese story61_Lyna_Helga_e79a3038:
    h "我觉得人过了某个阶段，就不会再改变自己{i}是什么{/i}了。但他们能改变自己拿它做什么。"

translate schinese story61_Lyna_Helga_93b5d864:
    h "我依然是那个在姐姐离开后需要掌控一切的小女孩。有时还是会害怕。"

translate schinese story61_Lyna_Helga_686ce939:
    h "但也许我可以自己决定拿那份恐惧怎么办，而不是让它替我决定。"

translate schinese story61_Lyna_Helga_3b9d2e37:
    l "这听起来像是那些励志书里的一句土味金句。"

translate schinese story61_Lyna_Helga_2df90d40:
    h "大概确实是。但这不代表它是错的。"

translate schinese story61_Lyna_Helga_340ad5e1:
    l "我想我愿意相信这个。相信我可以做真正的自己，而不必因此意味着什么坏事。"

translate schinese story61_Lyna_Helga_9e06657d:
    h "那不一定意味着什么坏事，莱娜。"

translate schinese story61_Lyna_Helga_33607c2b:
    h "我的意思是，你很极端。你很耗人。你把我逼得快疯了。哦对了，你还是个没救的怪胎色狼。"

translate schinese story61_Lyna_Helga_e05b2a96:
    l "哎呀，谢谢妈！{size=-5}我现在感觉好受宠若惊啊……"

translate schinese story61_Lyna_Helga_65540b32:
    h "{size=+5}不过！{/size}你也是我认识的最勇敢的人。"

translate schinese story61_Lyna_Helga_1874048c:
    h "我是认真的。"

translate schinese story61_Lyna_Helga_aa4e579f:
    h "你这些年做的一切。那些往前推、那些混乱，还有现在……这个夏天。连那些让我害怕的部分也是。"

translate schinese story61_Lyna_Helga_a8a85164:
    h "你做这些，是因为你不肯让这个家庭悄无声息地烂掉，对吗？"

translate schinese story61_Lyna_Helga_fd277c31:
    l "换来什么？我他妈什么都没解决。我只会让事情越来越糟。"

translate schinese story61_Lyna_Helga_4dd2238d:
    l "我以前是个蠢丫头，现在也是。我叛逆、残忍、自私……"

translate schinese story61_Lyna_Helga_b7e9ea17:
    h "但那是有原因的！只有你还在真的继续努力，对吧？"

translate schinese story61_Lyna_Helga_9f4c880d:
    h "只有你说过「这样不够。我要更多」。"

translate schinese story61_Lyna_Helga_6ddcce3c:
    h "你是这个家的黏合剂。或者说是它剩下的部分……"

translate schinese story61_Lyna_Helga_755f241b:
    h "你哥哥没有勇气。你爸早就走了。而我……？"

translate schinese story61_Lyna_Helga_6ffb3304:
    h "又一次想逃避我的问题。来这里之前我甚至把重启职业生涯的手续都办好了……"

translate schinese story61_Lyna_Helga_31e61da7:
    h "说实话，我不确定自己还想不想回到那种生活了。多亏了你，我开始动摇了。"

translate schinese story61_Lyna_Helga_8a6af42f:
    h "要不是因为这个夏天，因为你，我这个固执的女儿……"

translate schinese story61_Lyna_Helga_2ecd9dd9:
    h "我想我会一直躲在办公室里躲下去。"

translate schinese story61_Lyna_Helga_fd1fdff5:
    h "现在我想离那个未来越远越好……"

translate schinese story61_Lyna_Helga_6ef6240b:
    h "我能再问你一个问题吗？最后一个，我保证。"

translate schinese story61_Lyna_Helga_2e56ef98:
    l "好吧……问吧。"

translate schinese story61_Lyna_Helga_3ee8b666:
    h "{cps=25}你快乐吗，{w=0.5}莱娜？"

translate schinese story61_Lyna_Helga_113356dc:
    l "这算什么问题啊。"

translate schinese story61_Lyna_Helga_28b3abc4:
    h "一个简单的问题。我所知的最简单的问题。"

translate schinese story61_Lyna_Helga_a81512bd:
    l "已经没有人问过我这个问题了……{size=-5}我都记不清有多久了。"

translate schinese story61_Lyna_Helga_721c9d20:
    l "我现在大概挺开心的。在这栋别墅里，和你们两个一起。"

translate schinese story61_Lyna_Helga_7b28b1da:
    h "我问的不是这个。"

translate schinese story61_Lyna_Helga_73d9202f:
    l "那我不知道，妈！我甚至都不知道幸福该是什么感觉了！"

translate schinese story61_Lyna_Helga_f6737768:
    l "我一直同时感受着好多东西。那算{i}快乐{/i}吗？其中有任何一样算吗？！"

translate schinese story61_Lyna_Helga_3558b68a:
    l "有时候我觉得这个夏天是我这辈子最快乐的时候。有时候又觉得我只是……吵得足够大，大到察觉不到自己并不快乐。"

translate schinese story61_Lyna_Helga_c477a5be:
    h "这是你跟我说过的最有自知之明的一句话。"

translate schinese story61_Lyna_Helga_b545b349:
    l "是啊，不过月亮会让人变得奇怪……"

translate schinese story61_Lyna_Helga_8b70467a:
    h "月亮把我们所有人都变得奇怪了，宝贝。"

translate schinese story61_Lyna_Helga_cbc225a5:
    h "从今以后我会更努力地对你好。"

translate schinese story61_Lyna_Helga_86c827ec:
    h "不过我不能保证我做得好。我在这件事上练了十九年的糟糕水平。抱歉。"

translate schinese story61_Lyna_Helga_41b2b18f:
    l "我不需要你做得好，妈。我只需要你是{i}认真的{/i}。"

translate schinese story61_Lyna_Helga_4919bc3e:
    centered "{font=font_narration}{cps=25}{color=#f1b500}我是认真的，{w=0.5}宝贝。"

translate schinese story61_Lyna_Helga_cb192a02:
    h "不管明天发生什么……不管什么烂摊子在朝我们过来……"

translate schinese story61_Lyna_Helga_e6b18d0d:
    h "我选择这个。和你、和你的哥哥待在这里。"

translate schinese story61_Lyna_Helga_ba485921:
    h "这个家，这个夏天，还有我们之间正变成的那个该死的关系——我全都选择！"

translate schinese story61_Lyna_Helga_e0f58924:
    h "不是因为我别无选择，而是因为这正是我想要的。"

translate schinese story61_Lyna_Helga_56877f0d:
    l "{size=-5}连可怕的部分也算……？"

translate schinese story61_Lyna_Helga_df3c3214:
    h "{cps=20}尤其是{i}那些{/i}。"

translate schinese story61_Lyna_Helga_4c830e41:
    l "妈妈……停。今晚沉重的东西够多了，好吗？"

translate schinese story61_Lyna_Helga_f20c6aed:
    l "真是的，我敢说{size=-3}{i}大家{/i}{/size}都听得快烦死这些大道理了。"

translate schinese story61_Lyna_Helga_6e5b6c76:
    l "我们倾诉了感受，我们相爱了，我们现在没事了？是吧？那现在闭嘴吧！"

translate schinese story61_Lyna_Helga_e42f1cb5:
    h "噗哈哈！天啊，我的小恶魔……"

translate schinese story61_Lyna_Helga_4342603d:
    h "{cps=25}千万别变，{w=0.5}求你了。"

translate schinese story61_Lyna_Helga_9a22cb80:
    l "抱歉，只是因为我快饿死了，妈！是{i}真的{/i}快饿死了。"

translate schinese story61_Lyna_Helga_e31b516d:
    h "莱娜，都过午夜很久了。"

translate schinese story61_Lyna_Helga_bedc9db1:
    l "那正是饿意最强的时候！这是基本科学。"

translate schinese story61_Lyna_Helga_73d71a3b:
    h "那不是科学。那只是你自制力为零。"

translate schinese story61_Lyna_Helga_daeae0e5:
    l "本质上一回事。"

translate schinese story61_Lyna_Helga_5d168725:
    h "哦，{i}闭嘴{/i}。"

translate schinese story61_Lyna_Helga_624b2aa8:
    l "*咳嗽* *咳嗽* 哼，你也一样！"

translate schinese story61_Lyna_Helga_34bb967b:
    h "小坏蛋。"

translate schinese story61_Lyna_Helga_270f90b7:
    l "*咳嗽* 我要去搜刮你的厨房了，你这个臭烘烘的{i}大猩猩{/i}！"

translate schinese story61_Lyna_Helga_4892b488:
    h "行。去吧，往你那副小骨架上多填点肉，{i}小不点{/i}。"

translate schinese story61_Lyna_Helga_cf7c80d9:
    h "哎呀，你生气的时候更好看了……"

translate schinese story61_Lyna_Helga_e9b9d96e:
    l "嘿嘿嘿！话说回来，要点什么吗~？"

translate schinese story61_Lyna_Helga_81ae4af5:
    h "不用了，宝贝。我还要在外面待几分钟。"

translate schinese story61_Lyna_Helga_e840371f:
    l "随你便。但别抽第三根，好吗？"

translate schinese story61_Lyna_Helga_1ffd60f9:
    h "啧。我是你妈，不是反过来。"

translate schinese story61_Lyna_Helga_46e1001d:
    l "喂，我是认真的！它有害、有毒、会要了你的命！"

translate schinese story61_Lyna_Helga_9def84a4:
    l "我想和我漂亮的妈妈再一起活很多很多年，好吗？"

translate schinese story61_Lyna_Helga_642ad6ad:
    l "再说了，你告诉过我你已经戒过一次了，不是吗？"

translate schinese story61_Lyna_Helga_c135cc43:
    l "求你了，别让今晚又多一个偷偷抽烟的理由。"

translate schinese story61_Lyna_Helga_aa23f32f:
    h "呃……{size=-5}快走开吧……"

translate schinese story61_Lyna_Helga_6c7fe072:
    l "别太想我，好吗？"

translate schinese story61_Lyna_Helga_757b7ebb:
    l "{shader=wave:3}我好爱好爱好爱你哦妈妈~！"

translate schinese story61_Lyna_Helga_ed2cf513:
    hm "她上一次那样叫我{i}妈妈{/i}，是什么时候……？"

translate schinese story61_Lyna_Helga_42bd999b:
    hm "是真心话，没有任何目的。"

translate schinese story61_Lyna_Helga_99876500:
    hm "我都记不清了！我一直太害怕她那种强烈，以至于错过了她只是……我女儿的每一个瞬间。"

translate schinese story61_Lyna_Helga_43f6a64a:
    hm "然后我就纳闷，她为什么会在爱里饿着长大……"

translate schinese story61_Lyna_Helga_1609851b:
    hm "开始尝试吧，赫尔加。别再逃了。别再拿逃避当借口去面对我的过去。"

translate schinese story61_Lyna_Helga_041d0c2d:
    hm "现在就开始……"

translate schinese story61_Lyna_Helga_f863dbca:
    hm "……尝试。"

translate schinese hscene50_Lyna_Helga_b8b29461:
    n "{size=+15}{cps=20}{shader=flip}几分钟后……"

translate schinese hscene50_Lyna_Helga_129cc480:
    hm "我真的说出来了。这么多年后，我终于把它说出了口。"

translate schinese hscene50_Lyna_Helga_a031d56f:
    hm "而且我不但不觉得软弱，反而觉得…… {w=0.5}强大？"

translate schinese hscene50_Lyna_Helga_df0af580:
    hm "我熬过了那一切。我也熬过了约翰的背叛。我什么都熬过来了。"

translate schinese hscene50_Lyna_Helga_241d835c:
    hm "{i}他们{/i}让我觉得自己无能为力。渺小。被利用。"

translate schinese hscene50_Lyna_Helga_308c64e9:
    hm "但和我的儿子在一起，尤其是和我的女儿在一起……"

translate schinese hscene50_Lyna_Helga_24cd9132:
    hm "{cps=20}可以不一样。"

translate schinese hscene50_Lyna_Helga_9d9135d3:
    l "嗨，妈妈——！我回来啦。"

translate schinese hscene50_Lyna_Helga_9eacfbb4:
    l "太好啦~！ {size=-5}嘻嘻嘻……"

translate schinese hscene50_Lyna_Helga_d9c62907:
    l "喂……你到底来不来睡啊？"

translate schinese hscene50_Lyna_Helga_f6bb5cea:
    h "不。还不想。"

translate schinese hscene50_Lyna_Helga_2de443ec:
    l "今晚的月亮真美，对吧？"

translate schinese hscene50_Lyna_Helga_06d9e6cd:
    l "不过你得休息一下。明天会是漫长的一天。"

translate schinese hscene50_Lyna_Helga_50ab4138:
    h "我说了不要，莱娜。我现在不想睡。"

translate schinese hscene50_Lyna_Helga_ec06fb9d:
    l "妈妈……？你没事吧？"

translate schinese hscene50_Lyna_Helga_1adb01ab:
    l "哎呀，我该给你留块巧克力的。我全吃光了，失误~"

translate schinese hscene50_Lyna_Helga_e0c7660f:
    h "过来。坐在我旁边。"

translate schinese hscene50_Lyna_Helga_0b525dab:
    l "{size=-5}好吧……？"

translate schinese hscene50_Lyna_Helga_7557653e:
    h "刚才在外面，我告诉你我已经不再害怕了。我是认真的。"

translate schinese hscene50_Lyna_Helga_4ba6d7f1:
    h "但对着月亮说很容易……"

translate schinese hscene50_Lyna_Helga_202feb4f:
    h "对着你、在我的床上说，就是另一回事了。"

translate schinese hscene50_Lyna_Helga_6e872917:
    l "妈妈……？"

translate schinese hscene50_Lyna_Helga_90347500:
    h "我是个成年女人了，该死！我知道自己想要什么。"

translate schinese hscene50_Lyna_Helga_ef38173e:
    h "{cps=30}而现在， {w=0.3}在那张床上…… {w=0.5}我想要你。"

translate schinese hscene50_Lyna_Helga_080bfd01:
    l "哦~？你终于准备好回报我的{i}恩情{/i}了？"

translate schinese hscene50_Lyna_Helga_fbb36499:
    h "不是出于愧疚，也不是出于困惑。"

translate schinese hscene50_Lyna_Helga_9de165ce:
    h "不是因为喝醉、孤单、或者害怕。"

translate schinese hscene50_Lyna_Helga_8371e666:
    h "而是因为我终于明白，用尽一切去爱你们不会毁掉我们任何一个人。"

translate schinese hscene50_Lyna_Helga_1d0a980a:
    h "{cps=25}这是唯一或许真的能拯救我们的东西。"

translate schinese hscene50_Lyna_Helga_bea2b787:
    h "{size=-5}但我需要知道你能承受我，宝贝。{i}全部{/i}的我。"

translate schinese hscene50_Lyna_Helga_612812fe:
    h "{size=-5}那些自我出生前就被我锁起来的部分……"

translate schinese hscene50_Lyna_Helga_4f09f06e:
    l "{size=-5}好、好吧。意思是……？"

translate schinese hscene50_Lyna_Helga_b98a6e00:
    h "还记得地下室的那个箱子吗？你们在那里找到我的东西。那个自慰棒，我以前的情趣内衣……"

translate schinese hscene50_Lyna_Helga_01aa676d:
    l "啊对！你年轻时那些色色的东西，嘿嘿~"

translate schinese hscene50_Lyna_Helga_0223ec05:
    h "嗯，还有另一个箱子。藏得更深。它在——"

translate schinese hscene50_Lyna_Helga_1357dd33:
    h "去帮我拿过来，好吗？"

translate schinese hscene50_Lyna_Helga_38663cca:
    l "哦妈妈，我这就去！"

translate schinese hscene50_Lyna_Helga_791fc9ba:
    l "{size=+5}天哪！这也太重了！"

translate schinese hscene50_Lyna_Helga_5ad44e84:
    h "其实一点也不重。"

translate schinese hscene50_Lyna_Helga_af6e8cd0:
    l "是啊，那下次你去拿！ {size=-5}呼……"

translate schinese hscene50_Lyna_Helga_a91b7fa2:
    h "行了，别抱怨了，放到那边去。"

translate schinese hscene50_Lyna_Helga_c71ceca3:
    l "啧！说得轻巧，你的手臂比我粗三倍……"

translate schinese hscene50_Lyna_Helga_7a7a33d2:
    l "这鬼箱子里到底装了什么啊？还上了锁。"

translate schinese hscene50_Lyna_Helga_c130b277:
    h "是我遇见你父亲之前的东西。是安娜离开之后，我摸索自己是谁的那段时间。"

translate schinese hscene50_Lyna_Helga_dc671fc7:
    l "嗯哼。比如……？"

translate schinese hscene50_Lyna_Helga_688ccd81:
    h "那时候，我明白我必须{i}做主{/i}。"

translate schinese hscene50_Lyna_Helga_c3345e12:
    h "永远强势，永远掌控一切。害怕如果我不是这样会发生什么。"

translate schinese hscene50_Lyna_Helga_2f2bf631:
    h "你父亲不喜欢我这一面。说我有攻击性。「不像淑女」。"

translate schinese hscene50_Lyna_Helga_3e04690d:
    l "噗，也难怪！你拎起来就跟没重量一样。"

translate schinese hscene50_Lyna_Helga_98db6028:
    h "哼。使劲提，丫头。"

translate schinese hscene50_Lyna_Helga_ddc7c9b9:
    h "总之，我为了他顺从了。我把那一面埋了起来，就埋在对姐姐的记忆旁边。"

translate schinese hscene50_Lyna_Helga_836b7bdb:
    l "但那个赫尔加还在里面某个地方，对吧？"

translate schinese hscene50_Lyna_Helga_a17d8f44:
    h "最后一次机会了，莱娜。我们还可以假装今晚什么都没发生过。"

translate schinese hscene50_Lyna_Helga_699c1190:
    l "我也不想再假装了，妈妈。"

translate schinese hscene50_Lyna_Helga_70ca7f14:
    h "{cps=30}就算{i}接下来出现{/i}的不是你认识的那个妈妈？"

translate schinese hscene50_Lyna_Helga_af8da288:
    l "尤其是那样的话。"

translate schinese hscene50_Lyna_Helga_7ffd7cad:
    h "好。那就仔细听着，宝贝。"

translate schinese hscene50_Lyna_Helga_bd0abf9b:
    h "你知道什么叫安全词吗？我是说，在性的情境下。"

translate schinese hscene50_Lyna_Helga_b5b6428a:
    l "知道……？我知道。"

translate schinese hscene50_Lyna_Helga_c979c493:
    h "「兔子」。"

translate schinese hscene50_Lyna_Helga_1fa4c143:
    l "兔子？什么？"

translate schinese hscene50_Lyna_Helga_ffb4d0af:
    h "如果有任何地方感觉不对，如果感觉我在任何方面伤害了你……你就说出{i}那个词{/i}，我们立刻停止。"

translate schinese hscene50_Lyna_Helga_f8dfd312:
    lm "我靠。是我想的那样吗？！"

translate schinese hscene50_Lyna_Helga_a64ff895:
    l "知、知道了…… {size=-5}兔子。"

translate schinese hscene50_Lyna_Helga_99da2d21:
    h "哎，我甜美的小宝贝女孩。一定记住那个词，好吗？"

translate schinese hscene50_Lyna_Helga_3705e99b:
    h "{cps=25}这{i}非常{/i}重要。"

translate schinese hscene50_Lyna_Helga_36981768:
    l "{size=-5}嗯哼。是的妈妈。"

translate schinese hscene50_Lyna_Helga_661efd0f:
    h "给我二十分钟。在这里等我。"

translate schinese hscene50_Lyna_Helga_278780bc:
    h "从我走出浴室的那一刻起，我就不再是你认识的那个妈妈了。"

translate schinese hscene50_Lyna_Helga_6640f4a5:
    l "咦……？你要在里面做什么？"

translate schinese hscene50_Lyna_Helga_ad6c565e:
    centered "{font=font_narration}{cps=25}{color=#f1b500}变成一个我已经很久很久没有做过的人。"

translate schinese hscene50_Lyna_Helga_137181ff:
    lm "她第一次舔我阴蒂的时候不是叫我「小兔子」吗……？"

translate schinese hscene50_Lyna_Helga_aa926188:
    lm "安全词。她给了我一个他妈的安全词！"

translate schinese hscene50_Lyna_Helga_fd6307f8:
    lm "今年夏天我本想突破她的底线……但现在她要突破我的了。"

translate schinese hscene50_Lyna_Helga_2244cf77:
    n "{size=+15}{cps=20}{shader=flip}二十五分钟后……"

translate schinese hscene50_Lyna_Helga_032cda80:
    lm "她怎么这么慢？我该去敲门吗？"

translate schinese hscene50_Lyna_Helga_79fac130:
    h "咳咳！" with vpunch

translate schinese hscene50_Lyna_Helga_e8e220e9:
    lm "{shader=jitter:2.0,2.0}{size=+5}{cps=25}什、 {w=0.5}么。 {w=0.5}{size=+10}操？！"

translate schinese hscene50_Lyna_Helga_aece4db5:
    h "怎么样？说句话。"

translate schinese hscene50_Lyna_Helga_0c5eaac8:
    h "{size=+5}嗯？！{/size} 你到底知不知道自己在干什么，小丫头？"

translate schinese hscene50_Lyna_Helga_409b3c1e:
    l "{size=-5}在、在……自慰……因为是你……"

translate schinese hscene50_Lyna_Helga_8f5162ad:
    h "{size=+5}在我的床上？！你敢试试看，你这个肮脏的丫头！" with vpunch

translate schinese hscene50_Lyna_Helga_c4c3ff79:
    l "{size=-5}我……哎呀，冷静点。我对不起。只是…… {size=-10}哇。"

translate schinese hscene50_Lyna_Helga_1fb453ab:
    l "{size=-5}你、你怎么可以这么——"

translate schinese hscene50_Lyna_Helga_22defce4:
    h "接下来的话，好好想清楚再说。"

translate schinese hscene50_Lyna_Helga_159190f5:
    l "{cps=25}强大。 {w=0.5}性感。 {w=0.5}而且有点…… {w=0.3}{size=-5}可怕？"

translate schinese hscene50_Lyna_Helga_0ece273f:
    h "可怕？很好。我喜欢。"

translate schinese hscene50_Lyna_Helga_73839d20:
    h "现在站起来。好好面对我。"

translate schinese hscene50_Lyna_Helga_df95af24:
    l "妈妈，你……穿{i}那些{/i}有多高？！天哪。"

translate schinese hscene50_Lyna_Helga_84ff1b40:
    h "比平时高。"

translate schinese hscene50_Lyna_Helga_56c47561:
    l "那当然！我才到奶子那么高。"

translate schinese hscene50_Lyna_Helga_dacd01f3:
    l "你看，我现在就正好在奶子这个高度吧？"

translate schinese hscene50_Lyna_Helga_2795e8bf:
    h "嗯。多方便，是吧？"

translate schinese hscene50_Lyna_Helga_89d2981c:
    h "怎么样？你觉得如何？"

translate schinese hscene50_Lyna_Helga_f9ffbc70:
    l "{size=-5}呃，我…… {size=-10}我呃……"

translate schinese hscene50_Lyna_Helga_4f940e94:
    h "你该不会紧张了吧？"

translate schinese hscene50_Lyna_Helga_87f28df1:
    h "那个说要在我床上为我自慰的不知廉耻的丫头去哪儿了，嗯？"

translate schinese hscene50_Lyna_Helga_a07a6ac1:
    h "{cps=25}你害羞的样子真可爱。"

translate schinese hscene50_Lyna_Helga_7090f383:
    h "{cps=25}让我想起某一天……"

translate schinese hscene50_Lyna_Helga_eab945a5:
    h "{cps=25}……我不得不教训一个坏女孩的那一天。"

translate schinese hscene50_Lyna_Helga_3cb57f96:
    h "这种机会可不是每天都有，对吧？"

translate schinese hscene50_Lyna_Helga_21160a36:
    h "你怎么这么安静，嗯？说话。告诉我你在想什么。"

translate schinese hscene50_Lyna_Helga_1ec57824:
    h "你要是不说，我会不高兴。而让我不高兴就意味着{i}惩罚{/i}，懂吗？"

translate schinese hscene50_Lyna_Helga_de824b94:
    h "所以呢？看到这个……{i}我{/i}之后，你不想离开了吗？"

translate schinese hscene50_Lyna_Helga_50a7ca6d:
    h "{cps=25}你…… {w=0.5}不害怕吗？"

translate schinese hscene50_Lyna_Helga_fff58425:
    l "当、当然不怕！这个…… {size=-5}这个其实太让人兴奋了。"

translate schinese hscene50_Lyna_Helga_d88cacc9:
    l "{size=-10}就算你看起来有点可怕，还是。"

translate schinese hscene50_Lyna_Helga_50825147:
    h "很好。看来我们想到一块儿去了。"

translate schinese hscene50_Lyna_Helga_8b5d3669:
    l "{size=-5}是的。我想要这样。"

translate schinese hscene50_Lyna_Helga_736e3655:
    h "那你得遵守一条非常重要的规则。"

translate schinese hscene50_Lyna_Helga_cd22f90d:
    h "{cps=25}如果你今晚留在这里…… {w=0.5}你就得 {w=0.3}{size=+5}{i}臣服{/i}。"

translate schinese hscene50_Lyna_Helga_ec25a353:
    l "{size=-5}那我肯定更不会走了。"

translate schinese hscene50_Lyna_Helga_5f94de20:
    h "那就脱掉衣服。全脱光。现在就脱。"

translate schinese hscene50_Lyna_Helga_b73a8f0d:
    l "你、你是打算就坐在那里看着……？"

translate schinese hscene50_Lyna_Helga_92816592:
    h "哦？别告诉我这个家里最大的色狼突然对这种事有意见了。"

translate schinese hscene50_Lyna_Helga_dc60854e:
    l "不。当然没有。"

translate schinese hscene50_Lyna_Helga_c66ff7ce:
    h "那就闭嘴开始。我没耐心了，丫头。"

translate schinese hscene50_Lyna_Helga_d8adc138:
    h "没错……让我看看你那娇小的身体。"

translate schinese hscene50_Lyna_Helga_e9c51902:
    h "快点。把那条紧身小内裤也脱掉。"

translate schinese hscene50_Lyna_Helga_ceece0f2:
    h "对……宝贝。让我看看你的全身。"

translate schinese hscene50_Lyna_Helga_6cdf8bdf:
    h "现在转过去给妈妈看……"

translate schinese hscene50_Lyna_Helga_47c3d67b:
    h "而且要慢慢转。这是命令。"

translate schinese hscene50_Lyna_Helga_19031c2f:
    l "{i}非常{/i}慢……？"

translate schinese hscene50_Lyna_Helga_7014d575:
    h "对啊，给我你的最佳表演。"

translate schinese hscene50_Lyna_Helga_f3fd7ae1:
    h "呃……就是这样。"

translate schinese hscene50_Lyna_Helga_6597349f:
    h "啊……哦我的{i}天{/i}啊，对……" with vpunch

translate schinese hscene50_Lyna_Helga_7b83e7d2:
    l "妈妈？！你也在自慰！ {size=-5}你说过我不可以……"

translate schinese hscene50_Lyna_Helga_ea78956d:
    h "{cps=25}你不行。 {w=0.5}我可以。 {w=0.5}懂了吗？"

translate schinese hscene50_Lyna_Helga_0a16dc40:
    l "{size=-10}这也太坏了，你知道的……"

translate schinese hscene50_Lyna_Helga_f8fb7439:
    h "{size=+5}你说什么？！"

translate schinese hscene50_Lyna_Helga_fb387233:
    h "{size=+5}不准质疑我。清楚了吗？！"

translate schinese hscene50_Lyna_Helga_e123c1b8:
    l "{size=-5}是、是。对不起……"

translate schinese hscene50_Lyna_Helga_e2444a65:
    h "明智的选择。"

translate schinese hscene50_Lyna_Helga_41b91998:
    h "看吧？你安静的时候更乖。"

translate schinese hscene50_Lyna_Helga_75804c7c:
    h "我得说，你光着身子的样子好看多了，你不觉得吗？"

translate schinese hscene50_Lyna_Helga_e916c677:
    h "{cps=25}我美丽赤裸的女儿。 {w=0.5}这么急着服从。"

translate schinese hscene50_Lyna_Helga_9eef24b9:
    l "{size=-5}不过这也太不公平了。"

translate schinese hscene50_Lyna_Helga_ec3bc90c:
    h "啧。你就是不肯闭嘴，是吧？"

translate schinese hscene50_Lyna_Helga_131f5182:
    l "{size=-5}真的……太不公平了。真的。"

translate schinese hscene50_Lyna_Helga_aeba1716:
    h "什么事困扰着你？说。我允许你抱怨一次。"

translate schinese hscene50_Lyna_Helga_4c5a9281:
    l "{size=-5}就是那个……你现在比我大好多好多。"

translate schinese hscene50_Lyna_Helga_67da9986:
    h "然后呢？没什么新鲜的。"

translate schinese hscene50_Lyna_Helga_c94a1844:
    h "我可不一般。拿你跟我比，白费力气。"

translate schinese hscene50_Lyna_Helga_d088f96a:
    l "{size=-5}不过穿上那双高跟和紧身束腰，就更夸张了。"

translate schinese hscene50_Lyna_Helga_cb915348:
    l "{size=-5}说实话真烦。我在{i}你{/i}面前觉得自己很可悲。"

translate schinese hscene50_Lyna_Helga_cb668a74:
    l "{size=-5}就像站在宏伟雕像旁边的一只吉娃娃之类的……"

translate schinese hscene50_Lyna_Helga_64800f72:
    h "哈！也许我该开始叫你我的傻小狗了，嗯？"

translate schinese hscene50_Lyna_Helga_fa9f2a4f:
    l "喂！我才不是你的狗！" with vpunch

translate schinese hscene50_Lyna_Helga_4e1c5d1e:
    h "这是你说的，不是我说的。"

translate schinese hscene50_Lyna_Helga_45a76001:
    l "{size=-5}滚开。"

translate schinese hscene50_Lyna_Helga_94ad552f:
    h "{size=+10}把你那张肮脏的嘴闭上。"

translate schinese hscene50_Lyna_Helga_8a43d6f6:
    h "{cps=25}{size=+5}你看起来确实很{i}可悲{/i}， {w=0.5}呢。"

translate schinese hscene50_Lyna_Helga_11a5410f:
    h "抬头看着我，丫头。"

translate schinese hscene50_Lyna_Helga_d1139c42:
    l "{size=-5}我{i}确实{/i}在往上看。根本没有别的方向可看。"

translate schinese hscene50_Lyna_Helga_42833663:
    h "哼。习惯这个视角吧，小混蛋。"

translate schinese hscene50_Lyna_Helga_5acbfb7f:
    h "整个夏天你都在这个家里指手画脚，对吧？"

translate schinese hscene50_Lyna_Helga_35eb5686:
    l "{size=-5}指手画脚……？你什么意思？"

translate schinese hscene50_Lyna_Helga_5185bc37:
    h "噗，别装傻。指挥你哥哥。指挥我。"

translate schinese hscene50_Lyna_Helga_c6feb58b:
    h "{cps=25}施压。 {w=0.3}谋划。 {w=0.3}算计。 {w=0.3}胡闹。"

translate schinese hscene50_Lyna_Helga_08cc1c23:
    h "今晚你可不许{i}支使{/i}任何人，听见了吗？"

translate schinese hscene50_Lyna_Helga_dc46d98b:
    h "今晚你就得是你实际那么渺小。"

translate schinese hscene50_Lyna_Helga_d9d6ed92:
    l "{size=-10}好、好吧……？"

translate schinese hscene50_Lyna_Helga_477677bf:
    h "不过确实很烦，对吧。这个身高差。"

translate schinese hscene50_Lyna_Helga_305d874c:
    h "我想好好看看你，把你拉近到我的{i}唇边{/i}。"

translate schinese hscene50_Lyna_Helga_1ba2791c:
    h "看来我们得解决这个问题。"

translate schinese hscene50_Lyna_Helga_3719e3aa:
    l "{size=-5}呃……怎么？也许也给我来双高跟鞋~？ {size=-5}嘿嘿。"

translate schinese hscene50_Lyna_Helga_ebce8c2c:
    h "{shader=wave:2}{size=+10}哇哈哈哈！"

translate schinese hscene50_Lyna_Helga_0f997ce7:
    l "{size=+5}哎，拜托！你认真的吗？！"

translate schinese hscene50_Lyna_Helga_35d090cb:
    h "好了。解决了。"

translate schinese hscene50_Lyna_Helga_0e27a263:
    l "{size=-5}妈妈，那{i}一点{/i}也不好笑。"

translate schinese hscene50_Lyna_Helga_cf8564ec:
    h "对。事实上超级好笑！"

translate schinese hscene50_Lyna_Helga_8f5bb0f7:
    l "{size=+5}你就是……！{/size} 你就像捡个小婴儿一样把我拎起来了！啧。"

translate schinese hscene50_Lyna_Helga_01223a9d:
    h "没错。我的{size=+5}{i}宝贝{/i}{/size}女孩。"

translate schinese hscene50_Lyna_Helga_53a59206:
    h "你知道吗？我每一秒都很享受。"

translate schinese hscene50_Lyna_Helga_29d04101:
    l "可、可我都十九岁了…… {size=-5}天哪。"

translate schinese hscene50_Lyna_Helga_3a983339:
    h "体重跟我的健身包差不多！哈哈哈！"

translate schinese hscene50_Lyna_Helga_9a618fb3:
    l "那倒也——我是说，应该没那么夸张吧。"

translate schinese hscene50_Lyna_Helga_411c8657:
    l "我想这就是娇小身板的好处之一。哈哈。"

translate schinese hscene50_Lyna_Helga_5403dd57:
    h "{size=+5}嘘！{/size} 别闹了，丫头。"

translate schinese hscene50_Lyna_Helga_ede4df59:
    h "别忘了你为什么在这里……"

translate schinese hscene50_Lyna_Helga_404b7c62:
    h "今晚我要近距离探索你身体的每一处。不许打扰。"

translate schinese hscene50_Lyna_Helga_d8a72506:
    l "{size=-5}妈妈，这真的好奇怪。我不习惯被这样……摆弄。"

translate schinese hscene50_Lyna_Helga_cb9c5eae:
    h "哦，真的吗？别假装你不喜欢，小混蛋。"

translate schinese hscene50_Lyna_Helga_6f9e1607:
    h "现在，如果你想看起来不那么可怜，最好把弓着的背挺直。"

translate schinese hscene50_Lyna_Helga_d6747308:
    h "摆一个你会的性感姿势，不然我们就有麻烦了。明白了吗？"

translate schinese hscene50_Lyna_Helga_55ab95cb:
    h "就是这样！这才是我想要的色狼。"

translate schinese hscene50_Lyna_Helga_e91bad5e:
    h "看吧？你显然知道该怎么做，也知道为什么要这么做。"

translate schinese hscene50_Lyna_Helga_53aefcd8:
    h "整个夏天你都得意洋洋地展示着这具身体，对吧~？"

translate schinese hscene50_Lyna_Helga_41614a3b:
    h "那些暴露的衣服，那些小得可怜的比基尼……"

translate schinese hscene50_Lyna_Helga_10c34ab8:
    h "为了我。为了你哥哥。为了任何一个有眼睛的人。"

translate schinese hscene50_Lyna_Helga_31b37c3a:
    l "{size=-5}也许……"

translate schinese hscene50_Lyna_Helga_58797c83:
    h "{i}当然{/i}。但现在轮到妈妈独占你了。"

translate schinese hscene50_Lyna_Helga_feeba8be:
    l "{size=-5}妈妈……你的指甲好痒……"

translate schinese hscene50_Lyna_Helga_5c2a2cfc:
    h "不是靠偷瞄，也不是靠洗澡的借口……"

translate schinese hscene50_Lyna_Helga_52784563:
    h "{cps=25}我可以放开{i}他妈的{/i}慢慢享用我的宝贝女孩。"

translate schinese hscene50_Lyna_Helga_e0799a8a:
    h "怎么了，嗯？你平时可不害羞。难道你……害怕了？"

translate schinese hscene50_Lyna_Helga_a7813ea3:
    l "{size=-5}不、没有。只是你的手。有点凉。"

translate schinese hscene50_Lyna_Helga_739ffc8e:
    h "你的就不是吗？所以你才托着自己的奶子？"

translate schinese hscene50_Lyna_Helga_95c8e0dd:
    h "你不必藏着它们。也许它们能帮我把手捂热……"

translate schinese hscene50_Lyna_Helga_fee4dd42:
    l "{size=-5}你老是盯着看……别看了……"

translate schinese hscene50_Lyna_Helga_a5f5acc2:
    h "那是命令，丫头。双手放到背后。不许遮任何地方。"

translate schinese hscene50_Lyna_Helga_c0d17d16:
    l "{size=-5}妈妈……不要……"

translate schinese hscene50_Lyna_Helga_25cca287:
    h "现在就照做。别让我重复。"

translate schinese hscene50_Lyna_Helga_ba8376dc:
    h "天哪。看看这个因为年龄就假装成成年女人的小心眼东西。"

translate schinese hscene50_Lyna_Helga_79d24b36:
    h "满身小孩子的臭脾气，满脑子肮脏的小算盘。装在一个妈妈能折起来塞进钱包的小小身躯里。"

translate schinese hscene50_Lyna_Helga_b54ff439:
    l "{size=-5}别、别拿我的身材开玩笑。啧。"

translate schinese hscene50_Lyna_Helga_db88e4c0:
    h "哎哎，戳到痛处了？"

translate schinese hscene50_Lyna_Helga_64131036:
    h "小恶魔是不是觉得……{i}没有安全感{/i}？"

translate schinese hscene50_Lyna_Helga_e6bacd68:
    l "{size=-5}才没有……我为我的身材骄傲。我也知道你喜欢它。"

translate schinese hscene50_Lyna_Helga_7f77413d:
    h "那你为什么脸红得这么厉害，嗯？还这么安静？"

translate schinese hscene50_Lyna_Helga_3e117fbb:
    h "明明都已经到我这个高度了，你还是几乎不敢看我。"

translate schinese hscene50_Lyna_Helga_adbccea9:
    h "{cps=25}我觉得某个人怕得像个小不点、 {w=0.3}小得可怜、 {w=0.3}{i}小姑娘{/i}一样。"

translate schinese hscene50_Lyna_Helga_8edc9977:
    l "{size=-5}噗。 {size=-10}你做梦吧，你这个丑陋的色猩猩……"

translate schinese hscene50_Lyna_Helga_806b1bcb:
    h "嗯？！你刚才叫我什么？"

translate schinese hscene50_Lyna_Helga_2c5d37e7:
    l "{size=-5}没、没有啊…… {size=-10}没什么。"

translate schinese hscene50_Lyna_Helga_d3b0ea76:
    h "很好。我就知道……"

translate schinese hscene50_Lyna_Helga_90171c65:
    h "{size=-5}{cps=20}我口袋里的小色狼。"

translate schinese hscene50_Lyna_Helga_ee45d60c:
    l "{size=-5}唔嗯……！"

translate schinese hscene50_Lyna_Helga_88fffe3d:
    h "{size=-5}对啊，看看那个……"

translate schinese hscene50_Lyna_Helga_8ce1ae45:
    l "{size=-5}看什么？"

translate schinese hscene50_Lyna_Helga_605f5866:
    h "{size=-5}我刚给你盖了个章。"

translate schinese hscene50_Lyna_Helga_0896d05e:
    h "现在任何看着你的人都知道，你的嘴唇上沾着谁的嘴。"

translate schinese hscene50_Lyna_Helga_74671d54:
    h "再来一个，稳赚不赔。嘿嘿……"

translate schinese hscene50_Lyna_Helga_7003aa4e:
    h "现在让我们好好{i}看看{/i}你，怎么样？"

translate schinese hscene50_Lyna_Helga_70161a76:
    l "{size=-5}什、你想对我做什么……？"

translate schinese hscene50_Lyna_Helga_9422078e:
    h "哦，你会喜欢的，色狼。"

translate schinese hscene50_Lyna_Helga_991bcc74:
    h "我要探索你赤裸身体的每一处。清楚了吗？"

translate schinese hscene50_Lyna_Helga_c581977d:
    l "{size=-5}知、知道了。"

translate schinese hscene50_Lyna_Helga_71b492f0:
    h "那就准备好迎接我吧。转过身去。"

translate schinese hscene50_Lyna_Helga_740a1550:
    h "多么漂亮的小胸部。真是让人着迷。"

translate schinese hscene50_Lyna_Helga_10863aa6:
    l "{size=-5}我以为你不喜欢小的。"

translate schinese hscene50_Lyna_Helga_9bebf526:
    h "我喜欢。它们只是太完美了……"

translate schinese hscene50_Lyna_Helga_795d738e:
    h "发育得刚刚好。像是既想保持挺翘可爱，又……"

translate schinese hscene50_Lyna_Helga_f783fe5d:
    h "……也能方便地被握住。"

translate schinese hscene50_Lyna_Helga_7aae472b:
    l "啊嗯～！" with vpunch

translate schinese hscene50_Lyna_Helga_1f23f8e6:
    h "也很敏感呢。"

translate schinese hscene50_Lyna_Helga_81a9391b:
    l "{size=-5}呃……闭嘴。"

translate schinese hscene50_Lyna_Helga_cf4d5672:
    h "嗯。我记得它们开始长出来的时候。"

translate schinese hscene50_Lyna_Helga_f4e2a1ee:
    l "{size=-5}你、你真的……？"

translate schinese hscene50_Lyna_Helga_5e64978b:
    h "真的。你是个晚熟的孩子。十二岁，十三岁……还是什么都没有。完全是平的。"

translate schinese hscene50_Lyna_Helga_941b2b77:
    h "有时候你会偷偷看我换衣服，用那双又大又圆的眼睛。"

translate schinese hscene50_Lyna_Helga_e8dcb825:
    l "{size=-5}我{i}没有{/i}那样做。"

translate schinese hscene50_Lyna_Helga_cd8b9b72:
    h "你绝对有。就像小狗看人吃牛排一样。"

translate schinese hscene50_Lyna_Helga_1b10ef63:
    l "{size=-10}好吧……也许有一点。"

translate schinese hscene50_Lyna_Helga_9a1a0781:
    h "你那时候拼命想变得跟妈妈一样。"

translate schinese hscene50_Lyna_Helga_a469a32d:
    h "每个月都问我同一个问题，「我什么时候能像你的一样？」"

translate schinese hscene50_Lyna_Helga_035c0ef7:
    l "{size=-5}因为你的真的是天生完美，太不公平了……"

translate schinese hscene50_Lyna_Helga_76d70e10:
    h "不过你的也有一种魅力。这么多年过去了，还是……"

translate schinese hscene50_Lyna_Helga_dba956f2:
    l "{size=-5}唔嗯……！"

translate schinese hscene50_Lyna_Helga_99ca0ceb:
    h "可爱的小东西。几乎没怎么长大。"

translate schinese hscene50_Lyna_Helga_3cc22848:
    h "又小又挺，就那么一小把。"

translate schinese hscene50_Lyna_Helga_80863303:
    h "其实连一小把都不到。"

translate schinese hscene50_Lyna_Helga_85239606:
    l "{size=-5}噗，随便啦……"

translate schinese hscene50_Lyna_Helga_e1046b52:
    h "我那平得像块板的宝贝女儿。"

translate schinese hscene50_Lyna_Helga_3fb61fa1:
    l "{size=-5}而且我还挺自豪的，你知道的……"

translate schinese hscene50_Lyna_Helga_9aee0062:
    h "对吧。但我知道你心里总有一部分会嫉妒，对不对？"

translate schinese hscene50_Lyna_Helga_d516712c:
    l "{size=-5}哼。你现在就是在故意欺负我。"

translate schinese hscene50_Lyna_Helga_3ac10401:
    h "我告诉你，在你这个年纪之前，我的胸就已经很丰满了。"

translate schinese hscene50_Lyna_Helga_1fbdf319:
    l "{size=-5}对对对，水是湿的……"

translate schinese hscene50_Lyna_Helga_333c526e:
    h "我一直纳闷为什么它们最后没长成我这么大。"

translate schinese hscene50_Lyna_Helga_07a96d36:
    l "别说了！我懂了。 {size=-5}你这个大胸恶霸。" with vpunch

translate schinese hscene50_Lyna_Helga_d9d12379:
    h "事实上，你的发育结果{i}好得多{/i}，你不觉得吗？"

translate schinese hscene50_Lyna_Helga_f8997de6:
    l "咦？等等，什么……？"

translate schinese hscene50_Lyna_Helga_13e63435:
    h "对。我的很沉。太大了。"

translate schinese hscene50_Lyna_Helga_511f5e31:
    l "不可能吧！你开玩笑。我巴不得有那对。"

translate schinese hscene50_Lyna_Helga_61fa0b31:
    h "我可不这么认为。看。你没注意到吗……"

translate schinese hscene50_Lyna_Helga_3c7979b7:
    h "看？没有支撑它们就垂得那么厉害。"

translate schinese hscene50_Lyna_Helga_d062aae7:
    h "过了四十岁，地心引力对大奶子可不留情，相信我。"

translate schinese hscene50_Lyna_Helga_ea3351bb:
    h "但你的呢？等你三十岁的时候，它们会是那个样子。四十岁。甚至更久。"

translate schinese hscene50_Lyna_Helga_a655cd57:
    h "紧致。挺翘。不用任何东西托着的小小隆起。"

translate schinese hscene50_Lyna_Helga_2a256be2:
    l "{size=-5}你真的这么觉得……？"

translate schinese hscene50_Lyna_Helga_51fb6a35:
    h "我当然知道。我是个看着自己的身体变化了几十年的女人。"

translate schinese hscene50_Lyna_Helga_0e8f3763:
    h "而且我告诉你：你拥有的真的是一份礼物。"

translate schinese hscene50_Lyna_Helga_44a3e54f:
    h "要说该嫉妒的人，那个人是我。"

translate schinese hscene50_Lyna_Helga_713bb031:
    l "它们以后还是会长得像你那样，你知道的？我才十九岁。"

translate schinese hscene50_Lyna_Helga_cecc6a9e:
    h "噗。你早就过了青春期了，丫头。别指望了。"

translate schinese hscene50_Lyna_Helga_e9d28c03:
    l "我是认真的！我知道它们肯定还会再长一些……"

translate schinese hscene50_Lyna_Helga_a62f2410:
    h "哦？什么让你这么确定？"

translate schinese hscene50_Lyna_Helga_d98dceed:
    l "呃，那个……你知道， {size=-5}如果我哪天怀孕了……"

translate schinese hscene50_Lyna_Helga_1c94530e:
    h "哈哈！那就是你的终极计划？！让某个男生搞大你的肚子，就为了终于能长出奶子？"

translate schinese hscene50_Lyna_Helga_4e1ac4b0:
    h "{shader=wave:2}{size=+5}哈哈哈哈！"

translate schinese hscene50_Lyna_Helga_c84d8137:
    l "啧。我是说， {size=-5}这算是{i}好处{/i}之一……"

translate schinese hscene50_Lyna_Helga_371a7681:
    h "等等……你是当真的？！我的天。"

translate schinese hscene50_Lyna_Helga_41d67339:
    h "太可爱了！不过你还是个色狼。"

translate schinese hscene50_Lyna_Helga_8a8c3ec9:
    l "{size=-5}哼……"

translate schinese hscene50_Lyna_Helga_bb2f5f08:
    h "但你说得对。如果那真的发生了……它们肯定会变的。"

translate schinese hscene50_Lyna_Helga_d1d67f48:
    h "你的奶子会胀大，会充满乳汁，会变得更沉……"

translate schinese hscene50_Lyna_Helga_0de8786a:
    h "相信我，我知道。怀着你俩的时候，我的几乎涨了两个罩杯。"

translate schinese hscene50_Lyna_Helga_1070ad75:
    l "两个罩杯？！从{i}那里{/i}？！"

translate schinese hscene50_Lyna_Helga_3c574706:
    h "嗯哼。你那个双胞胎哥哥差点把我吸干了。"

translate schinese hscene50_Lyna_Helga_7f57d938:
    h "事实上你更糟。"

translate schinese hscene50_Lyna_Helga_09f3431f:
    l "{size=-5}所以我从第一天起就迷上你的奶子……"

translate schinese hscene50_Lyna_Helga_a21df322:
    h "从第一分钟开始！护士们得把你从这儿撬开。"

translate schinese hscene50_Lyna_Helga_596917d2:
    l "嘿嘿！有些事果然永远不会变。"

translate schinese hscene50_Lyna_Helga_f167ed51:
    h "而且你长出牙以后，我的小恶魔也常常会给我留下些咬痕{i}礼物{/i}……"

translate schinese hscene50_Lyna_Helga_4846db94:
    l "哇！我小时候原来这么凶啊！"

translate schinese hscene50_Lyna_Helga_876e52d6:
    h "确实…… {size=-5}我想是时候报复一下了，嗯？"

translate schinese hscene50_Lyna_Helga_105d0a6c:
    l "哦？那就来啊，随你怎么摸。"

translate schinese hscene50_Lyna_Helga_025ebfc8:
    l "我敢说你整个夏天都他妈特别想这么干，你这个迷小小奶子的色狼~"

translate schinese hscene50_Lyna_Helga_d0274bb7:
    h "{size=+5}闭嘴！别再废话了。"

translate schinese hscene50_Lyna_Helga_878cdb58:
    l "{size=-5}咦？可、可是你先……"

translate schinese hscene50_Lyna_Helga_44980e7c:
    h "啊，所以我的小奶子可爱到能破掉邪恶妈妈的法术？"

translate schinese hscene50_Lyna_Helga_2fe6fa5f:
    l "啊，所以我的奶子可爱到能破掉邪恶妈妈的法术？"

translate schinese hscene50_Lyna_Helga_b27c13bf:
    h "{size=+5}安静！{/size} 你忘了吗？你不是来被伺候的。"

translate schinese hscene50_Lyna_Helga_980ec661:
    h "{size=+5}你是来服从我的，丫头。"

translate schinese hscene50_Lyna_Helga_a6dde566:
    l "{size=-5}好、好吧……对不起。"

translate schinese hscene50_Lyna_Helga_c4c97b98:
    h "还有你的奶子……？现在是我的财产了。它们是{i}我的{/i}。"

translate schinese hscene50_Lyna_Helga_9febc876:
    h "我说清楚了吗，你这个没大没小的小混蛋？！"

translate schinese hscene50_Lyna_Helga_0166114f:
    h "我说清楚了吗，你这个 小混蛋？！"

translate schinese hscene50_Lyna_Helga_3d8f2d89:
    l "{size=-10}是、是、是的。"

translate schinese hscene50_Lyna_Helga_bc9cc4c1:
    l "呃……！"

translate schinese hscene50_Lyna_Helga_6b6bfba6:
    h "{size=+5}大声点！我没听见。"

translate schinese hscene50_Lyna_Helga_4328b061:
    l "是的！我的奶子全都是{i}你的{/i}！"

translate schinese hscene50_Lyna_Helga_a1d43a0a:
    h "没错。你最好别忘了。"

translate schinese hscene50_Lyna_Helga_d70658cc:
    l "{size=-5}只是别拉得太用力……"

translate schinese hscene50_Lyna_Helga_d7a55941:
    h "为什么不？那声可爱的娇喘已经告诉了我一切。"

translate schinese hscene50_Lyna_Helga_f2beb98a:
    l "{size=-5}拜、拜托，动作轻一点……"

translate schinese hscene50_Lyna_Helga_2ac85b02:
    h "像这样，嗯？"

translate schinese hscene50_Lyna_Helga_9f7cfc99:
    l "{size=-5}对……你之前指甲掐得有点深。很疼。"

translate schinese hscene50_Lyna_Helga_64d560a1:
    h "哎哟，疼了？我可怜的小东西~"

translate schinese hscene50_Lyna_Helga_b7a23ffd:
    h "只要你乖，就不会疼了……明白了吗？"

translate schinese hscene50_Lyna_Helga_6821c0dd:
    l "{size=-5}是的，嗯……我会乖的。"

translate schinese hscene50_Lyna_Helga_5ec48fd2:
    h "乖女孩。这才是我想听的。"

translate schinese hscene50_Lyna_Helga_3b44825c:
    l "{size=-5}你为什么停了……？"

translate schinese hscene50_Lyna_Helga_0647a94f:
    l "{size=-5}请继续摸我的乳头，真的很舒服……"

translate schinese hscene50_Lyna_Helga_a68b21ae:
    h "闭嘴。我有个更好的主意。"

translate schinese hscene50_Lyna_Helga_64bcbc72:
    h "对了，你想不想知道我为什么喜欢小奶子？"

translate schinese hscene50_Lyna_Helga_6d3af2b7:
    l "{size=-5}为什么……？"

translate schinese hscene50_Lyna_Helga_1b9b889c:
    h "{cps=30}{i}一切{/i}都刚好含进我嘴里。{w=1.5}{nw}"

translate schinese hscene50_Lyna_Helga_be06fb12:
    l "{size=+5}啊！我的天哪！"

translate schinese hscene50_Lyna_Helga_a67afa86:
    h "{size=-5}唔嗯……"

translate schinese hscene50_Lyna_Helga_f3576b78:
    hm "终于。我等这一刻回报你已经很久了……"

translate schinese hscene50_Lyna_Helga_cc4a8568:
    hm "这下没有回头路了。如果她本来就迷恋我，那现在她会上瘾的。"

translate schinese hscene50_Lyna_Helga_a18932c8:
    hm "而我？我已经没有任何借口了。我想要我的宝贝女儿，跟想要她哥哥一样强烈。"

translate schinese hscene50_Lyna_Helga_1d49dc7b:
    h "啊，真美味……"

translate schinese hscene50_Lyna_Helga_447806a3:
    l "{size=-5}妈妈……拜、拜托——"

translate schinese hscene50_Lyna_Helga_d9a34d82:
    h "拜托什么？"

translate schinese hscene50_Lyna_Helga_b956d283:
    l "{size=-5}我不知道……就是别停……但同时……我受不了了！"

translate schinese hscene50_Lyna_Helga_b6ff7656:
    h "嘘。你{i}能{/i}受得住。妈妈给你什么你就受什么。"

translate schinese hscene50_Lyna_Helga_f6ec8016:
    h "现在安静享受。早该这样了。"

translate schinese hscene50_Lyna_Helga_8fdec2de:
    l "呜～～嗯！"

translate schinese hscene50_Lyna_Helga_4edbe3fb:
    hm "我真是个固执的笨蛋。让自己的女儿玩了整整好几周……"

translate schinese hscene50_Lyna_Helga_2f7f8052:
    hm "却还在拼命克制，不肯越过最后那条线，用同样的下流事回报她们。"

translate schinese hscene50_Lyna_Helga_27dc6643:
    hm "我在骗谁呢。我早就迫不及待想扑向这具年轻的青春期身体了。"

translate schinese hscene50_Lyna_Helga_44d39333:
    hm "我一直梦想着这个。梦想着含着这些小花蕾，听我的宝贝女儿为我呻吟。"

translate schinese hscene50_Lyna_Helga_c8a9b2bd:
    l "{size=+5}呜呜呜……！妈妈！"

translate schinese hscene50_Lyna_Helga_18cfff87:
    l "{size=+5}呃啊啊！{/size} 等、等等！别用牙！"

translate schinese hscene50_Lyna_Helga_672ae849:
    h "{size=-5}手……"

translate schinese hscene50_Lyna_Helga_3783107b:
    l "什么？！{w=1.0}{nw}"

translate schinese hscene50_Lyna_Helga_b6d2744d:
    h "{size=-5}又一次放到背后。不然我真的会咬你。"

translate schinese hscene50_Lyna_Helga_6a566136:
    l "可、可是我想抓住你——"

translate schinese hscene50_Lyna_Helga_d90e8777:
    h "{size=-5}我不管你想要什么。服从。"

translate schinese hscene50_Lyna_Helga_ece0f6bd:
    h "很好。还有，不许再那样扯我的头发。"

translate schinese hscene50_Lyna_Helga_39c78e34:
    l "{size=-5}对、对不起……太激动了。"

translate schinese hscene50_Lyna_Helga_d079fa18:
    l "{size=-5}请继续含着……"

translate schinese hscene50_Lyna_Helga_db24e01b:
    h "贪心的小混蛋。"

translate schinese hscene50_Lyna_Helga_bf46eb26:
    l "呜～～操……！"

translate schinese hscene50_Lyna_Helga_29b96542:
    hm "这么久以来一直偷偷觊觎着我的孩子们……"

translate schinese hscene50_Lyna_Helga_77a806c5:
    hm "我真是个淫荡货。一个大婊子。一个糟糕的母亲。"

translate schinese hscene50_Lyna_Helga_66b23b9e:
    hm "因为她们，这个夏天我自慰的次数大概比过去十年加起来都多。"

translate schinese hscene50_Lyna_Helga_59557ad8:
    hm "而现在，我终于要夺回一直都属于我的东西。"

translate schinese hscene50_Lyna_Helga_620f7592:
    l "操～～！ {size=-5}妈妈……"

translate schinese hscene50_Lyna_Helga_248d5fb4:
    h "呃啊。哇，你看那个……"

translate schinese hscene50_Lyna_Helga_1f7af548:
    h "这么肿。这么漂亮。"

translate schinese hscene50_Lyna_Helga_8e64f8bf:
    h "你的奶子也许不会再怎么长大了，但我随时都能让你的乳头胀起来……"

translate schinese hscene50_Lyna_Helga_5499232c:
    h "要我连另一边也来一下吗，嗯~？"

translate schinese hscene50_Lyna_Helga_1ebbb24e:
    l "等、等——{w=1.0}{nw}"

translate schinese hscene50_Lyna_Helga_ce203281:
    l "呃嗯……！"

translate schinese hscene50_Lyna_Helga_7761d291:
    l "我靠……操！ {size=-5}你弄的时候感觉完全不一样。" with vpunch

translate schinese hscene50_Lyna_Helga_4e7ad024:
    h "唔嗯。哪里不一样……？"

translate schinese hscene50_Lyna_Helga_02b57504:
    l "{size=-5}我……呃，我是说，比、比我自己摸的时候不一样！"

translate schinese hscene50_Lyna_Helga_ffa94ffa:
    h "当然不一样。唔嗯……"

translate schinese hscene50_Lyna_Helga_91774883:
    h "这些可爱的小乳头需要的是一个成熟女人的嘴，而不是笨拙的青春期手指。"

translate schinese hscene50_Lyna_Helga_a09fee0c:
    h "它们值得被{i}供奉{/i}，而不是被当成无关紧要的东西。"

translate schinese hscene50_Lyna_Helga_120b63e8:
    hm "我知道她已经成年了，都快奔二十了……"

translate schinese hscene50_Lyna_Helga_ada85f58:
    hm "但吸着这两只奶子……？吸着她那平坦的小胸脯……？"

translate schinese hscene50_Lyna_Helga_8a45a971:
    hm "这感觉依然他妈的太不对劲了，而且不止一个层面。"

translate schinese hscene50_Lyna_Helga_2badd240:
    hm "就好像我不该对我女儿这样看起来还很年轻的女孩做这种事。"

translate schinese hscene50_Lyna_Helga_663d39a6:
    l "{size=+5}啊！{/size} 他、操！ {size=-5}继续……"

translate schinese hscene50_Lyna_Helga_5c9d3d28:
    hm "但莱娜绝不是什么天真的小姑娘。这个小不点实际上是个伪装的天魔。"

translate schinese hscene50_Lyna_Helga_0a378b4c:
    hm "所以道德就见鬼去吧。今晚，我的小宝贝会记住到底谁才是老大。"

translate schinese hscene50_Lyna_Helga_346e5e12:
    hm "她那么娇小又柔弱。这个体型差不知为何让我欲火焚身。"

translate schinese hscene50_Lyna_Helga_051e52a9:
    hm "我可以对她做任何事。惩罚她，使用她，把她的自信变成彻底的服从。"

translate schinese hscene50_Lyna_Helga_a34d6acd:
    l "是的～～！还要更多！"

translate schinese hscene50_Lyna_Helga_1d735d6d:
    hm "而且最妙的是……这是她自己要的……"

translate schinese hscene50_Lyna_Helga_72e7f4b9:
    l "{size=-5}啊……哎呀。"

translate schinese hscene50_Lyna_Helga_af5683d2:
    hm "……我女儿同意让我当一个肮脏下流的色狼。"

translate schinese hscene50_Lyna_Helga_6c4714d5:
    h "我的天啊，宝贝……真漂亮。它们现在配上了。"

translate schinese hscene50_Lyna_Helga_48869cb5:
    h "我从没见过你的乳头这么硬这么肿。你很喜欢这个，对不对？"

translate schinese hscene50_Lyna_Helga_a9beceec:
    l "{size=-5}有一点点……"

translate schinese hscene50_Lyna_Helga_87e99245:
    h "就一点点？真是个糟糕的骗子~"

translate schinese hscene50_Lyna_Helga_eb09e2a8:
    h "它们硬得像石头。看看。看看我把你弄成了什么样。"

translate schinese hscene50_Lyna_Helga_c275131e:
    l "{size=-5}哇。你、你是真的……到处都给我做记号。"

translate schinese hscene50_Lyna_Helga_2f17a0d1:
    h "没错。这具美丽的小身体的每一处都会记住它属于谁。"

translate schinese hscene50_Lyna_Helga_760fe8e7:
    l "{size=-5}我是不是正在习惯这个……这很奇怪吗？"

translate schinese hscene50_Lyna_Helga_0fe158cb:
    h "不。这说明你终于明白正在发生什么了。"

translate schinese hscene50_Lyna_Helga_38407872:
    l "{size=-5}到底在发生什么{i}呢{/i}，嗯~？"

translate schinese hscene50_Lyna_Helga_291e2a78:
    h "{cps=30}你正在被标记， {w=0.3}小宝贝女孩。 {w=0.5}一寸一寸地。"

translate schinese hscene50_Lyna_Helga_b768ebc7:
    h "{cps=25}而我们才刚刚开始……"

translate schinese hscene50_Lyna_Helga_788fd1c8:
    h "唔嗯……我的女儿一直在偷偷练功啊。"

translate schinese hscene50_Lyna_Helga_92e3379b:
    l "{size=-5}不，只是……跟你一起做瑜伽，还有你教我的那些核心训练。"

translate schinese hscene50_Lyna_Helga_d50c0cfe:
    h "所以某种意义上，这也是我自己练出来的。"

translate schinese hscene50_Lyna_Helga_ec61d8aa:
    h "现在就为我把这腹肌练硬。给我看看。"

translate schinese hscene50_Lyna_Helga_fe9c9573:
    h "天哪，你紧得不得了。一丝脂肪都没有。只有皮肤和肌肉。"

translate schinese hscene50_Lyna_Helga_dffc89f4:
    l "{size=-5}这样……好吗？"

translate schinese hscene50_Lyna_Helga_a284ab54:
    h "不公平。"

translate schinese hscene50_Lyna_Helga_990a0443:
    h "当你拥有{i}这个{/i}的时候，你不该嫉妒我的奶子。"

translate schinese hscene50_Lyna_Helga_97fb960e:
    h "我做了好几年的仰卧起坐和平板支撑，就为了让我的肚子保持平坦。"

translate schinese hscene50_Lyna_Helga_b4850721:
    h "而你呢？你拥有我见过最漂亮的肚子。毫不费力的那种。"

translate schinese hscene50_Lyna_Helga_4c5be8a8:
    l "{size=-5}我是说，我最近确实有稍微努力一下……"

translate schinese hscene50_Lyna_Helga_9283d599:
    h "再努力点，瘦巴巴的丫头。我还能看见你的肋骨。"

translate schinese hscene50_Lyna_Helga_0f347430:
    h "你得靠刻苦和坚持变强，而不是靠把我盘子里的菜剩下来，嗯？"

translate schinese hscene50_Lyna_Helga_afd06307:
    l "噗。抱歉我没中基因彩票，长成肌肉妈……"

translate schinese hscene50_Lyna_Helga_2d9b5cfd:
    h "哈！但我没说不喜欢。事实上……"

translate schinese hscene50_Lyna_Helga_a36793e3:
    h "这些性感的胯骨， {size=-5}操……"

translate schinese hscene50_Lyna_Helga_793554d6:
    h "我觉得我可能偏好瘦女孩。"

translate schinese hscene50_Lyna_Helga_1f96319f:
    l "等等！ {size=-5}啊……指甲…… {size=-10}那里好敏感。"

translate schinese hscene50_Lyna_Helga_97ffa250:
    h "呵。你总是装得凶悍又自信，其实还是那么柔软脆弱，像一根羽毛。"

translate schinese hscene50_Lyna_Helga_902769ae:
    h "稍微粗暴一点就会把你弄坏。"

translate schinese hscene50_Lyna_Helga_669b4fa4:
    l "{size=-5}哦……"

translate schinese hscene50_Lyna_Helga_5d2cdd7e:
    h "你真的是有天赋。"

translate schinese hscene50_Lyna_Helga_21aeb903:
    h "{cps=25}完美的、 {w=0.3}紧实的、 {w=0.3}少女的、 {w=0.3}肚子。"

translate schinese hscene50_Lyna_Helga_676e2092:
    lm "你这勾引少年的色狼，看在老天的份上别再吊我胃口了！"

translate schinese hscene50_Lyna_Helga_44ea5816:
    lm "把手再往下移，把手指伸进我的小骚穴里，把我操到失去意识……！"

translate schinese hscene50_Lyna_Helga_d9eefdaf:
    h "怎么了，嗯~？痒吗？"

translate schinese hscene50_Lyna_Helga_b172e792:
    l "{size=-5}唔嗯！"

translate schinese hscene50_Lyna_Helga_97e33908:
    h "这里也痒？嘿嘿。"

translate schinese hscene50_Lyna_Helga_19710032:
    h "我两只手差不多就能环住你的腰。天哪。"

translate schinese hscene50_Lyna_Helga_bb0e4c77:
    h "你之前说了句有意思的话，还记得吗？"

translate schinese hscene50_Lyna_Helga_b9556ac6:
    l "{size=-5}嗯？"

translate schinese hscene50_Lyna_Helga_1a42a195:
    h "就是关于想怀孕的那句……"

translate schinese hscene50_Lyna_Helga_f6d5f9ef:
    h "让你那对小奶子终于胀大。"

translate schinese hscene50_Lyna_Helga_cfa96094:
    l "{size=-5}我真不是在开玩笑。"

translate schinese hscene50_Lyna_Helga_35391c6c:
    h "对。听起来就是个一直在{i}想{/i}这件事的女孩。"

translate schinese hscene50_Lyna_Helga_3f957772:
    l "{size=-10}有一点点。"

translate schinese hscene50_Lyna_Helga_a5cf9fe0:
    h "嗯哼。我敢说肯定很多。"

translate schinese hscene50_Lyna_Helga_41c37657:
    h "你有没有也想象过有一天肚子鼓起来的样子？"

translate schinese hscene50_Lyna_Helga_ef4f4049:
    h "圆滚滚的。装着一个人，就像我曾经装着你那样。"

translate schinese hscene50_Lyna_Helga_bf81001b:
    l "{size=-5}操……"

translate schinese hscene50_Lyna_Helga_6eae2fbf:
    h "真不敢相信你最后会长得那么大…… {w=0.5}明明是个{i}小不点{/i}。"

translate schinese hscene50_Lyna_Helga_35064830:
    l "{size=-10}{i}袖珍{/i}型的。拜托。"

translate schinese hscene50_Lyna_Helga_d4d1fee3:
    h "却长出了这么火辣的小身子……"

translate schinese hscene50_Lyna_Helga_dca9d167:
    h "这么瘦，却又这么紧实。还有这个性感的肚脐，操。"

translate schinese hscene50_Lyna_Helga_da654807:
    h "你曾经就在这里连在我身上。就在这里。和妈妈连在一起。"

translate schinese hscene50_Lyna_Helga_b03ab8c5:
    l "{i}妈妈{/i}……操～～！"

translate schinese hscene50_Lyna_Helga_17e810f8:
    h "哎～！绷紧了，是吧？"

translate schinese hscene50_Lyna_Helga_13a0fd92:
    h "看来某类话题特别能让你兴奋，嗯？"

translate schinese hscene50_Lyna_Helga_7d251c44:
    l "{size=-5}我们曾经非、非常、非常{i}连在一起{/i}，对吧……？"

translate schinese hscene50_Lyna_Helga_7d409beb:
    h "确实。而这里就是你曾经住的地方，宝贝。在我体内整整九个月。"

translate schinese hscene50_Lyna_Helga_29d72c0b:
    h "也许有一天，也会有人住在你体内。"

translate schinese hscene50_Lyna_Helga_97b55bbc:
    h "你也想成为{i}母亲{/i}，对吧？"

translate schinese hscene50_Lyna_Helga_1ecf39e8:
    lm "要是我告诉你是谁的婴儿，我光看你的反应就能射出来！"

translate schinese hscene50_Lyna_Helga_3dbd7cda:
    lm "快点摸摸我的骚穴啊，你这个该死的变态妈妈……！"

translate schinese hscene50_Lyna_Helga_b69aee7e:
    h "男孩、女孩、双胞胎？谁知道呢。"

translate schinese hscene50_Lyna_Helga_38ce02b8:
    h "但如果真的发生了，他们会长在这里……"

translate schinese hscene50_Lyna_Helga_595f6de5:
    h "……这里。"

translate schinese hscene50_Lyna_Helga_07509246:
    h "哦，我的口红好像花了。真可惜~"

translate schinese hscene50_Lyna_Helga_118fa734:
    h "不过还有别的办法可以{i}标记{/i}你。"

translate schinese hscene50_Lyna_Helga_fb971a2c:
    l "{size=-5}拜、拜托你快点……做点什么吧。"

translate schinese hscene50_Lyna_Helga_a99a5412:
    h "嘘。我还没探索完呢。"

translate schinese hscene50_Lyna_Helga_a4f5d395:
    h "这个……？这个你肯定是遗传我的。"

translate schinese hscene50_Lyna_Helga_67e13444:
    h "这对适合{i}生育{/i}的宽胯，还有你大得惊人的屁股……"

translate schinese hscene50_Lyna_Helga_58c9cb03:
    h "这些都是你妈妈的基因。它们似乎完全无视了你的上半身，都长到下面去了。"

translate schinese hscene50_Lyna_Helga_e825807a:
    l "{size=-5}哈。哈。我真幸运……"

translate schinese hscene50_Lyna_Helga_e39d55cc:
    h "我们俩都很幸运。"

translate schinese hscene50_Lyna_Helga_579245f7:
    h "转过来。好好让我看看。"

translate schinese hscene50_Lyna_Helga_4a21372b:
    l "{size=-5}又来？你到底什么时候才肯{i}帮我{/i}……？"

translate schinese hscene50_Lyna_Helga_d538decd:
    h "等我高兴的时候！如果你乖的话。"

translate schinese hscene50_Lyna_Helga_71f8e180:
    h "快点。我刚才没看清，光顾着看你脱衣服了。"

translate schinese hscene50_Lyna_Helga_38615a8c:
    l "{size=-5}哼。你是说明顾着摸自己……"

translate schinese hscene50_Lyna_Helga_1f1a20c7:
    h "{size=+5}安静！{/size} 把那屁股撅起来，让我好好看清楚。"

translate schinese hscene50_Lyna_Helga_bdcb4299:
    h "{cps=20}唔嗯……对。就是那里。"

translate schinese hscene50_Lyna_Helga_d1cfb888:
    l "{size=-5}你老是盯着看……"

translate schinese hscene50_Lyna_Helga_45f27b25:
    h "哦，我确实在看。"

translate schinese hscene50_Lyna_Helga_414fe713:
    h "在你这个年纪拥有这样的屁股，简直不成体统。"

translate schinese hscene50_Lyna_Helga_bd35b32e:
    l "{size=-5}咦。那算是夸奖还是……？"

translate schinese hscene50_Lyna_Helga_8129ee54:
    h "这是事实。"

translate schinese hscene50_Lyna_Helga_cb85ef00:
    l "{size=-5}呃，你什么意思？"

translate schinese hscene50_Lyna_Helga_30792ce3:
    h "这屁股该长在一个成年女人身上，而不是一个年轻的青春期小混蛋身上。"

translate schinese hscene50_Lyna_Helga_a658316d:
    l "喂！ {size=+5}为什么？！"

translate schinese hscene50_Lyna_Helga_eb0dc6f3:
    h "我可以调皮地打自己女儿几下，不行吗？"

translate schinese hscene50_Lyna_Helga_d160301e:
    h "你的屁股也是我的财产，就像你那对小奶子一样。"

translate schinese hscene50_Lyna_Helga_9a4893f7:
    h "还是说你有异议？有什么理由让我打得更{i}重{/i}……？"

translate schinese hscene50_Lyna_Helga_15ab9aa3:
    l "{size=-5}我是说……那天你可没问过{i}那个{/i}。"

translate schinese hscene50_Lyna_Helga_364a3587:
    l "{size=+5}啊啊！"

translate schinese hscene50_Lyna_Helga_65e0e6c8:
    h "别惹我，丫头。"

translate schinese hscene50_Lyna_Helga_43af52bd:
    h "你知道今晚这具身体会遭遇什么吗，嗯~？"

translate schinese hscene50_Lyna_Helga_24bf6b1e:
    l "{size=-5}我……我可能有点概念……"

translate schinese hscene50_Lyna_Helga_c11d7e73:
    h "我明白了。那个概念让你害怕吗？"

translate schinese hscene50_Lyna_Helga_8883b603:
    l "{size=-5}有、有一点。"

translate schinese hscene50_Lyna_Helga_c30684f6:
    h "{size=-5}很好，小色狼……"

translate schinese hscene50_Lyna_Helga_191606bb:
    h "{size=-5}本来就该这样。"

translate schinese hscene50_Lyna_Helga_8d0b304a:
    h "再转过来。面对我。"

translate schinese hscene50_Lyna_Helga_c28d4616:
    l "*咳嗽* {size=-5}真的吗……？"

translate schinese hscene50_Lyna_Helga_ea9b8008:
    h "真的。还有最后一个地方需要检查。"

translate schinese hscene50_Lyna_Helga_d37d3535:
    h "这次没有犹豫。很好。"

translate schinese hscene50_Lyna_Helga_278e78b9:
    h "你{i}听话{/i}的时候我更喜欢。"

translate schinese hscene50_Lyna_Helga_a60e7049:
    h "不过有点可惜。你已经把那对奶子舔干净了。"

translate schinese hscene50_Lyna_Helga_e987cf57:
    l "{size=-5}它们看起来不好看。我想让你好好看看我的乳头变得有多肿。"

translate schinese hscene50_Lyna_Helga_c97d8e55:
    h "是吗~？真方便。"

translate schinese hscene50_Lyna_Helga_d1b7f5a2:
    h "不过嘛，就像我说的……"

translate schinese hscene50_Lyna_Helga_ab3db112:
    h "{cps=25}还有别的办法可以标记你。"

translate schinese hscene50_Lyna_Helga_8b58835b:
    h "嗯。你这边好暖。"

translate schinese hscene50_Lyna_Helga_eb8b7196:
    l "{size=-5}而你太吊我胃口了……"

translate schinese hscene50_Lyna_Helga_5b4ab523:
    h "就像你一向做的那样？啊，但我不是在吊你胃口，我只是在清点库存。"

translate schinese hscene50_Lyna_Helga_3ad44ad0:
    l "清点库存……？"

translate schinese hscene50_Lyna_Helga_1a023de0:
    h "对。今晚属于我的所有东西。"

translate schinese hscene50_Lyna_Helga_b59260a7:
    h "唔嗯，真漂亮……"

translate schinese hscene50_Lyna_Helga_633f3c55:
    h "完全光洁。一根毛都没有。"

translate schinese hscene50_Lyna_Helga_dfc3b2e8:
    l "{size=-5}我……自从我们那天去温泉之后我又开始刮了。还记得吗？"

translate schinese hscene50_Lyna_Helga_0c31d529:
    h "哦，我记得。上次你迫不及待地想给我看成果。"

translate schinese hscene50_Lyna_Helga_eb8c4856:
    l "{size=-5}不是为了你。我自己也喜欢，你知道的。"

translate schinese hscene50_Lyna_Helga_45a2522c:
    h "真的吗？你明明当时就问我，是该把毛留长还是刮掉。"

translate schinese hscene50_Lyna_Helga_2b60456c:
    h "所以没错，绝对是为了我。别撒谎。"

translate schinese hscene50_Lyna_Helga_e54f32b0:
    h "{cps=25}我的{i}小姑娘{/i}， {w=0.5}这么急着要为妈妈准备一个漂亮的骚穴。"

translate schinese hscene50_Lyna_Helga_d10fc6b5:
    l "呜嗯……！操！" with vpunch

translate schinese hscene50_Lyna_Helga_44cc3071:
    h "嗯哼。这说明了一切。"

translate schinese hscene50_Lyna_Helga_44504c60:
    h "这么肿。这么软。像是还不太清楚自己是用来干什么的。"

translate schinese hscene50_Lyna_Helga_d8295971:
    l "喂！我知道它是用来干什么的。"

translate schinese hscene50_Lyna_Helga_328e2eb0:
    h "是吗？这个可爱的小东西看起来可不像长在女人身上的。"

translate schinese hscene50_Lyna_Helga_2f0d6b2b:
    l "啧！ {size=-5}我{i}就是{/i}女人。"

translate schinese hscene50_Lyna_Helga_2777af64:
    h "唔嗯。既然你这么说……"

translate schinese hscene50_Lyna_Helga_6552c9ca:
    h "{cps=25}我那没有毛的宝贝女儿。"

translate schinese hscene50_Lyna_Helga_6cac6b35:
    l "{size=-5}啊……等等——"

translate schinese hscene50_Lyna_Helga_c7791022:
    h "嘘。我知道你想要我对它做什么。"

translate schinese hscene50_Lyna_Helga_c2641323:
    h "从我走出浴室开始你就一直在滴水，对吧？"

translate schinese hscene50_Lyna_Helga_fba1a32a:
    h "你偷看了我的束腰一眼，然后立刻就开始揉你那条细细的内裤。"

translate schinese hscene50_Lyna_Helga_aad2e4b8:
    l "{size=-5}你太色情了……对不起。"

translate schinese hscene50_Lyna_Helga_9bbebabc:
    h "我当然色情。我都能感觉到你已经在弄湿我的手指了。"

translate schinese hscene50_Lyna_Helga_781f1871:
    h "这个饥渴的青春期骚穴整个夏天都在求着我碰它。"

translate schinese hscene50_Lyna_Helga_2738d6bc:
    h "每一条比基尼。每一次「不小心」的走光。每一次你在沙发上把腿张得有点太开。"

translate schinese hscene50_Lyna_Helga_cb2901ea:
    h "你以为我没注意到？"

translate schinese hscene50_Lyna_Helga_a8db857e:
    l "{size=-5}我有点希望你会注意到……"

translate schinese hscene50_Lyna_Helga_cd617228:
    h "对，你这个色狼。我{i}什么都{/i}注意到了。"

translate schinese hscene50_Lyna_Helga_d5bba8b5:
    h "只是我还没准备好要对此做什么。"

translate schinese hscene50_Lyna_Helga_471f500b:
    l "{shader=jitter:1.0,1.0}{size=+5}啊啊啊！"

translate schinese hscene50_Lyna_Helga_710f5dcf:
    h "真敏感。稍微揉一下你就碎了。"

translate schinese hscene50_Lyna_Helga_3473a263:
    h "想想还会发生什么。不，等我把嘴贴上这几片可爱的唇瓣的时候，还会有什么{i}正在{/i}发生。"

translate schinese hscene50_Lyna_Helga_005f3d50:
    h "当妈妈终于把这个小骚穴扒开……"

translate schinese hscene50_Lyna_Helga_dcfe8f62:
    h "{cps=25}{size=-5}……并尝到自己女儿的味道。"

translate schinese hscene50_Lyna_Helga_0e7e9d24:
    l "{shader=jitter:1.0,1.0}我的天哪～～！" with vpunch

translate schinese hscene50_Lyna_Helga_aaf2e6ae:
    l "{shader=jitter:2.0,2.0}呃嗯……！"

translate schinese hscene50_Lyna_Helga_74f1907e:
    h "哇。刚才有人喷了一点~？"

translate schinese hscene50_Lyna_Helga_80958404:
    h "{size=-5}哎，有一点到我嘴上了……"

translate schinese hscene50_Lyna_Helga_7ee1e911:
    l "糟糕！那、对不起！"

translate schinese hscene50_Lyna_Helga_dc7a444c:
    h "{size=-5}为什么要道歉？省得我再弄了。"

translate schinese hscene50_Lyna_Helga_80e203e0:
    hm "唔嗯……几乎和我的酒一样好喝。"

translate schinese hscene50_Lyna_Helga_64ef6899:
    h "哎呀我的天哪~真是难以置信！"

translate schinese hscene50_Lyna_Helga_ef6f4a20:
    h "我那色气的小丫头差点就高潮了，而我几乎还没碰她，嗯？"

translate schinese hscene50_Lyna_Helga_cf34542a:
    l "{size=-5}没办法……"

translate schinese hscene50_Lyna_Helga_00d5e988:
    h "那看来我得好好训练你，非常多次。"

translate schinese hscene50_Lyna_Helga_e1943b03:
    l "{size=-5}拜、拜托你……舔它。"

translate schinese hscene50_Lyna_Helga_d08c0bc5:
    h "嗯。更卖力点地求我。"

translate schinese hscene50_Lyna_Helga_c7455153:
    l "妈妈求你了！我他妈太想要了。"

translate schinese hscene50_Lyna_Helga_66c5efe2:
    l "快点用手指弄我的骚穴，然后舔它！"

translate schinese hscene50_Lyna_Helga_b796ecc1:
    l "{size=+5}我想知道被另一个女人弄是什么感觉，求你、求你、求你了！"

translate schinese hscene50_Lyna_Helga_0bfa27a1:
    h "哈哈哈！耐心点，你这个色狼。"

translate schinese hscene50_Lyna_Helga_b5ab8251:
    l "{size=-5}噗，一点也不好笑……"

translate schinese hscene50_Lyna_Helga_49bb6200:
    h "{size=+5}就是不好笑！{/size} 小混蛋。"

translate schinese hscene50_Lyna_Helga_b658a13a:
    h "我说过了，今晚你妈妈会慢慢地陪你。就像整个夏天你也慢慢地陪我一样……"

translate schinese hscene50_Lyna_Helga_4bc660c0:
    h "你一直在推我。你一直在惹我生气。每一次。每周。毫不留情。"

translate schinese hscene50_Lyna_Helga_800964fb:
    centered "{font=font_narration}{cps=25}{color=#f1b500}现在轮到我反击了。"

translate schinese hscene50_Lyna_Helga_e304cc46:
    h "你得{i}挣{/i}来我的嘴，好吗？"

translate schinese hscene50_Lyna_Helga_a8f6411e:
    h "所以首先，我要你的嘴做点别的事。"

translate schinese hscene50_Lyna_Helga_c3dc8161:
    l "{size=-5}呃，你在想什么……？"

translate schinese hscene50_Lyna_Helga_ffcc048a:
    h "下去。跪在长凳上等着，丫头。"

translate schinese hscene50_Lyna_Helga_71411c01:
    l "{size=-5}好、好吧……"

translate schinese hscene50_Lyna_Helga_ca8d6484:
    h "把这个含进嘴里。"

translate schinese hscene50_Lyna_Helga_4f7cac74:
    l "认真的……？"

translate schinese hscene50_Lyna_Helga_fb07b04c:
    h "我不会说第二遍。"

translate schinese hscene50_Lyna_Helga_eff6f93c:
    h "做得好。看来你终究还是有点用处的。"

translate schinese hscene50_Lyna_Helga_32853d00:
    h "你未来的丈夫肯定会为这堂课感谢我的。"

translate schinese hscene50_Lyna_Helga_507ba46e:
    l "丈夫？！"

translate schinese hscene50_Lyna_Helga_556da1ab:
    h "不然你以为要靠什么怀孕，才能穿上更大的胸罩，像你那么急着要？"

translate schinese hscene50_Lyna_Helga_f5cc8cbb:
    h "我可希望有一天能当外婆。你最好别让我失望。"

translate schinese hscene50_Lyna_Helga_693ad09f:
    l "哦，我…… {size=-5}我会的，妈妈。"

translate schinese hscene50_Lyna_Helga_2413dae4:
    h "母亲。"

translate schinese hscene50_Lyna_Helga_65907c14:
    l "{size=-5}什么……？"

translate schinese hscene50_Lyna_Helga_43f171a2:
    h "以后你要称呼我「母亲」，不是「妈妈」。"

translate schinese hscene50_Lyna_Helga_c1e4d1f7:
    l "{size=-5}为什么？那样听起来怪怪的。"

translate schinese hscene50_Lyna_Helga_99887b3f:
    h "因为今晚规矩是我定的！"

translate schinese hscene50_Lyna_Helga_4ca51068:
    h "不过……如果你不过度使用，我还是允许你叫「妈妈」。"

translate schinese hscene50_Lyna_Helga_eac738c1:
    h "你不知道我那{i}小姑娘{/i}这么叫的时候，我有多兴奋……"

translate schinese hscene50_Lyna_Helga_aa35fe7e:
    l "{i}妈妈～{/i}"

translate schinese hscene50_Lyna_Helga_29f8520d:
    h "我说不要过度使用！"

translate schinese hscene50_Lyna_Helga_0f29a749:
    l "{size=-5}对、对不起，母亲。"

translate schinese hscene50_Lyna_Helga_200028ef:
    h "你知道接下来要发生什么，对吧？今晚妈妈要教你如何取悦一根鸡巴。"

translate schinese hscene50_Lyna_Helga_568e08b0:
    l "{size=-5}是的，母亲。"

translate schinese hscene50_Lyna_Helga_b3859f02:
    h "那么？你还在等什么？"

translate schinese hscene50_Lyna_Helga_75a09836:
    h "亲它。让我看看你接受了接下来要发生的事。"

translate schinese hscene50_Lyna_Helga_609e0851:
    h "很好，现在看着我。想象我就是{i}那个{/i}男孩，就是你背着我偷偷勾搭的那个……"

translate schinese hscene50_Lyna_Helga_9804ef22:
    h "你想再像照片里那样给他口交吗？"

translate schinese hscene50_Lyna_Helga_58127873:
    h "你想把他的鸡巴弄湿，好用在别的……事情上？"

translate schinese hscene50_Lyna_Helga_123e3bd2:
    l "{size=-5}我……好、是的。"

translate schinese hscene50_Lyna_Helga_3086c2d0:
    h "张开嘴。让我看看你的舌头。"

translate schinese hscene50_Lyna_Helga_53b691eb:
    h "天哪，我可爱的小姑娘……"

translate schinese hscene50_Lyna_Helga_0d4ac30b:
    h "你真是为我准备得{i}充分{/i}得不得了，对吧？"

translate schinese hscene50_Lyna_Helga_d0c017aa:
    h "对……让我看看你是真心的。"

translate schinese hscene50_Lyna_Helga_223d6101:
    h "假装这就是那个男孩。让我看看你会怎么取悦他。"

translate schinese hscene50_Lyna_Helga_dd94e05e:
    h "很好。就是这样。"

translate schinese hscene50_Lyna_Helga_10714a4a:
    h "但只有前端还不够……"

translate schinese hscene50_Lyna_Helga_7b63df0c:
    h "我知道你能含得更深，对吧？"

translate schinese hscene50_Lyna_Helga_1c5fd5c1:
    h "做出来。让我看看你能含到多深。"

translate schinese hscene50_Lyna_Helga_df36b221:
    h "就是这样。一直到最里面。"

translate schinese hscene50_Lyna_Helga_efddee69:
    l "呃呃呃嗯！"

translate schinese hscene50_Lyna_Helga_a5796883:
    h "你绝对不是没有经验的。"

translate schinese hscene50_Lyna_Helga_6201240d:
    h "他知道你会用我的性玩具练习吗，嗯？"

translate schinese hscene50_Lyna_Helga_a44b00e7:
    h "他知道你这个荡妇吗？一个坏透了的色狼？"

translate schinese hscene50_Lyna_Helga_4ce0ee2d:
    h "他知道是我教你怎么好好接吻的吗？"

translate schinese hscene50_Lyna_Helga_1ad4013d:
    h "{cps=25}他知道…… {w=0.5}我们之间的事吗？"

translate schinese hscene50_Lyna_Helga_614e722d:
    l "呃啊嗯…… {size=-5}不、不知道，母亲。他不知道。"

translate schinese hscene50_Lyna_Helga_c7261620:
    l "我发誓！拜、拜托别——{nw}{w=1.5}"

translate schinese hscene50_Lyna_Helga_a01ba57e:
    h "嘘。我没生气。我知道你希望他知道，对吧？"

translate schinese hscene50_Lyna_Helga_05984260:
    h "你想让他看到这个。我们两个。"

translate schinese hscene50_Lyna_Helga_b458b366:
    h "你想让他看着你，他的小女朋友，和自己的母亲做着性方面的事。"

translate schinese hscene50_Lyna_Helga_df135933:
    l "{size=-5}也许……？"

translate schinese hscene50_Lyna_Helga_3cd8afee:
    h "只是「也许」？老实说。如果他在这里，你会享受在他面前臣服于我吗？"

translate schinese hscene50_Lyna_Helga_af74c1f0:
    h "你那个发情的骚穴会不会因此颤抖？为妈妈湿透？"

translate schinese hscene50_Lyna_Helga_a20b33db:
    l "{size=-5}这是我的秘密，我总是很想要。"

translate schinese hscene50_Lyna_Helga_180a9522:
    h "现在就给我看。去床上。仰面躺下。双腿张开。"

translate schinese hscene50_Lyna_Helga_bc85f4d9:
    h "看看你。多美的画面……"

translate schinese hscene50_Lyna_Helga_45894c73:
    h "张开得这么乖。"

translate schinese hscene50_Lyna_Helga_026790e0:
    l "这就是你想要的……母亲？过来好好看看。"

translate schinese hscene50_Lyna_Helga_12bfca80:
    h "有自信了，是吧？"

translate schinese hscene50_Lyna_Helga_9ca68c37:
    h "我本来就打算这么做的。我可不会听一个小混蛋的命令。"

translate schinese hscene50_Lyna_Helga_fb52baee:
    h "唔嗯，我只是太喜欢那具可爱的十九岁身体了。"

translate schinese hscene50_Lyna_Helga_27de0240:
    l "为什么？是因为那是{i}我的{/i}身体，还是因为它才{i}十九岁{/i}~？"

translate schinese hscene50_Lyna_Helga_3885d42f:
    h "两个都是。"

translate schinese hscene50_Lyna_Helga_df47a25a:
    h "天哪，尤其是那道完美的裂缝。它让我快要发狂。"

translate schinese hscene50_Lyna_Helga_f848d5e2:
    h "我的小姑娘…… {size=-5}他妈的这么光洁，看起来这么年轻，啊……"

translate schinese hscene50_Lyna_Helga_848d1850:
    l "{cps=25}我{i}确实{/i}很年轻， {w=0.5}母亲。"

translate schinese hscene50_Lyna_Helga_6ad850e8:
    h "你已经够老了。"

translate schinese hscene50_Lyna_Helga_29b18568:
    l "是的，但我永远是你的「小姑娘」，对吧？我很喜欢你这样叫我。"

translate schinese hscene50_Lyna_Helga_6b5ace69:
    l "而且你老是提到我的年龄，对吧？为什么……？"

translate schinese hscene50_Lyna_Helga_0a621f2d:
    hm "几乎像在祈祷一样。十九岁。成年。自愿。"

translate schinese hscene50_Lyna_Helga_bce660ce:
    hm "这不一样。永远不会和那时候一样。我不是{i}她{/i}……"

translate schinese hscene50_Lyna_Helga_544c2f9e:
    centered "{font=font_narration}{cps=25}{color=#f1b500}( 我不是。)"

translate schinese hscene50_Lyna_Helga_74611187:
    l "你在想什么呀，妈妈？ {size=-5}我觉得某人喜欢角色扮演~"

translate schinese hscene50_Lyna_Helga_0c6bfd8f:
    l "你喜欢年轻的、柔软的、青春期身体吗？"

translate schinese hscene50_Lyna_Helga_32b3e6f7:
    h "比我该喜欢的程度还要多……"

translate schinese hscene50_Lyna_Helga_9d8842cb:
    l "你最喜欢哪个部位？"

translate schinese hscene50_Lyna_Helga_62d73834:
    l "我刚发育的小奶子……？又小又挺。"

translate schinese hscene50_Lyna_Helga_0408150e:
    l "我的乳头现在还又硬又肿，因为你刚才吸过。"

translate schinese hscene50_Lyna_Helga_84340101:
    l "我练得这么好了，对吧？你好像很喜欢我完美的精瘦腹肌。"

translate schinese hscene50_Lyna_Helga_eb24a85b:
    l "我练得这么好了，对吧？你好像很喜欢我完美的 腹肌。"

translate schinese hscene50_Lyna_Helga_1815c80b:
    l "或者也许是我青春期的骚穴……？它可爱得不得了，对吧？"

translate schinese hscene50_Lyna_Helga_e37774d9:
    l "你知道吗，我现在每次刮毛，都忍不住想到你……"

translate schinese hscene50_Lyna_Helga_e0ec7ffe:
    l "然后我就自慰，幻想着当我把光滑无毛的小裂缝展示给我妈妈时，她会露出什么表情。"

translate schinese hscene50_Lyna_Helga_0b1e31fd:
    h "你这个该死的色狼。真是让我难以决定……"

translate schinese hscene50_Lyna_Helga_9d53c08c:
    lm "那个表情。那个该死的表情！"

translate schinese hscene50_Lyna_Helga_e0cde68a:
    l "{size=-10}呃嗯……"

translate schinese hscene50_Lyna_Helga_b339fa32:
    h "你在干什么？我可没允许你自己摸。"

translate schinese hscene50_Lyna_Helga_9bfcad15:
    l "{size=-5}对、对不起，我只是在想很下流的事……"

translate schinese hscene50_Lyna_Helga_9154c103:
    h "什么样的{i}事{/i}，嗯？"

translate schinese hscene50_Lyna_Helga_4463c085:
    l "{size=-5}我说了你会很生气的。"

translate schinese hscene50_Lyna_Helga_3e4e3a6c:
    h "比你刚才说的还要下流？告诉我。"

translate schinese hscene50_Lyna_Helga_2ff4c41e:
    l "{size=-10}不、不……我不该说……"

translate schinese hscene50_Lyna_Helga_765a5bc6:
    h "{size=+5}丫头，这是命令！"

translate schinese hscene50_Lyna_Helga_7067b804:
    l "{size=-5}好吧，我……我只是在想如果……"

translate schinese hscene50_Lyna_Helga_999a7107:
    l "{size=-5}{cps=25}如果你希望我更小一点的话。"

translate schinese hscene50_Lyna_Helga_426b4ba2:
    h "嗯？"

translate schinese hscene50_Lyna_Helga_cd53102d:
    l "对，我是说…… {size=-5}字面意义上。"

translate schinese hscene50_Lyna_Helga_da107fc6:
    l "{size=-5}你能想象如果我们之间的事发生在很多年前会怎样吗？"

translate schinese hscene50_Lyna_Helga_a909fda9:
    l "{size=-5}你知道，有个词…… {cps=20}{w=0.5}{i}撩人小童{/i}。"

translate schinese hscene50_Lyna_Helga_beda10de:
    l "{size=-5}那些看起来完全未成年、即使合法也还是未成年的小男孩和小女孩。"

translate schinese hscene50_Lyna_Helga_e138137a:
    l "{cps=25}我符合条件吗~？ {w=0.5}我这个坏妈妈喜欢那一套……？"

translate schinese hscene50_Lyna_Helga_a9e97625:
    h "{size=+10}你他妈给我闭嘴！"

translate schinese hscene50_Lyna_Helga_83aaff97:
    l "{shader=jitter:2.0,2.0}天哪！你到底有什么毛病？！"

translate schinese hscene50_Lyna_Helga_556d3e5d:
    h "{size=+5}不，有毛病的是你！看在老天的份上！"

translate schinese hscene50_Lyna_Helga_8437f8e5:
    h "{size=+5}你不能拿{i}那种{/i}事开玩笑，明白了吗？！"

translate schinese hscene50_Lyna_Helga_33cbfd85:
    l "{size=-5}为、为什么打我？ {size=-10}好疼……"

translate schinese hscene50_Lyna_Helga_f186abb5:
    h "{size=+5}这就是小混蛋不知道什么时候该停手的下场！"

translate schinese hscene50_Lyna_Helga_18c28201:
    l "{size=-5}可、可是为什么？我知道什么叫角色扮演。我知道你喜欢……"

translate schinese hscene50_Lyna_Helga_963f123c:
    lm "尤其是对你那个小宝贝埃里克。"

translate schinese hscene50_Lyna_Helga_7733edd7:
    l "{size=-5}而且如果这一切都只是你脑子里的幻想，偶尔变得{i}更小{/i}一点又有什么错？"

translate schinese hscene50_Lyna_Helga_a6700eda:
    l "{size=-5}这又不是犯罪。只是幻想、想象。我可以假装。稍微演一点。"

translate schinese hscene50_Lyna_Helga_2d9f920b:
    h "{size=+5}你真是个肮脏下流的色狼。难以置信！"

translate schinese hscene50_Lyna_Helga_3386f329:
    l "{size=-5}可是你现在的打扮，你今晚对待我的方式……"

translate schinese hscene50_Lyna_Helga_5a49458d:
    l "{size=-5}我们在做性的事情，可你却一直说我是你的「小姑娘」……"

translate schinese hscene50_Lyna_Helga_d69c1e81:
    l "{size=-5}感觉已经没有任何界限了。好像你真的什么都{i}愿意{/i}做，对不对？"

translate schinese hscene50_Lyna_Helga_f2595c1b:
    h "{size=+5}所以你觉得根本没有该死的底线了，嗯？！"

translate schinese hscene50_Lyna_Helga_79f6c551:
    h "{size=+5}你那个发情的脑袋真的已经堕落到这种地步了吗？！"

translate schinese hscene50_Lyna_Helga_c34b035d:
    h "你、你真的以为在我跟你说过我姐——之后，我还会想要{i}那种{/i}事 {cps=25}{w=0.5}"

translate schinese hscene50_Lyna_Helga_f6609c77:
    h "{cps=20}{size=-5}关于安——{w=1.0}{nw}"

translate schinese hscene50_Lyna_Helga_913996ac:
    l "对不起，对不起！ {size=-5}你、你说得对。"

translate schinese hscene50_Lyna_Helga_4c514ca4:
    l "{size=-5}我……我只是觉得也许那能帮助治愈创伤，然后——"

translate schinese hscene50_Lyna_Helga_c8753510:
    h "{size=+5}你他妈是白痴吗？！不准再提那个。"

translate schinese hscene50_Lyna_Helga_368e94f3:
    h "{size=+5}还是说你想再挨一下，就是这样？！"

translate schinese hscene50_Lyna_Helga_6c09729f:
    l "不、不、不要！*咳嗽* {size=-5}我非常抱歉！"

translate schinese hscene50_Lyna_Helga_d903dacb:
    h "那他妈的给我摆正位置，你这个没心没肺的小混蛋。"

translate schinese hscene50_Lyna_Helga_50247144:
    l "{size=-5}妈、妈妈，我真的很抱歉。刚才太过分了，太快了。"

translate schinese hscene50_Lyna_Helga_06f6f07d:
    l "{size=+5}啊！"

translate schinese hscene50_Lyna_Helga_3eb658bf:
    h "看来你还是不明白这里谁说了算。"

translate schinese hscene50_Lyna_Helga_90b96ec3:
    h "把高跟鞋脱掉。现在。"

translate schinese hscene50_Lyna_Helga_eef2b57d:
    l "什么……？"

translate schinese hscene50_Lyna_Helga_fa067a6d:
    h "高跟鞋。不然我就更用力。"

translate schinese hscene50_Lyna_Helga_e79d0e71:
    l "{size=-5}你、你还按着呢。你生气了……？"

translate schinese hscene50_Lyna_Helga_ba652c3d:
    h "你说呢，嗯？！现在坐起来。"

translate schinese hscene50_Lyna_Helga_cbb8c556:
    h "好好看看它们，丫头。"

translate schinese hscene50_Lyna_Helga_663420b1:
    l "{size=-5}你的……脚？"

translate schinese hscene50_Lyna_Helga_449a17ac:
    h "对，我的脚。你喜欢吗？"

translate schinese hscene50_Lyna_Helga_22defce4_1:
    h "接下来的话，好好想清楚再说。"

translate schinese hscene50_Lyna_Helga_2b84bbed:
    l "{size=-5}好、喜欢……？我喜欢。"

translate schinese hscene50_Lyna_Helga_8c740f4a:
    h "有多喜欢？"

translate schinese hscene50_Lyna_Helga_eaf957ac:
    l "{size=-5}很喜欢……？"

translate schinese hscene50_Lyna_Helga_e83aa565:
    h "那就下去吧。"

translate schinese hscene50_Lyna_Helga_1ce19c57:
    l "{size=-5}嗯？{w=1.0}{nw}"

translate schinese hscene50_Lyna_Helga_f7242010:
    l "{size=+5}啊啊啊——！"

translate schinese hscene50_Lyna_Helga_915bfcda:
    h "好了。这才是你今晚真正该待的地方，嗯？"

translate schinese hscene50_Lyna_Helga_2520224d:
    l "{size=-5}妈妈，求你了……"

translate schinese hscene50_Lyna_Helga_cb9ea25a:
    h "你他妈给我闭嘴。"

translate schinese hscene50_Lyna_Helga_3529599c:
    h "你想知道有没有底线？这就是一个。"

translate schinese hscene50_Lyna_Helga_cb229fdc:
    h "你不许再提我人生的{i}那一段{/i}。"

translate schinese hscene50_Lyna_Helga_221a1ee2:
    h "今晚不行，永远都不行。"

translate schinese hscene50_Lyna_Helga_56d3f363:
    l "我不会有，我发誓！"

translate schinese hscene50_Lyna_Helga_b688b411:
    h "很好。你最好不会有。"

translate schinese hscene50_Lyna_Helga_b662fd76:
    h "那么，你打算在那儿待一整晚吗？"

translate schinese hscene50_Lyna_Helga_e211787e:
    l "{size=-5}你想让我做、做什、做什么，母亲？"

translate schinese hscene50_Lyna_Helga_53524248:
    h "首先，道歉。"

translate schinese hscene50_Lyna_Helga_26f11bea:
    l "{size=-5}对不起。"

translate schinese hscene50_Lyna_Helga_00b1664b:
    h "不是那样。爬过来。"

translate schinese hscene50_Lyna_Helga_f543a61b:
    h "看看你。真可怜。"

translate schinese hscene50_Lyna_Helga_20df72d9:
    h "不过我们还没进行你的惩罚环节。跪下。"

translate schinese hscene50_Lyna_Helga_c2da7817:
    h "什么？你又想要{i}那个{/i}……？"

translate schinese hscene50_Lyna_Helga_52ef789c:
    l "{size=-5}嗯哼。"

translate schinese hscene50_Lyna_Helga_bc3b9b41:
    h "不。那不是你接下来要含的东西，小混蛋。"

translate schinese hscene50_Lyna_Helga_b304821f:
    h "把我的丝袜撕下来。"

translate schinese hscene50_Lyna_Helga_90899bbd:
    l "什么？真的……？不可能！"

translate schinese hscene50_Lyna_Helga_e81d393b:
    h "你有什么好惊讶的？我还能再买一千双。"

translate schinese hscene50_Lyna_Helga_a5af6b46:
    h "你有没有试过自己赚点钱，嗯？掌控自己的人生？真正承担一些责任？"

translate schinese hscene50_Lyna_Helga_bde46d5f:
    h "而不是当一个他妈的被宠坏的孩子，老是跟我要贵东西……"

translate schinese hscene50_Lyna_Helga_9797fa79:
    h "怎么？我伤到你的自尊了，{i}小姑娘{/i}？"

translate schinese hscene50_Lyna_Helga_3159c5d5:
    h "看起来你有话想说。说吧。来。"

translate schinese hscene50_Lyna_Helga_9b448d86:
    h "没话说？我明白了。"

translate schinese hscene50_Lyna_Helga_3ddbb257:
    h "我认得那个表情。你骗不了我。"

translate schinese hscene50_Lyna_Helga_6ea14c36:
    h "你其实很享受这个惩罚，对吧？"

translate schinese hscene50_Lyna_Helga_76b88bf6:
    h "你当然享受。因为你坏掉了。"

translate schinese hscene50_Lyna_Helga_2312d193:
    h "你那个发情的脑袋已经坏掉了。"

translate schinese hscene50_Lyna_Helga_8c7c70e5:
    l "{size=-5}只是……你的脚好软，而且你——"

translate schinese hscene50_Lyna_Helga_f70fbdb9:
    h "好好为你指控我喜欢的东西道歉。"

translate schinese hscene50_Lyna_Helga_03026814:
    l "{size=-10}我…… {size=-5}怎么道？"

translate schinese hscene50_Lyna_Helga_47e1a5b7:
    h "用你的舌头。那条不听话的舌头。"

translate schinese hscene50_Lyna_Helga_eef2b57d_1:
    l "什么……？"

translate schinese hscene50_Lyna_Helga_fc347bd6:
    h "舔。"

translate schinese hscene50_Lyna_Helga_765d18f1:
    l "{size=-5}不、不要。好恶心……"

translate schinese hscene50_Lyna_Helga_6682cbeb:
    h "舔，不然就滚出这个房间，别再回来。"

translate schinese hscene50_Lyna_Helga_d70738d2:
    lm "我靠。她是认真的！"

translate schinese hscene50_Lyna_Helga_3002902d:
    lm "而我……天哪，我为什么有点想舔？"

translate schinese hscene50_Lyna_Helga_3fedad7f:
    h "{size=-5}唔嗯。就是这样。"

translate schinese hscene50_Lyna_Helga_eb91541b:
    lm "这怎么会让我兴奋成这样？！"

translate schinese hscene50_Lyna_Helga_c75c824a:
    lm "被这样推来推去，被命令，被{i}使用{/i}……？"

translate schinese hscene50_Lyna_Helga_ca879435:
    h "现在吸它们。吸妈妈的脚趾。"

translate schinese hscene50_Lyna_Helga_eb850d90:
    h "对，好女孩……"

translate schinese hscene50_Lyna_Helga_c1c8b6cc:
    h "慢慢来。每根脚趾。好好舔干净。"

translate schinese hscene50_Lyna_Helga_96ab844a:
    h "两根？你真是个不要脸的小混蛋，你知道吗？"

translate schinese hscene50_Lyna_Helga_413e5eab:
    h "大多数女孩被我这样搞到现在早就哭了……"

translate schinese hscene50_Lyna_Helga_7cc242a2:
    l "唔嗯……！ {w=1.0}{nw}"

translate schinese hscene50_Lyna_Helga_f3f9c456:
    h "你？被扇、被掐、被踢，却还吸得越来越用力……"

translate schinese hscene50_Lyna_Helga_57a37cbb:
    h "一点都不在乎。"

translate schinese hscene50_Lyna_Helga_3bf4f4af:
    h "啊…… {size=-5}大概也湿得更厉害了……"

translate schinese hscene50_Lyna_Helga_b564ee0e:
    h "{size=-5}在你那个呃嗯……那个年轻又发情的青春期骚穴里……啊……"

translate schinese hscene50_Lyna_Helga_8e586233:
    h "{size=-5}睁开眼睛。你他妈含着的时候看着我。"

translate schinese hscene50_Lyna_Helga_90903f79:
    h "{cps=25}多脏的一个小{i}婊子{/i}。"

translate schinese hscene50_Lyna_Helga_cfd34f99:
    h "对，你没听错。你喜欢这个对不对？"

translate schinese hscene50_Lyna_Helga_1555e355:
    h "终于被叫成你真正的样子。一个变味的青春期{i}淫妇{/i}。"

translate schinese hscene50_Lyna_Helga_52ef789c_1:
    l "{size=-5}嗯哼。"

translate schinese hscene50_Lyna_Helga_7df4ec5a:
    h "今晚早些时候你叫我「控制狂母狗」，还记得吗？"

translate schinese hscene50_Lyna_Helga_40eb0ab5:
    l "{size=-5}呃啊……对不起，我……我不是故意——"

translate schinese hscene50_Lyna_Helga_32622713:
    h "{size=+5}安静！"

translate schinese hscene50_Lyna_Helga_048fd1db:
    h "还有我姐姐，你叫她……？"

translate schinese hscene50_Lyna_Helga_65d1a94f:
    h "{cps=25}一个{i}恋童母狗{/i}， {w=0.5}是吗？"

translate schinese hscene50_Lyna_Helga_e868c954:
    l "{size=-5}母亲，求你了——"

translate schinese hscene50_Lyna_Helga_feae6554:
    h "一个趴在地上、嘴里塞满脚的可怜小姑娘，还敢嘴硬。"

translate schinese hscene50_Lyna_Helga_e71c7260:
    h "让你觉得自己有权势了，是吧？！"

translate schinese hscene50_Lyna_Helga_258a973e:
    h "让我重温创伤？看我哭？"

