# -*- coding: utf-8 -*-
# Generated by tools/generate.py - do not edit by hand.
# Sinful Summer (Chapter 3.6) - Simplified Chinese localisation.

translate schinese hscene33_Erik_Lyna_d30b6634:
    n "沉浸在这些轻声细语里，这对双胞胎仿佛退回了童年。"

translate schinese hscene33_Erik_Lyna_11b54b6e:
    n "他们又像小孩子一样，在共用的卧室里贴着耳朵说悄悄话。"

translate schinese hscene33_Erik_Lyna_8a30295a:
    l "好了，这件事说完了……你今晚要不留下来？"

translate schinese hscene33_Erik_Lyna_473ee5f5:
    l "我一整天都{i}紧绷{/i}得不行，毕竟和妈妈做了那些事……"

translate schinese hscene33_Erik_Lyna_82e63198:
    e "我想我知道怎么帮你……姐。"

translate schinese hscene33_Erik_Lyna_687965f0:
    l "好，好！现在准备好听每一个细节吧。"

translate schinese hscene33_Erik_Lyna_a9a1edcd:
    e "你又把她惹生气了？"

translate schinese hscene33_Erik_Lyna_c79204d0:
    l "生气？没有！事实上，我觉得妈妈其实非常——"

translate schinese hscene33_Erik_Lyna_39e89aa3:
    n "在莱娜把那天和母亲做过的所有脏事都说出来之后，可以说那对饥渴的双胞胎也……"

translate schinese hscene33_Erik_Lyna_97ac6032:
    centered "{font=font_narration}{cps=30}度过了一个相当美妙的夜晚。"

translate schinese hscene34_Lyna_Helga_28415d24:
    centered "{font=font_narration}{size=+10}{cps=20}第二天早上……"

translate schinese hscene34_Lyna_Helga_760a1f5b:
    l "好了妈，快好了！开始前还得先试几样东西。"

translate schinese hscene34_Lyna_Helga_8d95bd91:
    h "嘿，宝贝……？我还是不太确定这事。"

translate schinese hscene34_Lyna_Helga_eb210f8d:
    l "别这么胆小嘛妈~！你昨天答应过的，记得吗？"

translate schinese hscene34_Lyna_Helga_00be9dd5:
    l "来，试试这样拍一张？你看起来好自然。"

translate schinese hscene34_Lyna_Helga_1e3504ed:
    l "看？太美了！我就知道今天你状态对了。"

translate schinese hscene34_Lyna_Helga_e6316d6e:
    l "来张近一点的，嗯？"

translate schinese hscene34_Lyna_Helga_89d7d229:
    h "哦不，不行！哈哈。"

translate schinese hscene34_Lyna_Helga_92949dbf:
    l "你怎么又摆出律师的样子？应该去当模特！"

translate schinese hscene34_Lyna_Helga_f861fbc7:
    h "宝贝，你有时候真是……"

translate schinese hscene34_Lyna_Helga_3ef94908:
    l "可你还是爱我！现在去把自己打扮漂亮吧。"

translate schinese hscene34_Lyna_Helga_10ddebe1:
    l "这样等会儿就省下准备的时间了，对吧？"

translate schinese hscene34_Lyna_Helga_3822f064:
    h "有效率，我喜欢。"

translate schinese hscene34_Lyna_Helga_675b5f33:
    h "我只希望别把蛋糕弄得到处都是。"

translate schinese hscene34_Lyna_Helga_ec877da5:
    l "你可以让埃里克做啊，对吧？"

translate schinese hscene34_Lyna_Helga_3d3656ee:
    h "在他自己生日上？不行！"

translate schinese hscene34_Lyna_Helga_3b40312e:
    l "我可警告你，他最近给我做了些超厉害的东西！"

translate schinese hscene34_Lyna_Helga_4568af56:
    l "他正慢慢追上你的水平，嘿嘿~"

translate schinese hscene34_Lyna_Helga_4a0ede04:
    h "那完全没关系！没什么比这更让妈妈骄傲了。"

translate schinese hscene34_Lyna_Helga_c8d2dfdb:
    h "不过今天还是我给你们做，就这么定了！"

translate schinese hscene34_Lyna_Helga_a12e0930:
    l "好吧，好吧……"

translate schinese hscene34_Lyna_Helga_19347ced:
    h "我们只是拍几张照片，好吗？不搞花样……"

translate schinese hscene34_Lyna_Helga_1b26df28:
    l "当然啦妈妈~！"

translate schinese hscene34_Lyna_Helga_cbc06131:
    l "太惊艳了！简直惊艳！"

translate schinese hscene34_Lyna_Helga_59311932:
    l "好，现在开始有意思的部分吧！"

translate schinese hscene34_Lyna_Helga_a48b02df:
    h "意思是……？"

translate schinese hscene34_Lyna_Helga_8a6c7ee2:
    l "当然是比基尼！我们买的那些我还没看你穿过几件呢。"

translate schinese hscene34_Lyna_Helga_b4681432:
    h "哦，好吧……"

translate schinese hscene34_Lyna_Helga_0a35d57a:
    l "那个颜色真适合你，妈！"

translate schinese hscene34_Lyna_Helga_ea14c683:
    h "这个姿势怎么样？"

translate schinese hscene34_Lyna_Helga_36da25e5:
    l "好，完美！保持住……"

translate schinese hscene34_Lyna_Helga_e74d64e1:
    l "你以后该多拍拍，知道吗？你是天生吃这碗饭的！"

translate schinese hscene34_Lyna_Helga_a0a97785:
    l "妈，你看起来性感死了。"

translate schinese hscene34_Lyna_Helga_bce4076c:
    hm "又来？！天哪，这件上衣也太紧了！"

translate schinese hscene34_Lyna_Helga_5d642e5e:
    hm "不过说真的……"

translate schinese hscene34_Lyna_Helga_0bdd1203:
    hm "我穿着确实很{i}性感{/i}，没错。"

translate schinese hscene34_Lyna_Helga_4ece6f5f:
    l "我现在从下面拍一张，好吗？"

translate schinese hscene34_Lyna_Helga_ca725539:
    lm "操，我好想要她。"

translate schinese hscene34_Lyna_Helga_1fd0d400:
    h "那里好痒！哈哈~"

translate schinese hscene34_Lyna_Helga_41e9af8a:
    l "对了，我昨天忘了问你一件重要的事。"

translate schinese hscene34_Lyna_Helga_5fd983d9:
    h "哦？什么事？"

translate schinese hscene34_Lyna_Helga_21f9d328:
    l "我是你的第一个孩子吗？"

translate schinese hscene34_Lyna_Helga_81ab9351:
    h "咦？莱娜，你到底想说什么？"

translate schinese hscene34_Lyna_Helga_d6672408:
    l "我边摆姿势边跟你说，好吗？"

translate schinese hscene34_Lyna_Helga_d406fc2e:
    l "那在埃里克和我之间，你先「生出来」的是我们哪个……呃？"

translate schinese hscene34_Lyna_Helga_15221aa9:
    hm "真是的，这女孩怎么回事？！她真是毫无下限！"

translate schinese hscene34_Lyna_Helga_bd0fb39b:
    l "我知道这个问题很奇怪，但它最近一直困扰着我。"

translate schinese hscene34_Lyna_Helga_5cb9175f:
    l "我叫他哥哥，可要是他反而更小，那就怪怪的了，对吧？"

translate schinese hscene34_Lyna_Helga_c70d33e0:
    hm "她到底想干什么？不过是几分钟而已，有什么好在意的……"

translate schinese hscene34_Lyna_Helga_77782b3b:
    l "拜托你就告诉我嘛~？我超级好奇！"

translate schinese hscene34_Lyna_Helga_101ce588:
    h "你们还是双胞胎没错……不过，其实是你哥哥先出生的。"

translate schinese hscene34_Lyna_Helga_3bf9653d:
    l "那我就是他的小妹妹咯？！好可爱！"

translate schinese hscene34_Lyna_Helga_02103685:
    h "算是吧……不过也就差了几分钟。"

translate schinese hscene34_Lyna_Helga_35b3bd3b:
    l "我明白了。那谢谢妈回答我。"

translate schinese hscene34_Lyna_Helga_ddd4fdea:
    h "{size=-5}是吧……"

translate schinese hscene34_Lyna_Helga_234e9aab:
    l "对了，你觉得我能给你拍一张……{size=-5}不穿衣服的吗？"

translate schinese hscene34_Lyna_Helga_1657fb38:
    h "{size=+5}什么？！{/size}{size=+10}不行！{/size}我们说好了今天不搞花样……"

translate schinese hscene34_Lyna_Helga_ed209d20:
    l "抱歉！我的错。我说过不再逼你的。"

translate schinese hscene34_Lyna_Helga_09508d95:
    l "那要不我现在先教你基础知识，行吗？"

translate schinese hscene34_Lyna_Helga_abd8f99e:
    h "我没意见。需要我帮你挑衣服吗？"

translate schinese hscene34_Lyna_Helga_96b845c0:
    l "不用！是个惊喜。你已经帮我帮得够多了，这个——"

translate schinese hscene34_Lyna_Helga_66161aec:
    l "这个~！"

translate schinese hscene34_Lyna_Helga_c1a0b878:
    h "好看，宝贝。你太可爱了！"

translate schinese hscene34_Lyna_Helga_1e3d14c7:
    l "谢谢！我马上回来。"

translate schinese hscene34_Lyna_Helga_e9a1c440:
    lm "所以我算是老二了，嗯？不错嘛。毕竟我是他的小妹妹……"

translate schinese hscene34_Lyna_Helga_a4c3c4d9:
    h "等等！宝贝……？"

translate schinese hscene34_Lyna_Helga_971dd5ed:
    l "嗯？什——"

translate schinese hscene34_Lyna_Helga_4f681e7f:
    h "啧。你还在等什么……？"

translate schinese hscene34_Lyna_Helga_c5f0f697:
    l "可你不是说——"

translate schinese hscene34_Lyna_Helga_fae84f72:
    h "{size=-5}快点，趁我还没后悔。"

translate schinese hscene34_Lyna_Helga_736b7d79:
    h "把那些藏好，好吗？别给任何人看。{size=-5}我是认真的。"

translate schinese hscene34_Lyna_Helga_6e8e57e0:
    l "好、好的。放心吧……"

translate schinese hscene34_Lyna_Helga_65e31e33:
    h "好了好了，别盯着了，快去换衣服！"

translate schinese hscene34_Lyna_Helga_92a205de:
    l "好的妈妈，当然！{size=-5}对不起……"

translate schinese hscene34_Lyna_Helga_ad4bb97e:
    h "别让我等太久！"

translate schinese hscene34_Lyna_Helga_5f38fa7e:
    hm "我为什么就答应了？！我是不是越来越享受这个了？"

translate schinese hscene34_Lyna_Helga_8519d91f:
    hm "把光着的身子给自己的孩子看，任他们怎么看都不设防……"

translate schinese hscene34_Lyna_Helga_53b3a127:
    hm "我喜欢这么做吗？感觉确实……很有力量。"

translate schinese hscene34_Lyna_Helga_0d57e837:
    n "一如往常，莱娜慢悠悠地磨蹭了好久……"

translate schinese hscene34_Lyna_Helga_ec0fc066:
    l "嘘嘘妈，我回来了！"

translate schinese hscene34_Lyna_Helga_52077deb:
    h "嘿，终于好了！"

translate schinese hscene34_Lyna_Helga_5631fe3f:
    h "咦？！这……？！"

translate schinese hscene34_Lyna_Helga_6ec7d3ea:
    l "惊喜！还记得这个小宝贝吗？"

translate schinese hscene34_Lyna_Helga_415e1907:
    l "{cps=30}我穿着我妈妈的{w=0.25}内{w=0.25}衣{w=0.25}套！{w=0.5}我穿着我妈妈的{w=0.25}内{w=0.25}衣{w=0.25}套~"

translate schinese hscene34_Lyna_Helga_2ade2471:
    h "亲爱的，能不能别这样了？！哈哈哈！"

translate schinese hscene34_Lyna_Helga_bd7fd116:
    hm "真是的，还是这么软……"

translate schinese hscene34_Lyna_Helga_3119becf:
    h "我还以为好多年前就把它处理掉了！"

translate schinese hscene34_Lyna_Helga_e85e0946:
    l "我不是告诉过你，埃里克和我是在地下室找到它的吗？"

translate schinese hscene34_Lyna_Helga_46bf189c:
    h "哦……我记得，是有这么回事。"

translate schinese hscene34_Lyna_Helga_5cea2a5d:
    l "我知道我没以前那么好了，不过还是……"

translate schinese hscene34_Lyna_Helga_90959e79:
    l "穿在我身上很好看对吧，嗯？"

translate schinese hscene34_Lyna_Helga_8c6c06a7:
    hm "那对刚发育的小乳房……穿在她身上显得松松垮垮的。"

translate schinese hscene34_Lyna_Helga_7c055b9d:
    hm "是啊，我像她那么大的时候可比这对大多了。"

translate schinese hscene34_Lyna_Helga_64d8f1cb:
    hm "天哪，我又来了！别盯着看了，赫尔加！"

translate schinese hscene34_Lyna_Helga_457c2948:
    l "你也该试试穿上它。"

translate schinese hscene34_Lyna_Helga_a39825d9:
    h "你在开玩笑吧？！我现在怎么可能穿得进去。"

translate schinese hscene34_Lyna_Helga_b0f8457e:
    l "是啊……「巨乳小姐」在这上面肯定有点困难。"

translate schinese hscene34_Lyna_Helga_76c58c8d:
    h "{size=+10}亲爱的！{/size}啧。" with vpunch

translate schinese hscene34_Lyna_Helga_5e85b643:
    hm "天哪，我女儿前面可能有点发育不足，不过她那后面嘛……"

translate schinese hscene34_Lyna_Helga_3d8433cd:
    h "你穿着真好看，我的宝贝。比当年我强多了。"

translate schinese hscene34_Lyna_Helga_07dda270:
    l "你真这么觉得？！"

translate schinese hscene34_Lyna_Helga_28b2a17e:
    h "是啊，有点怀念的感觉。"

translate schinese hscene34_Lyna_Helga_9d59d472:
    hm "要是{i}那些{/i}回忆没有附着在上面就好了……"

translate schinese hscene34_Lyna_Helga_f5018fde:
    hm "安娜……我们光裸的身体彼此摩擦……"

translate schinese hscene34_Lyna_Helga_38b44488:
    lm "哇！她他妈在干什么？！"

translate schinese hscene34_Lyna_Helga_13664b46:
    lm "她那些怀旧回忆……是不是很火辣？真好！"

translate schinese hscene34_Lyna_Helga_5ba904fb:
    l "你买这个是为了哪个幸运儿？爸……？"

translate schinese hscene34_Lyna_Helga_5e4405d6:
    h "不！没、没有谁。我只是在镜子前摆姿势，给……我自己看。"

translate schinese hscene34_Lyna_Helga_ae46e6be:
    l "哦，镜子啊！{size=-10}是吧。"

translate schinese hscene34_Lyna_Helga_1e397ee8:
    l "{size=-5}妈妈？给我点空间行不行？"

translate schinese hscene34_Lyna_Helga_e315593f:
    h "啊！真对不起宝贝……"

translate schinese hscene34_Lyna_Helga_6382c012:
    l "我现在穿着它，你不自在吗？"

translate schinese hscene34_Lyna_Helga_0a8a852d:
    h "嗯……穿你身上是好看，可这毕竟是我少女时代的旧内衣！"

translate schinese hscene34_Lyna_Helga_8ccce182:
    h "你不该穿这种衣服的，你知道……"

translate schinese hscene34_Lyna_Helga_d2353447:
    l "为什么不？穿我身上好看极了，而且也很舒服！"

translate schinese hscene34_Lyna_Helga_22c0f3fd:
    l "这说明我的品味和你一样好！你当年可太超前了。"

translate schinese hscene34_Lyna_Helga_9010ec5a:
    l "总之，废话少说！该上课了，你不觉得吗？"

translate schinese hscene34_Lyna_Helga_8c516894:
    n "莱娜用她一贯的热情，花了好一会儿给母亲讲解相机的基础知识。"

translate schinese hscene34_Lyna_Helga_453c1004:
    l "很好。现在试着拍出我最好看的一面！"

translate schinese hscene34_Lyna_Helga_af1395a0:
    l "就是现在流行的那种侧身曲线！"

translate schinese hscene34_Lyna_Helga_92ba9a19:
    h "好吧，我看看……"

translate schinese hscene34_Lyna_Helga_6f52e52f:
    l "新手来说不错，但还能更好。"

translate schinese hscene34_Lyna_Helga_2a7cdabe:
    l "你要用对焦，还要想着角度，妈！角度！"

translate schinese hscene34_Lyna_Helga_53c16cce:
    h "是是……这比我想象的难。"

translate schinese hscene34_Lyna_Helga_6efe3bd9:
    l "要把这些照片拍出我的灵魂，而不只是我的身体！"

translate schinese hscene34_Lyna_Helga_44e627aa:
    hm "她看起来真优雅、真漂亮……"

translate schinese hscene34_Lyna_Helga_fad34383:
    hm "我的小女儿真的开始处处像我了。"

translate schinese hscene34_Lyna_Helga_1570e668:
    l "看？拍得真好！你开始上手了。"

translate schinese hscene34_Lyna_Helga_4791cc58:
    l "可你知道还缺什么吗？"

translate schinese hscene34_Lyna_Helga_fe1360dd:
    h "熟能生巧，对吧？"

translate schinese hscene34_Lyna_Helga_c47877a7:
    l "不，我们需要另一个模特！你和我，像一对闺蜜那样，啊？"

translate schinese hscene34_Lyna_Helga_414b9138:
    h "你是要我换上内衣……？"

translate schinese hscene34_Lyna_Helga_967b870e:
    l "对！说不定你还可以试试我专门为你挑的那套？"

translate schinese hscene34_Lyna_Helga_33a3f6b2:
    h "哦！可那套有点太……露了，对吧？"

translate schinese hscene34_Lyna_Helga_2f6e368a:
    l "拜托妈！那就是内衣啊！不过我知道你撑得住。"

translate schinese hscene34_Lyna_Helga_6c9397ee:
    l "毕竟你是我见过最自信的女人！"

translate schinese hscene34_Lyna_Helga_ca83dc67:
    h "哦，少来！你又想哄我开心了，小姐？"

translate schinese hscene34_Lyna_Helga_33fe42d3:
    l "也许吧……？我们在一起玩得很开心，不是吗？"

translate schinese hscene34_Lyna_Helga_6f93b8f2:
    h "好吧好吧……但你得答应我这是最后一套。我得开始准备午饭了。"

translate schinese hscene34_Lyna_Helga_ee823471:
    l "{size=+10}好耶～！成交！"

translate schinese hscene34_Lyna_Helga_3c051cd8:
    l "妈，你看起来……好危险！"

translate schinese hscene34_Lyna_Helga_a70cc025:
    l "像个性感杀手！你这是要勾引谁啊？"

translate schinese hscene34_Lyna_Helga_9e61490f:
    h "莱娜！你就好好拍你的照片……"

translate schinese hscene34_Lyna_Helga_1c3cd963:
    l "完美！你简直是女神！"

translate schinese hscene34_Lyna_Helga_4c054c0f:
    h "呃……宝贝？我穿这个不是为了和你一起拍照吗？"

translate schinese hscene34_Lyna_Helga_2bc297bf:
    l "哦，对！我怎么拍都看不够你，哈哈！"

translate schinese hscene34_Lyna_Helga_137fc842:
    l "等我一下。马上回来！"

translate schinese hscene34_Lyna_Helga_2d813626:
    h "等等……！你要去哪儿？！"

translate schinese hscene35_Erik_Lyna_Helga_ee5027ad:
    e "你确定吗？{size=-5}她可能会生气……"

translate schinese hscene35_Erik_Lyna_Helga_1f854d6e:
    l "不会的，没问题，相信我！"

translate schinese hscene35_Erik_Lyna_Helga_79b1095c:
    l "妈咪~？嗨！刚才抱歉了！"

translate schinese hscene35_Erik_Lyna_Helga_e38dc0ef:
    h "太好了！你为什么——"

translate schinese hscene35_Erik_Lyna_Helga_4187929d:
    h "{size=+5}啊！他来干什么？！怎么回事，莱娜？"

translate schinese hscene35_Erik_Lyna_Helga_9c43d232:
    l "别担心，妈。埃里克只是来帮我们拍照的！"

translate schinese hscene35_Erik_Lyna_Helga_726ac9f4:
    h "{size=+5}可是……为什么？！"

translate schinese hscene35_Erik_Lyna_Helga_c9106467:
    l "你看见三脚架了吗？因为我肯定没有！"

translate schinese hscene35_Erik_Lyna_Helga_c45a7d80:
    l "不然你想怎么把我们俩都好好框进画面里？"

translate schinese hscene35_Erik_Lyna_Helga_9c3a1954:
    h "呃，我……嗯……"

translate schinese hscene35_Erik_Lyna_Helga_b8e2342c:
    e "没关系，妈。我很乐意帮忙。"

translate schinese hscene35_Erik_Lyna_Helga_80a1d2c0:
    hm "哎呀，他已经在盯着我看了！"

translate schinese hscene35_Erik_Lyna_Helga_24885248:
    hm "到底怎么回事？！他怎么能接受这个？！"

translate schinese hscene35_Erik_Lyna_Helga_14c78a40:
    hm "而且她为什么在自己哥哥面前这么自在？！"

translate schinese hscene35_Erik_Lyna_Helga_0b35c674:
    hm "那衣服几乎遮不住她，可她们一点也不觉得难为情！"

translate schinese hscene35_Erik_Lyna_Helga_57f0e815:
    l "来嘛妈，来嘛！怎么了？"

translate schinese hscene35_Erik_Lyna_Helga_6d8b231e:
    l "你不是急着做完吗？你还有蛋糕要烤！"

translate schinese hscene35_Erik_Lyna_Helga_a667d413:
    h "呃……对。{size=-5}哈哈……"

translate schinese hscene35_Erik_Lyna_Helga_bf2e4205:
    l "看？我们的摄影师已经准备好啦！"

translate schinese hscene35_Erik_Lyna_Helga_1f0d20f5:
    h "可是莱娜，你——"

translate schinese hscene35_Erik_Lyna_Helga_c645fd71:
    l "没时间说「可是」了，妈！开始吧！"

translate schinese hscene35_Erik_Lyna_Helga_3514c429:
    l "亲爱的哥哥，还记得我教过你的吗？"

translate schinese hscene35_Erik_Lyna_Helga_e3616237:
    e "记得，姐，我最喜欢的女孩们在可靠的手里。"

translate schinese hscene35_Erik_Lyna_Helga_e939e2a0:
    hm "真的吗？！她们是在整我吧？！"

translate schinese hscene35_Erik_Lyna_Helga_b6e842c0:
    em "居然说动她了，真不敢相信……"

translate schinese hscene35_Erik_Lyna_Helga_3fff7c03:
    l "那你知道该做什么了吧，埃里克。给我们展示你内心的艺术家！"

translate schinese hscene35_Erik_Lyna_Helga_c2352662:
    l "准备好了吗妈妈~？"

translate schinese hscene35_Erik_Lyna_Helga_0d44c8ed:
    h "{size=-5}我……我不确定……"

translate schinese hscene35_Erik_Lyna_Helga_6bd411ca:
    l "只是拍几张傻照片而已，好吗？放轻松。"

translate schinese hscene35_Erik_Lyna_Helga_88bbfd56:
    h "啧，好吧……{size=-5}赶紧搞完。"

translate schinese hscene35_Erik_Lyna_Helga_77e12b06:
    e "好！现在，要不你站近一点？"

translate schinese hscene35_Erik_Lyna_Helga_7723dde6:
    e "比如呃……肩并肩？{size=-5}我也不清楚。"

translate schinese hscene35_Erik_Lyna_Helga_401ebeaa:
    lm "他有点不知所措，不过这还挺可爱的。我哥哥就算当大色鬼也还是很帅！"

translate schinese hscene35_Erik_Lyna_Helga_cab3d073:
    n "男孩用一连串姿势指导她们，每一个都比上一个更暧昧。"

translate schinese hscene35_Erik_Lyna_Helga_23b0941b:
    n "可看着他最亲的两位亲人——母亲和女儿——那两具完美的身体在如此轻薄的衣服下紧贴在一起……"

translate schinese hscene35_Erik_Lyna_Helga_c9eb5d63:
    n "让他的想象力彻底失控。"

translate schinese hscene35_Erik_Lyna_Helga_9fd3d8a9:
    l "你干得太棒了，哥！"

translate schinese hscene35_Erik_Lyna_Helga_4c9561ed:
    e "谢谢。你是个很棒的老师……"

translate schinese hscene35_Erik_Lyna_Helga_48e8f171:
    l "你觉得呢？妈妈和我够不够火辣，能当模特了吗？"

translate schinese hscene35_Erik_Lyna_Helga_0928dd91:
    h "{size=+10}莱娜！{/size} {size=-5}天啊……"

translate schinese hscene35_Erik_Lyna_Helga_0726080d:
    e "当然。你们俩都好看极了。"

translate schinese hscene35_Erik_Lyna_Helga_04e876d9:
    l "只是好看？拜托，你可以说得更好听点吧！"

translate schinese hscene35_Erik_Lyna_Helga_36fb42d5:
    l "细节，细节！我是说，现在你是摄影师了！"

translate schinese hscene35_Erik_Lyna_Helga_8a20d58d:
    l "你觉得哪一点最吸引你，嗯？"

translate schinese hscene35_Erik_Lyna_Helga_ff9c6f5a:
    e "呃，那个……"

translate schinese hscene35_Erik_Lyna_Helga_91a91dec:
    hm "说真的，她们简直在挑战每一条底线！"

translate schinese hscene35_Erik_Lyna_Helga_98e1bff2:
    hm "我的孩子们真是越来越没规矩了，好像我根本不在场一样！"

translate schinese hscene35_Erik_Lyna_Helga_09b0ac4f:
    e "我觉得你们的姿势很到位，妆也完美……"

translate schinese hscene35_Erik_Lyna_Helga_71d4d540:
    l "那我们的衣服呢，嗯？"

translate schinese hscene35_Erik_Lyna_Helga_3250fdeb:
    e "它们真是……{size=-5}太火辣了。"

translate schinese hscene35_Erik_Lyna_Helga_3938b305:
    hm "{size=+5}哦我的天！什么？！"

translate schinese hscene35_Erik_Lyna_Helga_efd18477:
    hm "还有等等，他在哪……？！"

translate schinese hscene35_Erik_Lyna_Helga_094115b4:
    e "而且这些性感衣服真的很衬你美丽的曲线。"

translate schinese hscene35_Erik_Lyna_Helga_8e608255:
    h "{size=+5}够了儿子！我们听明白了！"

translate schinese hscene35_Erik_Lyna_Helga_47149fd2:
    e "怎么了妈？我知道什么叫内衣。"

translate schinese hscene35_Erik_Lyna_Helga_a3a319c3:
    h "即便这样，你也不能对我们说那种话，好吗？！"

translate schinese hscene35_Erik_Lyna_Helga_79fefe75:
    hm "他本来就不该在这儿！"

translate schinese hscene35_Erik_Lyna_Helga_75da0e48:
    e "可如果它们就是性感衣服，那我该叫它们什么？"

translate schinese hscene35_Erik_Lyna_Helga_a1f30402:
    h "亲爱的？！呃，它们……"

translate schinese hscene35_Erik_Lyna_Helga_8499c821:
    l "妈妈，它们确实很性感啊。你可是听家里男人说的！"

translate schinese hscene35_Erik_Lyna_Helga_2a665317:
    l "我们不是小孩子了，可以聊这些事！"

translate schinese hscene35_Erik_Lyna_Helga_801f4964:
    e "是的，妈……我们知道由你来说可能听着有点怪，但我们在家里都互相信任，对吧？"

translate schinese hscene35_Erik_Lyna_Helga_74d22179:
    e "再说了，如果你们俩身材都这么棒，我为什么要撒谎？你一直教我要诚实。"

translate schinese hscene35_Erik_Lyna_Helga_a15cfdb1:
    hm "他们这是怎么了？！而且我那害羞的小王子怎么会说这些还不结巴？！"

translate schinese hscene35_Erik_Lyna_Helga_c1ea42ab:
    hm "这……这肯定是他们俩在整我，对！"

translate schinese hscene35_Erik_Lyna_Helga_12acd80c:
    h "你们两个，{size=-5}就……{/size}赶紧弄完吧。"

translate schinese hscene35_Erik_Lyna_Helga_fcaa29e5:
    l "再来一张嘛~？给我们摆姿势很难拒绝，对吧？"

translate schinese hscene35_Erik_Lyna_Helga_8543639d:
    h "就一张，好吗？！{size=-5}蛋糕不会自己烤好……"

translate schinese hscene35_Erik_Lyna_Helga_5e850092:
    l "好！就这么办。"

translate schinese hscene35_Erik_Lyna_Helga_3514f642:
    l "最后来一张亲密点的收尾怎么样？"

translate schinese hscene35_Erik_Lyna_Helga_a550b899:
    h "亲密？怎么个亲密法？"

translate schinese hscene35_Erik_Lyna_Helga_d6959978:
    l "对，就像……两个闺蜜在分享一个超级大秘密！"

translate schinese hscene35_Erik_Lyna_Helga_01dc7ceb:
    l "摄影师先生，这样可以吗？"

translate schinese hscene35_Erik_Lyna_Helga_0443289b:
    e "好主意，小莱！去坐下吧。"

translate schinese hscene35_Erik_Lyna_Helga_5d11f626:
    l "像这样，你看？小小的一碰，一堆笑声……"

translate schinese hscene35_Erik_Lyna_Helga_1e6ee5d5:
    l "{size=-5}一个只有我们知道的、非常特别的秘密。"

translate schinese hscene35_Erik_Lyna_Helga_7ecd689c:
    hm "哦天哪……她又来了？！而且还是当着我的亲儿子、她哥哥的面，就在那儿看着？！"

translate schinese hscene35_Erik_Lyna_Helga_4a07a09c:
    hm "我该阻止她的，可不知怎么……这居然有点刺激？"

translate schinese hscene35_Erik_Lyna_Helga_e2fcc7e7:
    l "我们就像两块拼图，对吧？妈妈和我拼在一起天衣无缝！"

translate schinese hscene35_Erik_Lyna_Helga_115add0d:
    h "咳！孩子们？差不多了吧……？" with vpunch

translate schinese hscene35_Erik_Lyna_Helga_e07b69d9:
    e "好、好了，都拍完了。"

translate schinese hscene35_Erik_Lyna_Helga_f8e26655:
    l "太棒了！你干得真漂亮，埃里克！"

translate schinese hscene35_Erik_Lyna_Helga_02669409:
    e "我开始明白你为什么这么喜欢拍照了……"

translate schinese hscene35_Erik_Lyna_Helga_e0e94d44:
    l "对啊！我的相机就像我的孩子，嘿嘿~"

translate schinese hscene35_Erik_Lyna_Helga_22178abb:
    l "妈？连句再见都没有……？"

translate schinese hscene35_Erik_Lyna_Helga_2d79783e:
    e "她会忙一阵的，姐。你到底想不想吃蛋糕？"

translate schinese hscene35_Erik_Lyna_Helga_6fd4d5fb:
    l "哼，那你就慢慢折腾吧……"

translate schinese hscene35_Erik_Lyna_Helga_b561c840:
    e "妈，需要我帮忙吗？"

translate schinese hscene35_Erik_Lyna_Helga_a7c7a77c:
    l "不用啦，哥！你就留在这儿再跟我多拍几张，好不好？"

translate schinese hscene35_Erik_Lyna_Helga_55466155:
    hm "穿着我的内衣？还跟他那样……那个？！"

translate schinese hscene35_Erik_Lyna_Helga_47218d0c:
    h "{size=+5}想都别想，你这个小恶魔！"

translate schinese hscene35_Erik_Lyna_Helga_d8dfa7ab:
    h "你哥哥现在得跟我走，总得有人来学家里的独门菜谱！"

translate schinese hscene35_Erik_Lyna_Helga_195c5de2:
    l "所以你打算穿着那玩意儿做饭？真坏！"

translate schinese hscene35_Erik_Lyna_Helga_335d0955:
    h "好、好的。抱歉亲爱的，我去一下洗手间。"

translate schinese hscene35_Erik_Lyna_Helga_bb920600:
    e "小莱，刚才那是怎么回事？！" with vpunch

translate schinese hscene35_Erik_Lyna_Helga_3120c687:
    l "你说呢？！你从来没这么有自信过！"

translate schinese hscene35_Erik_Lyna_Helga_4ecc4040:
    l "「这些性感衣服真的很衬你美丽的曲线。」哈哈哈，老哥！"

translate schinese hscene35_Erik_Lyna_Helga_c2ab18f0:
    l "难怪她的小金童那么一说，她就跑了……"

translate schinese hscene35_Erik_Lyna_Helga_41888316:
    e "随便吧姐，这太疯狂了！你怎么能让妈穿上那个？而且她为什么这么自在？"

translate schinese hscene35_Erik_Lyna_Helga_79faee10:
    e "你昨天跟我说的那些事……真的都和我们母亲做了？！"

translate schinese hscene35_Erik_Lyna_Helga_6b8b862a:
    l "嘿嘿嘿~！只能说，会撩的不止你一个……"

translate schinese story49_Erik_Lyna_Helga_9d0244fa:
    centered "{font=font_narration}{size=+10}{cps=20}两小时后……"

translate schinese story49_Erik_Lyna_Helga_96360a98:
    h "{size=+10}孩子们，生日快乐！"

translate schinese story49_Erik_Lyna_Helga_acec7d18:
    e "妹妹，我们要许愿吗？"

translate schinese story49_Erik_Lyna_Helga_0dc81073:
    l "要要要！随时都可以！"

translate schinese story49_Erik_Lyna_Helga_0bd9a1b1:
    h "怎么样？我可是倾注了全部心思！"

translate schinese story49_Erik_Lyna_Helga_2951dbc9:
    l "妈，你真的太厉害了！"

translate schinese story49_Erik_Lyna_Helga_61dbc554:
    e "一切都太棒了对吧！吃的、还有装饰……"

translate schinese story49_Erik_Lyna_Helga_1a577368:
    h "谢谢！现在要由你来切蛋糕吗？"

translate schinese story49_Erik_Lyna_Helga_ff6c3b93:
    l "妈咪——～不能先拆礼物吗？"

translate schinese story49_Erik_Lyna_Helga_b47d694f:
    h "哦？这么急的小丫头！哈哈~"

translate schinese story49_Erik_Lyna_Helga_816c32c3:
    e "对啊，我也想看看你给我们准备了什么！"

translate schinese story49_Erik_Lyna_Helga_6cb55355:
    h "好吧，好吧……"

translate schinese story49_Erik_Lyna_Helga_30733b7c:
    h "这份是给我家小宝贝的，全世界最可爱的那个！"

translate schinese story49_Erik_Lyna_Helga_ca7ab71f:
    l "天啊！这也太可爱了吧！"

translate schinese story49_Erik_Lyna_Helga_d70fc4cf:
    h "我想着你们以后去酒吧玩会需要，还有……也是为了惊艳那些男孩子！"

translate schinese story49_Erik_Lyna_Helga_436ce887:
    l "对啊！不过你早就该给我了！"

translate schinese story49_Erik_Lyna_Helga_2ce1675d:
    l "想想我拍照片能好看多少……"

translate schinese story49_Erik_Lyna_Helga_5eea8232:
    h "真可惜……下次吧，好吗？"

translate schinese story49_Erik_Lyna_Helga_e733e207:
    lm "她还想再来一次？！"

translate schinese story49_Erik_Lyna_Helga_af96cac9:
    l "当、当然！"

translate schinese story49_Erik_Lyna_Helga_b70b319e:
    h "这份给你，我的小王子。最贴心最靠谱的男孩！"

translate schinese story49_Erik_Lyna_Helga_14c4900f:
    e "哇，妈，这些太棒了！"

translate schinese story49_Erik_Lyna_Helga_83d36419:
    h "我想你学习的时候能听点好音乐。"

translate schinese story49_Erik_Lyna_Helga_a209c269:
    e "谢谢，太谢谢了！"

translate schinese story49_Erik_Lyna_Helga_8ea5cae7:
    h "真高兴你们俩都喜欢礼物！"

translate schinese story49_Erik_Lyna_Helga_01b0484d:
    e "对！全世界最好的妈，对吧妹妹？！"

translate schinese story49_Erik_Lyna_Helga_3f19658d:
    l "{size=+5}耶！妈咪~！"

translate schinese story49_Erik_Lyna_Helga_67f43e51:
    h "好了好了，我的小宝、宝贝们，够了……"

translate schinese story49_Erik_Lyna_Helga_eae69c8d:
    l "现在该吃蛋糕啦！"

translate schinese story49_Erik_Lyna_Helga_c7b10a0c:
    e "对！我饿死了。"

translate schinese story49_Erik_Lyna_Helga_d65cabb5:
    h "来……第一块给两位寿星！"

translate schinese story49_Erik_Lyna_Helga_784c69c8:
    l "嗯唔！好好吃~！"

translate schinese story49_Erik_Lyna_Helga_19ff8ad8:
    l "{size=+5}唔咕噜！" with vpunch

translate schinese story49_Erik_Lyna_Helga_54673739:
    h "慢点吃丫头！哈哈！"

translate schinese story49_Erik_Lyna_Helga_5b9fb925:
    e "噗哈哈哈哈莱娜！你好好笑！"

translate schinese story49_Erik_Lyna_Helga_24dcd6e7:
    l "妈你一定得尝尝，真的超棒！"

translate schinese story49_Erik_Lyna_Helga_40d22f4e:
    h "宝贝你喜欢就好。"

translate schinese story49_Erik_Lyna_Helga_1daa4520:
    e "做出来真的很好吃！你真该开家面包店。"

translate schinese story49_Erik_Lyna_Helga_213f8c61:
    h "哈！不行不行，宝贝！当个爱好就够了。"

translate schinese story49_Erik_Lyna_Helga_b5405ed6:
    l "你知道这蛋糕有多好吃吗？不认真切开简直是对它的犯罪！"

translate schinese story49_Erik_Lyna_Helga_b278378d:
    e "说得对！我一个人全吃完太不好意思了……"

translate schinese story49_Erik_Lyna_Helga_6231de8b:
    h "嗯？你们俩又在计划什么？可别胡闹哦？"

translate schinese story49_Erik_Lyna_Helga_929bf339:
    l "不会的妈，我们才不会！{size=-10}除非……"

translate schinese story49_Erik_Lyna_Helga_75ba5171:
    h "{size=+5}莱娜！我刚说什么了？！"

translate schinese story49_Erik_Lyna_Helga_3ec9be5e:
    e "哦，战争开始了妹妹！"

translate schinese story49_Erik_Lyna_Helga_dc1aa2bc:
    l "你休想抓到我！"

translate schinese story49_Erik_Lyna_Helga_49cdc032:
    h "小心点莱娜！别穿着高跟鞋到处跑！"

translate schinese story49_Erik_Lyna_Helga_d04d1f44:
    h "喂！当心！奶油会弄得到处都是！"

translate schinese story49_Erik_Lyna_Helga_c8bbf0ba:
    e "哈！抓到你了，你这个小恶魔！"

translate schinese story49_Erik_Lyna_Helga_3191d302:
    l "{size=+5}妈咪——！救救我！！！" with hpunch

translate schinese story49_Erik_Lyna_Helga_f0145eef:
    l "{size=+10}噗哈哈哈，埃里克——！"

translate schinese story49_Erik_Lyna_Helga_43b5b776:
    h "饶了我吧两位……你们跟小孩一样！"

translate schinese story49_Erik_Lyna_Helga_97ec61cb:
    e "莱娜，我觉得妈干净得过分了吧？"

translate schinese story49_Erik_Lyna_Helga_b0120be9:
    h "什么？！别这样。"

translate schinese story49_Erik_Lyna_Helga_4440a964:
    l "其实我觉得她保持原样就最完美！"

translate schinese story49_Erik_Lyna_Helga_ca726625:
    h "啧。你这傻丫头……"

translate schinese story49_Erik_Lyna_Helga_34fe9b7e:
    e "我可不敢这么说！"

translate schinese story49_Erik_Lyna_Helga_9945b05a:
    h "小心点儿子！你这是在玩火哦，哈哈！"

translate schinese story49_Erik_Lyna_Helga_10b054c3:
    e "哦，我很确定我能搞定。"

translate schinese story49_Erik_Lyna_Helga_59ab51ea:
    h "什么？！天啊莱娜，你对你哥哥做了什么？！"

translate schinese story49_Erik_Lyna_Helga_e9a43f7f:
    h "我还以为只有你一个人会恶作剧呢！"

translate schinese story49_Erik_Lyna_Helga_b3bec7a5:
    l "我？我什么都没做……{size=-5}嘿嘿~"

translate schinese story49_Erik_Lyna_Helga_8db415ce:
    l "给你的，全世界最棒的哥哥！"

translate schinese story49_Erik_Lyna_Helga_1f54b221:
    l "别担心，我也没忘了我的新欢！"

translate schinese story49_Erik_Lyna_Helga_849ce775:
    h "好、好吃，宝贝……{size=-5}但这些傻游戏我可玩够了。"

translate schinese story49_Erik_Lyna_Helga_255abe99:
    e "这样很舒服，姑娘们……我们该多点才行。"

translate schinese story49_Erik_Lyna_Helga_2f621273:
    l "对！感觉我们又像个正常家庭了！"

translate schinese story49_Erik_Lyna_Helga_9e24e143:
    h "天啊，{size=-5}我的两个小宝贝……"

translate schinese story49_Erik_Lyna_Helga_30e2166c:
    h "我们会的，我保证！我爱你们胜过世上一切。"

translate schinese story49_Erik_Lyna_Helga_cc3989b8:
    h "现在……我们去把剩下的午饭吃完吧，好吗？"

translate schinese story49_Erik_Lyna_Helga_e796c651:
    l "天，我好撑！"

translate schinese story49_Erik_Lyna_Helga_e16e53fe:
    e "同感。太饱了！"

translate schinese story49_Erik_Lyna_Helga_5ce07648:
    h "*叹气*你那些新朋友这次没来，我有点难过。"

translate schinese story49_Erik_Lyna_Helga_73e090c4:
    h "这算不上什么派对，对吧？"

translate schinese story49_Erik_Lyna_Helga_bbc04fc9:
    e "妈别担心，完全没关系！"

translate schinese story49_Erik_Lyna_Helga_731ae174:
    e "说实话，最近我们更喜欢这种安安静静的日子。"

translate schinese story49_Erik_Lyna_Helga_b57eb4ae:
    l "对！能和你一起度过就已经足够了！"

translate schinese story49_Erik_Lyna_Helga_a1aeec7e:
    h "呜……不过我还是觉得今天该做点更特别的事。"

translate schinese story49_Erik_Lyna_Helga_c4ba9eb4:
    h "不如我们去一家好餐厅吃晚饭？或者一起去那种夏季露天影院？"

translate schinese story49_Erik_Lyna_Helga_b081092e:
    l "其实……{size=-5}关于那件事……"

translate schinese story49_Erik_Lyna_Helga_9855e95a:
    e "我们晚点其实已经有点安排了。"

translate schinese story49_Erik_Lyna_Helga_8fa3bce1:
    h "哦，那对我们可是好消息！你们想做什么？"

translate schinese story49_Erik_Lyna_Helga_cadd2603:
    l "你知道满十九岁意味着什么吧？会有大事发生的。"

translate schinese story49_Erik_Lyna_Helga_fadd05c6:
    e "对啊，像是人生的新篇章什么的？一条新的路。"

translate schinese story49_Erik_Lyna_Helga_4add4ac1:
    h "你们在说什么，孩子们？看起来有点……怪。"

translate schinese story49_Erik_Lyna_Helga_61bd3cc9:
    e "呃，我和莱娜……我们确实有安排，但是……"

translate schinese story49_Erik_Lyna_Helga_5708a92c:
    l "但妈不在里面。"

translate schinese story49_Erik_Lyna_Helga_bc693c5f:
    h "什么……？你不是认真的吧！"

translate schinese story49_Erik_Lyna_Helga_2203c226:
    h "生日当天你们要丢下我？！真是不可思议！"

translate schinese story49_Erik_Lyna_Helga_02bb7e23:
    l "不是丢下！只是……也许一起出去走走，你看？"

translate schinese story49_Erik_Lyna_Helga_69e8c6b6:
    l "我们只是想作为兄妹，好好相处一段时间而已。"

translate schinese story49_Erik_Lyna_Helga_8a64df0d:
    e "是的妈，我们好久没做过什么特别的事了。"

translate schinese story49_Erik_Lyna_Helga_72454dbd:
    l "对！而且明年我们就要各自过自己的生活了，各忙各的……我们想好好把握这个夏天。"

translate schinese story49_Erik_Lyna_Helga_edcbc889:
    h "哦……我明白了。"

translate schinese story49_Erik_Lyna_Helga_ae657821:
    h "听着，我一直很感动你们俩这么在乎彼此。真的很暖心……"

translate schinese story49_Erik_Lyna_Helga_6c515c99:
    h "但我就是觉得这样有点怪，你懂吧？"

translate schinese story49_Erik_Lyna_Helga_eddd4825:
    h "为什么偏偏是今天？夏天还长着呢……"

translate schinese story49_Erik_Lyna_Helga_ca949cf5:
    l "因为今天是我们生日啊，笨蛋！我们想单独待一会儿。"

translate schinese story49_Erik_Lyna_Helga_d8890ee1:
    h "可你们老是这样啊！你们大半辈子都是这么过的……"

translate schinese story49_Erik_Lyna_Helga_29d1d61c:
    h "我是说，现在非走不可有什么特别的，把可怜的母亲一个人丢下？"

translate schinese story49_Erik_Lyna_Helga_b244a4bf:
    lm "又打法律牌又打感情牌，不讲道理！"

translate schinese story49_Erik_Lyna_Helga_c81d6527:
    lm "哥们，帮我一把！"

translate schinese story49_Erik_Lyna_Helga_25570a83:
    e "妈，这不是要把你一个人留下……而是为了我们。"

translate schinese story49_Erik_Lyna_Helga_fb710c38:
    e "你知道我们双胞胎之间的羁绊有多深。那是我们生命中最重要的东西之一！"

translate schinese story49_Erik_Lyna_Helga_f78e29a7:
    l "没错！某种程度上……几乎算是神圣的了。"

translate schinese story49_Erik_Lyna_Helga_58271bef:
    e "老实说，我们只想清静一下，不要那种例行家庭庆祝。再也不要派对了，或者任何类似的东西……"

translate schinese story49_Erik_Lyna_Helga_8ab85f74:
    l "对！就放松一下，你懂的？蛋糕和礼物我们都有了。你真的为我们做得够多了。"

translate schinese story49_Erik_Lyna_Helga_7b9e0bed:
    h "好吧，好吧，我懂了！"

translate schinese story49_Erik_Lyna_Helga_091c602f:
    h "也许我有点自私，只想着自己的感受。"

translate schinese story49_Erik_Lyna_Helga_967daadb:
    h "我知道过去这一年你们俩经历了很多……"

translate schinese story49_Erik_Lyna_Helga_6561bf4d:
    e "拜托，别担心我们！我们能照顾好自己的。"

translate schinese story49_Erik_Lyna_Helga_41dd4013:
    l "对！我们还会拍些照片，给你看我们玩得多开心！"

translate schinese story49_Erik_Lyna_Helga_8f8b846c:
    h "呜，我的小宝贝们……"

translate schinese story49_Erik_Lyna_Helga_932a8d2b:
    h "你们两个真是把我的心弦拨弄得够呛啊？"

translate schinese story49_Erik_Lyna_Helga_6447b82e:
    hm "天啊，感觉就在昨天，他们还拿着小玩具在屋里跑来跑去……"

translate schinese story49_Erik_Lyna_Helga_7c8ce719:
    hm "已经到{i}那个{/i}时候了吗？我已经这么老了？！生活太不公平了！"

translate schinese story49_Erik_Lyna_Helga_9c243f9f:
    hm "我不想让他们走，可是……我也不能成为他们不开心的原因。"

translate schinese story49_Erik_Lyna_Helga_ac9fb1e8:
    h "没关系孩子们。我不介意……"

translate schinese story49_Erik_Lyna_Helga_09cf0da0:
    e "真的吗？！"

translate schinese story49_Erik_Lyna_Helga_97772ecc:
    h "去吧，去你们想去的地方……{size=-5}但记得打电话给我。"

translate schinese story49_Erik_Lyna_Helga_13187fa4:
    e "我们答应你，妈！谢谢，太谢谢了！"

translate schinese story49_Erik_Lyna_Helga_e85e27ef:
    l "别担心，我们明天就回来，一眨眼的事！"

translate schinese story49_Erik_Lyna_Helga_37f7bf92:
    h "一、一定要玩得开心，好吗？"

translate schinese story49_Erik_Lyna_Helga_283f0889:
    e "当然，妈！"

translate schinese story49_Erik_Lyna_Helga_1585897d:
    l "是的妈咪，我们一定会的……"

translate schinese story49_Erik_Lyna_Helga_2cd22ec8:
    lm "啧。快点快点！"

translate schinese story49_Erik_Lyna_Helga_ac669600:
    e "{size=-5}莱娜，出发！路途很远，还得坐船。"

translate schinese story49_Erik_Lyna_Helga_e28e425f:
    e "快点好吗？我把你的包拿到车上。"

translate schinese story49_Erik_Lyna_Helga_03b04862:
    l "好，谢谢！等我一下下。"

translate schinese story49_Erik_Lyna_Helga_f584bfe7:
    lm "终于！全部传完了。"

translate schinese story49_Erik_Lyna_Helga_caab3f0c:
    lm "把相机里的全删掉……？不，不是全部。"

translate schinese story49_Erik_Lyna_Helga_caf7332b:
    lm "我看看……这些应该就够了！"

translate schinese story50_Erik_Lyna_ccd25255:
    centered "{font=font_narration}{size=+10}{cps=20}一段时间后……"

translate schinese story50_Erik_Lyna_f9fc87fd:
    l "{size=-5}拜拜！明天见！"

translate schinese story50_Erik_Lyna_449b0a49:
    l "这里的人都很友善，对吧？！"

translate schinese story50_Erik_Lyna_417d2a19:
    e "我是说……在港口时大部分工作人员都对我们投来奇怪的目光。"

translate schinese story50_Erik_Lyna_41f65b4b:
    e "毕竟这是蜜月度假村，而且我们还——"

translate schinese story50_Erik_Lyna_e95fbd87:
    l "你说他们发现我们是双胞胎了吗？"

translate schinese story50_Erik_Lyna_9ade0485:
    l "嘿嘿嘿~！那可太刺激了，对吧？"

translate schinese story50_Erik_Lyna_e4dd676b:
    l "「天啊，为什么一兄一妹要在我们情侣酒店订一间房？！」"

translate schinese story50_Erik_Lyna_f3e2f999:
    l "「亲兄妹？你疯了！他们只是一对长得像的普通情侣。」"

translate schinese story50_Erik_Lyna_a113d2dc:
    l "「也许吧，可是如果……{size=-5}那不就是乱伦了吗？」"

translate schinese story50_Erik_Lyna_ae6bf6b6:
    e "噗。莱娜，你就不能换个方式捉弄我吗？"

translate schinese story50_Erik_Lyna_c8f43ffa:
    l "才不。永远不~"

translate schinese story50_Erik_Lyna_0105692a:
    e "*叹气*我们去转转看看环境吧？"

translate schinese story50_Erik_Lyna_3d8740de:
    e "挺酷的吧？"

translate schinese story50_Erik_Lyna_7ca7c789:
    l "对！比照片上还美！"

translate schinese story50_Erik_Lyna_77bdc549:
    e "那我挑地方的眼光不错咯？"

translate schinese story50_Erik_Lyna_9dce4c34:
    l "当然是最好的！{w=1.0}{nw}"

translate schinese story50_Erik_Lyna_4794b12e:
    l "哇！好舒服~"

translate schinese story50_Erik_Lyna_a6bb3bf1:
    e "我来帮你……"

translate schinese story50_Erik_Lyna_151ef4fb:
    l "谢谢~！真的太棒了！"

translate schinese story50_Erik_Lyna_376d79b3:
    e "你还没看到最棒的那间房呢。"

translate schinese story50_Erik_Lyna_3c3fac59:
    l "哦？！给我看看给我看看！"

translate schinese story50_Erik_Lyna_e756b2a1:
    l "天啊！简直像做梦一样！"

translate schinese story50_Erik_Lyna_efc2bb0d:
    e "我真的很想要一个完美的生日地点。"

translate schinese story50_Erik_Lyna_759bef0c:
    l "岂止是完美，埃里克！我都说不出话来！"

translate schinese story50_Erik_Lyna_0684b3f5:
    e "是啊……而且我们终于独处了，真正地独处。"

translate schinese story50_Erik_Lyna_7e294ff6:
    l "就我们俩独处，嗯？这就是你想要的？就我们两个……？"

translate schinese story50_Erik_Lyna_cc9191d1:
    e "比这世上任何东西都想要。"

translate schinese story50_Erik_Lyna_bcc08759:
    e "我希望这一天我们会永远记得。"

translate schinese story50_Erik_Lyna_66f9263b:
    l "哥哥……我……{size=-5}我只是……"

translate schinese story50_Erik_Lyna_e1bafb4b:
    l "{cps=30}我想要你……{w=0.5}想要得要命，现在就要。"

translate schinese story50_Erik_Lyna_b7f815ac:
    l "那些花架子就免了吧……什么浪漫晚餐、看星星之类的老套安排。"

translate schinese story50_Erik_Lyna_3b5da7ac:
    e "可你不是说，要让它更特别一点吗？"

translate schinese story50_Erik_Lyna_ad52e704:
    l "已经很特别了。简直完美……{size=-5}你就是。"

translate schinese hscene36_Erik_Lyna_c8772469:
    centered "{font=font_narration}{color=#12f7fc}{size=+10}开发者声明：{/size}\n\n 接下来的音乐视频将自动播放！{/color} {color=#ff0000}在左下角的提示消失之前，请不要点击或操作游戏{/color}，{color=#12f7fc}否则歌词会不同步。{/color}"

translate schinese hscene36_Erik_Lyna_b252ce2f:
    centered "{font=font_narration}{cps=20}埃里克，{cps=15}{w=1.0}我的血，{cps=15}{w=1.0}心底深处的火焰{w=1.0}{nw}"

translate schinese hscene36_Erik_Lyna_45177f98:
    centered "{font=font_narration}{cps=20}我灵魂的{w=0.25}倒影，{cps=15}{w=0.75}罪恶{w=1.0}开始之处{w=1.5}{nw}"

translate schinese hscene36_Erik_Lyna_f10fbde4:
    centered "{font=font_narration}{cps=20}紧紧{w=0.25}织就，{cps=10}{w=1.25}因血缘，也因恩典{w=0.5}{nw}"

translate schinese hscene36_Erik_Lyna_cd1c4ce6:
    centered "{font=font_narration}{cps=20}我们禁忌的{w=0.5}触碰，{cps=10}{w=1.0}时间{w=0.5}也无法抹去{w=1.5}{nw}"

translate schinese primalcall_chorus1_a682eec7:
    centered "{font=font_narration}{cps=30}身与心，{w=0.75}欲望牢牢攫住{w=1.0}{nw}"

translate schinese primalcall_chorus1_39de2d98:
    centered "{font=font_narration}{cps=30}兄妹的相拥，{w=0.75}一段无人诉说的传说{w=0.25}{nw}"

translate schinese primalcall_chorus1_09df9279:
    centered "{font=font_narration}{cps=30}我们将越过那条线，{w=0.75}再无退路{w=1.0}{nw}"

translate schinese primalcall_chorus1_d82a3620:
    centered "{font=font_narration}{cps=30}这份罪恶的爱，{w=0.75}来自本源的呼唤{w=1.5}{nw}"

translate schinese primalcall_verse2_c27ca283:
    centered "{font=font_narration}{cps=20}莱娜，{cps=15}{w=0.75}我的血亲，{cps=10}{w=1.5}我孪生的灵魂{w=1.0}{nw}"

translate schinese primalcall_verse2_c3c79ecf:
    centered "{font=font_narration}{cps=15}在隐秘的{w=0.5}低语里，{cps=15}{w=0.75}我们的激情便已成型{w=1.25}{nw}"

translate schinese primalcall_verse2_29e2197e:
    centered "{font=font_narration}{cps=15}禁忌的{w=0.25}舞蹈，{cps=10}{w=1.25}我们的身体交缠{w=0.75}{nw}"

translate schinese primalcall_verse2_3ffd4521:
    centered "{font=font_narration}{cps=20}在这禁忌里，{w=0.25}我寻到，{cps=10}{w=1.25}真正属于我的一切{w=1.75}{nw}"

translate schinese primalcall_chorus2_a682eec7:
    centered "{font=font_narration}{cps=30}身与心，{w=0.75}欲望牢牢攫住{w=1.0}{nw}"

translate schinese primalcall_chorus2_72fe5811:
    centered "{font=font_narration}{cps=30}兄妹的相拥，{w=0.75}一段无人诉说的传说{w=0.5}{nw}"

translate schinese primalcall_chorus2_09df9279:
    centered "{font=font_narration}{cps=30}我们将越过那条线，{w=0.75}再无退路{w=1.0}{nw}"

translate schinese primalcall_chorus2_0a517a12:
    centered "{font=font_narration}{cps=30}这份罪恶的爱，{w=0.75}来自本源的呼唤{w=1.0}{nw}"

translate schinese primalcall_verse3_a4d9035b:
    centered "{font=font_narration}{cps=15}他们低语着耻辱，{w=1.75}咒骂着我们的名字{w=1.5}{nw}"

translate schinese primalcall_verse3_2133c9ea:
    centered "{font=font_narration}{cps=15}但我们共有的血脉，{w=1.25}让这爱并不逊色{w=1.0}{nw}"

translate schinese primalcall_verse3_78bfc8f2:
    centered "{font=font_narration}{cps=20}我们被牢牢缚在一起，{w=1.5}共担彼此所有的罪{w=1.0}{nw}"

translate schinese primalcall_verse3_2d0905b6:
    centered "{font=font_narration}{cps=15}那如此正确的一切，{w=1.25}正是新生命开始之处{w=1.5}{nw}"

translate schinese primalcall_chorus3_96823b18:
    centered "{font=font_narration}{cps=10}身{w=0.5}与心，{w=1.0}欲望{w=0.3}牢牢攫住{w=0.35}{nw}"

translate schinese primalcall_chorus3_de383e88:
    centered "{font=font_narration}{cps=15}兄妹的{w=0.25}相拥，{w=0.75}一段{w=0.5}无人诉说的传说{w=0.5}{nw}"

translate schinese primalcall_chorus3_98b02252:
    centered "{font=font_narration}{cps=20}我们将{w=0.5}越过那条线，{cps=10}{w=1.0}再{w=0.25}不{w=0.25}回头{w=1.0}{nw}"

translate schinese primalcall_chorus3_0d92edb4:
    centered "{font=font_narration}{cps=15}这份罪恶的爱，{w=1.0}来自本源的呼唤{w=1.0}{nw}"

translate schinese primalcall_end_10cc1b88:
    l "我要你进来，求你了！收走我的第一次吧！"

translate schinese primalcall_end_fa5ee10b:
    e "我会的，莱娜，但先……"

translate schinese primalcall_end_ccc7ef9a:
    e "我们得做点防护措施。"

translate schinese primalcall_end_24368c72:
    l "什么？！才不要，责任先生！{size=+5}我要无套！"

translate schinese primalcall_end_de530135:
    l "怎么，被你看到的这一幕让你心动了？"

translate schinese primalcall_end_6e0c4e02:
    l "{cps=30}这光秃秃的、{w=0.25}稚嫩的、{w=0.25}未经开垦的小穴，{w=0.5}整整养了十八年。"

translate schinese primalcall_end_fabda4bc:
    l "{cps=30}第一次只有一次。{w=0.25}你不想把{i}一切{/i}都感受一遍吗……？"

translate schinese primalcall_end_09647aef:
    l "今天是安全期，好吗？再说你也可以直接拔出来……"

translate schinese primalcall_end_3989739d:
    l "前提是你能忍住。嘿嘿嘿~"

translate schinese primalcall_end_0c8b228c:
    l "哈！这么着急啊？我他妈想要这个想要疯了……"

translate schinese primalcall_end_eed59302:
    e "我也是，小莱。我都不敢相信这是真的在发生。"

translate schinese primalcall_end_ee4bf0ee:
    e "我好紧张！我想把每件事都做对，也不想弄疼你……"

translate schinese primalcall_end_07a5ff1b:
    l "放松啦，笨蛋！我很能扛的，撑得住。"

translate schinese primalcall_end_cc264f62:
    l "你知道，我以前有多恨妈妈总是偏心你……她的小金童，完美的儿子。"

translate schinese primalcall_end_b7ca1a99:
    l "无论在哪方面，我都在努力让自己比她更靠近你。"

translate schinese primalcall_end_24766e27:
    l "而现在你终于成了男人，一个很「大」的男人……"

translate schinese primalcall_end_36908e0b:
    l "{cps=25}是时候让你把我那个梦变成现实了。"

translate schinese primalcall_end_681edc9d:
    e "呃啊……！你他妈快把我逼疯了。"

translate schinese primalcall_end_ccc78df6:
    l "那你还等什么？让我看看你到底是不是认真的。"

translate schinese primalcall_end_2a077256:
    l "快点，现在就放进来！{size=-5}让我们融为一体……"

translate schinese primalcall_end_9827f16f:
    l "啊啊啊啊~！进来了！终于进来了！"

translate schinese primalcall_end_a3c172e5:
    n "埃里克猛地一动，把急切的龟头推进了妹妹紧致的处女入口……"

translate schinese primalcall_end_a653739b:
    n "……让他那硬如岩石的鸡巴前端，抵上她最私密的那道入口。"

translate schinese primalcall_end_11aa9d3f:
    l "再深一点！填满我的小穴……！"

translate schinese primalcall_end_1d52256d:
    l "{size=+5}啊啊啊！是的！"

translate schinese primalcall_end_33ce2e1a:
    n "龟头越往深处探去，那女孩感到一种难以言喻的滋味——膜上传来的压力。"

translate schinese primalcall_end_f9d21a1b:
    n "她哥哥的龟头裹着一层薄薄的淫液，正危险地撑开她柔嫩的膜……"

translate schinese primalcall_end_6e8cd259:
    l "顶到最深处！给我顶到最深！"

translate schinese primalcall_end_dd18ed3f:
    n "一道薄膜，在她整个童贞的岁月里始终完好无损。"

translate schinese primalcall_end_0829f388:
    l "{size=+10}靠——！好痛啊……！"

translate schinese primalcall_end_a58ac370:
    e "姐？！糟了……那是——"

translate schinese primalcall_end_cd9a07a0:
    e "{size=-5}血……血……"

translate schinese primalcall_end_48734188:
    l "什么？！让我看看……！"

translate schinese primalcall_end_67006244:
    e "该死，该死，该死！我弄疼你了吗？！我真——"

translate schinese primalcall_end_3be41490:
    l "{size=+5}你做到了！天啊，你他妈真的做到了！"

translate schinese primalcall_end_60734698:
    l "这么久以来，我……{size=-5}一直都在为你留着……"

translate schinese primalcall_end_553a29a0:
    e "但你没事吧？！不疼吗？"

translate schinese primalcall_end_cc8dcee6:
    l "我好得不能再好了！{size=+5}我感觉活过来了！"

translate schinese primalcall_end_f29b4d08:
    l "你终于夺走了本就属于你的东西！"

translate schinese primalcall_end_67782325:
    l "我们不再是两个愚蠢的处女了，对吧？！"

translate schinese primalcall_end_102f30ab:
    l "我该死的哥哥，正在给我破处……哈……{size=+5}哈哈哈~！"

translate schinese primalcall_end_22214071:
    e "该死……我们俩都疯了，是吧？真是想不到。"

translate schinese primalcall_end_48c27851:
    l "没错！那就快点，再把你亲妹妹操一遍，用力操我！"

translate schinese primalcall_end_8825d9c8:
    l "{size=+5}对！就是这样……！"

translate schinese primalcall_end_25f4782c:
    e "这……天啊！这到底是什么感觉？！"

translate schinese primalcall_end_62f5f7e6:
    e "又热又紧，而且……而且——"

translate schinese primalcall_end_bb8ded45:
    l "这是我的小穴！处女的穴就是这种感觉！"

translate schinese primalcall_end_39f9e0dc:
    e "靠，比你的嘴爽一百万倍！"

translate schinese primalcall_end_6cabfd2f:
    e "我们怎么不早点做，小莱？！"

translate schinese primalcall_end_69f6b6eb:
    l "早点？你说早点啊？"

translate schinese primalcall_end_90c0afde:
    l "要是几年前我们还……的时候，你也会想做吗？"

translate schinese primalcall_end_37879a05:
    e "莱娜？！当然不会！那会变成——"

translate schinese primalcall_end_30d90619:
    l "超级乱搞的，对吧……？" with hpunch

translate schinese primalcall_end_2d5e13ed:
    e "该死！我可不想去想象那个画面！"

translate schinese primalcall_end_b9f641fb:
    l "所以你刚才才突然加快速度？噗哈哈哈！"

translate schinese primalcall_end_52843942:
    e "啧。我只是高兴我们终于在做这件事了，好吗？！"

translate schinese primalcall_end_7b80744b:
    l "我知道你是什么人……一个和我一样的下流小色鬼。我们真像！"

translate schinese primalcall_end_594540c0:
    e "我……我承认有点难为情，但我确实早就想做这件事了，是。"

translate schinese primalcall_end_479a0b2c:
    l "看、看吧？所以你早就急着要无套操你可爱的亲妹妹了……？色狼！"

translate schinese primalcall_end_5ee70575:
    e "我想我确实就是……现在也没法否认了。"

translate schinese primalcall_end_b74f056a:
    l "你不该否认！把色鬼放出来吧，大哥！"

translate schinese primalcall_end_7acbdd0f:
    e "对！爽毙了！简直像在吸我的鸡巴……"

translate schinese primalcall_end_bc1399e7:
    l "埃里克，那是我紧致小肉穴的内壁……又滑又湿。"

translate schinese primalcall_end_c7b56f8f:
    l "一收一缩地跳动着……像在按摩你那胀痛的鸡巴。"

translate schinese primalcall_end_20313292:
    e "操！太爽了……"

translate schinese primalcall_end_4f76f177:
    e "这不真实啊姐！我停不下来了！"

translate schinese primalcall_end_b57c75a5:
    l "进出得这么顺滑，对吧？为什么会这样……？"

translate schinese primalcall_end_f8bddc2d:
    e "因为它就是为我而生的！"

translate schinese primalcall_end_981e6d73:
    l "哎呀~！回答得好！你的鸡巴果然就是为插在我里面而生的。"

translate schinese primalcall_end_dd5e9062:
    l "像钥匙配锁一样，是吧？我们毕竟是双胞胎。"

translate schinese primalcall_end_3615d993:
    e "{size=-5}对，我完美的双胞胎妹妹……"

translate schinese primalcall_end_1cd66949:
    e "我觉得我爱上你这个新发型了。"

translate schinese primalcall_end_34ed5662:
    l "哦？我很高兴你喜欢剪短。"

translate schinese primalcall_end_3cde2b5f:
    e "配上那两个可爱的双马尾……操。真的让我兴奋死了。"

translate schinese primalcall_end_065f2cc9:
    l "哈哈哈！为什么呀，嗯~？"

translate schinese primalcall_end_db912a4d:
    e "因为它们让你看起来可爱死了！"

translate schinese primalcall_end_49f4d443:
    l "真的吗？该不会是因为它们让你想起我当年那对可爱的……？"

translate schinese primalcall_end_4a9468c4:
    e "什么？！不是！别又来这一套……"

translate schinese primalcall_end_e2f2e456:
    l "果然是大色鬼，哈哈！"

translate schinese primalcall_end_95073e7c:
    e "拜托，我可不是因为那个意思！"

translate schinese primalcall_end_f7b1d54e:
    e "只是……你长大了很多。你现在是个彻头彻尾的女人了。我完美的、美丽的女人。"

translate schinese primalcall_end_a866f957:
    l "哦，所以我是你的{i}所有物{/i}了？"

translate schinese primalcall_end_8ad0a897:
    e "对！所以准备好，我要让你看看一个真正的女人需要什么。" with vpunch

translate schinese primalcall_end_e3775f22:
    l "哇哦！到脚踝了？！今天真够大胆的嘛~？"

translate schinese primalcall_end_c30e5d60:
    e "是你自己说想要我粗暴一点的，不是吗？"

translate schinese primalcall_end_3f5d3edc:
    l "我那个害羞的哥哥连「粗暴」是什么意思都不知道吧？！哈哈！"

translate schinese primalcall_end_83e84ea3:
    e "{size=+10}就是这样！让你见识什么叫粗暴！"

translate schinese primalcall_end_da038e2d:
    l "{size=+5}天啊，太对了……！{/size}这正是我需要的！"

translate schinese primalcall_end_464e6f1e:
    l "埃里克，又凶又狠地用我这个小洞吧！"

translate schinese primalcall_end_76ec2398:
    e "你就喜欢这样对吧？你喜欢你哥哥{size=-5}操{/size}你的样子？！"

translate schinese primalcall_end_6b288867:
    l "{size=+5}我喜欢！我他妈爱死了！"

translate schinese primalcall_end_ea63e399:
    l "我真的很喜欢你不再克制自己……"

translate schinese primalcall_end_b718533a:
    e "我还能怎么办？我从来没和女孩好好做过，而偏偏对象还是你……"

translate schinese primalcall_end_894f9405:
    l "可你现在已经不在乎这些了对吧？乱伦这种事只会让你更兴奋。"

translate schinese primalcall_end_5abf15ed:
    e "是啊，这让我硬得要命……{size=-5}我控制不住。"

translate schinese primalcall_end_b8b3f236:
    l "看吧？！你正在和我一起彻底拥抱你最黑暗的幻想！"

translate schinese primalcall_end_fded8f0d:
    e "都是因为你用那些从你嘴里冒出来的脏话，把我带进了这种淫荡的情绪里……"

translate schinese primalcall_end_fe6d9be1:
    l "所以是因为你正要夺走亲妹妹的第一次吗……？嘿嘿嘿~"

translate schinese primalcall_end_d0f15c97:
    l "你把我弄出血了！你用那根乱伦的鸡巴把你的小妹妹变成了真正的女人！这不是爽爆了吗~？"

translate schinese primalcall_end_8c7873de:
    e "{size=+5}啊啊啊……！操！{/size}这不该这么爽的，小莱！"

translate schinese primalcall_end_91513168:
    l "可它就是很爽，对吧？感觉就像——"

translate schinese primalcall_end_2b53a533:
    e "就像它本来就该是这样……"

translate schinese primalcall_end_fe8a0909:
    l "没错！那就给我看！把你所有的本事都使出来！"

translate schinese primalcall_end_96ad397d:
    e "你会感受到我每一寸的！"

translate schinese primalcall_end_40e5c4c0:
    l "哦我的天~！你进得好深好深，对吧……"

translate schinese primalcall_end_f5d4b1c5:
    l "可、可是我要说，你居然还憋得住，我真意外！"

translate schinese primalcall_end_6f632d5d:
    e "老实说……我今天确实自慰了好多次。"

translate schinese primalcall_end_a1202a52:
    l "哈！我就知道！所以我们一路上才停下来差不多三次，对吧~？"

translate schinese primalcall_end_4ce8128a:
    e "我本来想多坚持一会儿，让第一次变得特别一点……"

translate schinese primalcall_end_d284e6b4:
    l "真他妈色！想到你一边撸着那根处女鸡巴，一边想着我们接下来要做的事……"

translate schinese primalcall_end_34ed4157:
    l "不……！我们正在做的这种事啊！" with hpunch

translate schinese primalcall_end_ec912fc8:
    e "{size=-5}和我自己的双胞胎姐姐做爱……"

translate schinese primalcall_end_4b70afa6:
    l "太棒了！！淫荡的乱伦爱！光是想想就让我——啊嗯~！"

translate schinese primalcall_end_5ef50536:
    e "我们做的是兄妹之间绝不该做的事，这让你兴奋得不得了吗……？"

translate schinese primalcall_end_7bd1b356:
    l "{size=+10}埃里克——，擄——！擄对！" with vpunch

translate schinese primalcall_end_45f1078d:
    e "我那淫荡的小妹妹，该不会要在我之前高潮吧？"

translate schinese primalcall_end_d7b06586:
    l "啊……该死，这一下不公平啊老哥！"

translate schinese primalcall_end_9b602b4a:
    e "哈！我开始掌握说脏话的诀窍了，对吧？"

translate schinese primalcall_end_011d780f:
    l "啧。我会让你高潮得更厉害，等着瞧！"

translate schinese primalcall_end_75d62d17:
    l "来。现在抓住我的腰，好吗？"

translate schinese primalcall_end_cbe5e395:
    l "那就一直在我温暖的小洞里进出，直到你感觉不到自己的腿为止。"

translate schinese primalcall_end_60aa0c1f:
    l "好！现在拔出来，对吧？我想看看我这平胸被你最浓的一发精液覆盖。"

translate schinese primalcall_end_331fa5f3:
    e "你以前不是这样的，小莱。你的粗话，你的没规矩……"

translate schinese primalcall_end_af577463:
    e "你变成了这么一个——"

translate schinese primalcall_end_63f6af6d:
    e "……色欲熏心的妹妹！"

translate schinese primalcall_end_fa29e505:
    l "呃啊！我……我想你是说小妹妹！" with hpunch

translate schinese primalcall_end_6ffb958e:
    l "我今天问妈了哦。她说是你先出来的！"

translate schinese primalcall_end_22391b61:
    e "什么？！你居然还去问她这种问题？！你该羞愧！"

translate schinese primalcall_end_b98a9f89:
    e "羞愧于不规矩地触碰我们的母亲，羞愧于用这些可怕的想法带坏自己的亲哥哥……"

translate schinese primalcall_end_6522a524:
    e "{size=+5}你果然是个非常骚的小妹妹！" with hpunch

translate schinese primalcall_end_d32f8367:
    l "{size=+5}啊啊啊……！就这样一边说一边无套狠干我的小穴！"

translate schinese primalcall_end_6b0e0809:
    e "我真的好喜欢用这副紧致的小身体，姐！"

translate schinese primalcall_end_f9a334d9:
    e "我就喜欢蛋蛋拍打你柔软屁股的感觉，也喜欢感觉鸡巴深深埋在你……小穴里！"

translate schinese primalcall_end_1f4d5a3a:
    l "{size=+10}咿——啊啊啊！！！干我，大哥！" with vpunch

translate schinese primalcall_end_c9a40692:
    e "我们今天可违反了不少规矩，对吧？"

translate schinese primalcall_end_8021b463:
    l "是、是的！她要是看到我们现在的样子会怎么想？！"

translate schinese primalcall_end_978ec128:
    e "妈……她不会赞成的。"

translate schinese primalcall_end_f5b7ff9e:
    e "我真不知道之后要怎么和你分开。"

translate schinese primalcall_end_a16abb10:
    l "那就别分开！我们会永远在一起。{size=-5}就像我们约定的那样……"

translate schinese primalcall_end_93538a05:
    l "我们属于彼此！现在谁也分不开我们了，连妈也不行！"

translate schinese primalcall_end_0a121773:
    e "{size=+5}对！我现在浑身每一根纤维都感觉到了！"

translate schinese primalcall_end_28ca4df7:
    e "我爱你爱得远超一个好兄妹该有的程度，但我已经不在乎了！"

translate schinese primalcall_end_0f790f69:
    l "{size=+5}我们还要让妈也看到这一点，对吧？！对吧？！"

translate schinese primalcall_end_b7ac5a61:
    e "{size=+10}我们会的！我保证！"

translate schinese primalcall_end_11d039df:
    l "你不也感觉到了吗？这不只是欲望？！"

translate schinese primalcall_end_0400d8ae:
    l "我一直都觉得应该是我哥哥。只有你，只有你！"

translate schinese primalcall_end_f451a0af:
    e "我再也不会离开你身边了，好吗？不管发生什么！"

translate schinese primalcall_end_dfd7bd14:
    l "对，对！妈也该早点看清真相了！" with vpunch

translate schinese primalcall_end_8b81834f:
    l "她会学会接受的——她的孩子们乱伦相恋，才是世界上最正常不过的事！"

translate schinese primalcall_end_59a3be97:
    l "因为我们是双胞胎。相爱的双胞胎。我们有某种特别的东西，某种别人无法真正理解的纽带……"

translate schinese primalcall_end_2502153b:
    e "不管付出什么代价，我们都要让她看到！"

translate schinese primalcall_end_e6025477:
    l "为了让妈妈明白，你愿意做任何事吗？"

translate schinese primalcall_end_8e832b86:
    e "{size=+5}啊啊啊……！什、什么事都愿意！"

translate schinese primalcall_end_e315c101:
    l "哪怕像我们说的那样去{i}勾引{/i}她……？你们两个到底能走到哪一步？"

translate schinese primalcall_end_297997bf:
    l "{cps=25}你也……{w=0.5}想操我们自己的妈妈吗？！"

translate schinese primalcall_end_edf6cbad:
    e "{size=+20}呃啊啊啊啊啊啊啊啊！"

translate schinese primalcall_end_d2bb0ab4:
    l "{size=+10}操，太棒了！就这样射得我全身都是！"

translate schinese primalcall_end_e537f3c0:
    l "{size=+5}连我这张可爱的脸也遮上！像你对妈妈做的那样！"

translate schinese primalcall_end_9ad19613:
    e "呃……哇，那、那真是……{size=-5}疯了。"

translate schinese primalcall_end_2e771b66:
    e "我这辈子从来没射得这么厉害过，我……{size=-5}好像射空了。"

translate schinese primalcall_end_8422d461:
    l "已经射了？！我们才刚开始呢！"

translate schinese primalcall_end_1ba1180b:
    l "我们不就是为了这个才来的吗？把彼此的脑子都操出去？"

translate schinese primalcall_end_1a00ae1d:
    e "哈！你说话总是这么「委婉」……"

translate schinese primalcall_end_505d10b5:
    l "你还指望什么？！刚才爽死了！"

translate schinese primalcall_end_eefc3a54:
    l "来吧，来吧！试试别的姿势！"

translate schinese primalcall_end_2f2fae00:
    e "真是的，丫头！给我几分钟缓一下行不行？"

translate schinese primalcall_end_f96b45b3:
    e "我又不是超人，不可能立刻就硬起来。哈哈……"

translate schinese primalcall_end_1edc4bb5:
    l "哪怕是当着你刚刚玷污的这副性感小身子的面也不行？"

translate schinese primalcall_end_07a30a08:
    l "你不想再给我一份生日礼物吗~？"

translate schinese primalcall_end_f4f081f6:
    e "礼物？等等，我们……我们完全忘了！"

translate schinese primalcall_end_8430367b:
    e "妈给了我们一些东西，但我们互相之间还没送过礼物！"

translate schinese primalcall_end_fddab960:
    l "哦？我想我们确实忘了，对吧？"

translate schinese primalcall_end_771ca050:
    e "哈哈哈！我们怎么能忘呢？我们真蠢！"

translate schinese primalcall_end_86a774b8:
    l "现在才想起来有点晚了吧？嘿嘿嘿~"

translate schinese primalcall_end_66d64645:
    l "你早就把你那玩意儿当成我收到过最好的礼物了。"

translate schinese primalcall_end_d0ac81a7:
    l "这种感觉……我们之间的联结……你知道它比什么都珍贵。"

translate schinese primalcall_end_8ef7cd4d:
    e "你说得对。我无法想象没有你的生活……"

translate schinese primalcall_end_068ef576:
    e "既然我们已经有彼此了，就不需要别的礼物了。"

translate schinese primalcall_end_31927b23:
    l "「射空」？你说射空？它现在还硬得像石头。"

translate schinese primalcall_end_91052a7c:
    e "好吧，你确实让我……{size=-5}很多感觉。"

translate schinese primalcall_end_94898e12:
    l "什么感觉？说具体点。再他妈说点脏话。"

translate schinese primalcall_end_c0898d14:
    e "你那张可爱的小天使脸蛋，被我自己的精液糊满了……"

translate schinese primalcall_end_5c2703dc:
    e "还有这具你让坏哥哥拿来取乐的绝美身体……"

translate schinese primalcall_end_a126f072:
    l "啊！这副身体确实全是你的，只属于我那……大……坏……哥哥~！"

translate schinese primalcall_end_201b526b:
    l "抚摸，亲吻……然后干你。"

translate schinese primalcall_end_6024db34:
    e "{cps=25}你让我硬了，{w=0.35}小莱。{w=0.5}所以。{w=0.25}他妈的。{w=0.25}硬了。"

translate schinese primalcall_end_a6ce684a:
    l "{cps=30}嗯哼。{w=0.35}那我大概知道你需要什么了……"

translate schinese primalcall_end_98d6b8d2:
    n "那一天，他们曾经纯真的关系被彻底击碎，永远。"

translate schinese primalcall_end_80ba8f0e:
    n "他们之间的兄妹纽带，已经变成一种逾越一切逻辑、一切道德的东西……"

translate schinese primalcall_end_44a965de:
    n "他们不再只是双胞胎，而是远不止于此。"

translate schinese primalcall_end_1fe69674:
    n "那座僻静的度假村，远离母亲监视目光的隐秘港湾，成了他们暂时的避风港……"

translate schinese primalcall_end_b3047438:
    n "……一个他们终于可以卸下家庭的束缚、卸下社会期待的地方。"

translate schinese primalcall_end_48d8018a:
    n "而他们的秘密，如今已成了公开的反抗，宣告着一种由他们自己定义的人生即将开始。"

translate schinese primalcall_end_c7bb1081:
    n "他们一次又一次地回到彼此身边。克制终于消失殆尽。"

translate schinese primalcall_end_7b71b66d:
    n "外面的世界不复存在，取而代之的是一个纯粹由肉体快感构成的宇宙，只有他们彼此重要……"

translate schinese primalcall_end_e9c497e1:
    n "两颗年轻的灵魂在禁忌欲望的舞蹈中交缠。"

translate schinese primalcall_end_6bf1839e:
    n "那些在童年嬉戏中长久沉睡的禁忌渴望的种子，终于绽放成了一场完整的乱伦之爱。"

translate schinese primalcall_end_68320762:
    n "这对双胞胎正拥抱自己的罪孽，他们最黑暗、最根深蒂固的欲望。而在那场越界之中……"

translate schinese primalcall_end_8382df99:
    n "……他们找到了一种比以往任何经历都更有力量、更真实的联结。"

translate schinese primalcall_end_16ad1a77:
    centered "{font=font_narration}{cps=25}{color=#69d9fe}( 完美。{w=0.5}我们的第一次……{w=0.35}不可能是别的样子。 )"

translate schinese story51_Helga_c5668567:
    hm "我们玩得那么开心，我真希望还能继续下去……"

translate schinese story51_Helga_652cccd9:
    hm "我应该为他们高兴，他们终于自由了一次……可是……"

translate schinese story51_Helga_95a01050:
    hm "嗯？那是不是……？"

translate schinese story51_Helga_e0756ec4:
    hm "哇！她还真有两下子。莱娜真把我拍得像明星一样……"

translate schinese story51_Helga_0f5fdea7:
    hm "还有我拍的那些……天啊，她真是太可爱了。"

translate schinese story51_Helga_9cfcce79:
    hm "我还是不敢相信她居然真的穿了我的少女内衣！"

translate schinese story51_Helga_20e1cf91:
    hm "这些是……？天哪，是埃里克拍的！"

translate schinese story51_Helga_5095d139:
    hm "他确实很专注于我那些不老实的地方，对吧？"

translate schinese story51_Helga_1e0a2b69:
    hm "我的宝贝最后硬成那样，看着我穿那身淫荡衣服一定是一种折磨……"

translate schinese story51_Helga_6c7c81b9:
    hm "希望他当时没有对自己妹妹也动歪心思！那套内衣那么——"

translate schinese story51_Helga_f82ee1ae:
    hm "真是的！我在想什么啊？！他绝对不会……"

translate schinese story51_Helga_44f8f813:
    hm "我真得把这些不健康的想法抛开，想想该怎么跟儿子谈我们之间的事。"

translate schinese story51_Helga_0b025056:
    hm "昨天，还有今天……都太尴尬了。我们不能再逃避我对他做过的事。"

translate schinese story51_Helga_5af8edf9:
    hm "至少希望他们在外面玩得开心……"

translate schinese story51_Helga_baeafd78:
    hm "说起来，他们为什么把相机落下了？我还以为莱娜要拍些照片给我看。"

translate schinese story51_Helga_3461c031:
    hm "再多看几张也没关系吧？我已经开始想他们了……"

translate schinese story51_Helga_3de22360:
    hm "看看，她还拍了些什么……？"

translate schinese story51_Helga_ae79d65d:
    hm "等等，我认识那个泳池！"

translate schinese story51_Helga_f0494e9e:
    hm "她是……？天啊！现在我真觉得自己在侵犯她的隐私。"

translate schinese story51_Helga_7406cef5:
    hm "我都不知道她给自己拍了这种照片……"

translate schinese story51_Helga_f5624da4:
    hm "但我女儿已经成年了，对吧？她用自己的身体做什么，我有什么资格评判？哪怕是在家里……"

translate schinese story51_Helga_dc9de27d:
    h "{size=+5}{cps=30}什么？！{w=0.25}莱娜和一个……{w=0.25}男的在一起？！"

translate schinese story51_Helga_c2220ed8:
    h "{size=+10}{cps=20}哦。{w=0.35}我的。{w=0.35}天。"

translate schinese hscene37_Erik_Lyna_dc476800:
    centered "{font=font_narration}{size=+40}{cps=15}第三章：品尝罪恶"

translate schinese hscene37_Erik_Lyna_d5cb6e56:
    e "{size=+5}你做了……{size=+10}什么？！" with vpunch

translate schinese hscene37_Erik_Lyna_3d9ecc0a:
    l "冷静点，埃里克。就两三张照片而已。"

translate schinese hscene37_Erik_Lyna_66c8dc75:
    e "可、可照片里有我吗？！"

translate schinese hscene37_Erik_Lyna_71e47e1c:
    l "你的鸡巴算是有吧……但没有脸，没有证据，对吧？"

translate schinese hscene37_Erik_Lyna_c6c25b54:
    e "该死妹妹！她可是律师，你不明白吗？！"

translate schinese hscene37_Erik_Lyna_f60e24ec:
    e "妈妈可是靠推理吃饭的！要是她——"

translate schinese hscene37_Erik_Lyna_bc5152f7:
    l "她能怎样？认得你的鸡巴？哈哈哈！"

translate schinese hscene37_Erik_Lyna_e4f3f759:
    e "{size=-5}真是的。我发誓你太蠢了……"

translate schinese hscene37_Erik_Lyna_6d3100d0:
    l "妈妈是多想操她唯一的儿子，连他的鸡巴都已经背下来了？"

translate schinese hscene37_Erik_Lyna_e92f329b:
    e "{size=+5}搞什么？！莱娜！{size=-5}我……"

translate schinese hscene37_Erik_Lyna_792d187b:
    e "我只是说她可能会从照片里看出什么。"

translate schinese hscene37_Erik_Lyna_49e8f0ed:
    l "拜托……她还在为爸爸的事哭得不可开交，哪有空当侦探。"

translate schinese hscene37_Erik_Lyna_40502f16:
    e "可我们的计划怎么办？万一她太早发现了？"

translate schinese hscene37_Erik_Lyna_4bbfa1a3:
    l "总比我们自己说出来好吧？那多尴尬。"

translate schinese hscene37_Erik_Lyna_3cc99754:
    l "「你看，妈……我、我和莱、莱娜……」"

translate schinese hscene37_Erik_Lyna_185b5915:
    l "「咳咳！你的两个孩子相爱到开始像他妈的兔子一样做爱，你懂吗？」"

translate schinese hscene37_Erik_Lyna_9b5373fe:
    e "那不是——呃……"

translate schinese hscene37_Erik_Lyna_246c3fe1:
    l "噗哈哈！你就自求多福吧，兄弟。"

translate schinese hscene37_Erik_Lyna_7014c01e:
    e "这不好笑妹妹！你那样做之前该先问我的。"

translate schinese hscene37_Erik_Lyna_b8d21d49:
    e "我还以为要一起做的……你这个疯主意！"

translate schinese hscene37_Erik_Lyna_d8af1e8c:
    l "可这全都在计划之内啊，你不懂吗？"

translate schinese hscene37_Erik_Lyna_4483f48e:
    l "我只是用那些照片又种下一颗种子。"

translate schinese hscene37_Erik_Lyna_c9b6b693:
    e "我……{size=-5}靠。{/size}这样不对，要是妈妈察觉——"

translate schinese hscene37_Erik_Lyna_0f5cf86c:
    l "她可能会彻底崩溃，是啊。"

translate schinese hscene37_Erik_Lyna_93070840:
    l "或者她也想尝尝……？"

translate schinese hscene37_Erik_Lyna_971e50e6:
    l "埃里克，妈妈在水疗中心摸我的样子……"

translate schinese hscene37_Erik_Lyna_3a873705:
    l "操。你真该看看她眼里那副饥渴的表情。"

translate schinese hscene37_Erik_Lyna_3206b4b0:
    l "再说了，你自己不是说前两天妈妈也主动投怀送抱了吗？"

translate schinese hscene37_Erik_Lyna_80c08a69:
    l "顶级熟女路数，嗯？"

translate schinese hscene37_Erik_Lyna_5ac899ee:
    e "噗……我是说——"

translate schinese hscene37_Erik_Lyna_6a6fc41b:
    l "妈妈很寂寞！埃里克，她孤独得要命，性方面也很压抑。你跟我一样清楚。"

translate schinese hscene37_Erik_Lyna_99942650:
    e "说真的，这太疯了……{size=-5}她会杀了我们的。"

translate schinese hscene37_Erik_Lyna_ef8fae13:
    l "或者加入我们的乐趣，对吧？让她找个能满足自己的人。"

translate schinese hscene37_Erik_Lyna_ec7dcf10:
    l "这样你就能同时拥有我们俩，你的妈妈和她的女儿……你能想象吗？"

translate schinese hscene37_Erik_Lyna_ed17365e:
    l "总之，先别管那些照片了。"

translate schinese hscene37_Erik_Lyna_36caefaf:
    l "你不想再跟我好好玩玩吗？"

translate schinese hscene37_Erik_Lyna_56a34caa:
    l "{cps=30}这具紧致的小身子终究{w=0.5}完全属于你……"

translate schinese hscene37_Erik_Lyna_6b71a5a8:
    l "{cps=25}我那小小的奶子。"

translate schinese hscene37_Erik_Lyna_20e21a1d:
    l "{cps=25}我漂亮的小腹。{w=0.5}这么平，{w=0.35}这么完美……"

translate schinese hscene37_Erik_Lyna_96485dc5:
    l "{cps=20}还有我这才刚合法的少女小穴，{w=0.5}大哥。"

translate schinese hscene37_Erik_Lyna_be1fa478:
    e "莱娜！不！别那么说！你那样说我——"

translate schinese hscene37_Erik_Lyna_099a153a:
    l "你什么，嗯？"

translate schinese hscene37_Erik_Lyna_6ed45d3a:
    e "我会突然涌起……{size=-5}对你做很坏事的冲动。"

translate schinese hscene37_Erik_Lyna_133d98d6:
    l "好！那你还等什么？"

translate schinese hscene37_Erik_Lyna_c5652396:
    e "只是……我们真的得谈谈这件事，关于妈妈。"

translate schinese hscene37_Erik_Lyna_bbe87ecd:
    l "不。去他的！"

translate schinese hscene37_Erik_Lyna_921063bf:
    centered "{font=font_narration}{cps=30}{color=#00bfff}因为今晚你是我的。"

translate schinese hscene37_Erik_Lyna_28688c81:
    l "浪漫的看星星你已经享受过了，现在回到有意思的部分吧。"

translate schinese hscene37_Erik_Lyna_ad187d36:
    e "可我们……才过去一个小时而已。"

translate schinese hscene37_Erik_Lyna_fa14f611:
    l "……像动物一样做爱做到动不了？没错！"

translate schinese hscene37_Erik_Lyna_f3ae313f:
    e "那是我人生中最棒的经历。我都数不清射了多少次。"

translate schinese hscene37_Erik_Lyna_afe9c47d:
    l "幸好那时候我没让你射在里面，嗯？"

translate schinese hscene37_Erik_Lyna_f1fdf093:
    e "是的……我们绝对不能那样。永远不能。"

translate schinese hscene37_Erik_Lyna_1f350e65:
    l "嘿嘿嘿～也行，可你不想要我了……？"

translate schinese hscene37_Erik_Lyna_2c1ab8c4:
    l "说啊，埃里克。说啊，你不想操你那个饥渴的妹妹。"

translate schinese hscene37_Erik_Lyna_a51526b0:
    em "靠，靠……妈妈这下肯定要发现了。"

translate schinese hscene37_Erik_Lyna_1d7c0677:
    l "告诉我你更想回到假装的状态。"

translate schinese hscene37_Erik_Lyna_9549a98a:
    l "沉默？那好吧。"

translate schinese hscene37_Erik_Lyna_d2dde09c:
    l "那就回到一对正常兄妹的样子吧……"

translate schinese hscene37_Erik_Lyna_5b7ddc9f:
    em "那些该死的照片！她为什么要那么做？！"

translate schinese hscene37_Erik_Lyna_c53f86b5:
    em "真是扫兴……"

translate schinese hscene37_Erik_Lyna_7b2530f1:
    em "该死，莱娜！这非常非常糟糕！"

translate schinese hscene37_Erik_Lyna_926a8470:
    em "妈妈的计划就没法进行下去，我们又会让她可怜的心碎一次……"

translate schinese hscene37_Erik_Lyna_328268cf:
    em "再这样下去，我们会把本已破碎的家庭仅剩的东西也毁掉。"

translate schinese hscene37_Erik_Lyna_438952b7:
    em "可尽管如此，我——"

translate schinese hscene37_Erik_Lyna_a196f1c9:
    l "晚安，埃里克。{size=-5}别担心，我完全理解……"

translate schinese hscene37_Erik_Lyna_bcb2b586:
    e "{size=-5}闭嘴。{/size}"

translate schinese hscene37_Erik_Lyna_66538f08:
    l "哦？什么事，帅哥～？"

translate schinese hscene37_Erik_Lyna_25235aac:
    e "他妈的给我停下！"

translate schinese hscene37_Erik_Lyna_2b09870f:
    e "你以为我是谁？！"

translate schinese hscene37_Erik_Lyna_c75534c3:
    l "你真想知道……？"

translate schinese hscene37_Erik_Lyna_a0a0513e:
    l "一个懦夫，一个软蛋。你就是这样。"

translate schinese hscene37_Erik_Lyna_f81757ce:
    l "你没那个胆量，嘿嘿~"

translate schinese hscene37_Erik_Lyna_4abdd30e:
    e "{size=+5}闭上你的臭嘴！{/size}我可是你哥哥，你得尊重我！"

translate schinese hscene37_Erik_Lyna_7571e1dd:
    e "我受够了你这些小把戏，听见没？！"

translate schinese hscene37_Erik_Lyna_94405339:
    e "重大决定是有后果的！我还以为你比这更懂事。"

translate schinese hscene37_Erik_Lyna_807ebc50:
    e "我对你最近的行为太失望了！"

translate schinese hscene37_Erik_Lyna_caf6998a:
    l "{size=-5}可、可是埃里克……"

translate schinese hscene37_Erik_Lyna_27856335:
    e "不！你现在给我听好。接下来会是这样……"

translate schinese hscene37_Erik_Lyna_31cc76a8:
    e "不管你用那台摄像机拍了什么，妈妈都会学着接受。"

translate schinese hscene37_Erik_Lyna_fe5d012d:
    e "我会再一次替你收拾你那些愚蠢的失误，就像我一直做的那样。"

translate schinese hscene37_Erik_Lyna_af0147c8:
    e "但你得冷静下来！你对妈妈太鲁莽了。"

translate schinese hscene37_Erik_Lyna_ff4ed32a:
    e "我最不希望的就是让她的心更碎……"

translate schinese hscene37_Erik_Lyna_1d67edb2:
    e "我曾经很崇拜他，你知道的。可他全扔了。漂亮的妻子，美丽的女儿……"

translate schinese hscene37_Erik_Lyna_8b5bef89:
    e "所以现在由我来做这个家的顶梁柱，而不是我们那个可悲的借口父亲。"

translate schinese hscene37_Erik_Lyna_80269e02:
    e "而妈妈，她会成为我们约定的一部分。"

translate schinese hscene37_Erik_Lyna_2493274b:
    l "我们的约定……？{size=-5}可那个是神圣的，只属于我们。"

translate schinese hscene37_Erik_Lyna_cdd2a4bf:
    e "是的……但妈妈对我来说同样神圣，就像你一样。"

translate schinese hscene37_Erik_Lyna_8d321227:
    e "我永远不会抛下你们任何一个。绝不！"

translate schinese hscene37_Erik_Lyna_73f59519:
    l "可、可是她……"

translate schinese hscene37_Erik_Lyna_4b496481:
    e "{size=+5}给我闭嘴！{/size}不许再背着我搞这种花样，好？！"

translate schinese hscene37_Erik_Lyna_43115046:
    e "你一直是个很坏的妹妹，很差的女儿……"

translate schinese hscene37_Erik_Lyna_be90a5cb:
    l "我……有吗～？"

translate schinese hscene37_Erik_Lyna_7ef3214e:
    e "有！所以从现在起这个计划要怎么推进，我也要有发言权。"

translate schinese hscene37_Erik_Lyna_7c750221:
    e "因为我比你更了解妈妈。明白了吗？"

translate schinese hscene37_Erik_Lyna_e3f45828:
    l "{size=-5}好、好吧。"

translate schinese hscene37_Erik_Lyna_9b98a3ac:
    e "现在道歉！为这个夏天把妈妈当成一块肉，为你不经她同意就摸她……"

translate schinese hscene37_Erik_Lyna_0435b93c:
    e "为污染我的思想，为逼我玩你那些恶心变态的游戏……"

translate schinese hscene37_Erik_Lyna_276d7e1f:
    l "嘿嘿嘿……所以你是说你一点都不喜欢？"

translate schinese hscene37_Erik_Lyna_6ddb5991:
    l "你刚才可是挺积极的，对吧？填满我小穴的时候~"

translate schinese hscene37_Erik_Lyna_22e20a49:
    e "嘘！你会学会尊重妈妈和她的决定的。"

translate schinese hscene37_Erik_Lyna_29ba642c:
    e "你会像以前那样重新尊重我，因为我可是你哥哥！清楚了吗？！"

translate schinese hscene37_Erik_Lyna_c9dd396b:
    l "我怎么尊重这么个软弱的男人？噗。你现在都没用力……"

translate schinese hscene37_Erik_Lyna_075a24eb:
    e "{size=+5}{cps=25}立{w=0.15}即{w=0.15}道{w=0.15}歉。{w=0.5}现在！"

translate schinese hscene37_Erik_Lyna_c2a7e9f1:
    lm "{size=+10}对啊啊啊！埃里克你他妈硬气点！终于！"

translate schinese hscene37_Erik_Lyna_fc08a3ae:
    l "*咳嗽* 我……我、呃……"

translate schinese hscene37_Erik_Lyna_0709ab26:
    l "{size=-5}我为所有事都非、非常抱歉，大、大哥……"

translate schinese hscene37_Erik_Lyna_2c2612e4:
    e "骗子。变态。你看起来挺享受的。"

translate schinese hscene37_Erik_Lyna_d239d370:
    l "{size=+5}啊啊啊～！"

translate schinese hscene37_Erik_Lyna_b6015973:
    e "好吧莱娜，那就按你的方式来。"

translate schinese hscene37_Erik_Lyna_a7b2c2fd:
    centered "{font=font_narration}{size=+5}{cps=30}{color=#07ff93}跪下。{w=0.5}现在。"

translate schinese hscene37_Erik_Lyna_bef3ffd1:
    e "你刚说谁软弱？！"

translate schinese hscene37_Erik_Lyna_c712696b:
    e "你那两条细胳膊连只苍蝇都拍不死……"

translate schinese hscene37_Erik_Lyna_780c4112:
    l "埃、埃里克只是——"

translate schinese hscene37_Erik_Lyna_9319589e:
    e "喜欢这样吗，变态？！什么都做不了。"

translate schinese hscene37_Erik_Lyna_9e7d2ff3:
    l "直接……{size=-5}操我吧。"

translate schinese hscene37_Erik_Lyna_22064fd7:
    e "说吧。"

translate schinese hscene37_Erik_Lyna_f35f7097:
    l "求你了～？"

translate schinese hscene37_Erik_Lyna_067533cd:
    e "乖女孩。"

translate schinese hscene37_Erik_Lyna_c49e134a:
    e "天哪，你这屁股对这么娇小的身体来说实在太大了。"

translate schinese hscene37_Erik_Lyna_ba4913f7:
    e "而它就摆在那儿给你大哥操，不是吗……？"

translate schinese hscene37_Erik_Lyna_1d1c04c9:
    lm "{size=+5}太火辣了！他突然这么投入。我终于攻下他了！"

translate schinese hscene37_Erik_Lyna_0b25e723:
    lm "看来我得先把变态哄到有兴致才行，嗯？"

translate schinese hscene37_Erik_Lyna_41d57c84:
    l "你还等什么？过来让我肥硕的屁股弹起来！"

translate schinese hscene37_Erik_Lyna_546c7393:
    e "{size=+5}变态！谁准你说话的？！"

translate schinese hscene37_Erik_Lyna_29784482:
    e "你还没为所有事道歉……所以我想我得给妹妹上一课。"

translate schinese hscene37_Erik_Lyna_f75efa4c:
    lm "{size=+5}对，对啊！好粗暴！我要让他他妈彻底占有我！"

translate schinese hscene37_Erik_Lyna_24c22806:
    e "从今往后，跟妈妈的事由我说了算。"

translate schinese hscene37_Erik_Lyna_757886b2:
    e "我不会再让你操纵我。我不会让你毁掉这个家仅剩的东西，莱娜！"

translate schinese hscene37_Erik_Lyna_bdb43d32:
    l "好、好吧……但至少尽情毁掉我的小穴，行吧？"

translate schinese hscene37_Erik_Lyna_221686c5:
    l "呜啊，大哥……！"

translate schinese hscene37_Erik_Lyna_466dfd62:
    em "那些照片……她真是又蠢又莽！我早该知道的！"

translate schinese hscene37_Erik_Lyna_bec716ae:
    em "这种……怒火。我这是怎么了？！我他妈气疯了！"

translate schinese hscene37_Erik_Lyna_ade10a0e:
    em "可我却爱着她，爱着我自己的双胞胎妹妹。"

translate schinese hscene37_Erik_Lyna_acc3485a:
    em "操！她里面已经狠狠夹住我的前端了。"

translate schinese hscene37_Erik_Lyna_132e3555:
    em "我……需要她！我想——"

translate schinese hscene37_Erik_Lyna_3f5d27a7:
    em "{size=+5}……一次又一次地操我妹妹！"

translate schinese hscene37_Erik_Lyna_dbca5b03:
    lm "{size=+5}对！他插到底了！"

translate schinese hscene37_Erik_Lyna_a55363a6:
    lm "我让我哥哥彻底对我上瘾了，{size=+5}对乱伦上瘾！"

translate schinese hscene37_Erik_Lyna_c6276f95:
    e "过来，坏女孩……"

translate schinese hscene37_Erik_Lyna_d37910d4:
    l "对，对！我们又像兔子一样做爱了！你不喜欢吗？！"

translate schinese hscene37_Erik_Lyna_c6f9e4d0:
    e "你毁掉这么完美的夜晚之后还问我这个？"

translate schinese hscene37_Erik_Lyna_8ca1cfe0:
    e "说真的，你他妈为什么要把摄像机留在那儿？！"

translate schinese hscene37_Erik_Lyna_e1bca8d0:
    l "因为我也要让妈妈堕落。"

translate schinese hscene37_Erik_Lyna_d3f74380:
    e "该死！你之前到底有没有在听我说话？！"

translate schinese hscene37_Erik_Lyna_74fb0f8d:
    e "你有时候真是烦死了！这么不小心，这么不守规矩！"

translate schinese hscene37_Erik_Lyna_820a698b:
    e "更别提还是个该死的变态！"

translate schinese hscene37_Erik_Lyna_64b81f96:
    l "嘻嘻~！这也算魅力的一部分吧？"

translate schinese hscene37_Erik_Lyna_76e5e867:
    e "我们的家教不是这样的，莱娜！"

translate schinese hscene37_Erik_Lyna_ceb120fa:
    e "你得重新学学礼貌。{size=-5}我想念以前那个天真的妹妹……"

translate schinese hscene37_Erik_Lyna_f25c5669:
    l "哦？你喜欢那样的？纯洁、害羞、没被碰过？"

translate schinese hscene37_Erik_Lyna_cd210731:
    l "哈！我明白了！我知道你抵抗不了我！"

translate schinese hscene37_Erik_Lyna_7ecbe9e0:
    l "一个年轻的少女，还有……{size=+5}你的双胞胎妹妹！"

translate schinese hscene37_Erik_Lyna_48ef2a05:
    e "我们还有时间停下这场疯狂，不毁掉自己和妈妈的人生，做一个……正常的家庭。"

translate schinese hscene37_Erik_Lyna_761041c3:
    l "哈哈哈！想都别想，埃里克！"

translate schinese hscene37_Erik_Lyna_286b1d52:
    l "那好吧，只要你现在就停下，我就把一切都忘干净？成交？嘿嘿嘿~"

translate schinese hscene37_Erik_Lyna_93f45106:
    e "{size=+5}我是认真的，你这个变态！"

translate schinese hscene37_Erik_Lyna_157879d0:
    l "听、听着，我不傻。我知道这一切都太不真实了，好吗？！"

translate schinese hscene37_Erik_Lyna_bbac096f:
    l "可我们已经永远成交了。不许退缩！"

translate schinese hscene37_Erik_Lyna_07c78738:
    e "啧……{size=-5}你说得有道理。"

translate schinese hscene37_Erik_Lyna_c3febbaf:
    l "对！所以你余生都要把你这个爱乱伦的妹妹当成肉便器了，嗯？！"

translate schinese hscene37_Erik_Lyna_5269ae00:
    e "{size=+5}给我闭嘴！你已经疯了。你就是个彻底的怪胎！"

translate schinese hscene37_Erik_Lyna_c3bd728a:
    l "{size=+10}你的怪胎。"

translate schinese hscene37_Erik_Lyna_ff15862a:
    e "所以你真的很喜欢{i}大哥{/i}对你很粗暴，嗯？！"

translate schinese hscene37_Erik_Lyna_4435b930:
    e "当我{i}使用{/i}你性感的小身子的时候……？！"

translate schinese hscene37_Erik_Lyna_7e4b87e0:
    l "{size=+5}对！就是这样！我被我火辣的双胞胎狠狠干着，这是有史以来最棒的生日礼物！"

translate schinese hscene37_Erik_Lyna_680bc409:
    l "{size=+10}再用力！让我少女的屁股弹起来！我想尖叫着喊你的名字！"

translate schinese hscene37_Erik_Lyna_168fa4b9:
    e "操，操。你简直疯了！我爱你的全部，你的所有……"

translate schinese hscene37_Erik_Lyna_252bef15:
    l "{size=+5}那就让他们听见啊。{size=+10}让全世界都知道！"

translate schinese hscene37_Erik_Lyna_efe5cf96:
    e "{size=+10}我如此深爱着我的双胞胎妹妹！"

translate schinese hscene37_Erik_Lyna_3617795f:
    e "{size=+15}而且我热爱操她光秃秃的小穴！"

translate schinese hscene37_Erik_Lyna_ab9508de:
    l "{size=+10}对！这违法，这变态！可我完全上瘾了！"

translate schinese hscene37_Erik_Lyna_76a56fec:
    l "{size=+5}你也上瘾了吗，大哥……？{size=+10}对乱伦上瘾？！"

translate schinese hscene37_Erik_Lyna_090b3b70:
    e "这他妈太不对了，妹。{size=-10}但我他妈爱死了。"

translate schinese hscene37_Erik_Lyna_0374b679:
    e "我们正在做的，那晚我们对妈妈做的，还有我们为她准备的……"

translate schinese hscene37_Erik_Lyna_76b99b2c:
    e "{size=+20}我们两个会一起在地狱里烧成灰！"

translate schinese hscene37_Erik_Lyna_4788d0ca:
    l "{size=+25}那就把这一路搞得值回票价吧……！"

translate schinese story52_Erik_Lyna_Helga_aba3ee92:
    centered "{font=font_narration}{size=+10}{cps=20}第二天早上……"

translate schinese story52_Erik_Lyna_Helga_f37ecac2:
    hm "无论看多少次，都没法否认……"

translate schinese story52_Erik_Lyna_Helga_833fd2d3:
    hm "这肯定就是我女儿，跟一个男人在做坏事。"

translate schinese story52_Erik_Lyna_Helga_c3c6d9e2:
    hm "原来她一直在背后做这种事……？"

translate schinese story52_Erik_Lyna_Helga_3b2f17b3:
    hm "我们分享的那些亲密时刻，她说自己的不安、说不知道怎么跟男生相处……"

translate schinese story52_Erik_Lyna_Helga_05d30623:
    hm "{size=+10}那个小骗子！我早觉得不对劲！"

translate schinese story52_Erik_Lyna_Helga_04e2296e:
    l "现在我明白妈咪为什么那么喜欢了，嘿嘿嘿~"

translate schinese story52_Erik_Lyna_Helga_d56944fd:
    e "我这么擅长这个吗？哈哈……"

translate schinese story52_Erik_Lyna_Helga_98a45435:
    l "对！不过听着，我现在想试点别的……"

translate schinese story52_Erik_Lyna_Helga_c6ffe254:
    hm "原来一直在装……一边跟我做那些不要脸的事，还背着我。"

translate schinese story52_Erik_Lyna_Helga_5e0459d6:
    hm "这已经不是单纯的好奇了！是卑劣的。是……有预谋的。"

translate schinese story52_Erik_Lyna_Helga_573e547b:
    hm "{size=+5}这到底是怎么回事？！我不明白！"

translate schinese story52_Erik_Lyna_Helga_0b8cdd19:
    hm "{size=+5}我一直以为我们是在努力重新联络感情、弥补过去的一切！可是——"

translate schinese story52_Erik_Lyna_Helga_ddded270:
    hm "结果我女儿还在撒谎，而且更糟……是个变态。"

translate schinese story52_Erik_Lyna_Helga_76350e4a:
    hm "{size=+5}一个对自己亲生母亲有欲望的该死变态！天啊！"

translate schinese story52_Erik_Lyna_Helga_8a48f736:
    centered "{font=font_narration}{cps=25}{color=#00bfff}如果你没有无视我、没有多年来把我当成可有可无的人……"

translate schinese story52_Erik_Lyna_Helga_84e500f1:
    hm "但也许真的是我的错。那些年来的忽视、偏心、不切实际的期待……"

translate schinese story52_Erik_Lyna_Helga_797f4763:
    hm "现在她对爱的渴望，全都投错了地方。"

translate schinese story52_Erik_Lyna_Helga_49f7ba22:
    hm "她哥哥知道这些照片的事吗？是不是我的孩子们请了朋友来？"

translate schinese story52_Erik_Lyna_Helga_18902773:
    hm "也许是莱娜趁第一周家里只有他们的时候拍的……"

translate schinese story52_Erik_Lyna_Helga_b7018fde:
    hm "{size=+5}不可能！这些照片上的日期明明是几天前的！"

translate schinese story52_Erik_Lyna_Helga_d12fcc6a:
    hm "{size=+5}那我儿子知道吗？！他也瞒着我吗……？"

translate schinese story52_Erik_Lyna_Helga_757fa310:
    hm "那他今年夏天怎么突然这么大胆了……？"

translate schinese story52_Erik_Lyna_Helga_356c382b:
    hm "说起来，他确实在那段禁忌的师生恋上骗过我……"

translate schinese story52_Erik_Lyna_Helga_05ee6b95:
    hm "还有对我身体的痴迷、那些勃起、甘愿让他对我做那些羞耻的事……又算什么？"

translate schinese story52_Erik_Lyna_Helga_b93b68e7:
    hm "我知道自己不是最好的母亲，但这说不通。"

translate schinese story52_Erik_Lyna_Helga_e1b8121f:
    hm "我无法相信自己养出了一对狡猾的、会骗人的……变态！"

translate schinese story52_Erik_Lyna_Helga_abd703b7:
    l "快、快点吧哥哥！我们得赶紧回家了……"

translate schinese story52_Erik_Lyna_Helga_e8031b88:
    l "你可不想惹{i}妈妈{/i}生气吧？"

translate schinese story52_Erik_Lyna_Helga_b560a17c:
    e "没有，没有！我……马上就到了，莱娜！"

translate schinese story52_Erik_Lyna_Helga_cefd7f90:
    l "那就快点射出来啊！"

translate schinese story52_Erik_Lyna_Helga_46ec5a14:
    e "{size=+5}耶！等着瞧，我要把你屁股涂成花！"

translate schinese story52_Erik_Lyna_Helga_ad680ff6:
    l "{size=+10}对！你双胞胎妹妹的翘屁股……！"

translate schinese story52_Erik_Lyna_Helga_4fda4bb3:
    hm "我女儿……？很有可能。她故意一直在试探我的耐心。"

translate schinese story52_Erik_Lyna_Helga_9fde981d:
    hm "但我的宝贝儿子？绝不！他太纯洁了，不会那样。"

translate schinese story52_Erik_Lyna_Helga_c243d5d8:
    hm "他们最近的行为一定有个合理的解释，对吧？"

translate schinese story52_Erik_Lyna_Helga_0122369c:
    hm "莱娜好像一直在我们眼皮底下背着我们做坏事……我们俩怎么会都没察觉？"

translate schinese story52_Erik_Lyna_Helga_0e93538e:
    hm "可如果她哥哥真的知道什么，也许只是因为——"

translate schinese story52_Erik_Lyna_Helga_080bd9b8:
    centered "{font=font_narration}{cps=30}{color=#00bfff}我那些不干净的梦里的男孩，他非常性感……"

translate schinese story52_Erik_Lyna_Helga_43a9613b:
    centered "{font=font_narration}{cps=30}{color=#00bfff}他有一双蓝眼睛……"

translate schinese story52_Erik_Lyna_Helga_0646cc43:
    centered "{font=font_narration}{cps=30}{color=#00bfff}而且他很害羞，妈……非常、非常害羞。"

translate schinese story52_Erik_Lyna_Helga_9bab8ac1:
    centered "{font=font_narration}{cps=30}{color=#00bfff}可我们是亲兄妹啊妈咪……我们看过彼此的裸体很多次了！"

translate schinese story52_Erik_Lyna_Helga_caba82f7:
    centered "{font=font_narration}{cps=30}{color=#07ff93}莱娜昨晚甚至让我睡她的床……"

translate schinese story52_Erik_Lyna_Helga_06a34df7:
    centered "{font=font_narration}{cps=30}{color=#07ff93}这关系到……一个女孩。一个我真的很在意的人。"

translate schinese story52_Erik_Lyna_Helga_c36a239e:
    centered "{font=font_narration}{cps=30}{color=#07ff93}很复杂，妈。算是……一种禁忌之恋。"

translate schinese story52_Erik_Lyna_Helga_e55d9678:
    hm "{size=+10}不！不可能！完全荒谬！"

translate schinese story52_Erik_Lyna_Helga_decf0e57:
    hm "{size=+5}不敢相信我居然对自己的孩子有这种想法！"

translate schinese story52_Erik_Lyna_Helga_510dcea0:
    hm "这该死的酒、压力、寂寞……{size=-5}我一定是疯了，开始看到不存在的东西。"

translate schinese story52_Erik_Lyna_Helga_9139b873:
    hm "答案……这才是我需要的。"

translate schinese story53_Erik_Lyna_Helga_0d8fbaa1:
    centered "{font=font_narration}{size=+10}{cps=20}几小时后……"

translate schinese story53_Erik_Lyna_Helga_e11cba27:
    l "天啊，那些颠簸真是我存在的克星……还有我的脖子！"

translate schinese story53_Erik_Lyna_Helga_8ea58814:
    e "那正好又给了按摩一个借口，对吧？"

translate schinese story53_Erik_Lyna_Helga_70c31593:
    e "莱娜？怎么了？怕自己会太喜欢……？"

translate schinese story53_Erik_Lyna_Helga_fd22e9c2:
    l "才不！想按多久都可以，帅哥哥~！"

translate schinese story53_Erik_Lyna_Helga_7ecf7108:
    l "但他也得给你留点，对吧妈？"

translate schinese story53_Erik_Lyna_Helga_0a9341fb:
    e "妈……？怎么了？"

translate schinese story53_Erik_Lyna_Helga_e78d134b:
    e "哦？！嗨……{size=-5}没、没看到你在这儿。"

translate schinese story53_Erik_Lyna_Helga_5cbb18e3:
    h "你好……孩子们。"

translate schinese story53_Erik_Lyna_Helga_64613715:
    l "{size=+5}妈咪——！我好想你！"

translate schinese story53_Erik_Lyna_Helga_f286e481:
    e "呃，妈？抱歉让你等了。回程比预想的久了一点……"

translate schinese story53_Erik_Lyna_Helga_2d635bcf:
    l "对！都是「负责任先生」坚持要开慢点。嘿嘿~"

translate schinese story53_Erik_Lyna_Helga_b4692a5c:
    l "但安全第一嘛，对吧？他最棒了！"

translate schinese story53_Erik_Lyna_Helga_bf6caf40:
    h "你们真体贴……{size=+10}埃里克。"

translate schinese story53_Erik_Lyna_Helga_cf5ed4ae:
    e "是、是的。为了妹妹什么都行……"

translate schinese story53_Erik_Lyna_Helga_a4cfc7e3:
    h "{size=+5}咳咳！{/size}你们俩还愣着干什么？"

translate schinese story53_Erik_Lyna_Helga_8a789e67:
    h "你们俩都进来吧。午饭都凉了。"

translate schinese story53_Erik_Lyna_Helga_cd7ed80f:
    e "好的……走吧，莱娜。"

translate schinese story53_Erik_Lyna_Helga_d897c5bf:
    e "看起来很好吃，妈！不过你不用亲自做，我可以帮忙的。"

translate schinese story53_Erik_Lyna_Helga_549aa102:
    h "没事。别担心。"

translate schinese story53_Erik_Lyna_Helga_28efdfcc:
    h "毕竟整个上午我都可以……{size=+5}独处{/size}。"

translate schinese story53_Erik_Lyna_Helga_f1c65180:
    lm "糟了！她肯定已经看到照片了。"

translate schinese story53_Erik_Lyna_Helga_9ff68192:
    e "妈，你是不——"

translate schinese story53_Erik_Lyna_Helga_f19c7eed:
    h "是，我已经吃过了。{size=-5}一个人。"

translate schinese story53_Erik_Lyna_Helga_0afc25f5:
    e "好吧……但你至少现在能陪我们坐会儿吗？"

translate schinese story53_Erik_Lyna_Helga_40c5522a:
    l "会的妈咪~！陪陪我们嘛！"

translate schinese story53_Erik_Lyna_Helga_76a0814e:
    h "啧。行吧。"

translate schinese story53_Erik_Lyna_Helga_27f02348:
    l "那我们不在的时候你还干了什么？瑜伽？"

translate schinese story53_Erik_Lyna_Helga_8036e348:
    h "嗯，差不多吧。"

translate schinese story53_Erik_Lyna_Helga_4f6696f1:
    h "{size=-5}主要是让自己忙着……想事情。"

translate schinese story53_Erik_Lyna_Helga_bc9ffa4e:
    lm "靠。冷静点，埃里克。"

translate schinese story53_Erik_Lyna_Helga_2a3a2a7c:
    h "跟我说说。感觉怎么样？你们那次……双胞胎小旅行？"

translate schinese story53_Erik_Lyna_Helga_49f7e59a:
    l "嗨，我们玩疯了！最棒的生日，对吧哥哥？"

translate schinese story53_Erik_Lyna_Helga_c5653047:
    e "是啊，莱娜。相当不错。平静的海、沙滩……{size=-5}是啊。"

translate schinese story53_Erik_Lyna_Helga_0dced961:
    h "听起来……不错。这边也有的是。"

translate schinese story53_Erik_Lyna_Helga_e79cfa20:
    e "当然，不过……换个环境有时也挺好的。"

translate schinese story53_Erik_Lyna_Helga_63db20f2:
    l "是啊妈，你一定会喜欢的！还有露天温泉池、霓虹灯……超级惬意。"

translate schinese story53_Erik_Lyna_Helga_de1ee4a7:
    h "确实挺时髦的……{size=-5}大概你妈这把年纪太古板，不适合那些。"

translate schinese story53_Erik_Lyna_Helga_0db5f071:
    e "不是的妈！你才不古——"

translate schinese story53_Erik_Lyna_Helga_48bb1633:
    h "少来！我只是开玩笑。{size=-15}大部分是。"

translate schinese story53_Erik_Lyna_Helga_74eab132:
    l "你、你好吗妈咪？你今天看起来……有点紧绷。"

translate schinese story53_Erik_Lyna_Helga_fd88f850:
    h "是吗……大概是这酒吧。{size=-5}它陪了我一上午。"

translate schinese story53_Erik_Lyna_Helga_98119ade:
    em "靠。我们完蛋了！"

translate schinese story53_Erik_Lyna_Helga_e0c9a512:
    h "嗯？你是想喝点什么吧……？"

translate schinese story53_Erik_Lyna_Helga_7546a3db:
    l "哦~？当然！还以为你永远不会问呢！"

translate schinese story53_Erik_Lyna_Helga_6488f9d4:
    e "妹，拜托——"

translate schinese story53_Erik_Lyna_Helga_85c54221:
    e "咳咳！妈，我们……"

translate schinese story53_Erik_Lyna_Helga_e9de9d7d:
    e "我们也很想你。"

translate schinese story53_Erik_Lyna_Helga_9fe7b72d:
    l "对！我们超级想你的！没有你在就不一样。"

translate schinese story53_Erik_Lyna_Helga_34d7e45f:
    h "哼。现在才说这种话……{size=-5}真甜。"

translate schinese story53_Erik_Lyna_Helga_153bf32f:
    h "总之，再多跟我说说你们这趟旅行吧，好吗？"

translate schinese story53_Erik_Lyna_Helga_bd4d740d:
    h "你们两个到底去了哪里？"

translate schinese story53_Erik_Lyna_Helga_e1f5810e:
    e "呃……其实……"

translate schinese story53_Erik_Lyna_Helga_40d375f1:
    e "我们先去了……去了我们那个秘密洞穴，对！去庆祝。"

translate schinese story53_Erik_Lyna_Helga_1be1dd4d:
    e "就是很多年前我们还是小不点时候的那个，还记得吗？"

translate schinese story53_Erik_Lyna_Helga_6f0323ea:
    h "哦，那个啊……"

translate schinese story53_Erik_Lyna_Helga_e02ca3dd:
    h "啧。你们俩单独出去的时候可把我吓坏了。"

translate schinese story53_Erik_Lyna_Helga_885da59a:
    h "不过这次我想你们已经大到能照顾自己了……"

translate schinese story53_Erik_Lyna_Helga_04e8a257:
    l "我们当然！而且我也到能喝酒的年纪了，对吧？"

translate schinese story53_Erik_Lyna_Helga_423364b0:
    l "那你到底给我倒不倒酒……？我还在等呢！"

translate schinese story53_Erik_Lyna_Helga_87e8ca31:
    l "求求啦~？"

translate schinese story53_Erik_Lyna_Helga_b9522ce1:
    h "也是……抱歉。"

translate schinese story53_Erik_Lyna_Helga_c22a9323:
    h "那你们是在外面睡的？在那个……洞穴里？"

translate schinese story53_Erik_Lyna_Helga_401f9de3:
    h "求你告诉我你们没有。"

translate schinese story53_Erik_Lyna_Helga_9ad6aa35:
    l "才没有！我们——"

translate schinese story53_Erik_Lyna_Helga_ffc09d22:
    h "{size=+5}不！不是你。{/size}埃里克，你说。"

translate schinese story53_Erik_Lyna_Helga_4c140146:
    e "对、对，呃……没有。之后我们当然得找个安全的地方休息。"

translate schinese story53_Erik_Lyna_Helga_4d9acc47:
    l "对！还有超级棒的晚餐、美丽的日落、豪华的卧室……"

translate schinese story53_Erik_Lyna_Helga_ee8e1526:
    l "说真的，你肯定会爱上那里的！嘿嘿嘿~"

translate schinese story53_Erik_Lyna_Helga_a87bc8a4:
    e "莱娜，别闹了！就是家普通旅馆，妈。没什么大不了的。"

translate schinese story53_Erik_Lyna_Helga_13cde088:
    l "{cps=25}而且还是个非常{size=+10}浪漫{/size}的地方，{w=0.5}真的。"

translate schinese story53_Erik_Lyna_Helga_972f5595:
    em "{size=+10}莱娜你他妈在逗我吗？！"

translate schinese story53_Erik_Lyna_Helga_ad6a7762:
    l "靠！我、我太抱歉了！{size=-5}烂玩笑……"

translate schinese story53_Erik_Lyna_Helga_52be6ed9:
    e "{size=+5}妈，拜托！她不是那个意思！"

translate schinese story53_Erik_Lyna_Helga_399c4e9a:
    h "哎宝贝，你那些既傻又完全不合时宜的玩笑！"

translate schinese story53_Erik_Lyna_Helga_755ad55f:
    h "你真是太逗了，真的！哈哈哈！"

translate schinese story53_Erik_Lyna_Helga_40a12cd9:
    l "嗯？好、好笑！{size=-5}哈哈……"

translate schinese story53_Erik_Lyna_Helga_14674052:
    h "别担心。意外总会发生的，对吧？"

translate schinese story53_Erik_Lyna_Helga_f1b62e1e:
    l "好、好的。你需要我帮你——呃……？"

translate schinese story53_Erik_Lyna_Helga_b41ffefb:
    h "{size=+5}{cps=20}不用。"

translate schinese story53_Erik_Lyna_Helga_f976c452:
    h "{size=+5}{cps=15}真的不用。"

translate schinese story53_Erik_Lyna_Helga_58149e75:
    h "至少……不是要你帮。"

translate schinese story53_Erik_Lyna_Helga_aa287b13:
    h "埃里克，跟我来。现在。"

translate schinese story53_Erik_Lyna_Helga_ce2ae982:
    e "嗯？我……？"

translate schinese story53_Erik_Lyna_Helga_f5efad29:
    e "好的！好、好吧。"

translate schinese story53_Erik_Lyna_Helga_0183ea7e:
    h "楼上，我的房间。走吧。"

translate schinese story53_Erik_Lyna_Helga_aed09c90:
    l "妈、妈咪，那我呢？{size=-5}你生气了吗？"

translate schinese story53_Erik_Lyna_Helga_ff7b13e2:
    h "生气？当然不是，我可爱的小天使。"

translate schinese story53_Erik_Lyna_Helga_fad09954:
    h "你就安心把饭吃完，好吗？我相信你会很享受{size=+15}独自{/size}一人的。"

translate schinese story53_Erik_Lyna_Helga_f3c2e7c7:
    l "{size=-5}那好吧……"

translate schinese story53_Erik_Lyna_Helga_8d959289:
    hm "太棒了。真他妈太棒了。"

translate schinese story53_Erik_Lyna_Helga_79d5a226:
    h "{size=-5}老样子，对吧？又是因为你那臭妹妹搞出一堆烂摊子。"

translate schinese story53_Erik_Lyna_Helga_851fee18:
    e "{size=-5}妈……别开始了。我们走吧，好吗？"

translate schinese hscene38_Erik_Helga_6909c6b1:
    h "怎么？别干站着，埃里克。帮帮我。"

translate schinese hscene38_Erik_Helga_1987db03:
    e "哦！呃……怎么帮？"

translate schinese hscene38_Erik_Helga_e6581d7c:
    h "那边也湿了一点。"

translate schinese hscene38_Erik_Helga_95b533e8:
    h "帮我把它脱下来。你知道怎么……？"

translate schinese hscene38_Erik_Helga_94eb298b:
    e "我……会，我想我会。"

translate schinese hscene38_Erik_Helga_bc7c0d04:
    h "很好。先解挂钩。"

translate schinese hscene38_Erik_Helga_8c800f0c:
    e "咳咳！那个……请从胳膊开始。"

translate schinese hscene38_Erik_Helga_5a7f2392:
    e "妈妈，你确定你没事吗？"

translate schinese hscene38_Erik_Helga_a8e298ea:
    e "我是说，刚才在楼下你好像——"

translate schinese hscene38_Erik_Helga_23c387a3:
    h "生气……？有点。寂寞……？{size=-5}绝对。"

translate schinese hscene38_Erik_Helga_fd0d8df6:
    e "妈、妈妈，我——"

translate schinese hscene38_Erik_Helga_46d3b860:
    h "嘘！现在我一个人能应付了，儿子。你退开。"

translate schinese hscene38_Erik_Helga_ada76c32:
    h "所以，就像我刚才说的，没有你们两个，昨天安静得很。"

translate schinese hscene38_Erik_Helga_d58f1ae9:
    h "所以你们住在汽车旅馆？{size=-5}你妹妹显然觉得那很「浪漫」。"

translate schinese hscene38_Erik_Helga_6d3a7438:
    h "{cps=25}用这种词来形容那种地方，{w=0.35}有意思吧？"

translate schinese hscene38_Erik_Helga_87dffe92:
    em "该死。该死！"

translate schinese hscene38_Erik_Helga_8d9c6849:
    e "我、我是说，我想只是……那个风景的整体氛围……"

translate schinese hscene38_Erik_Helga_38a56eac:
    e "但她在夸张！你也知道莱娜开玩笑是什么样。"

translate schinese hscene38_Erik_Helga_e67c66d2:
    e "真、真的只是我们俩。在一起玩。"

translate schinese hscene38_Erik_Helga_3bc7235e:
    h "一起玩……是吗。"

translate schinese hscene38_Erik_Helga_9dedce9f:
    h "{size=-5}你们两个都很擅长这个。"

translate schinese hscene38_Erik_Helga_90687519:
    h "你们两个到底做了什么？"

translate schinese hscene38_Erik_Helga_24f6b906:
    e "妈妈？！你忘了你是——"

translate schinese hscene38_Erik_Helga_e33bc9f3:
    h "埃里克，马上告诉我！你们两个孩子做了什么？"

translate schinese hscene38_Erik_Helga_ca67522e:
    e "只、只是……玩得很开心，我发誓！"

translate schinese hscene38_Erik_Helga_f7d76e2a:
    e "兄妹之间平常的小事。{size=-5}我们一直这样。"

translate schinese hscene38_Erik_Helga_d12a79e1:
    hm "他在躲。你还有什么没告诉我，我的孩子？"

translate schinese hscene38_Erik_Helga_0033ae87:
    h "是啊。你们俩最近贴得可紧了……"

translate schinese hscene38_Erik_Helga_d7fcb272:
    h "{cps=25}比以往任何时候都紧。"

translate schinese hscene38_Erik_Helga_9e0fc83b:
    e "我们是双胞胎啊妈妈！我们一直形影不离……"

translate schinese hscene38_Erik_Helga_2a1b23d8:
    h "是的，我{size=+10}非常{/size}清楚。"

translate schinese hscene38_Erik_Helga_9aa3c120:
    em "操！莱娜到底留下了她多少照片？！"

translate schinese hscene38_Erik_Helga_67209c9c:
    h "我一整天都在想你俩。在猜测。"

translate schinese hscene38_Erik_Helga_bbb5dc0d:
    e "嗯哼。猜……什么？"

translate schinese hscene38_Erik_Helga_d931649f:
    h "没什么……就一些事。"

translate schinese hscene38_Erik_Helga_1c337741:
    h "比如莱娜怎么还像个孩子一样。"

translate schinese hscene38_Erik_Helga_1453a06d:
    h "啧！你妹妹是没救了，对吧？"

translate schinese hscene38_Erik_Helga_8d179631:
    h "我以为她变了，我真是天真……"

translate schinese hscene38_Erik_Helga_0a09a179:
    e "可、可不是嘛，哈哈……"

translate schinese hscene38_Erik_Helga_8e10d6f5:
    e "她最近确实很不安分，但我觉得我能应付。我能把她掰回来。"

translate schinese hscene38_Erik_Helga_d5153a0c:
    h "哈！你已经试了十八年了，儿子。"

translate schinese hscene38_Erik_Helga_3b9c9f6d:
    e "可时间还多着呢，不是吗？"

translate schinese hscene38_Erik_Helga_e23517f1:
    h "儿子，昨天我真的满脑子都是你。"

translate schinese hscene38_Erik_Helga_1d248f5a:
    h "还有我们最爱惹事的那个……我比她以为的更爱她。"

translate schinese hscene38_Erik_Helga_3a9fae34:
    e "我们知道啊妈妈！我们也爱你，胜过一切……"

translate schinese hscene38_Erik_Helga_1d220993:
    e "所、所以呃，你还想到我们什么了吗？"

translate schinese hscene38_Erik_Helga_7cf13efe:
    h "你们两个长、长得这么大了……{size=-5}再也不需要我了……"

translate schinese hscene38_Erik_Helga_7732831c:
    em "该死。她是真的难过，非常难过……我讨厌看到妈妈这样！"

translate schinese hscene38_Erik_Helga_e59e8500:
    h "{size=-5}但你至少还是我的乖儿子，对吧……？埃里克？"

translate schinese hscene38_Erik_Helga_82b96e3e:
    e "当然是妈！永远都是。"

translate schinese hscene38_Erik_Helga_b790daa8:
    h "可你却把我一个人丢在这儿！"

translate schinese hscene38_Erik_Helga_699d064f:
    e "什、什么？不是！"

translate schinese hscene38_Erik_Helga_9bde5af5:
    h "就是！孤零零的……{size=-5}就像你爸当年一样。"

translate schinese hscene38_Erik_Helga_f87894e1:
    e "{size=+5}妈妈？！不！莱娜和我不是——"

translate schinese hscene38_Erik_Helga_91a0b9a3:
    h "嘘！没关系……其实我很高兴我的孩子们相处得这么好。"

translate schinese hscene38_Erik_Helga_98070746:
    h "我知道你不是故意要伤我的心，宝贝。你从来都不会……"

translate schinese hscene38_Erik_Helga_7b7f9708:
    h "因为你是我的完美儿子，我的一切……"

translate schinese hscene38_Erik_Helga_5db91bc9:
    em "她在干什么？！我还以为她在难过……？"

translate schinese hscene38_Erik_Helga_85d63dd4:
    em "糟了！她又进入{i}那种{/i}心情了。"

translate schinese hscene38_Erik_Helga_039a0851:
    h "你也会想我吗……？"

translate schinese hscene38_Erik_Helga_17d53663:
    e "当然会啊妈！就算只分开了一天……"

translate schinese hscene38_Erik_Helga_ea9e80c0:
    e "{size=-5}要是你知道过去一年我在国外有多想你就好了。"

translate schinese hscene38_Erik_Helga_1d5ef1c1:
    h "啊……总是这么贴心。{size=-5}这才是我儿子。"

translate schinese hscene38_Erik_Helga_f405c3be:
    h "你知道我听到这话有多高兴吗？"

translate schinese hscene38_Erik_Helga_f1b5afad:
    h "{cps=30}我的乖儿子……"

translate schinese hscene38_Erik_Helga_c61650d1:
    h "{cps=20}{size=-5}……想他的妈妈。"

translate schinese hscene38_Erik_Helga_8a8bdfa8:
    e "妈妈，呃……"

translate schinese hscene38_Erik_Helga_fbd918ca:
    h "怎么了？母亲就不能和自己的儿子亲近吗？"

translate schinese hscene38_Erik_Helga_602aebd9:
    h "{cps=20}和她可爱的、{w=0.35}小小的、{w=0.35}小宝贝儿子……"

translate schinese hscene38_Erik_Helga_4d2167d5:
    h "嗯，我下面这玩意儿是什么感觉？"

translate schinese hscene38_Erik_Helga_29de8bd8:
    e "妈，我发誓这不是你想的那——"

translate schinese hscene38_Erik_Helga_de138c2d:
    h "哎呀~我敢打赌{i}他{/i}可不这么想，对吧？"

translate schinese hscene38_Erik_Helga_7fa35e8d:
    e "咳！你今天喝了多少酒……？"

translate schinese hscene38_Erik_Helga_c91fad88:
    h "宝贝，如果你想问的是这个，我非常清楚自己现在在做什么。"

translate schinese hscene38_Erik_Helga_d82a6f82:
    hm "而且我厌恶这个。我厌恶自己居然想要！"

translate schinese hscene38_Erik_Helga_c233b4a4:
    h "告诉我。你又需要我帮忙了，像前几晚那样？"

translate schinese hscene38_Erik_Helga_731e1e68:
    e "妈、妈妈你为什么要这样……？"

translate schinese hscene38_Erik_Helga_77642f6c:
    h "嘘……别抗拒，好吗？让我再帮你一次。"

translate schinese hscene38_Erik_Helga_2077704f:
    hm "就再一次。"

translate schinese hscene38_Erik_Helga_d2075b95:
    em "操！怎么回事？！她怎么突然这么——"

translate schinese hscene38_Erik_Helga_17d82661:
    hm "他是完全属于我的……我的儿子。天啊，我为什么又想要这个？！"

translate schinese hscene38_Erik_Helga_85841f8f:
    hm "我必须停下。我知道我该停下，但自从那晚之后……"

translate schinese hscene38_Erik_Helga_61db4423:
    hm "我就对这副身体着了魔。"

translate schinese hscene38_Erik_Helga_e4bf5fb9:
    hm "一个才将满十九岁的男孩的年轻身躯……"

translate schinese hscene38_Erik_Helga_278f830c:
    hm "天啊，我是个怪物。我脑子坏了。"

translate schinese hscene38_Erik_Helga_282330c1:
    hm "可这强健又柔软的肌肉……"

translate schinese hscene38_Erik_Helga_24486457:
    hm "这份纯真，这份清澈……"

translate schinese hscene38_Erik_Helga_1e13e335:
    hm "这份炽烈而强大的欲望……"

translate schinese hscene38_Erik_Helga_2b2cc01f:
    hm "还有这禁忌的气息……！"

translate schinese hscene38_Erik_Helga_12310c3d:
    em "我……我动不了！为什么？！"

translate schinese hscene38_Erik_Helga_58b71e9a:
    hm "{size=-5}我的孩子。我亲生的儿子。"

translate schinese hscene38_Erik_Helga_0b6569a7:
    e "妈、妈妈？！你在——"

translate schinese hscene38_Erik_Helga_dc97b298:
    h "相信我。"

translate schinese hscene38_Erik_Helga_077acb69:
    h "到床上去。"

translate schinese hscene38_Erik_Helga_5093b325:
    e "不！拜托，我们得好好谈谈。"

translate schinese hscene38_Erik_Helga_f3b63457:
    h "别逼我重复，埃里克。"

translate schinese hscene38_Erik_Helga_132879b3:
    e "先听我说句话！"

translate schinese hscene38_Erik_Helga_8a7b148f:
    hm "对不起宝贝！妈妈真的很抱歉！但是——"

translate schinese hscene38_Erik_Helga_9573eb98:
    h "{cps=20}上。{w=0.35}床。{w=0.35}上。{w=0.5}立刻。"

translate schinese hscene38_Erik_Helga_54d4b6c1:
    h "上次你为什么那么主动？！你为什么没有拒绝我的挑逗？！"

translate schinese hscene38_Erik_Helga_76ee0264:
    e "什么？……我……{size=-5}我不明白你的意思。"

translate schinese hscene38_Erik_Helga_5e8977e1:
    h "你做那事只是为了安慰我？！{size=+5}为了缓解我的痛苦？！"

translate schinese hscene38_Erik_Helga_719c6924:
    e "妈妈，拜托……冷静点。"

translate schinese hscene38_Erik_Helga_ee04952c:
    h "不！这次你看起来犹豫多了，为什么？！"

translate schinese hscene38_Erik_Helga_8a4ed045:
    h "你不再爱我了，儿子？"

translate schinese hscene38_Erik_Helga_f58621fd:
    h "是不是因为……有别人了？"

translate schinese hscene38_Erik_Helga_d5b5d908:
    e "啥？！妈妈……我——"

translate schinese hscene38_Erik_Helga_6179397c:
    em "拜托，醒醒埃里克！她起疑了！快收拾莱娜留下的烂摊子！"

translate schinese hscene38_Erik_Helga_4d66e5c0:
    h "还是说……是因为我的身体？"

translate schinese hscene38_Erik_Helga_b50edf8e:
    h "嗯，不可能。你明明很喜欢妈妈的身体……"

translate schinese hscene38_Erik_Helga_bfdbbf5a:
    e "是、是的！你是世界上最美的女人！"

translate schinese hscene38_Erik_Helga_b49629e6:
    e "你身上每一处都……热得要命。比我这个年纪任何女孩都强。"

translate schinese hscene38_Erik_Helga_41a82ac0:
    hm "天啊埃里克，别再火上浇油了……"

translate schinese hscene38_Erik_Helga_42ae29f6:
    h "{i}性感{/i}又有什么用？！我他妈还是这么寂寞！"

translate schinese hscene38_Erik_Helga_caba47ca:
    h "我需要一个再次爱我的男人，一个真正让我觉得自己是女人的人……"

translate schinese hscene38_Erik_Helga_bacd2285:
    hm "{size=+5}赫尔加你到底在干什么？！你忘了他是谁了吗？！你……不能！"

translate schinese hscene38_Erik_Helga_4b450d71:
    h "{cps=20}我需要一个欣赏完整的我的人。"

translate schinese hscene38_Erik_Helga_617c8d7e:
    h "宝贝，我知道我们前几晚做的事非常不合适，可是……"

translate schinese hscene38_Erik_Helga_efd6007e:
    h "现在每次我看着你，都会忍不住温情地想起它，虽然这听起来也许很奇怪。"

translate schinese hscene38_Erik_Helga_b947939c:
    h "我忆起了自己的青春，那些我曾拥有过的美妙时刻……"

translate schinese hscene38_Erik_Helga_1a7caf21:
    h "还有那些我可能再也不会拥有的东西。"

translate schinese hscene38_Erik_Helga_4ae96429:
    h "但我还没准备好就这样放手……"

translate schinese hscene38_Erik_Helga_3d17c732:
    e "我完全明白，妈妈……但我们不该——"

translate schinese hscene38_Erik_Helga_aa68c8e1:
    hm "没错！停！我们当然不该！"

translate schinese hscene38_Erik_Helga_500f24c8:
    h "埃、埃里克……{size=-5}就让我拥有这一次，拜托。"

translate schinese hscene38_Erik_Helga_15d8dce6:
    e "这解决不了你的问题妈妈，只会让事情更糟！"

translate schinese hscene38_Erik_Helga_f1e11e4b:
    hm "我知道，可它好痛……我需要他，我需要他的爱。"

translate schinese hscene38_Erik_Helga_228b10f3:
    e "我是你儿子，我没法替代——"

translate schinese hscene38_Erik_Helga_c9aa117f:
    h "{size=+5}你父亲……？！可他伤透了我的心，他毁了我的人生！"

translate schinese hscene38_Erik_Helga_ef3e093e:
    h "{size=+5}我们一起经历了那么多，他就那么……{size=-5}就那么……*抽泣*"

translate schinese hscene38_Erik_Helga_7d0e3315:
    h "求、求你了宝贝……！*抽泣*{size=-5}纵容我一会儿吧。"

translate schinese hscene38_Erik_Helga_6667a939:
    em "该死……我从没见妈妈这样过。我想帮她，可是……"

translate schinese hscene38_Erik_Helga_fa7232f3:
    em "我那个变态妹妹居然是对的，真他妈气人。"

translate schinese hscene38_Erik_Helga_9266ca9c:
    em "也许把妈妈牵扯进来真的是我们唯一的办法？"

translate schinese hscene38_Erik_Helga_6d4b38f1:
    em "行吧，莱娜。去他的！这本来就是我、我们的计划，不是吗？"

translate schinese hscene38_Erik_Helga_c5808d5e:
    em "反正道德早就扔了，再搞砸一次又能怎样？"

translate schinese hscene38_Erik_Helga_d1027d9d:
    em "我告诉过她现在由我说了算，我就打算照做！"

translate schinese hscene38_Erik_Helga_24b234e7:
    em "不管怎样，我都要收拾好我妹妹那个愚蠢的烂摊子……"

translate schinese hscene38_Erik_Helga_64d4bc0b:
    em "而要做到这一点，我就得给她母亲应得的爱。"

translate schinese hscene38_Erik_Helga_cad9d54a:
    e "妈妈，你美得惊人。活生生的女神。"

translate schinese hscene38_Erik_Helga_c3bbdcf7:
    e "我一定是世界上最幸运的儿子……"

translate schinese hscene38_Erik_Helga_c22e8715:
    e "求你告诉我一件事。你介意我——"

translate schinese hscene38_Erik_Helga_c357935f:
    e "啥？妈妈……？！"

translate schinese hscene38_Erik_Helga_543f2eaf:
    h "{cps=25}给你个忠告，{w=0.35}我的小儿子。"

translate schinese hscene38_Erik_Helga_1e659068:
    h "{cps=25}要是你想在床上摆布我这样的女人……"

translate schinese hscene38_Erik_Helga_679b4342:
    h "{cps=25}你不需要征求许可。"

translate schinese hscene38_Erik_Helga_cf539b6b:
    h "{size=-5}{cps=15}你只要把属于你的东西拿走就行。"

translate schinese hscene38_Erik_Helga_7bb02baa:
    h "第一课：湿漉漉的吻。"

translate schinese hscene38_Erik_Helga_d2f6443b:
    h "你灌进去的口水越多，我就越喜欢。"

translate schinese hscene38_Erik_Helga_f3018d3e:
    h "来，现在复述一遍。"

translate schinese hscene38_Erik_Helga_e4a23017:
    e "啥……？什——"

translate schinese hscene38_Erik_Helga_3c85945a:
    h "妈妈喜欢什么样的吻呢，嗯~？"

translate schinese hscene38_Erik_Helga_963db366:
    e "{size=-5}湿、湿润的，含很多……很……多口水。"

translate schinese hscene38_Erik_Helga_e96e3891:
    h "乖儿子。再来一次。"

translate schinese hscene38_Erik_Helga_b2646d4d:
    em "莱娜，我们到底把自己搞进什么局面了？！"

translate schinese hscene38_Erik_Helga_5e5194cd:
    hm "还觉得自己做主吗，小宝贝？"

translate schinese hscene38_Erik_Helga_10a44836:
    em "操！妈妈在床上真是判若两人！"

translate schinese hscene38_Erik_Helga_ee4f9064:
    em "她那么粗暴，可同时又……异常温柔？"

translate schinese hscene38_Erik_Helga_043a02c6:
    em "就像她施加的力道刚刚好，拿捏得恰到好处。"

translate schinese hscene38_Erik_Helga_a5d863d5:
    em "她……压得我喘不过气。我动不了。"

translate schinese hscene38_Erik_Helga_5148f4d2:
    em "感觉我只是一尊满足她欲念的雕像。"

translate schinese hscene38_Erik_Helga_2872031f:
    em "可我连假装讨厌都做不到，因为奇怪的是……"

translate schinese hscene38_Erik_Helga_03d39479:
    em "在妈妈的怀里，我比任何时候都安心！"

translate schinese hscene38_Erik_Helga_2b4068c5:
    h "干得好，宝贝。你是天生这块料。"

translate schinese hscene38_Erik_Helga_aa1e32db:
    h "不过我还以为你从没跟女孩做过这个……？"

translate schinese hscene38_Erik_Helga_d7a884c7:
    e "这个，我、呃……{size=-5}我不知道。"

translate schinese hscene38_Erik_Helga_f6c84ec2:
    h "没关系，小甜心。我知道你还是我那个纯洁的小儿子。"

translate schinese hscene38_Erik_Helga_4974f163:
    h "还是说不是……？你那条舌头用起来可是相当熟练。"

translate schinese hscene38_Erik_Helga_e15dee48:
    h "是不是有{size=+5}什么人{/size}你想告诉我……？"

translate schinese hscene38_Erik_Helga_7b087203:
    e "妈妈……？我、我不知道你在说什么。"

translate schinese hscene38_Erik_Helga_05309c0a:
    h "你在发抖。怎么了宝贝？"

translate schinese hscene38_Erik_Helga_7b2b0618:
    e "{size=-5}太、太近了。"

translate schinese hscene38_Erik_Helga_f3d7f180:
    h "好些了吗？对不起，妈妈刚才跨坐得有点用力。"

translate schinese hscene38_Erik_Helga_f57da7db:
    e "别担心……{size=-5}没、没事。"

translate schinese hscene38_Erik_Helga_83d3798e:
    h "我在这儿呢，好吗？放松。"

translate schinese hscene38_Erik_Helga_b92974c8:
    h "宝贝……？"

translate schinese hscene38_Erik_Helga_02853614:
    h "哎呀~我知道问题出在哪儿了。"

translate schinese hscene38_Erik_Helga_db0a2de3:
    e "你、你的吻太舒服了……"

translate schinese hscene38_Erik_Helga_56105629:
    hm "天啊，我从没见过男人只靠这个就射出来。我可怜的儿子……"

translate schinese hscene38_Erik_Helga_1f4797a6:
    e "对不起，我……毁了这气氛。"

translate schinese hscene38_Erik_Helga_79046a0f:
    h "哎、哎……没事的，我的小王子。"

translate schinese hscene38_Erik_Helga_0114be0d:
    h "这种事会发生的。尤其是……年轻没经验的男孩。"

translate schinese hscene38_Erik_Helga_4fa1e2cd:
    em "你不懂啊妈妈，这太丢人了！我跟莱娜的时候明明能做更多。"

translate schinese hscene38_Erik_Helga_9a806796:
    em "为什么？！为什么我妈妈对我影响还更大？"

translate schinese hscene38_Erik_Helga_49a8bc62:
    h "哎呀，别脸红成这样嘛。"

translate schinese hscene38_Erik_Helga_6fc3b109:
    h "你只是……缺少耐力。嘿嘿~"

translate schinese hscene38_Erik_Helga_fafadcb3:
    h "但别担心，我正好知道该怎么给你补点「燃料」。"

translate schinese hscene38_Erik_Helga_51fc9499:
    e "你还想继续……？莱娜怎么办？我们花太久了。"

translate schinese hscene38_Erik_Helga_f0561228:
    h "没事宝贝，这次我把门锁上了。"

translate schinese hscene38_Erik_Helga_9c927e8f:
    e "可我们还是——"

translate schinese hscene38_Erik_Helga_a4866a37:
    h "哼！别再操心你妹妹了，行吗？"

translate schinese hscene38_Erik_Helga_ef0ff266:
    h "你我之间还没结束。"

translate schinese hscene38_Erik_Helga_df6dfb04:
    h "你弄出来的这个烂摊子……还不够让我满足。"

translate schinese hscene38_Erik_Helga_32b61bee:
    h "{cps=30}因为你的{size=+5}嘴{/size}真的让我爽到了，{w=0.5}儿子。"

translate schinese hscene38_Erik_Helga_755fe79b:
    h "{cps=20}所以我得好好还这个人情。"

translate schinese hscene38_Erik_Helga_8db23a0b:
    em "不会吧！她要……？"

translate schinese hscene38_Erik_Helga_89255355:
    h "咳咳！前几晚，我在沙发上帮你的时候……"

translate schinese hscene38_Erik_Helga_99ecaa33:
    h "你说你很喜欢，对吧？"

translate schinese hscene38_Erik_Helga_2a514b2d:
    e "是、是的，妈妈……"

translate schinese hscene38_Erik_Helga_9f4ab20e:
    h "感觉非常非常棒，对吧？当我让你下面酥麻发麻的时候……"

translate schinese hscene38_Erik_Helga_43bf5de4:
    e "非常……舒服，是的。"

translate schinese hscene38_Erik_Helga_6b35ea1e:
    h "你妹妹打断了我们，你当时特别需要妈妈，对吧？"

translate schinese hscene38_Erik_Helga_4e22ab21:
    em "她又这样说话了！操。"

translate schinese hscene38_Erik_Helga_6f436e5d:
    h "哎呀，你这个小鸡鸡真可爱。"

translate schinese hscene38_Erik_Helga_23781567:
    h "我已经很多年没见过它这么小了……"

translate schinese hscene38_Erik_Helga_f2cec5a5:
    h "那天我处理你伤口的时候，它绝对不是这样。"

translate schinese hscene38_Erik_Helga_88fda457:
    e "对、对不起，我不知道自己为什么软了——"

